### ISSUE TITLE
Analog video output broken after 20190515

### ISSUE THREAD

**Issue by nilp0inter** [MiSTer-devel/Main_MiSTer#100]
I've been using MiSTer with a [VGA-SCART cable](https://github.com/mist-devel/mist-board/wiki/ScartCable) connected to a TV without any issue up to 20190515. 

I tested newer versions from the working one to the latest, and none of them display the menu with my setup, just something that appears to be a very fast rolling menu.

So it seems that something broke between 20190515 and 20190525. I noticed two commits in the history between those releases relating to video changes, which are https://github.com/MiSTer-devel/Main_MiSTer/commit/448cc2cf6798d89708a5de602b8589fe40bdf728 and https://github.com/MiSTer-devel/Main_MiSTer/commit/414861e3bf66bddf38339bbb14ea37ee13c27b71. Just in case that helps.

Thanks!

**Comment by nilp0inter** [comment]
Sorry, my bad. I reformat the SD card and now everything is working fine with the latest release. Maybe  something is not compatible with the version of the bootloader I had and the latest release?

**Comment by sorgelig** [comment]
most likely you didn't update the Linux before.
