### ISSUE TITLE
Feature Request: Gamma Slider

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/Main_MiSTer#102]
I think MiSTer would really benefit from a gamma slider, especially for those people who use scanline filters, but even for those who don't use any scanline filters.   I noticed the Genesis core was noticeably darker than my Mega SG without scanlines turned on, so it would be nice to be able to adjust the gamma to better match other devices.

**Comment by sorgelig** [comment]
Gamma correction requires quite "expensive" math.
There is no plans for this.
