### ISSUE TITLE
NeoGeo Turboload issues

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/Main_MiSTer#103]
NeoGeo Turboload is instable. Sometimes needs loading twice on some sets.

Check against this (it always fails):

Metal Slug 4 Mame Set is the only working set so far. Darksoft had always graphical issues.

Since Turboload Metal Slug 4 Mame has also graphical issues and is not working anymore. 
Mister Main up to commit fb6cab78b527801148ef7bbb9f85e6ac4c3dd9ae working fine always.

**Comment by sorgelig** [comment]
Cannot confirm.
Metal Slug 4 darksoft always loads fine. This game requires alternative srom file to display static graphics correctly, but it's not related to turbo loader.

Core sometimes may build with glitches. Or your SDRAM has stability issue as turbo loader uses block transfer and stresses SDRAM more.

**Comment by PhantombrainM** [comment]
Okay, I can confirm that darksoft metal slug 4 loads correctly when switching from standard darfsoft 512kb srom to mame 131k srom.

Nevertheless turbo main mister breaks metal slug 4 mame set (with graphical errors) while old main mister with slow loading is fine. I don't know it its kind of important. Otherwise you may close this case now.

**Comment by sorgelig** [comment]
it may not directly related to turbo loader but some other changes made at the same time
