### ISSUE TITLE
Minimig harddrisks menu

### ISSUE THREAD

**Issue by xolod79** [MiSTer-devel/Main_MiSTer#105]
In Minimig harddrisks menu select HDF image with PFS or SFS fail "Cannot open the file", but remember selected file. i think problem with check file system signature.
In Mist check 3 file system signs DOS, PFS, SFS 
https://github.com/mist-devel/mist-firmware/blob/23ad06e0fdaa629092f97c9aca62b32a522bf6ff/hdd.c
900 line.

**Comment by mickstone** [comment]
I see the same issue.  It still opens this hdf though.

**Comment by sorgelig** [comment]
The files where you get "Cannot open file" warning in OSD indeed have problem. It's just message a little confusing. I will find a better message text.
Files you want to open most likely created in UAE which tends to put prohibited CHS values. Usually it puts >255 sectors in the header. IDE device can address only 255 max. UAE has its own virtual driver, so it intercept IDE access and translates it internally.
MiSTer tries to translate such illegal CHS into legal values with less sectors and more heads if there is a room for such translation.
So, there is a general rule: create HDD on MiSTer.

**Comment by mickstone** [comment]
Not sure how to create HDD on MiSTer?

**Comment by sorgelig** [comment]
Make an empty file (filled by zeros) of required HDD size on PC.
Then mount it on MiSTer and do usual procedure of new disk installation in HDToolBox.

**Comment by rsn8887** [comment]
Can I mount a hdf with manual settings, e.g. surfaces=2 instead of surfaces=1?

**Comment by sorgelig** [comment]
there are no manual settings. parameters are read from RDB header.

**Comment by rsn8887** [comment]
What about non-rdb hdf?

**Comment by sorgelig** [comment]
non-rdb disks are apended by virtual header with calculated parameters,

**Comment by rsn8887** [comment]
Ok then my files should work. If not, I will try to use the awesome xdftool to convert my hdf to rdb http://lallafa.de/blog/amiga-projects/amitools/xdftool/
