### ISSUE TITLE
Feature request: 180 deg screen rotation for native portrait arcade cores

### ISSUE THREAD

**Issue by eskwadrat** [MiSTer-devel/Main_MiSTer#106]
Some already implemented arcade cores like Amidar rotate 90 deg CCW from default landscape orientation when set to native vertical (portrait) display. While other cores like 1942 rotate CW when set to vertical mode. So only one of those games can be played with monitor fixed in portrait position - used mostly in real arcade cabinets, while other game is unplayable because the image is upside down. 
Request is to add a 180 deg rotation feature or expand VERT mode option into two sub options for CW and CCW rotation when switching to Vertical (portrait) mode. Valid only for natively supporting portrait mode arcade cored. Irrelevant for natively landscape arcade cores. 
Requested feature would enable using MISTer platform in arcade cabinets w/portrait oriented monitor where both types of cores are played (CW and CCW). 
Issue also explained in the video here:
https://youtu.be/cVATdWNYOuU

**Comment by sorgelig** [comment]
Original arcade HW is designed for specific rotation. There is no way to rotate it on analog output without frame buffer. ROM and HDL need to be patched. It needs to be done per core.

Won't fix.

**Comment by eskwadrat** [comment]
OK, thanks. What about HDMI output, is there a way to have it rotated on this one?

**Comment by sorgelig** [comment]
HDMI uses the scaler and rotator, so generally it's possible, although the main orientation for MiSTer is horizontal. MiSTer is not about arcade cores only.

**Comment by eskwadrat** [comment]
I agree, arcades are one of many. Fantastic job on console cores like SNES.
Thanks for all the work.

Steve
