### ISSUE TITLE
Feature request: assign OSD settings through ini file

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#107]
If a core has a say "difficulty" setting in the OSD menu, it would be nice if the user could add that to the ini file. That way the user doesn't have to set it up manually each time the core is loaded.

**Comment by sorgelig** [comment]
User just need to save the Settings. All OSD settings will be loaded on next core start.

**Comment by jotego** [comment]
Awesome. Thanks.
