### ISSUE TITLE
zip files in neogeo core

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Main_MiSTer#108]
Hi

dont know if this affects much the loading of the games but a ziped darkrom set is less than 3gb and the unziped set is almost 8GB.
Its possible to core accepts also zip files?
Thanks

**Comment by sorgelig** [comment]
actually it should be supported already.  I didn't try it yet. May be there is some bug.
It should be the whole pack in a single zip.
zip inside the zip is not supported.

**Comment by sorgelig** [comment]
there are several issues preventing to use zips in NeoGeo.
I will fix it.

**Comment by eubrunosilva** [comment]
oh yeah...
its works with the games i've tried (darksoft set). Mame/hbmame romsets should also work.
Thanks
