### ISSUE TITLE
folders inside zips

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Main_MiSTer#109]
Hi
it´s possible to have support for folders inside zips?
Thanks

**Comment by eubrunosilva** [comment]
well it looks like its because of the zip format... i will also "investigate" this...

**Comment by sorgelig** [comment]
Yes, as i've told to kitrinx, your zip format doesn't include folders alone. 
I've re-packed your zip with mine, and it started to list the folders.
btw, now you can embed romsets.xml per zip.
