### ISSUE TITLE
Octopart BOM

### ISSUE THREAD

**Issue by alanswx** [MiSTer-devel/Main_MiSTer#11]
I tried to create some BOM for the other boards:
RTC:
https://octopart.com/bom-tool/95qomeBj
IO Board:
https://octopart.com/bom-tool/KurIZPWc

I doubt these are perfect - but it might save some time.

The SDRAM BOM is incorrect - the capacitor count should be 5, not 1.
https://octopart.com/bom-tool/7Rk7V11w

**Comment by sorgelig** [comment]
Thanks for BOM.
I've updated DIY pages. Actually, Wiki is opened for public editing.

Unfortunately SDRAM BOM is not mine, so i cannot edit. Anyway, it's just example - should be no problem to correct if you will order the parts.

**Comment by alanswx** [comment]
Yes - i can't figure out a way to share the BOM so you can edit it. I ordered the SDRAM one (x10) and realized I only had (x2) sets of capacitors. I will order some more.  Thank you for this great project!  I think you could download the CSV and maybe rebuild a new one. I can make the BOMs read/write if you think that would be better.

**Comment by sorgelig** [comment]
I prefer to let other people (may be you?) to track the BOM. You can create a new BOM for SDRAM - i will put it in place of existing BOM. I have no time to check everything by myself. Especially if i don't use it by myself (i buy many components in local store). It's open source project and supposed to be maintained by contributors.

**Comment by alanswx** [comment]
Sounds good. I wrote to octopart to see if we can make it so a few of us can share the BOM. I am planning on helping contribute to this project. I am exploring making the MiSTer_Main handle decompression automatically so we can leave the ROMS compressed in zip/7z and maybe rar format. Also hoping to add some other feature enhancements in the C side of things.  I need to build out a windows setup to start hacking on the cores.

**Comment by sorgelig** [comment]
There is no real need of compressed ROM support. You can use any size of SD card, or even USB storage. So there is no space shortage. 
Adding compressed format will require support from FPGA side since files are filtered by extensions. 
It's not a problem to uncompress all your ROMs at once and problem is solved.

Or are you talking about the single compressed file with many ROMs inside? This could be useful, although i think it's not a problem to uncompress it once.

**Comment by alanswx** [comment]
I am going to be without a computer traveling for the next few weeks - so no changes until early next year from me.  

I had a bunch of different roms stored up and a lot are in a .rar then .zip individually. I can manually or write a script to pull the apart, but I thought it would be nice to be able to use them as is.  We can link against libarchive - and then change some of the code in the scandirectory function so that it treats zip/rar/tar/7z as a directory. In the file loader we can check the path, and if it goes through an archive, we can intercept it and use the archive reader to open up the rom.  I would like to make the arcade games be able to use the mame rom zip/7z files directly as well. I haven't looked into that yet.  Maybe a file with a table of mappings - get it out of the shell scripts into a config file.  Libarchive would require adding a couple of compression libraries to the linux distribution.

Also, I have appleii files stored as DSK and C64 files on T64. I think we can move the DSKtoNIB converter into the linux side, and just convert the data on the fly before we send it over the spi bus to the appleii.  The C64 might need a modification on the FPGA side - i need to do some tests. I have to look at the code I wrote 20 years ago for my C64 emulator and remember how it all works. I think we can use the PRG loader and a little code to read the PRG file out of the T64 file and send it over spi. This might not be 100% compatible, I think some tapes might have multiple files. But it is simple, so it is worth a quick try. Otherwise the FPGA needs to be modified so we can send the tape and memory addresses over the wire and have it end up in the correct spot in memory.  Not sure if it is best to modify the config of the AppleII/C64 to add the extensions in the FPGA config, or modify them when the config string is sent back to the linux side. There is a weird dependency that needs to happen between both linux/FGPA cores.

The last thing I want to think about is building in a package installer system so we can trivially install FPGA cores, and upgrade them over the net when new ones come in. I haven't thought about this too much yet. Is there some other package system we should use? Or should we just drop a json file on github? Have you thought about this?

**Comment by sorgelig** [comment]
About updates, i'm pretty fine with current way it is.
