### ISSUE TITLE
Feature request: DB9 joystick input via GPIOs

### ISSUE THREAD

**Issue by sajattack** [MiSTer-devel/Main_MiSTer#112]
There are so many GPIOs on DE10 Nano, surely we can spare 9 (or less) for low-latency retro joystick input?

**Comment by sorgelig** [comment]
There are no confirmed input lags. USB input lag for joysticks is usually 2-5ms while retro consoles query the joysticks once per frame, i.e. once per 16-20ms. 
Input lag is commercial myth.

**Comment by sajattack** [comment]
Ok, maybe lag was the wrong way to frame the problem, wouldn't it still be good to support classic joysticks?

**Comment by hmusta** [comment]
Some retro consoles (such as the NES) may poll joysticks more than once per frame:
https://wiki.nesdev.com/w/index.php/Controller_reading_code#DPCM_Safety_using_Repeated_Reads

**Comment by sorgelig** [comment]
There are many USB converters for classic joysticks. So they are basically supported already.

**Comment by sorgelig** [comment]
> 
> 
> Some retro consoles (such as the NES) may poll joysticks more than once per frame:
> https://wiki.nesdev.com/w/index.php/Controller_reading_code#DPCM_Safety_using_Repeated_Reads

MiSTer has no such glitch as original joystick. And this trick is basically just to get the same - get the joystick data once per frame. Core can query the joystick data as fast as it wants - it won't make it slower or other issues.
