### ISSUE TITLE
Question: Analogue DAC, compatibility?

### ISSUE THREAD

**Issue by ioev** [MiSTer-devel/Main_MiSTer#113]
The Analogue DAC was recently put up for preorder:  https://www.analogue.co/dac/

I'm curious, with the work done for direct_video via the hdmi port, would a device like this possibly be compatible?  If not now, could it be in the future?  Or is this the kind of question that can't really be answered until the thing has actually been released?

**Comment by alfishe** [comment]
"DAC outputs unadulterated, crystal clear & stunning RGB, Component, S-Video, Composite & Analog audio." - what a wonderful BS... anything that HDMI can transmit is possible to downconvert and transform to oldschool interfaces. MiSTer is using standard video modes and PCM audio stereo stream.

**Comment by sorgelig** [comment]
Audio DAC is not 9038pro? then BS..  ;)
Seriously, making fancy a-la Samsung Galaxy web site doesn't make this HDMI->CVBS/VGA converter special.
For direct video you need simple $2-$7 HDMI->VGA converter.
But if you have money you don't know where to put, then by this Analogue DAC (Analogue DAC, wut??), although i have no idea if it will work with anything but Analogue consoles.
