### ISSUE TITLE
Hide folders not in xml

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Main_MiSTer#114]
Hi
it's possible to add a setting in xml to hide specific folders or all folders not in xml?
Thanks

**Comment by sorgelig** [comment]
You can't hide folders as they are natural way to browse the files. Just like in other cores.
Also it's easy to recognize that some game is not described in xml. So either describe the game in xml or remove the folder if it doesn't contain any sub-folders with games.

**Comment by sorgelig** [comment]
I guess we are talking about NeoGeo core. Otherwise there are no any xml in other cores.

**Comment by eubrunosilva** [comment]
yes. neogeo core...
i ask this because there is zips with games/demos that has some folders that should be deleted or not displayed (because they are bad, encrypted or other motive).

just try to improve experience to end user with zips from hbmame... i will try in other way
thanks

**Comment by eubrunosilva** [comment]
well this could be a nice to have... why?
example:
neogeo1.cpp from hbmame
its has these folders:
breakrev ("original" mame game)
// Breakers Revenge
breakrevs01 => Breakers Revenge (Mode Easy)
breakrevs02 => Breakers Revenge (Doomsday Heroes Strengthens Lite 2015-01-13)
breakrevs03 => Breakers Revenge (Unknown Hack Data)"
breakrevs04 => Breakers Revenge (Enable Hidden Characters 2018-07-17)

i need to maintain breakrev folder because the other folders only have the changed files from original release.
"doesn't make any sense" to have the original release here in this hack pack.

not possible to have something like:
<romset name="breakrev" noshow="1" /> ?

the other sets you replace the name of the folder and here you just doesn't show the folder?
Thanks

**Comment by sorgelig** [comment]
> not possible to have something like:
> ?

like what?

**Comment by eubrunosilva** [comment]
ups strange... i remember that i wrote that
<romset name="breakrev" display="0" />

**Comment by sorgelig** [comment]
ok. i will check it

**Comment by sorgelig** [comment]
check my latest commit
```<romset name="breakrev" hide="1" />```
actually hide may have any value - it always hides if present.

**Comment by eubrunosilva** [comment]
hi
that's it!
thanks
