### ISSUE TITLE
Latest update has invalid DVI output?

### ISSUE THREAD

**Issue by thejpster** [MiSTer-devel/Main_MiSTer#117]
I use a DVI monitor with an HDMI to DVI cable. I set dvi_mode = 1 in the config file, and it works great at 1920x1080@60.

I ran the update script last night, and now when I boot the MiSTer the monitor says "Out of range!".

Did I get a bad update? Has the config file moved? Has the DVI mode option changed?

**Comment by sorgelig** [comment]
Copy MiSTer.ini to the root of SD card.

**Comment by thejpster** [comment]
It occurred to me to check SSH after I posted this, which works fine. So the MiSTer is running - it's just the video output that's wrong.

**Comment by thejpster** [comment]
> Copy MiSTer.ini to the root of SD card.

Aha! That did it.
