### ISSUE TITLE
How to create bootable sd-card under Linux?

### ISSUE THREAD

**Issue by toms001** [MiSTer-devel/Main_MiSTer#12]
I don't use windows and i'm searching for a howto. There is a deprecated guide in the wiki,
but the new linux-image-creator only creates images. Thanks!

**Comment by sorgelig** [comment]
Linux users are smart enough to make it by themself :)
Check here: http://www.atari-forum.com/viewtopic.php?p=340314#p340314

**Comment by toms001** [comment]
ok thanks, my glassball was broken ;)
For information here again:
2 Partitions
1. exFAT, type 0x07 
2. uboot (1mb), type  0xa2, (dd if=<uboot.img> of=<Partition2>)
