### ISSUE TITLE
Is there a Wiki page defining what menu symbols mean?

### ISSUE THREAD

**Issue by Leesam** [MiSTer-devel/Main_MiSTer#121]
I updated yesterday and noticed a new symbol in the menu, it looks like the third to last icon on this default font:
![](https://raw.githubusercontent.com/MiSTer-devel/Fonts_MiSTer/master/preview/Default.png)

Most icons are straightforward like bluetooth, wifi, wired network. For this chip looking icon my guess would be some sort of space gauge, i'm just not sure if it's referring to usb, sdcard, ram, etc.

**Comment by rikard-softgear** [comment]
@Leesam It means you have a 32MB RAM module. 

> ![image](https://user-images.githubusercontent.com/36540711/66594656-d8b86e80-eb99-11e9-9dac-cbf3d58780ed.png)
> 0MB (No module)

> ![image](https://user-images.githubusercontent.com/36540711/66594739-01406880-eb9a-11e9-8236-a5c5e8b3a922.png)
> 32MB

> ![image](https://user-images.githubusercontent.com/36540711/66594776-11584800-eb9a-11e9-9e60-ef29b7525190.png)
> 64MB

> ![image](https://user-images.githubusercontent.com/36540711/66594938-4fee0280-eb9a-11e9-9af9-131a3f639a38.png)
> 128MB
