### ISSUE TITLE
Rotated control with rotated screen

### ISSUE THREAD

**Issue by bonnefoi** [MiSTer-devel/Main_MiSTer#122]
When you select horizontal orientation with a core, the direction controller is not rotated and you can't play like this.

You get no scanlines either.

Is there any config option to enable this ?

Thank you for your support,
Pierre-François.

**Comment by sorgelig** [comment]
control rotation is core specific. Usually core provides input rotation post an issue in core where input is wrong.
Arcades will be updated to provide more options like scanlines/hq2x on HDMI output

**Comment by sorgelig** [comment]
Not related to this repository.
