### ISSUE TITLE
How much SDRAM is required by which core?

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Main_MiSTer#128]
Can https://github.com/MiSTer-devel/Main_MiSTer/wiki/SDRAM-Requirement-by-cores be updated to list how much memory I need for the various cores that use the SD RAM board? It seems there are three boards: 32 MB, 64 MB and 128 MB.

Currently, the wiki only lists the speed requirements. I don't know how that is useful.

**Comment by sorgelig** [comment]
only NeoGeo needs more than 32MB

**Comment by rsn8887** [comment]
Ok thanks! I added that information to the page.

**Comment by dev31337** [comment]
Hi,

The page is now empty, did it move ?

Regards.

**Comment by arodland** [comment]
It's now https://github.com/MiSTer-devel/Main_MiSTer/wiki/Cores-that-use-SDRAM
