### ISSUE TITLE
DE10-Lite?

### ISSUE THREAD

**Issue by thejpster** [MiSTer-devel/Main_MiSTer#129]
I picked up a DE10-Lite for next to nothing in an auction (and I already have a -Nano). Are there massive differences between the -Lite and the -Nano? Do you think it would be straightforward enough to port MiSTer to the Lite?

**Comment by sorgelig** [comment]
Completely different board. Nothing common besides the part "de10" in the name. MiSTer is impossible on it.

**Comment by thejpster** [comment]
Fair enough! Thanks.
