### ISSUE TITLE
Joystick works in menu but not in core

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Main_MiSTer#132]
When I map my retrousb competition pro joystick in menu core it works fine. But when I load the C64 core and try to “define C64 buttons”, I can define right and then it says left but immediately switches to saying “Cancelling” and stays there until I wiggle the joystick.

Needless to say, only right direction works in the core, not left. But in menu navigation after pressing F12, joystick works fine in all directions and fire. But only in menu navigation, not in the core itself and in games.

This is using latest C64 and menu core from September 2019.

I suspect this is due to some Linux usb his crap, I have only ever had bad experience with usb controller support in linux

**Comment by rsn8887** [comment]
Also what does this mean:
Space/Menu: Undefine
Menu-hold: Cancel
Enter: Finish

This is one of the most confusing on screen messages I have ever seen. When I press space, space is mapped, not undefined. When I try to hold menu (F12) or press menu, then nothing happens. ESC does exit but that is NOT shown.

**Comment by rsn8887** [comment]
Also how is player 2,3 and 4 mapped?

**Comment by Newsdee** [comment]
The player assignment is independent from mapping.  You just need to define each joystick once.
Players are assigned after you start a core and press a button on a controller.

**Comment by rsn8887** [comment]
In Amiga core it works perfectly ;)

It must be user error or something weird about C64 core only!

Btw: wow Amiga gameplay seems lag free and perfect!!

**Comment by rsn8887** [comment]
Maybe I shouldn’t have even touched that “define C64 keys” menu, because on Amiga it worked perfect without that.

Can I reset that somehow?

**Comment by Newsdee** [comment]
The maps are stored under the /media/fat/config/ folder.  You can just delete the C64*.map files to reset it.

**Comment by rsn8887** [comment]
Perfect thank you

**Comment by rsn8887** [comment]
Ok I deleted those *map* files and now it works also in C64! I should have never touched the “Define C64 Buttons” menu option.

Might be good to add an option “reset all [core] button defines” to prevent users from falling into this trap :)

**Comment by sorgelig** [comment]
F12 is F12, not "Menu" button.
Menu button is button defined on gamepad as "Menu".
