### ISSUE TITLE
Define [core] buttons doesn’t work with usb controller

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Main_MiSTer#134]
As long as I don’t touch the option “Define [core] buttons” everything works.

But when I try to use the option, I can map Down. But then the display says “canceling” and I can only exit the submenu by wiggling the joystick.

Tested with Mojo Retroadapter Competition Pro DB9 to USB adapter. The adapter appears as usb hid device with analog joystick and one button. The analog joy axes values switch from 0 to +- max when the competition pro joystick is actuated.

It works great as long as I don’t touch that “define” core option.

**Comment by rsn8887** [comment]
A different adapter, RetroUSB, has a different issue: it activates buttons AND analog joy axes value changes at the same time when the user actuated the stick, which seems to make mapping in menu, as well as in “define buttons” pretty much impossible.

**Comment by sorgelig** [comment]
I don't have such issue.. Do you use key combo for menu button?

**Comment by rsn8887** [comment]
I also have a bliss box 4-play I will try it soon.

**Comment by rsn8887** [comment]
I don’t use a comb, I skipped all that via space.

**Comment by sorgelig** [comment]
I cannot deal with joysticks/adaptors generating more than 2 events from the same button/direction. 
Simply get rid of such weird joystick/adaptor. It's not correct behavior.

**Comment by rsn8887** [comment]
The RetroUSB has this simultaneous button plus axes behavior also in Windows Controller test.

**Comment by sorgelig** [comment]
I know. There are such devices. They are not compatible with MiSTer.
It's still possible manually create the config files for such non-standard input devices. But it's not worth.

**Comment by sorgelig** [comment]
Still unclear to me why you have canceling message... Need more inputs so i can reproduce it.

**Comment by sorgelig** [comment]
So i guess in Menu core you define only LRDU + A button and skip everything else?

**Comment by rsn8887** [comment]
Yes. But the other adapter, Mojo Retroadapter, can be mapped perfectly in menu core and works great. Just when I go to define buttons option, the it gets stuck on “cancelling” so that might be a real issue.

**Comment by rsn8887** [comment]
Yes I skipped everything after “A” using space.

**Comment by rsn8887** [comment]
I also skipped STick X test, only did DPAD test.

**Comment by sorgelig** [comment]
so from your words you did everything correct.

**Comment by bSr43** [comment]
I have a similar issue with a standard USB controller which used to work before the latest release.

I'm able to map buttons in the "Define joystick buttons" system menu, but impossible to define a mapping in any of the core. For instance, the Genesis core asks me to press RIGHT, once done the USB ID is displayed and it asks for me to press LEFT, but as soon as I press the left button, I receive the message "Canceling".

The controler is the Retrobit Sega USB Controller.

**Comment by Newsdee** [comment]
Can you send your .map file from the menu core? Perhaps you defined a OSD
button incorrectly and it is resetting the mapping when you try to add one?

**Comment by bSr43** [comment]
I've attached the two versions of the input mapping files for this controller (0079:0011).

[input_map_files.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/3818464/input_map_files.zip)

I don't think I've defined anything for OSD on the controller, at least, not intentionally.

**Comment by Newsdee** [comment]
Can you try this?

[input_0079_0011_v3.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/3819503/input_0079_0011_v3.zip)

I noticed your OSD button was not defined at all - which I think may be causing the issue.
(I mapped it here to Up+Start - so won't interfere with anything unless you specifically use it)

**Comment by bSr43** [comment]
No, sorry, it doesn't work either, and this time, the issue is even weirder: for instance, I tried to map buttons in the Genesis core, every button is recognized except the left direction on D-pad. When I press the left direction, nothing happens at all. As soon as I revert to core MiSTer_20191019, controller works as expected.

**Comment by Newsdee** [comment]
I think there's two different issues going on. One is a misbehavior if the OSD button is not defined, which causes that "cancelling" message. I was able to reproduce that.

For the other one, I'm not sure. Try remapping but this time, skip until the OSD button and use a combination e.g. up + start to define it. That should avoid the first issue, and you can test if the auto translation to core mapping works.

**Comment by Newsdee** [comment]
Try renaming your old Genesis*_V2.map file into Genesis*_V3.map ; it may work around the problem.

**Comment by sorgelig** [comment]
I will test with OSD button undefined.

**Comment by bSr43** [comment]
> Try renaming your old Genesis*_V2.map file into Genesis*_V3.map ; it may work around the problem.

Renaming Genesis input mapping file works, indeed. Mapping from the OSD still doesn't work, but at least, it makes it possible to use the core in the meantime. Thank you!

**Comment by DesktopMan** [comment]
I am having similar issues with a Retro USB SNES controller. It maps fine in the main menu, but if I try to map it in a core I think it maps right to both right and left (left is always skipped).

I can also map up to every button, which doesn't happen with e.g. the A-button, so I think it might be related to bouncing + allowing the d-pad to be mapped to multiple buttons.

**Comment by rsn8887** [comment]
My issue was solved with latest release 20191111 https://github.com/MiSTer-devel/Main_MiSTer/commit/c5e3d0a113e8d7fc62236b7dae0dec90bcf94f41

Unless anybody else still has issues, I think this can be closed.
