### ISSUE TITLE
Pixel aspect ratio via HDMI maybe incorrect TG16 core?

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Main_MiSTer#137]
First of all, thank you again for this incredible work. The more I use my Mister, the more I love it.

Now to my issue, which might not be an issue: It seems to me that the aspect ratio of the pixels is not correct in some cores, but perfect in others. I am using HDMI output. I set "Aspect Ratio: 4:3" in all cores. I haven't tested all cores, but here is what I have observed so far:

- TurboGrafix16/Pc Engine core seems to show a picture that is not quite wide enough horizontally. It looks like Mister maybe assumes the pixels should be square, when on a real TV, they were slightly rectangular. Or maybe Mister is not treating overscan area correctly. Here is a link with real hardware footage on a CRT TV, note the aspect is 4:3, there are no black bars on left or right: https://www.youtube.com/watch?v=QLs4TjM7DFE

- NES core seems to be slightly not wide enough, even when I use the "Hide Overscan" feature. Without Hide Overscan the picture is definitely much too narrow horizontally. The Hide Overscan helps, but still it is a bit too narrow I think. EDIT I tested my photograph of Super Mario Bris Running with Hide Overscan and I think it is actually 4:3 so maybe this core is fine as long as that option is enabled.

- C64, Amiga, Neogeo, SNES, and Genesis cores look perfect to me.

It could be that I am judging it wrong, because I compare visible screen area. Maybe some visible overscan pixels should be ignored when comparing systems, and what I am really looking for is a kind of "zoom" option. 

Here are some pictures to illustrate differences when I expect 4:3 aspect to be the same everywhere. Notice the differences in black bars on left and right, when I expect them (maybe wrongly expect them?) to be the same as long as I have 4:3 aspect ratio selected in the core menu. BTW is there a forum or Discord or IRC channel were Mister development can be discussed, or is Github the main communication channel?

![IMG_3459](https://user-images.githubusercontent.com/13071547/68528693-e0b01f00-02bb-11ea-9de0-c6eb6c7db27d.jpg)
![IMG_3460](https://user-images.githubusercontent.com/13071547/68528694-e0b01f00-02bb-11ea-82bd-97876c2762f8.jpg)
![IMG_3461](https://user-images.githubusercontent.com/13071547/68528695-e0b01f00-02bb-11ea-8148-8cf85b9641e4.jpg)

**Comment by rikard-softgear** [comment]
4:3 doesn't mean that the picture will be 4 by 3, it means that it will have the same aspect ratio as the original console on a 4:3 TV.

**Comment by rsn8887** [comment]
If the NES put out a 64:49 image, why did it not have black borders on a 4:3 TV then? Was it just “zoomed” so much that the inevitable black borders were moved into the overscan areas?

And is it true that the PC Engine hardware really put out such a narrow aspect ratio as the core does? I think I remember the real console put out a wider AR and the YouTube video I linked seems to verify that.

**Comment by paulb-nl** [comment]
A real NTSC NES has colored borders on the sides, normally hidden by overscan: [https://youtu.be/TMiHy-P_k8M?t=116](https://youtu.be/TMiHy-P_k8M?t=116)

Use the 240p test suite Linearity test to verify the correct aspect ratio.

**Comment by rsn8887** [comment]
Ok that explains NES. What about Turbografix16? The only core I still think might have wrong AR judging by that video.

**Comment by paulb-nl** [comment]
That video just shows a 4:3 CRT with overscan. How can you tell from that what the pixel aspect ratio should be? You are mixing up frame aspect ratio and pixel aspect ratio.

If you want to know if the TG16 core has proper pixel aspect ratio then run the 240p test suite Linearity test and measure the circles.

**Comment by rsn8887** [comment]
Link to TG176 core 240p test suit Linearity test please?

**Comment by rsn8887** [comment]
I ran the linearity test and clearly the circles are distorted into vertical ellipses. What more do you want me to do to prove that something is wrong?

Also, how did nobody else ever see this problem? Am I missing something here?

**Comment by paulb-nl** [comment]
No more proof is needed :wink: You can open an issue at the TG16 repo.

Apparently the aspect ratio is different when Vertical blank is changed from Normal to Reduced and also between 240p and 224p resolution and 256/320/512 horizontal resolution. These all need to be corrected.

256x240 with Normal vertical blank seems to be correct.
