### ISSUE TITLE
Set USB polling to 1ms for improved input latency. "usbhid.jspoll" parameter not working from Linux on MiSTer

### ISSUE THREAD

**Issue by klaritan** [MiSTer-devel/Main_MiSTer#139]
"usbhid.jspoll=1" does not have any effect and linux still polls at the requested rate of controllers.
Having it at 1000Hz can eliminate some of the needs to get those commercial LLAPI adapters as it can pull the results down to near 1ms.

Modifying the module "drivers/hid/usbhid/hid-core.c" should yield the same result as the parameter seems to have no effect.

Test results of 1000Hz polling rate improving controller's input latency across all tested controllers documented here: https://medium.com/@WydD/controller-input-lag-how-to-measure-it-1ebfd2c9d60

**Comment by sorgelig** [comment]
It would be good if you could make a patch to kernel if you know how.
I cannot handle everything myself.

**Comment by rsn8887** [comment]
Looking at the code in hid-core.c, it supports the jspoll kernel parameter. It might be good to find out why the parameter has no effect.

I know Mister is not using ArchLinux, but they have very nice documentation that might help: https://wiki.archlinux.org/index.php/Mouse_polling_rate

**Comment by klaritan** [comment]
> 
> 
> It would be good if you could make a patch to kernel if you know how.
> I cannot handle everything myself.

Sure thing. I created a pull request here: https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/pull/8

**Comment by bootsector** [comment]
The correct "patch" should be making the configurable option to work on MiSTer and not making this hardcoded. Some controllers will operate incorrectly with this polling rate.

**Comment by sorgelig** [comment]
I've added commit related to jspoll

to apply jspoll value i suggest to create file /media/fat/linux/u-boot.txt with following content:
```
v=loglevel=4 usbhid.jspoll=1
```

for more debug messages you can set loglevel=7. You can see HID usage value and applied polling interval with this value. Just unplug and then plug your gamepad.
Some gamepads have completely different usage like Logitech F710 having 0xFFA00001 usage which is not joystick or gamepad, so such devices won't receive jspoll value.

**Comment by klaritan** [comment]
> 
> 
> I've added commit related to jspoll
> 
> to apply jspoll value i suggest to create file /media/fat/linux/u-boot.txt with following content:
> 
> ```
> v=loglevel=4 usbhid.jspoll=1
> ```
> 
> for more debug messages you can set loglevel=7. You can see HID usage value and applied polling interval with this value. Just unplug and then plug your gamepad.
> Some gamepads have completely different usage like Logitech F710 having 0xFFA00001 usage which is not joystick or gamepad, so such devices won't receive jspoll value.

It doesn't seem to be working with u-boot.txt: https://i.imgur.com/FksmqT0.png

**Comment by sorgelig** [comment]
![image](https://user-images.githubusercontent.com/917089/69235895-68a3fc00-0bcd-11ea-951a-e1852a0d618f.png)
it works for me.
Make sure u-boot.txt has linux line ending.

[u-boot.txt](https://github.com/MiSTer-devel/Main_MiSTer/files/3868980/u-boot.txt)

**Comment by klaritan** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/917089/69235895-68a3fc00-0bcd-11ea-951a-e1852a0d618f.png)
> it works for me.
> Make sure u-boot.txt has linux line ending.
> 
> [u-boot.txt](https://github.com/MiSTer-devel/Main_MiSTer/files/3868980/u-boot.txt)

Thank you, I can now confirm u-boot.txt works. I'll close this once I test the parameter is properly working on the official release build.

**Comment by James-F2** [comment]
Oh Yeah,, Thank you very much for this!

**Comment by sorgelig** [comment]
So, this is with 1ms polling?

**Comment by James-F2** [comment]
Not yet.
This controller has exceptionally good results.
Other controllers are around 7-10ms average.

**Comment by James-F2** [comment]
Here are my results with a USB iBuffalo SNES controller,
https://www.answerminer.com/calculators/histogram/?id=e817b380b12f2463

Should be faster with 1ms polling.

**Comment by sorgelig** [comment]
DS4 has 5ms by default

**Comment by James-F2** [comment]
Most games poll at VBlank.
So with total latency of 5ms, we have probability of 5/16.7 for the button press to register in the next vblank. 
It's not consistently 5ms of latency,, but a 5/16.7 probability of missing the vblank.

**Comment by rsn8887** [comment]
Can you test in BT mode also? I wonder how much more laggy BT is.

**Comment by James-F2** [comment]
Bluetooth is not HID so it is not affected by this change.
But yes, we measure the BT latency too using Kitrinx's core.

**Comment by rsn8887** [comment]
The official DS4 dongle is USB HID AFAIK.

![76ACC58D-F789-4EF8-86BD-D2F74A0963EB](https://user-images.githubusercontent.com/13071547/69253387-34ebb680-0b7a-11ea-9e7a-f3af5fc2171a.jpeg)

**Comment by sorgelig** [comment]
DS4 supports wired USB connection. This is what can be tweaked by jspoll (with my latest commit). With this adapter i think jspoll will be useless. Basically you can use generic BT dongle.

**Comment by James-F2** [comment]
I've tried jspoll=64 (this is the max), and the DS4 is super laggy.
So I confirm it works... both ways.  :)

**Comment by rsn8887** [comment]
What I like about the adapter, it appears to the host system as a normal USB HID controller (not as a bluetooth dongle), so it is compatible with any OS that supports USB HID.

**Comment by sorgelig** [comment]
This is already outdated.
usb poll is implemented and working.
