### ISSUE TITLE
Add core-specific volume that's retained

### ISSUE THREAD

**Issue by klaritan** [MiSTer-devel/Main_MiSTer#140]
Cores in general have varied volume as they are not normalized to the global volume setting.  Some cores are extremely loud while other cores can become incredibly silent.

User experience would be significantly improved if there's a separate core-specific volume setting in additional to global, but if you believe this clutters a bit, we could just have one volume setting each core.

**Comment by c0d3h4x0r** [comment]
Yes please!

**Comment by sorgelig** [comment]
And then in quiet time you return to the core you played yesterday on party, and get loud sound.
I don't see how it can be more useful than now.

**Comment by c0d3h4x0r** [comment]
I don’t understand what you mean.  It’s not unreasonable to want a way to manually normalize all the cores to approximately equal volumes.  Some cores are just way louder than others, so they already blow me out of my seat sometimes.  That’s why we would like the ability to permanently fix it.

**Comment by sorgelig** [comment]
implemented
