### ISSUE TITLE
How to best use Usb storage and the noexec flag.

### ISSUE THREAD

**Issue by TomFaulkner** [MiSTer-devel/Main_MiSTer#147]
How is the USB storage intended to be used? Seeing that when I chose switch to USB initially I received a message that there were no files, I installed all of MiSTer on the drive, just as it is on the SD card, and this worked. However, when I go to run the `update.sh` script it fails with a permission denied due to the USB drive being mounted with the `noexec` flag.

Is this the intended way to use the switch to USB option? If so, I think removing `noexec` would be an improvement.

If not, what is the intended use?

I wouldn't mind just putting more ROMs there if that is an option.

Love the project, thanks for all the hard work.

**Comment by sorgelig** [comment]
There will be an option to use USB just an additional storage for ROMs. So you still boot from SD card but keep ROMs on USB for some cores. 
In this case exec flag won't be required

**Comment by blackjer** [comment]
Tom,

Do not enable the usb option in the OSD. just put your /games folder in the
USB and leave the rest on the SD card. then its just plug and play like
connecting to USB to any PC.

**Comment by TomFaulkner** [comment]
Thanks
