### ISSUE TITLE
Please consider integer scaling for both axis

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Main_MiSTer#153]
I like clear pixels :) - to avoid un-even lines both horizontally and vertically on LCDs/OLEDs with perfect clarity/sharpness - and avoid any shimmering in scrolling graphics - it would be great to have **integer scaling on both axis**.

Integer scaling vertically is currently possible ... but not horizontally - so sideways **scrolling graphics either change shape** when they move - or **shimmer if e.g. Lancos2_15 scaling is used**. To avoid this **integer scaling could be applied horizontally** too.

It would **change the aspect ratio** slightly in some modes/cores. But I suspect most users probably wouldn't notice - or at least MiSTer users would have **the option of choosing** between the perfect aspect ratio but shimmering graphics with a slight blur - or - slighty wrong aspect but **perfect sharpness without any shimmering**.

I hope you'll consider adding this :)

**THEC64** Maxi actually **has that perfect square pixel mode**.

https://youtu.be/z2GACGEucTI?t=975

![scaling comparison - 02](https://user-images.githubusercontent.com/15096058/71426803-dac99e00-26af-11ea-97e0-03e50e26bedc.jpg)

**Comment by sorgelig** [comment]
This is per-core task. If core is able to provide a perfect 4:3 and/or 16:9 resolution, then integer scaling on Y will automatically transferred to integer scaling on X.

**Comment by dfilskov** [comment]
I see. How come the vscale_mode is not a per core task then?

**Comment by dfilskov** [comment]
And are you sure perfectly square pixels cannot be enforced by MiSTer? (not per-core)
