### ISSUE TITLE
Shortcut to open core when in game osd

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Main_MiSTer#154]
Hi
it's possible to have a shortcut (maybe already exists) to open new core when we are in the osd of a core:
- now we have to press f12, right key, press enter over the core option and it opens the cores selection screen
- the goal is to press only a key (or two keys) and open right away the core selection screen

Thanks

**Comment by sorgelig** [comment]
Alt-F12

**Comment by eubrunosilva** [comment]
how god... how did I miss this? :X thanks :)
