### ISSUE TITLE
MRA Option

### ISSUE THREAD

**Issue by RetroDriven** [MiSTer-devel/Main_MiSTer#155]
Would if be possible or feasible to have an INI Option to hide MRAs that don't have a matching RBF? That way the list of Arcade Cores will be cleaner and more accurate.

**Comment by sorgelig** [comment]
It's time consuming operation. 
I will make it when i will find a good and fast way to do it.

**Comment by RetroDriven** [comment]
Fair enough. It was just something I was thinking about so I figured I'd mention it. It would just be gravy on top of the amazing things you already do. Thank you for all of your hard work.
