### ISSUE TITLE
Can't Skip Stick X: Tilt RIGHT/LEFT when mapping controller

### ISSUE THREAD

**Issue by misteraddons** [MiSTer-devel/Main_MiSTer#158]
Since the (welcome) re-introduction of OK and Back as mappable buttons (separate from A, and B), you can no longer skip the last two button map prompts (Stick X: Tilt RIGHT, and Stick X: Tilt LEFT) by pressing 'Space'. You can skip them by pressing 'Enter'. Possibly an issue with a button number index or integer value not being incremented properly?

**Comment by sorgelig** [comment]
i've pushed the fix. Will be included in next release.
