### ISSUE TITLE
Busy waiting

### ISSUE THREAD

**Issue by newinnovations** [MiSTer-devel/Main_MiSTer#16]
When I look at the top results, I see that that MiSTer takes 50% cpu, which means that one core is running at 100%.

```Mem: 68568K used, 438476K free, 184K shrd, 3596K buff, 48744K cached
CPU:  25% usr  24% sys   0% nic  49% idle   0% io   0% irq   0% sirq
Load average: 1.00 1.01 0.96 2/65 2463
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
  857     1 root     R    20248   4%  50% /media/fat/MiSTer /media/fat/Arcade-MrDoNightmare_20180313.rbf
```

A quick look at the code confirms my suspicion that the process is  indeed busy waiting. Which is unwise from a power consumption and heat standpoint. I was wondering if this is by design?

**Comment by sorgelig** [comment]
This is discussed to the death already. Some discussions you can find on Atari forum.
In short: ARM CPU used in this chip has no power management and thus no sleep/idle states. So it's absolutely doesn't matter if application sleeps or doing empty loops - power consumption and heat production will be the same.
If you don't believe, then you can be just another person who will spend his time for tweaking and measurements to find at the end you just wasted the time.
