### ISSUE TITLE
Ways to contribute / document the repos

### ISSUE THREAD

**Issue by icaroscherma** [MiSTer-devel/Main_MiSTer#160]
Hi @sorgelig , I'm enjoying this project as a __player__ but I want to get into it as a __developer__.

- What do you suggest to __start coding__ for MiSTer? I mean important things that someone might want to know before spending lots of hours on some basic errors / debugs, a basic IDE configuration for it.
- Do you have a to-do list? Or a list of bugs or wishlist?
- Can I organize the repo following the github guidelines? For instance using github releases*. I noticed 2 other closed issues related to this but no one was volunteering, like I am now.

_*_  https://help.github.com/en/github/administering-a-repository/creating-releases (step 7)

Is there any other "administrative" thing that is time consuming that I might help streamline it for you? While I learn the basics of the project.

**Comment by sorgelig** [comment]
Hi,
I don't want releases feature. It's not streamlined at all. Current way is more streamlined as release can be easily pushed by git without messing with github website. Also released files ara always comes with repository, so always available for those who cloned and pulled the repo locally without going to github.

As for Wiki - it's opened for editing to everyone. So you can add info you think can be useful.

**Comment by icaroscherma** [comment]
And about the first 2 questions...

**Comment by sorgelig** [comment]
1) I suggest to play with existing cores. Pick the one you like and try to understand the code. Almost all cores have room for improvements, so you can try to improve. May be from small changes unless you will get familiar with it.
2) There are no written to-do list. It's hobby project developing spontaneously depending on current needs or mood. Cores are independent on each other and follow their devs (if any).
