### ISSUE TITLE
Scanlines don't apply currectly using custom filters over HDMI when forced_scandoubler=1 

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/Main_MiSTer#162]
Scanlines don't apply currectly using custom filters over HDMI when forced_scandoubler=1 
I have to use that option because I am also using a CRT monitor (as opposed to a TV) and that doesn't work over a 15Khz analog output.

Filters do have an effect but there are no separation rows between lines (and thus no scanlines) over HDMI when selecting a scanline filter while this option is set to 1 in Mister.ini

The Scandoubler fx option does work to add scanline but that applies over both the VGA and HDMI output (and obviously the CRT monitor connected through VGA already has scanlines of its own), there is no option to only apply scandoubler fx to a specific output.

Setting forced_scandoubler=0 fixes the scanlines issue through filters over HDMI but renders the CRT monitors through VGA inoperable.

**Comment by sorgelig** [comment]
MiSTer never positioned as dual output device. There are many things (and resource saving wise) preventing dual output. So you have to choose to use either HDMI or VGA and still to that. 
Not an issue.

**Comment by sorgelig** [comment]
Filters are working per line and per pixel. More lines and pixels - less visible effect of scanlines and LCD. So obviously you have to avoid the scandoubled video for better effect.

**Comment by mathieulh** [comment]
That's obviously a bug, you can't say "it's not an issue" just because "MiSTer never positioned as dual output device."

**Comment by mathieulh** [comment]
> Filters are working per line and per pixel. More lines and pixels - less visible effect of scanlines and LCD. So obviously you have to avoid the scandoubled video for better effect.

That's the thing, it's not about "less visible effect of scanlines" there are no scanlines to begin with while using filters and forced_scandoubler=1 (which should have no effect over HDMI output), not visible to the naked eye at the very least.

**Comment by sorgelig** [comment]
> That's obviously a bug, you can't say "it's not an issue" just because "MiSTer never positioned as dual output device."

Not an issue means "nothing to fix" as it's supposed to work this way. You may accept it or not - it's up to you.
