### ISSUE TITLE
[question] Have you ever dealt with De10-Nano crashing when FPGA is turned off?

### ISSUE THREAD

**Issue by yurivict** [MiSTer-devel/Main_MiSTer#164]
Sorry for the question not related to the MiSTer project. -)

I am trying to bring up the De10-Nano board to run the WMware Cascade FPGA compiler.
However, the board crashes when the FPGA control is switched to HPS and then the FPGA is turned off.

These 2 commands from this sample project https://github.com/nhasbun/de10nano_fpga_linux_config cause the board to crash and reboot:
```
./fpga_rbf_load set_ctrl_en 1
./fpga_rbf_load fpga_off
```
 
Have you ever encountered such situation by any chance? It seems like the FPGA is already used by something and turning it off causes something important to fail.

**Comment by sorgelig** [comment]
Sorry, i have no time to support other projects. Please ask there.
