### ISSUE TITLE
Under development: PDP-6 and PDP-10

### ISSUE THREAD

**Issue by larsbrinkhoff** [MiSTer-devel/Main_MiSTer#165]
Hello,

@aap has written HDL for the PDP-6 and PDP-10 mainframes.  They run on a DE10 nano board.

**Comment by larsbrinkhoff** [comment]
CC @hrvach.

**Comment by sorgelig** [comment]
If you want to discuss about these cores, then it's better to discuss on forum. Issue is not a right place for general talk.

**Comment by larsbrinkhoff** [comment]
Thank you.  I didn't intend to start a discussion, but I can post to the forum too.
