### ISSUE TITLE
Release 20200122 issue. 15khz CRT screen crashed.Mister no longer loads the menu... :(

### ISSUE THREAD

**Issue by Titofff** [MiSTer-devel/Main_MiSTer#167]
Again, lost the menu with this version. Screen unstable and no menu.

**Comment by Titofff** [comment]
it seems it was my linux folder...sorry.

**Comment by vpelletier** [comment]
I also lost my /linux folder in this upgrade, and had to recreate it from SD-Installer-Win64_MiSTer archive. I also lost the system configuration (which services are enabled, timezone, ssh keys...), which I guess is stored in it.

So I think this bug report should be kept open, as there may be a bug to fix. Maybe vFAT isn't shutdown cleanly ?

For reference, in my case the µSD is large (128G). Cyclone V family supports SDXC, so it should be unrelated, but posting just in case it helps narrowing down the common denominator of affected installations.

**Comment by sorgelig** [comment]
It's most likely related to updater script.
Also enabling many options providing frequent writes (recents, save backup RAM when menu opens, etc) increase risk of corruption. This is why all these options are off by default.

Nothing to do with Main anyway.
