### ISSUE TITLE
Wiki: Direct Video

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-devel/Main_MiSTer#169]
Hi,

As I've commeted in the Wiki thread from the forum, I took some time to write some Wikis about Direct Video.

Here is a commit you could use: https://github.com/theypsilon/MiSTer-wiki/commit/426dcabb71c322f110b482862c8a533303c6bbcf

**Comment by sorgelig** [comment]
Looks good. You can add your Wiki change directly.

**Comment by theypsilon** [comment]
Ok, I've done it. There is one thing missing though. I don't know how to add pictures to the wiki repository with direct editing (and I'm not allowed to push to the wiki repository).

So these two pictures are missing:
https://github.com/theypsilon/MiSTer-wiki/blob/direct_video/pictures/direct-video-dac.jpg
https://github.com/theypsilon/MiSTer-wiki/blob/direct_video/pictures/sync-on-green-circuit.png

If somebody could upload them to the wiki 'pictures' folder, it would be great.

**Comment by sorgelig** [comment]
done
