### ISSUE TITLE
Sharp MZ Series Core

### ISSUE THREAD

**Issue by pdsmart** [MiSTer-devel/Main_MiSTer#17]
Hi Sorgelig,

As per your message, please regard this issue as identification (and not an issue).

I should be in a position to upload the dev in the next week or so (beta version), albeit it is undergoing continuous development as I intend to add the FDC for the MZ80K/A/700 and additionally develop the new machines MZ80B/MZ800. I am making it all as one emulation with configuration albeit the MZ80B will be a seperate sub-module.

Many thanks in advance,

Brgds,

Philip

**Comment by sorgelig** [comment]
You've got invitation you need to accept. And then you will be able to create your repository in MiSTer-devel group.
Please follow a common naming rule <core_name>_MiSTer

**Comment by pdsmart** [comment]
Hi Sorgelig,


Many thanks, will setup everything over the next week.


We use Git/Gitlab internally and I've used Github just for pulls, so will take my time to make sure all is set correctly and the namng for the repository is noted.


Many thanks for your time and help,


Philip

________________________________

**Comment by pdsmart** [comment]
Hi Sorgelig,

I have uploaded my current code to github which is an early beta snapshot level. As I have made changes (2 additional files and some hook code in menu.cpp/user_io.cpp) in Main_MiSTer, what is the procedure you are using for making updates? On Wednesday I cloned the latest copy and merged my changes locally into it, so as it stands I have an up to date code set. Do you create a branch, then merge or do you work directly on the master branch?

Many thanks for your time and help,

Brgds,

Philip

**Comment by sorgelig** [comment]
You need to fork required repository to your own. Make a changes you want, then make pull request to my repository.
Start it from forking on github - you will see the "fork" button on upper right corner in Main_MiSTer repository. This will bind your fork with my repository. Then after changes you will be able to make a pull request.

**Comment by pdsmart** [comment]
Hi Sorgelig,

Ok, will look to do this when Im physically back at my dev machine.

I noted your comment about 8Bit. The menu system I’m using is more than 8Bit could provide, more like Archie/Amiga where you have a lot of configurable options, hence putting them in a separate file.

Ive attached snapshots of the menu below. Once Ive added Floppy Storage that will be another menu item needed, for what Im trying to develop, the 8bit menu wasn’t sufficient.

Brgds,

Phil


[image1.jpeg]

[image2.jpeg]

[image3.jpeg]


[image5.jpeg]

[image6.jpeg]

[image7.jpeg]

[image8.jpeg]

**Comment by pdsmart** [comment]
Hi Sorgelig,

Points noted from the merge. I'm not sure why GitHub shows no differences (other than those intended) before a Pull Request, but thank-you for the hard work resolving it.

I note your comments regarding the MiSTer binary, my intention is to create a standalone emulation where everything is done within the fpga (with a layer on top which MiSTer provides to setup/load files), but as you rightly point out, it is, in hindsight, too much code for the intended project goals. I will look to create a light version for the public release and a full version for my private use.

**Comment by sorgelig** [comment]
Since the code is merged already, there is no point to cut it down.
It's not about restricting the functionality. It's about encapsulating the functions in the core. MiSTer ARM code is mostly for basic functionality common for all cores. Specific implementation must be done in the core. Sharp core isn't big and can include for example ZPU core with its code like some cores have (Atari 800 for example). So, Atari 80 specific code is inside the core and can be updated independently later.
But sometimes it's OK to put some code on ARM side like TZX and SCL file support.
