### ISSUE TITLE
Feature Request: Only use the scandoubler on one output while using both the direct video and IO board analog out at the same time

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/Main_MiSTer#170]
Because it is possible to have 2 analog outputs at the same time, one over direct video (through hdmi) and the other using the IO board, would it be technically possible (and if so, is it something considered) to add the possibility of using the scandoubler on only one of the outputs? (currently it is only possible to enable or disable it for both output?)

I intent to connect both a VGA CRT PC monitor (which requires the scandoubler) and a SD CRT Television (which does not work with scandoubler enabled) at the same time.

**Comment by sorgelig** [comment]
This is not possible without great re-write of framework. Both direct video and VGA use the same resources like OSD, Scaler (in case of Linux video output) and the whole video path. And there is no plans to make such big changes.
