### ISSUE TITLE
Not being given the option to map menu button, mouse inputs etc.

### ISSUE THREAD

**Issue by girlsperhour** [MiSTer-devel/Main_MiSTer#171]
I have a bare DE10-Nano running MiSTer v200202, OS v200122. I'm connected via a single-port OTG adapter switching between a generic keyboard and an XB1 Hori Fighting Commander.

When joystick mapping from the boot core, it eventually asks me to test Stick 2. I know the controller is read as an Xbox 360 controller (or Xbox One, but I have the slider set to 360), but the Fighting Commander doesn't allow control over two sticks. You can set the D-pad to behave as a D-pad or a left stick. That's it.

So when it prompts me to test Stick 2, I swap to the keyboard and skip it with the space bar, then swap back to the gamepad and continue with mapping the pad. I get as far as the basic buttons (pad, face buttons, sel + start and the shoulders) and then it finishes without offering me the option to map the OSD menu button or any of the other stuff. I REALLY want to map that button.

I've been able to map everything on my Hori RAP V Kai no problem, on account of it DOES allow the stick to behave as a D-pad, left or right stick, so I didn't need to swap and skip any of the steps.

Can this issue be remedied somehow?

**Comment by sorgelig** [comment]
MiSTer needs a HUB when both joystick and keyboard can be connected at the same time. Then you will be able to map the joystick normally.
When you punplug the joystick (to plug the keyboard) all information about the josytick get vanished. What you are doing is incorrect. You cannot unplug the joystick once you started to map it till you finish mapping and config got saved.

**Comment by sorgelig** [comment]
It's not an issue. Use Forum for discussions.
