### ISSUE TITLE
Access external USB drives via Samba

### ISSUE THREAD

**Issue by akudaikon** [MiSTer-devel/Main_MiSTer#176]
Would it be possible to get access to any external USB drives via Samba? Right now the Samba config only shares /media/fat. The only way to access drives at /media/usb# is to use FTP, which doesn't seem to be working for me. Now that CD systems are starting to get support and people are resorting to external HDs/SSDs for more space, maybe changing the Samba share to just /media would be beneficial?

As I mentioned above, logging in via FTP and trying to access my drive at /media/usb0 gives me a "/media/usb0: No such file or directory" error. The MiSTer is happily reading roms from the drive, and if I log in via SSH I can traverse through the files on that mount point just fine. Only trying to access it via FTP seems to be an issue.

**Comment by sorgelig** [comment]
You can edit the file /etc/samba/smb.conf  and add required folders

**Comment by akudaikon** [comment]
I thought I read that the linux filesystem was mounted as read-only, but I guess that's not the case. Thanks!
