### ISSUE TITLE
Release 20200308 may have broken input config saving

### ISSUE THREAD

**Issue by michaelshmitty** [MiSTer-devel/Main_MiSTer#178]
# How to reproduce
With a clean MiSTer release 20200308:
- With keyboard hit F12 and go to 'Define joystick buttons'.
- Joystick is detected, map your keys, skipping some unnecessary ones, make sure to define the OSD keys (menu ok, menu back, etc.). Notice keys work and are detected during mapping process.
- Once mapped, joystick is not responsive in menu.
/media/fat/config/input seems to be non-existent.

Go back to release 20200307, repeat process above: works as expected.

Issue might have something to do with https://github.com/MiSTer-devel/Main_MiSTer/commit/1ba97325e47e780e1393f965eafaa86333daed60
Perhaps the info config is accidentally deleted? Just guessing here.

Many thanks for all your work on MiSTer.

**Comment by aikon82** [comment]
I'm getting the same issue after attempting to map the controller. I've tried 2 different ibuffalo controllers and also a wired 8bitdo SNES controller and am unable to control the menu with any joypad.

**Comment by sorgelig** [comment]
i've fixed the problem. Source code is updated. 
I didn't release it yet.

**Comment by michaelshmitty** [comment]
Fixed in upcoming release.
