### ISSUE TITLE
Automatically start the latest game played when launching a core

### ISSUE THREAD

**Issue by onthewaveagain** [MiSTer-devel/Main_MiSTer#179]
It would be great to have a feature where the latest game played on a specific core would  systematically start when the particular core is launched.
 
In other words, the corename.rom feature but dynamic.
That could perhaps be implemented through a symbolic link with the existing corename.rom feature. Just an idea.

This would reproduce the behavour with a real console hardware where once you slot a game in, it always starts as you power your system up and until you swap the game with another one or remove the cartridge.

**Comment by zakk4223** [comment]
I actually got about 90% of the way through implementing something like this; it abused the Mister's "recents" feature to restore the state of what was previously loaded into the core. 

Unfortunately there are too many cores where the 'last state' is not immediately obvious without more information. Something like the TG16 core has two 'load' entries, and they both load carts (of different types) and can't both be 'selected'. You can kinda fake it by just looking at the last modified date of the recent files, but that's just a core special case. A lot of the computer cores have similar problems. There's no good way to track 'unloads' and in many of the computer cores resetting it is how you accomplish 'unloading' a disk/cart etc.

Cores that don't have issues like this? It works great. 

It might be doable to ship it with an 'autoboot' config file/option that let you 
1) opt-in a core for auto-restore
2) exclude certain loadable types on a per-core basis (i.e don't restore input number #3 on this core)
3) indicate when inputs should be 'grouped' and only the most recent one restored (I suspect this is only relevant for the TG16?)

The Mister could ship a config file for all the official cores that defines the correct behavior. If users download unofficial cores they can add entries to the config if they'd like.

As you can see, it turns into a bit more of an annoying problem than you'd initially think.

**Comment by sorgelig** [comment]
This is why it's good to leave it as it's is now. I already know the problems with auto-load.
With recents you just have to open OSD (one button press) and then press Select button while on Load option then press OK in the recents.  So totally 2(if OSD opened automatically)-3 button presses.

And no - i'm not going to implement half-solution where some cores will be able to auto-load and some not. This is not a professional solution and won't be implemented.

**Comment by ghorricks** [comment]
Do all cores use a boot.rom or is that a half solution?

**Comment by Em-K-IronFist** [comment]
I would like to propose a compromise solution. This would only save a few more extra button presses, but some people might really like it: what if we had an option to automatically show the `recents` list upon core startup? That way we could have the next best thing to autobooting the last game but without the technical issues that would come with it.

It might sound silly and unnecessary but popular emulators like Mesen start with a recents list by default, so it might be worth it to consider.

**Comment by sorgelig** [comment]
Some cores have several entries to open different kinds of ROMs or mount different kinds of images.
Some console cores are already open OSD at startup, so it's just a matter of pressing "select" button or move to other option.

**Comment by onthewaveagain** [comment]
Would be a nice compromise. The recents option already exists in the mister.ini. there could be an additional option to automatically bring the recents list when a core starts instead of the default menu. This should however be a per core option.

**Comment by sorgelig** [comment]
There is a good idiom:
"Make the thing when even idiot will be able to use, and only idiots will use it."
I'm against rail road of use. It implies only one specific usage scenario. And usually it implies lazy-man scenario. Not everyone likes it. And i'm the first who don't like it.
MiSTer gives enough conveniences to do things fast without rails.

**Comment by Em-K-IronFist** [comment]
That's fair. I'm happy with the current of state of things with the `recents` menu anyway. :)

**Comment by onthewaveagain** [comment]
Closed as the recents menu  is convenient enough to mimic the feature requested.

**Comment by vertexmachina** [comment]
@zakk4223 Would you mind please sharing that 90%? I would like to implement this features at least for my own local use even if it never gets merged back in.

**Comment by ludzeller** [comment]
@vertexmachina Could you please share your implementation? Can you still use the update scripts or would you rather merge by hand then in order not to loose your local changes?
