### ISSUE TITLE
Surprise me

### ISSUE THREAD

**Issue by sacredbanana** [MiSTer-devel/Main_MiSTer#182]
Nowadays we are spoiled for choice with what to play for we have thousands of ROMs spanning multiple platforms. How difficult would it be to add a surprise me feature that loads a random game from a random core?

**Comment by sorgelig** [comment]
such feature should include this issue:
https://github.com/MiSTer-devel/Main_MiSTer/issues/179
It's already answered there why it's hard to implement.
