### ISSUE TITLE
Use the mini USB ports

### ISSUE THREAD

**Issue by mortaca** [MiSTer-devel/Main_MiSTer#183]
Hello, I have searched the rest of the open and closed issues and I have not seen anything, why the two mini USB connectors are not being used? if they can be controlled from the FPGA they could be used to control the keyboard or an external memory and avoid using a hub.

**Comment by sorgelig** [comment]
If you don't have airplane, it doesn't mean you can use car to fly.
With de10-nano you should have the paper sheet showing which port has which function. Or you can go to Terasic website and download the whole CD with full documentation.
