### ISSUE TITLE
REQUEST: Alternate Screenshot Key

### ISSUE THREAD

**Issue by farhanjiwani** [MiSTer-devel/Main_MiSTer#184]
My compact keyboard doesn't have a `print scr` key like all my previous ones.

Can we get an option to bind it to another key or button?

OR

Is there a way to do this already which is undocumented?

**Comment by sorgelig** [comment]
Use keyboard remap function in Menu core to map any key to PrnScr.

**Comment by farhanjiwani** [comment]
Sorry for the late response, this pandemic sucks.

Anyways, thank you! I connected 2 keyboards and that worked perfectly.
