### ISSUE TITLE
<part> doesn't parse single digit numbers

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#186]
MiSTer MRA parser seems to parse wrongly single digit numbers:

``` <rom index="1"><part> 1 </part></rom>```

fails; whereas:

``` <rom index="1"><part> 01 </part></rom>```

works.

I think that a regular `scanf` would accept both cases so I wonder what went wrong there.

**Comment by sorgelig** [comment]
The numbers are supposed to be a hex dump, so it's expected to have 2 digits per item.

**Comment by sorgelig** [comment]
closing as it's not an issue (it's hex dump, not number)
