### ISSUE TITLE
NeoGeo memory issue when used as bootcore=lastcore

### ISSUE THREAD

**Issue by ghorricks** [MiSTer-devel/Main_MiSTer#192]
bootcore=lastcore
When used for NeoGeo with 128MB RAM the error message when loading a ROM from a set says: "not enough memory graphics will be corrupted"
If loading the menu and then trying again, the issue is not present.

**Comment by sorgelig** [comment]
Because you have to load Menu core first.
bootcore is more like hack, not really a proper way to use MiSTer.
There is nothing to fix as it's interfere proper work.
