### ISSUE TITLE
REQUEST : Mister Logo - Custom X&Y to allow custom backgrounds to be better displayed.

### ISSUE THREAD

**Issue by ghorricks** [MiSTer-devel/Main_MiSTer#193]
I may not have the correct code which needs to be addressed, but in video.cpp : line 1283

imlib_blend_image_onto_image(logo, 1,
					0, 0,         //int source_x, int source_y,
					src_w, src_h, //int source_width, int source_height,
					dst_x, dst_y, //int destination_x, int destination_y,
					dst_w, dst_h  //int destination_width, int destination_height
				);

It would be good if it could use a custom X and Y (from the MiSTer.ini) so that people who wish to relocate the logo can do so to be positioned on their custom background better.

**Comment by sorgelig** [comment]
option to hide logo has been added, so logo can be embedded on wallpaper if required.
