### ISSUE TITLE
REQUEST : Assign ROM as BOOT.ROM

### ISSUE THREAD

**Issue by ghorricks** [MiSTer-devel/Main_MiSTer#194]
While using the bootcore=lastcore, it is great to be able to continue using the last used core. The only issue I have here is that it would be great to be able to continue where I left off.
So if there could be a way to "Set current rom as boot.rom", this option could potentially copy the file to be a boot.rom file... or, perhaps the path could simply be contained in text file somewhere, and then loaded if set, bootromPath.txt?

I have used the recents, and understand the number of button presses to load manually.
The recents appears to slow down the menu with a lot of lag for me.

I appreciate that there are other requests regarding a similar feature:
https://github.com/MiSTer-devel/Main_MiSTer/issues/179

**Comment by sorgelig** [comment]
there is already similar request. Don't make another one.
It's development area, not chat or forum.
