### ISSUE TITLE
Full recents list (16) causing problems with menu 2 key combination

### ISSUE THREAD

**Issue by ghorricks** [MiSTer-devel/Main_MiSTer#195]
Using SNES core with full list of 16 recent recent games.
My MENU combination is SELECT+START on a USB Arcade Stick.
Once i have loaded a game from Recents, just pressing START on its own is opening up the MENU.
This is reproducible every time.

**Comment by sorgelig** [comment]
I cannot reproduce it.
May be it's related to specific controller. 
Try to assign other combo like DPAD Up + Select.
