### ISSUE TITLE
NeoGeo Samurai Spirits 4 Power bars

### ISSUE THREAD

**Issue by MonokromFR** [MiSTer-devel/Main_MiSTer#197]
Hi. I have seen the upper rectangle power bars's verticals lines are doubled than the original hardware is single line.
Look at the demo mode, issu happens when power bars are static. When a hard blow is done by fighter, bars are normally bouncing a couple of time but with no doubled line.

Thanks!
(using NEOGEO 20200325)

**Comment by MonokromFR** [comment]
[https://image.noelshack.com/fichiers/2020/16/4/1587067378-ss4-2.jpg](url)

**Comment by MonokromFR** [comment]
https://image.noelshack.com/fichiers/2020/16/4/1587067378-ss4-2.jpg

**Comment by sorgelig** [comment]
Not a Main issue.
