### ISSUE TITLE
Todays release breaks CPS1 Support

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/Main_MiSTer#199]
black screen / freezes MISTer

**Comment by PhantombrainM** [comment]
It seems only some games are broken:

suvermanheute um 15:12 Uhr
I never ran Mega Twins before but it hangs in Joystick 1 screen like PhantombrainM said
Varth hangs as well
but Megaman is working

gomadosnitroheute um 15:14 Uhr
i tested with 417 and 418 and black screen after updated last mister main
SF2 not working
SF2 HF works for me
SF2 CE also is working

**Comment by ctafield** [comment]
Same here. Seems to cause it to lock up on the "kbd mode: joystick 1" screen. Tested here with Final Fight, and SF Alpha.

**Comment by sorgelig** [comment]
All this is related to a single CPS1 core, not to Main. So open issue on CPS1 repo.

**Comment by PhantombrainM** [comment]
To be clear... Mister MAIN is breaking CPS1.

MiSTer_20200325 -> works
MiSTer_20200419 -> breaks support

So it's a Main problem and not a CPS1 problem.

**Comment by sorgelig** [comment]
No, It's because CPS1 doesn't use standard framework.
Take ZX Spectum core - it works. Take other arcade cores like MCR - they all work. And all of them released long ago before Main change. 
If only one core breaks, then problem is in the core.

**Comment by PhantombrainM** [comment]
Thank you for clarification!
Closed.
