### ISSUE TITLE
Issue in mra processing

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Main_MiSTer#200]
Hi
after the last update there is some kind of issue processing some mra files.
Mister stops processing files and it hangs (must reboot with button)

the example that I attach, if i remove this part, mister process well all the remaining files:
`
        
        <part name="41_9.12b" crc="0f9d8527"/>
        
        <part name="41_18.11c" crc="d1f15aeb"/>
        <part name="41_19.12c" crc="15aec3a6"/>
`

this mra works with MiSTer_20200325 and with MiSTer_20200419 if I replace romutils.cpp with 2020325 version

Thanks

[1941  Counter Attack -World 900227-.txt](https://github.com/MiSTer-devel/Main_MiSTer/files/4499993/1941.Counter.Attack.-World.900227-.txt)

**Comment by sorgelig** [comment]
i've pushed the fix against crash but i cannot test it fully as version of cps1 i have seems too old.

**Comment by Chocobobobo** [comment]
It is working properly with latest CPS1 0417 version with all the games I checked so far, thanks Sorg.
Any chance you could make a release version with this commit? Thanks in advance.

**Comment by eubrunosilva** [comment]
hi. yes. its looks ok :)
