### ISSUE TITLE
bootcore setting is broken

### ISSUE THREAD

**Issue by zakk4223** [MiSTer-devel/Main_MiSTer#205]
Looks like the bootcore (lastcore etc) was broken a few weeks ago.

Bisect tells me this commit is the issue: 547e101524f25efb399ddb8e1d745c5f85e0d8ed

The autoboot is being immediately cancelled at menu.cpp line 886

**Comment by zakk4223** [comment]
A bit more info (with updated line numbers): It is being canceled by KEY_F12 UPSTROKE at line menu.cpp:908. The UPSTROKE key is generated from menu.cpp:964.

I can fix it by either setting the Timer in menu_key_get to zero, or adding a test of the release flag to line 908.

if (!release && c && c != KEY_F12 && cfg.bootcore[0] != '\0')

I would assume this is the better solution since I can't imagine the GetTimer was added for no reason.

**Comment by sorgelig** [comment]
if it solves the issue and doesn't make other then ok.

**Comment by sorgelig** [comment]
it's already fixed
