### ISSUE TITLE
Scan doubler issue

### ISSUE THREAD

**Issue by calle81** [MiSTer-devel/Main_MiSTer#214]
A few arcade cores does not produce a picture with the scan doubler enabled on 31 khz screens connected over VGA to to the IO-board, unless you set direct video to true. This happens with for example Xevious and Pac-man.

The error message on screen is out of range.

The work around is to enable direct video but that means you cannot use HDMI and VGA at the same time for the affected cores.

**Comment by sorgelig** [comment]
in OSD, set orientation to Horizontal, then scandoubler should work.

**Comment by calle81** [comment]
Thank you! I can confirm this solves the issue with Pac man and Xevious.

I still have the same error with Jotego's CPS cores and changing orientation does not help but I know he uses his version of sys so I will close this.
