### ISSUE TITLE
Error compiling last changes @sharpmz

### ISSUE THREAD

**Issue by Renaud-Pagin** [MiSTer-devel/Main_MiSTer#22]
Hello,

`
xxxxx@xxxxxx:~/FPGA/mister-fpga/Main_MiSTer$ make
sharpmz.cpp
In file included from /usr/arm-linux-gnueabihf/include/fcntl.h:289:0,
                 from sharpmz.cpp:34:
In function ‘int open(const char*, int, ...)’,
    inlined from ‘int sharpmz_file_write(fileTYPE*, const char*)’ at sharpmz.cpp(67, 20):
/usr/arm-linux-gnueabihf/include/bits/fcntl2.h(50, 26): error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
                          ^
In function ‘int open(const char*, int, ...)’,
    inlined from ‘int sharpmz_file_write(fileTYPE*, const char*)’ at sharpmz.cpp:67:20,
    inlined from ‘short int sharpmz_read_ram(const char*, short int)’ at sharpmz.cpp(1576, 28):
/usr/arm-linux-gnueabihf/include/bits/fcntl2.h(50, 26): error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
                          ^
In function ‘int open(const char*, int, ...)’,
    inlined from ‘int sharpmz_file_write(fileTYPE*, const char*)’ at sharpmz.cpp:67:20,
    inlined from ‘short int sharpmz_save_tape_from_cmt(const char*)’ at sharpmz.cpp(1917, 40):
/usr/arm-linux-gnueabihf/include/bits/fcntl2.h(50, 26): error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
                          ^
Makefile:37 : la recette pour la cible « sharpmz.o » a échouée
make: *** [sharpmz.o] Erreur 1
`

Ubuntu 16.4 / x64 / Xenial LTS.
Arm version : gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) 

Quick & dirty fix :

in file sharpmz.cpp 

  - file->fd = open(fullPath, file->mode);
 + file->fd = open(fullPath, file->mode, 0600); 

 owner can read and write

Regards

**Comment by sorgelig** [comment]
I think it's compiler version related. I have no such error.
sharp code is not mine, so i cannot provide quick fix now. You can check it with Sharp MZ core author.

**Comment by Renaud-Pagin** [comment]
I added fix in my post , to add the 3rd arguments missing, once you add the
right file mask ( added 0600 by default )
Compilation is ok.

**Comment by pdsmart** [comment]
Hi,

The mode parameter is optional, ie: Function: int open (const char *filename, int flags[, mode_t mode]) from the GNU library definition, it takes your sessions umask value if not defined. Best I add the explicit mode to my code as you have done to avoid platform/version differences.

Thank-you for this, I will also check for other 'assumptions' I've made and correct them.
