### ISSUE TITLE
"Undefine" command mislabeled in button mapping menu

### ISSUE THREAD

**Issue by Em-K-IronFist** [MiSTer-devel/Main_MiSTer#220]
I heard that the way to skip a button or axis in the mapping dialogue is now the `user` button rather than the OSD/`menu` button; I also noticed the OSD/`menu` button exits the mapping dialogue completely. However, the text for the mapping dialogue incorrectly still says:
```
Space/Menu > Undefine
Menu-hold > Cancel
```

Shouldn't it be something more like this?
```
Space/User > Undefine
Menu > Cancel
```

**Comment by sorgelig** [comment]
Menu is the button you defined as "Menu" on controller. So, it's correct.

**Comment by Em-K-IronFist** [comment]
Ok. So the buttons listed do not apply to IO buttons at all?

**Comment by sorgelig** [comment]
The label doesn't apply for I/O board OSD button. 
But user button also can be used to skip/clear map.

**Comment by Em-K-IronFist** [comment]
Great to know. Thanks again!
