### ISSUE TITLE
New "display 2 lines for long files" feature pushing items off of list.

### ISSUE THREAD

**Issue by doublescand** [MiSTer-devel/Main_MiSTer#223]
When scrolling in osd items at the bottom of list gets pushed off and are not displayed. [Look at the last item in list when watching this video.](https://gfycat.com/specificdemandingbarnacle)

Is the first line supposed to scroll like that when the second line is static? Looks very out of place.
Possible to put option in ini for 1-line scroll or 2-line static file names?

**Comment by sorgelig** [comment]
that's definitely a bug.
i will investigate.

**Comment by James-F2** [comment]
Yes this is quite distracting.
1-line scroll (like it was) is good for me.

**Comment by eubrunosilva** [comment]
@James-F2 in mister.ini:

; Uncomment following option if you don't want to see a second line for long file names in listing.
;browse_expand=0

**Comment by gnadenlos** [comment]
two lines are a good option, but the first line shouldn't scroll if we use two lines.

**Comment by sorgelig** [comment]
it's feature by design. Some names may be longer than 2 lines.
Anyway, original bug is fixed already.
