### ISSUE TITLE
Sidebar linked 1943 arcade core repo is "disabled" but not removed from sidebar

### ISSUE THREAD

**Issue by aberusugi** [MiSTer-devel/Main_MiSTer#229]
Currently the sidebar arcade cores list links to a 1943 core. That core's repo is disabled (https://github.com/MiSTer-devel/Arcade-1943_MiSTer/issues/9#event-3360313433) and has lagged behind in arcade core MRA format standardization.

Also, the original creator (?) of the core seems to have his own newer expansion of that previous core (https://github.com/jotego/jt_gng) that is more fully fleshed out in the works that might be an appropriate substitute to link to, but it's not officially part of the MiSTer-devel project, so that might not be appropriate. jotego seems to close the last few recent issues with a referral to their jt_gng core (https://github.com/MiSTer-devel/Arcade-1943_MiSTer/issues/6) - (https://github.com/MiSTer-devel/Arcade-1943_MiSTer/issues/2).

**Comment by sorgelig** [comment]
ok. fixed.
