### ISSUE TITLE
Proposal: Create a 'releases' or 'binaries' repo, which has the latest version of all cores/files.

### ISSUE THREAD

**Issue by coughlanio** [MiSTer-devel/Main_MiSTer#23]
Similar to how the MiST project does it, it would be nice, as more, newer users come to the platform, that they can go to a single repo to bootstrap the MiSTer environment.

Thoughts?

**Comment by sorgelig** [comment]
I have no time for this

**Comment by rattboi** [comment]
Delegate it to others?

**Comment by Newsdee** [comment]
Anybody is free to volunteer and do it.
