### ISSUE TITLE
Console messages for "repeat" in mra

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Main_MiSTer#231]
Hi

I have this in console:
```
302572: data (1 bytes) from xml
302572: file: /media/fat/_Arcade/hbmame/captcomm.zip/cc_09.11a, start=0, len=0
```

that first line comes from:
<part repeat="‭1039054‬">FF</part>

should the next start address (2nd line of the example) be the current address + (the number of repeats x number of bytes in part) and not the same address?

**Comment by sorgelig** [comment]
I think it's already fixed. Next address already includes the total amount. The amount of bytes will be displayed correctly in next release.
