### ISSUE TITLE
SP/DIF digital audio through IO board seems to be broken in the latest release

### ISSUE THREAD

**Issue by akerasi** [MiSTer-devel/Main_MiSTer#235]
Although I haven't tested the previous release, was previously running on the 4.29 release, after update my SP/DIF audio through my IO board does not function; analog audio through the IO board functions fine, and digital functioned fine prior to update.

**Comment by sorgelig** [comment]
Main doesn't handle the audio from core. It's solely core specific. 
Also make sure you didn't flip any switches on de10-nano.

**Comment by sorgelig** [comment]
This problem is more about SPDIF jittering and subject to improve in cores later. 
Not related to Main.
