### ISSUE TITLE
HDMI signal does not sync after ini file switch.

### ISSUE THREAD

**Issue by sigismond0** [MiSTer-devel/Main_MiSTer#238]
As of MiSTer_200601, HDMI signal appears not to sync after switching to an alt_ini file.

My setup;
mister.ini - [Menu] block with vga_scaler=1, and custom video_mode
mister_alt_1.ini - No custom menu block, no vga_scaler, video_mode=10

On all MiSTer_main releases 200529 and earlier, I could freely toggle between these two ini files, and the HDMI output would always sync immediately on alt_1 or show garbage on the main ini.

As of 200601, it shows garbage on mister.ini as expected, then blacks out and says no signal on alt_1.  If I launch a core and exit back to the menu, the display shows correctly.  If I switch back to mister.ini and then back to alt_1, it blacks out again and requires a core to be launched to generate a signal.

I just rolled back to 200529 and confirmed it is working the way I remembered, so it appears something must have changed in this latest release to cause this.

**Comment by sorgelig** [comment]
I cannot reproduce the issue.
It works fine to me. Probably it's specific to your setup/TV.

**Comment by sigismond0** [comment]
Yeah, I just tested again on my setup and it seems to work as expected.  Will close this out and see if I can come up with any other way to replicate.
