### ISSUE TITLE
Multi-line filename at end of list wraps around to top of screen

### ISSUE THREAD

**Issue by sigismond0** [MiSTer-devel/Main_MiSTer#239]
See attached image.  If the final item in the menu list is a long name, it will not wrap down to a second line, but instead tries to write the second line somewhere at the top of the menu.

![p](https://user-images.githubusercontent.com/51833276/83811719-f7ff9100-a67f-11ea-9ffd-e8f9f8792d5a.jpeg)

**Comment by sorgelig** [comment]
will be fixed in next release

**Comment by sorgelig** [comment]
fixed
