### ISSUE TITLE
Transferred my MiSTer bootstrap tool written in Go to the organization.

### ISSUE THREAD

**Issue by coughlanio** [MiSTer-devel/Main_MiSTer#24]
I was previously asked to move over my bootstrap tool that I wrote in Node.js, but I've recently restarted a port to Golang, which theoretically will be able to run on the MiSTer itself without requiring any additional dependencies.

Would it be possible to get admin rights to the repo so I can continuing building on it, handling issues and pull requests if any? I also plan to add some tests and continuous integration etc.

Thanks,
Chris

**Comment by sorgelig** [comment]
You don't need to have Admin rights. Just fork the repo, add the changes and make a pull request. If i will agree with changes, then i will apply it to my repo.

**Comment by coughlanio** [comment]
Well that really kills my interest in any continued development under the organisation. As someone who is happy to contribute code, I would have wished to continue ownership of that code, and have influence in the direction of the codebase.

You have shown a lack of interest in continuous integration and release management, and I would have liked to be able to manage these things on my own codebase.

Lesson learned I guess.

**Comment by sorgelig** [comment]
Wait, which repo do you mean? 
Some of your own repo you've created before? Sorry i have so many parallel works so it's hard to track everything.

**Comment by sorgelig** [comment]
do you mean this repo? https://github.com/MiSTer-devel/MiSTer-bootstrap-go  
Since you've created that repo - you have full control on it.

**Comment by coughlanio** [comment]
Yes, that's the one. For example, I can't access the settings. This prevents me from managing deploy keys, integrations etc.

**Comment by sorgelig** [comment]
I gave admin right to you for this repo.
Check if it's ok.

**Comment by sorgelig** [comment]
I guess the problem is solved
