### ISSUE TITLE
Checkered pattern on main menu (wallpaper display issue)

### ISSUE THREAD

**Issue by snicelord** [MiSTer-devel/Main_MiSTer#240]
I decided to make a [video](https://youtu.be/BkhMwipeca4) to better show the issue with wallpapers!

**Comment by sorgelig** [comment]
Don't open second same issue. You can reply to existing issue if you have something to add.
Your SD card it seems too slow, so MiSTer give up on waiting for it...

**Comment by sorgelig** [comment]
there are debug message in USB console, so you can paste it here, may be i can see where is the problem.
background debug messages are started from: **** BG DEBUG START ****

**Comment by c0d3h4x0r** [comment]
Fyi, a handy way to get at the console output is to `ssh` into MiSTer, run `kill -s SIGTERM $(ps -o pid,comm | grep -F MiSTer | cut -d’ ‘ -f2)` to kill the current MiSTer main process, and then run `/media/fat/MiSTer` to relaunch it so you can see its output right in the `ssh` terminal.

**Comment by sorgelig** [comment]
This kind of issues should be discussed on forum as it looks like some specific setup problem. OP doesn't provide any details to track it down.. 
This issue will be closed soon.
