### ISSUE TITLE
Possible HDMI scaler/buffer problem in v200606

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Main_MiSTer#241]
After updating to MiSTer v200606, vsync_adjust=1 and vsync_adjust=2 (match core refresh rate) both result in periodic scrolling stutters.  This is most easily seen in vertically-scrolling shooters or other slow constant scrolling (such as jotego’s credit/pause screens).

I took [an HFR (slo-mo) video of a stutter](https://1drv.ms/v/s!AjhPgJi61wHDtuEweT_dU2Hh5qICdA) for you to see.  It looks like it scrolls backward for one frame.

When I set vsync_adjust=0, the problem goes away.

My TV is a Samsung UN43MU630D, and I have its “Game Mode” enabled and all of its motion-enhancing options completely disabled.

I don’t know if the v200606 update specifically introduced what I’m seeing, or if some earlier recent version introduced it, or if it’s just an issue with this TV.  Could be any of those, I guess... but this is the first time I’ve seen this problem.

**Comment by sorgelig** [comment]
Update in 200606 has no any changes in this matter.
I suggest to post your issue in forum (display subforum) as it's more about discussing.
Main doesn't do frame sync itself.

**Comment by c0d3h4x0r** [comment]
I will try this again on my main TV instead and see if it repros there.  If it does, then this is definitely a regression.
