### ISSUE TITLE
Defining paddles difficult with no DPAD

### ISSUE THREAD

**Issue by pashdown** [MiSTer-devel/Main_MiSTer#245]
Identifying the USB controller with "DPAD test: Press RIGHT" is impossible with a paddle, so instead I use the fire button so it gets the right USB ID.  Once that is done, I can define the paddles with "Tilt RIGHT" and "Tilt DOWN" and A&B buttons.  The problem comes in that the "DPAD RIGHT" is still retained, so hitting the fire button also sends a hard right for the paddle.

I can also identify by moving the paddle right, but then it won't let me properly set Tilt RIGHT.

Would it be better to identify the USB ID with the A or "fire" button? IE: "Controller test: Press A or FIRE" to start the USB ID?

**Comment by sorgelig** [comment]
Currently only Mr.Spinner (and compatible controllers based on Arduino Micro) is acting as real paddle.
All other paddles aren't really paddles. They may act as analog joystick X/Y but it's different, it's not paddle.
Use Mr.Spinner opensource adapter to get correct paddle support.

**Comment by pashdown** [comment]
I've built a Mr.Spinner.  It was a lot of fun because in the end, something short circuited the Arduino, and now I've got to order another.  It would appear that something like the 2600-daptor is a cleaner, easier solution for most.

Mr.Spinner doesn't appear to support the buttons on paddles 3&4 if you are using two of them.  Am I reading this wrong?  4-player Warlords would be nice to see supported.

**Comment by sorgelig** [comment]
Mr.Spinner supports 2 paddles per board. So if you want 4 players, then you need to assemble 2 Mr.Spinners. Original 2600 paddles have only 1 button per paddle. Not sure if i understood 3&4 right.

As for daptor 2600 it's not so easy as it's not paddle only. So you haev to deal with different devices connected to it. While Mr.Spinner is for paddle/spinner only. 
Connecting paddles to Mr.Spinner is really simple, so 40+ ppl was dealing with original retro systems should be able to assemble it. Also good exercise for brain and hands :)

**Comment by sorgelig** [comment]
since paddles/spinners aren't requiring definition this issue is irrelevant.
Also recent changes allow to use mouse as spinner, so no soldering required.
