### ISSUE TITLE
JammaSD not working good on Release 20200608.

### ISSUE THREAD

**Issue by nakuakaben** [MiSTer-devel/Main_MiSTer#246]
Hi, 
with the latest version, Menu access and control options are no longer available on the jammaSD.
MENU:show / MENU:ok / MENU:back

on the previous version no problem Release 20200606.
I can make a video if necessary.

ty

**Comment by nakuakaben** [comment]
I'm making an addition right now.
It is also now impossible to press the space bar for undefine when configuring the joystick (JAMMASD). 
Always on Release 20200608.

**Comment by sorgelig** [comment]
did you update MiSTer.ini options. jammasd_vid/pid must be changed to jamma_vid/pid.
Also, some system keys on jammasd changed their codes, so simply re-define the buttons in Menu core.

**Comment by nakuakaben** [comment]
Oops, I didn't see the subtlety in the code.
Everything's perfect, including the J-PAC.
It's just a PEBCAK :)

Thanks sorgelig
