### ISSUE TITLE
Mister.ini bootcore option does not work

### ISSUE THREAD

**Issue by misteraddons** [MiSTer-devel/Main_MiSTer#247]
Rolling back to March main and menu.rbf fixes the issue. I haven't gone through main releases in-between to further specify where the change occurred.

**Comment by sorgelig** [comment]
funny to see this issue when it's especially fixed in latest Main release.
I've tested it with both rbf and mra.

**Comment by c0d3h4x0r** [comment]
duplicate of #205

**Comment by sorgelig** [comment]
checked, working.
