### ISSUE TITLE
DIP switch problem with MRA files

### ISSUE THREAD

**Issue by MacroFPGA** [MiSTer-devel/Main_MiSTer#253]
If there is a DIP SWITCH heading in the core menu, but no switches are present in the MRA file, then everything below is out of line by 1 line.

i.e. it does not display the DIP SWITCH item, but for anything below where that would be you then toggle the line by selecting the line below it (so reset toggles the final line)

**Comment by sorgelig** [comment]
fixed here: https://github.com/MiSTer-devel/Main_MiSTer/commit/467744346b93bc42b01a2e659b1c1056228bf232
