### ISSUE TITLE
ZIP file navigation issue with (only) subdirectories

### ISSUE THREAD

**Issue by rhester72** [MiSTer-devel/Main_MiSTer#255]
If you try to navigate inside a ZIP archive that contains *all* of the following attributes:

- Files are contained in subdirectories
- There are *no* files in the root
- There are no "directory-only" entries

then the navigation pane will be blank and show no content.

Steps to reproduce (using NES as example, commands shown assume a secondary Linux host, name of the ROM is irrelevant):

```
mkdir -p /tmp/nestest/directory
cp <where_your_roms_are>/NFL\ \(USA\).nes /tmp/nestest/directory
cd /tmp/nestest
zip -Dr ../NES_broken.zip *
zip -r ../NES_works.zip *
```

NES_broken.zip will demonstrate the bug, NES_works will behave as expected.

The reason is because of the "D" flag passed to zip (which is also the default for other compressors, e.g. kzip), which excludes separate directory-specific entries in the ZIP file (and should not be necessary for proper operation).

See the following output:

```
$ unzip -v /tmp/NES_broken.zip
Archive:  ../NES_broken.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
  131088  Defl:N    56297  57% 2020-06-23 11:53 9178f257  directory/NFL (USA).nes
--------          -------  ---                            -------
  131088            56297  57%                            1 file

$ unzip -v /tmp/NES_works.zip
Archive:  ../NES_works.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 2020-06-23 11:53 00000000  directory/
  131088  Defl:N    56297  57% 2020-06-23 11:53 9178f257  directory/NFL (USA).nes
--------          -------  ---                            -------
  131088            56297  57%                            2 files
```

In NES_works.zip, there is an extra 0-byte Stored entry called "directory/" that, without which, the ZIP navigator in the MiSTer framework will not parse the archive structure properly.

**Comment by coughlanio** [comment]
I've ran into this same issue, but specifically with TorrentZip files. I use ROMVault to manage my Hardware Target Game Database packs, and the TorrentVault specification states that any 0-byte directory references in the zip are removed, as the directory structure is implicit in the file paths contained.

The docs are here: https://www.romvault.com/trrntzip_explained.pdf
