### ISSUE TITLE
Request: Multiple USB storage pools for games

### ISSUE THREAD

**Issue by yayitsd4n** [MiSTer-devel/Main_MiSTer#256]
I really love that we can use an external drive for the games folder, but currently, it looks like it only works with one external drive. I think it would be nice if we could have multiple games folders spread across any number of drives.

It might be a niche case since hard drives are cheap enough for more space than you can fill, but for someone who doesn't have or want to buy more storage, it would be great if they could plug in any number of spare usb drives they have laying around.

**Comment by sorgelig** [comment]
More USB storages you plug - more unstable USB will be. Say thanks it allows to use USB storage at least.
DE10-nano is NOT a computer and doesn't have a robust USB host. It glitches enough with simple joysticks.

**Comment by yayitsd4n** [comment]
Oh didn’t know it was a technical constraint. I’m glad we have the option for one at least. Thanks for the comment :)
