### ISSUE TITLE
Cooling section in Wiki is incorrect

### ISSUE THREAD

**Issue by rickycodes** [MiSTer-devel/Main_MiSTer#257]
From the <a href="https://github.com/MiSTer-devel/Main_MiSTer/wiki/How-to-start-with-MiSTer#4-cooling-fpga">Wiki</a>

> but bear in mind that only 5V is available from the Terasic DE10-Nano board, so a 5V fan is required.

Hoever, it seems <a href='https://www.terasic.com.tw/cgi-bin/page/archive_download.pl?Language=English&No=1046&FID=1c19d1d50e0ee9b21678e881004f6d81'>the manual</a> (and the hardware) beg to differ:

> and also provides DC +9V (VCC9), DC +5V (VCC5), DC +3.3V (VCC3P3 and
IOREF)

You can also clearly see the +9V next to the two GND.

+9V can also be used to power a fan and can turn some 12V fans that the 5V is incapable of powering (I've tested this and it seems fine?)

**Comment by sorgelig** [comment]
If you use I/O board then you can't access this pin. It's deliberately hidden to avoid short it to any other signals.
If you want to mess with 9V - good luck.

**Comment by c0d3h4x0r** [comment]
Maybe the wiki should be revised to say something like this instead:

>but bear in mind that you should only use the 5V line from the Terasic DE10-Nano board to drive a 5V fan.  (The DE10-Nano's 9V line is deliberately hidden by the MiSTer I/O board to prevent any possibility of accidentally shorting it to any other signals.)

**Comment by rickycodes** [comment]
> If you use I/O board then you can't access this pin.

The I/O daughter board is optional, so I don't think this really makes a difference? My reason for opening the issue is because the Wiki explicitly says the de10 nano only comes with a 5V pin out, which is confusing because it's not accurate.

> If you want to mess with 9V - good luck.

If there's a any risk in utilising the 9V pin out then that should be mentioned in Wiki. In my case I simply noticed it was possible, but wasn't sure if it was risky.

**Comment by rickycodes** [comment]
@c0d3h4x0r I think your suggestion would alleviate any future confusion and if it makes sense I can open a PR with the amendment to close this issue?

cc @sorgelig

**Comment by sorgelig** [comment]
Wiki is updated by different users. There is no point to open the issue about it as it's not related to Main code. There is Wiki sub-forum on MiSTer discussion board.
You are free to add the note to Wiki about 9V.
