### ISSUE TITLE
Joystick won't fully configure or save - all cores (Release 20181031)

### ISSUE THREAD

**Issue by esmith13** [MiSTer-devel/Main_MiSTer#26]
after upgrading to Release 20181031 all cores fail to configure all of the needed joystick buttons (never gets to configuring an OSD button). No joystick changes save nor do any of the programmed buttons work for the current session in their unsaved state.

Reverting to the previous release (20181019) resolves all of the issues.

**Comment by sorgelig** [comment]
You need to configure the joystick in Menu core for OSD navigation.
