### ISSUE TITLE
Latest update causes USB game pad not to work in games

### ISSUE THREAD

**Issue by mike-hartman** [MiSTer-devel/Main_MiSTer#264]
The latest update causes my USB game pad not to work.  I only use the arcade cores, so I’m not sure if it is universally broken or just the arcade cores.

I can F12 and setup the game pad in the main menu and core menu, and it takes the inputs from the game pad, but once I return to a game, none of the buttons are recognized.

The game pad is a generic USB X-Box 360 wired game pad.  I went back to my backup (most recent update minus one) and everything works fine again, so I don’t think it is a hardware issue.

**Comment by sorgelig** [comment]
New version requires the button assigned to 'A' (in Menu core)  to be pressed to get assigned to player.
In core got to OSD system page and choose "reset player assignment" and after that simply press 'A' button.

**Comment by mike-hartman** [comment]
Thanks.  That helps!
