### ISSUE TITLE
"No files" message after exiting from any core 

### ISSUE THREAD

**Issue by mabalmer** [MiSTer-devel/Main_MiSTer#266]
Main menu starts fine, but upon returning to main menu via reboot option, main menu reports no files available for cores (like it's looking at an empty root directory). Cold reboot restores functionality and switching from core to core via OSD works.

**Comment by theypsilon** [comment]
I can confirm this bug happens. A fix has been tried in this PR https://github.com/MiSTer-devel/Main_MiSTer/pull/265, and it works. But I closed it because it looks like it will break new shared_folder functionality. A better fix is still needed.

**Comment by ghorricks** [comment]
I get the no files constantly on first boot, rebooting, replacing the file doesn't change things.
Replacing with 20200701 works fine.

**Comment by sorgelig** [comment]
should be fixed now

**Comment by mabalmer** [comment]
Indeed fixed now! Closing.
