### ISSUE TITLE
First loaded game from cold boot persists until hard power off

### ISSUE THREAD

**Issue by aberusugi** [MiSTer-devel/Main_MiSTer#270]
Hard to summarize the problem in the title accurately. This may be indicative a minor issue, no issue, or a major problem.

If I start up the MiSTer cold (power completely off then completely on), and launch the Memory Test utility for instance... And then I cold reboot (from within the menu) and load a new core (like Genesis/SNES core) there is a quick flash of the memory test that happens. This same exact behavior happens if it's a fresh cold boot from hard poweroff state, I load up the NES core, load a ROM, use the menu to do a cold reboot, load a new core and load a new ROM, the first ROM I loaded's last video state will flash on the screen momentarily.

This could (as a guess) indicate (but is not limited to) a few things happening.:

* The DE10-Nano's onboard Memory possibly does not clear fully upon using the cold reboot option. 
* The custom video driver for the FPGA does not have it's associated memory cleared upon cold reboot. 
* The SDRAM's memory is not cleared upon cold reboot.
* Unlikely: There is a pointer of some kind to the first loaded state's screen that persists upon cold reboot and is referenced at each ROM load.

I have the 128MB SDRAM module from misterfpga.co.uk, and am connected via USB to a Denon Receiver which goes to my Samsung TV. This issue has persisted as long as I have noticed it which is roughly 1-2 months.

**Comment by sorgelig** [comment]
So you create an issue because you see one frame from previous core??

**Comment by aberusugi** [comment]
I didn't realize this would be controversial to bring up. I am trying to be proactive as cold reboot doesn't seem to be an actual cold reboot if something like this persists. I'll just close it to save you a headache, have a good one.

**Comment by sorgelig** [comment]
scaler's buffer is not cleared, so it lives in DDR3 and may display first frame from previous core. It doesn't affect to core work as it's not related to core itself.
