### ISSUE TITLE
Silent noise over hdmi/optical

### ISSUE THREAD

**Issue by ioev** [MiSTer-devel/Main_MiSTer#271]
This was discussed briefly at https://misterfpga.org/viewtopic.php?f=29&t=661&sid=bbdec4e764b70ddb81c52410fac49299, but I thought it wouldn't hurt to submit an issue in regards to it in case it's feasible to fix in the MiSTer codebase.

The issue is that some amps, dacs, tvs don't appear to recover well from pure silence/pure black video very well, and end up clipping some of the signal.

A good example in my case is loading a GBA rom, the beginning of the BIOS sound effect/video will be cut off, since the signal is transitioning from pure black/no audio.  I also have bad transitions in games that have introductions of still pictures that fade in and out (ex: Ninja Gaiden), the black signal between causes my display to appear as if it's turned off, and then the signal is clips a few frames when it resumes.

If it's helpful, I can make a few videos of what this all looks like.

My TV is an older Samsung Plasma, amplifier is an older Pioneer.  I've connected MiSTer directly to the TV through hdmi and get the same result.  I've also checked through all the options on my TV/Amp for any way to disable this behavior, but it doesn't seem possible.

From what I understand, a potential fix for this would be an option that generates some silent noise over the audio/video to keep the signal active.

**Comment by rsn8887** [comment]
My Vizio sound bar does the same thing. It automatically turns off audio on silence, and then back on when there's some sound. But the turn-on time is probably a few hundred ms. So in certain cases, for example games with only sound fx but no music, some sounds are "missed" and never play, or only play partially.

**Comment by sorgelig** [comment]
It's impossible as core controls the video and audio. While you reloading the core - no one controls the audio and video.
It has nothing to do with Main.

If it annoys you then choose the display/amplifier which doesn't provide automatic shutdown after timeout.

**Comment by sorgelig** [comment]
You have the thread on forum - that the right place for discussion.
