### ISSUE TITLE
Press A to enable pad is counter intuitive

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/Main_MiSTer#272]
Can we make this optional and non-default?

**Comment by sorgelig** [comment]
this is done to prevent sporadic assign to player of some input devices generating key presses upon connect/disconnect or during other cases. It even more serious now when MiSTer tries to keep player assignment during connect/disconnect.

**Comment by paulb-nl** [comment]
At least make it optional to require pressing A so we can disable it.

**Comment by rhester72** [comment]
Or intercept the first press of A and don't pass it through - MegaAGS on Minimig reacts to it and there's no way to bypass it.

**Comment by Left-Empty** [comment]
Please forgive my bluntess, but this is has been terrible change: not only is it counter intuitive (I have to explain daily to a few poeple on the discord who just updated why what they think is the core not saving their controller layout is instead that change, and that they don't need to rebuild their SD card — yes, it confuses people that much!), but it also register that A button press, sometimes activating a wrong menu item in a game, requiring you to reset the game afterwards. 
Please, plase, put it it the way it was before, and let us tell people who connects/disconnects devices willy-nilly to stop doing it — That is so much simpler to explain, and doesn't affect our experience with the MiSTer which has been really impended for the last two months by that change :'(

**Comment by Left-Empty** [comment]
Maybe this should be closed bootsector, since it's not an issue anymore?

**Comment by bootsector** [comment]
Agreed!
