### ISSUE TITLE
Intermittent 'no files' message with San Disk 128 Gb SD

### ISSUE THREAD

**Issue by cadocking** [MiSTer-devel/Main_MiSTer#273]
This affects multiple cores; after loading/playing a ROM successfully, opening the menu again shows a no files message. When this occurs the reset function no longer works, requiring a full power-down.

This affects situations where files are inside a zip and folders without a zip.

I also have an 8 Gb SD card which shows none of these symptoms, with the same cores and files tested. I've tried multiple rewrites of the 128 card with the MISTer SD utility. 

The blame seems to be firmly with the larger SD card. Anyone know of issues with larger SD cards?

**Comment by rsn8887** [comment]
I use a 400 Gb Sandisk card and have no such issues.

**Comment by rhester72** [comment]
512GB SanDisk here, no issues whatsoever.

The only time I've ever seen "NO FILES" is if I delete the ROM (or directory) I'm running out from under the core while it's running and then try to load the menu.  At that point I have to reboot, but I wouldn't expect it to do anything else.

**Comment by sorgelig** [comment]
According to description card is glitching so it simply disappear from system.
This is cannot be fixed as it's hardware problem. Probably card is faulty. I have several 128GB and 256GB Sandisk cards - no such issue.

Nothing can be done.
