### ISSUE TITLE
Support ext3/4 for USB

### ISSUE THREAD

**Issue by solskogen** [MiSTer-devel/Main_MiSTer#275]
MiSTer is not able to use the USB if the filesystem is ext3 or ext4. It will say: "is NOT a VFAT mountpoint"

**Comment by sorgelig** [comment]
ext3/4 has some compatibility issues like case sensitivity, access rights.
If you are knowledgeable enough you may tweak the system so it will recognize and mount ext3/4 then you have to deal with problems above they will be any.

**Comment by sorgelig** [comment]
Not an issue. ext3/4 is not fully compatible with requirements.
