### ISSUE TITLE
GPIO17 (BTN_RESET) Pull-up resistor doesn't appear to be working?

### ISSUE THREAD

**Issue by sofakng** [MiSTer-devel/Main_MiSTer#281]
Can anybody verify that the internal pull-up resistor is enabled and working for GPIO17 (BTN_RESET) ?  LegacyPixels showed me code where it appears to be activated but it doesn't seem to be working.

When I touch GPIO17 with a screwdriver or any length of bare wire, the button triggers.

I've checked this on my oscilloscope and the voltage drops to 1.68v as well:

![Touch With Tweezers](https://user-images.githubusercontent.com/2228499/90970047-e767f580-e4cd-11ea-8223-d11eb376b1ce.jpg)

I discovered this issue by attempting to attach external buttons to the P3 header on the I/O board (v6.1).  When I plugged in a button to PIN 3 (btn_reset), it would cause the MiSTer to constantly reset.  The other pins (1/2, user/osd) work fine with external buttons.

Additionally, when I pressed the physical OSD button, GPIO17 also shows a voltage drop and activates a reset:

![Touching Button Next To Reset](https://user-images.githubusercontent.com/2228499/90970089-42015180-e4ce-11ea-8304-bf0d1cd4825f.jpg)

**Comment by sofakng** [comment]
OK thanks!

What is the largest resistor you would recommend I try?  4.7k didn’t seem to work. I was going to maybe try 150 ohm but no bigger than that.

**Comment by sorgelig** [comment]
You need to check your wires. 4.7K is pretty strong pullup. I don't recommend to go bellow 1K.

**Comment by sofakng** [comment]
OK - It looks like the pull-up resistor wasn't the problem.  I added a 0.1uf cap between GPIO17 and GND and it solved the problem.

When I press the OSD button, GPIO17 (RESET) voltage still drops from 3.3v to around 3.0v but it's not enough to trigger a reset.  Hopefully this is the 'correct' solution and won't cause any other problems.
