### ISSUE TITLE
Missing core memory requirements page

### ISSUE THREAD

**Issue by dev31337** [MiSTer-devel/Main_MiSTer#283]
Hi,

The web page with the memory requirements of each core is no longer available:

https://github.com/MiSTer-devel/Main_MiSTer/wiki/SDRAM-Requirement-by-cores

Regards.

**Comment by sorgelig** [comment]
Do not use direct links! 
Navigate from Main Wiki page. 
Everything is there.

**Comment by dev31337** [comment]
I'm clicking on the sentence/link "SDRAM is required by most cores" in the page below:

https://github.com/MiSTer-devel/Main_MiSTer/wiki/SDRAM-Board

And the web page is empty when I click.

**Comment by dev31337** [comment]
thanks :)
