### ISSUE TITLE
Two different zip files to be loaded sequentially in a single MRA file

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#292]
Hello,

For some systems, MAME keeps one of the roms in a separate zip file. So there are two zip files to load from: the game zip plus the common zip. This happens to QSound chip firmware, which is stored in qsound.zip whereas each game using it does not include the file in its own zip.

I figured out one approach would be to add more than one **rom** element in the MRA with independent zip files. Such as:

```
<rom index="0" zip="wof.zip" type="merged" md5="None">
  ...
</rom>
<rom index="0" zip="qsound.zip" md5="None">
   <part name="dl-1425.bin" crc="d6cf5ef5" length="0x2000"/>
</rom>
```

I tried this in MiSTer but the tty log shows that the second **rom** is ignored.

I have also tried mixing in the two rom statements like this:

```
<rom index="0" zip="wof.zip|qsound.zip" type="merged" md5="None">
  ...
   <part name="dl-1425.bin" crc="d6cf5ef5" length="0x2000"/>
</rom>
```
Using both merged and unmerged as type. But the dl-1425.bin (in qsound.zip) was not found in either case.

Is this kind of dual-zip ROM set supported by the firmware?

Thank you

[dualzip-sample.mra.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/5287968/dualzip-sample.mra.zip)

**Comment by paulb-nl** [comment]
Hi Jose,

It should work with `<rom index="0" zip="wof.zip|qsound.zip" type="merged" md5="None">`

If it can't find the file then this is in the log (no qsound.zip):
`FileOpenZip(mz_zip_reader_locate_file) Zip:/media/fat/_Arcade/mame/wof.zip, file:dl-1425.bin, error: file not found`
`dl-1425.bin does not exist`

Here it is found:
`FileOpenZip(mz_zip_reader_locate_file) Zip:/media/fat/_Arcade/mame/wof.zip, file:dl-1425.bin, error: file not found`
`file: /media/fat/_Arcade/mame/qsound.zip/dl-1425.bin, start=0, len=8192`

**Comment by jotego** [comment]
You are right. It works correctly with that syntax. MiSTer also seemed to fall in MAME folder hell again about this.

Thank you for your kind advice.

[dualzip-sample.mra.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/5288812/dualzip-sample.mra.zip)
