### ISSUE TITLE
USB connectivity issue

### ISSUE THREAD

**Issue by patjohnny** [MiSTer-devel/Main_MiSTer#300]
Since a recent update, any controller or my 8bitdo Bluetooth has connectivity issues. Almost never works on startup. Green light on usb board blinks but won’t go solid. I can fix it by resetting the mister. Sometimes takes a couple resets using the button on top. Once connected, it stays connected. I’ve tried different ports and changing my keyboard to other ports. Doesn’t fix the issue. Thanks.

**Comment by sorgelig** [comment]
I can't confirm this issue as i also use USB gamepads - it's basically the only way to use gamepads.
So i have no such issue. It's some specific HW setup.

**Comment by patjohnny** [comment]
Specifically it’s my 8bitdo ps1 classic Bluetooth and a dual shock 4. Wired the dual shock doesn’t seem to have the problem. A wired snes classic 8bitdo controller does have the problem. Maybe just an 8bitdo issue? The problem never happened before the update before the one we’re currently on. Thanks.

**Comment by sorgelig** [comment]
if you think it's related to updates then try to go back to version when it was working to make sure.
USB driver is in Linux kernel. Main cannot affect the USB LED. So you can try zImage_dtb from previous SD Installer release.

**Comment by patjohnny** [comment]
Wired controllers work so maybe it’s just the 8bitdo receiver. I’ll close it out.
