### ISSUE TITLE
Game Gear games missing extension (.gg) in file menu

### ISSUE THREAD

**Issue by okdana** [MiSTer-devel/Main_MiSTer#302]
I'm not very familiar with the MiSTer code base, so i'm sorry in advance if this is the wrong place. But searching the code led me here.

The [SMS core](https://github.com/MiSTer-devel/SMS_MiSTer/) supports Game Gear games using the file extension `.gg`. I noticed that, unlike every other game that appears in the menus of any core (including SMS), these do not display with their extension. This doesn't affect the core's functionality in any way, but it is a bit confusing/distracting and it reduces the information displayed in the menu.

My *guess* is that this has something to do with [Game Genie cheat file handling](https://github.com/MiSTer-devel/Main_MiSTer/blob/ea1b77e7486825f897475a44cff3283fc366a05a/cheats.cpp#L326)?

Steps to replicate:

1. Create `foo.sms` and `bar.gg` files in `/media/fat/games/SMS`
2. Start up SMS core
3. Select `Load *.SMS,SG` from menu — `foo.sms` is listed as `foo.sms`
4. Select `Load *.GG` from menu — `bar.gg` is listed as `bar`

Tested with `MiSTer_20201027` and `SMS_20200819.rbf`

**Comment by sorgelig** [comment]
If filter has only single extension then it's not displayed in file browser.
It's not a bug, it's a feature.

**Comment by okdana** [comment]
Oh, i see. I guess i didn't realise because most of the other console cores' load commands support multiple extensions, and because even with a single extension it still shows e.g. `.zip` for zip files. Sorry for the dumb assumption.

I personally found it a little unintuitive, since (aside from the apparent inconsistency if you haven't noticed the pattern) there's no other indication in the browser itself of what the current filter is. If something doesn't look the way you expect, you're left wondering if maybe you pressed the wrong button, &c. But i guess that must be true when you're browsing for things like palette files too, and i apparently didn't notice it there.

Anyway, if it's working as intended, i'll just leave it at that. Thanks
