### ISSUE TITLE
vfilter_default does not respect space in file name

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Main_MiSTer#303]
vfilter_default=Interpolation (Sharp).txt does not work.
It displays it as Interpolation(Sharp).txt with no space and the image is distorted.

Also, there is typo in the comment: "filter filders"

**Comment by ghogan42** [comment]
If there is some reason to, the filter filenames could be changed to remove spaces. But the updater script doesn't generally delete files so users could end up with many repeat filters if the names change without deleting the old files.

**Comment by sorgelig** [comment]
i've pushed the commit supporting spaces.
However now other ini settings need to be entered carefully without extra spaces. For example custom video modes may not work if there will be spaces between parameters (although may still work - need more tests).
