### ISSUE TITLE
Down+Select, OSD sub-menu bug

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Main_MiSTer#306]
In any core, while in OSD, pres Down+Select, and you'll see sub-menu content.

I use dual button for OSD/Menu, and tried to close OSD.

**Comment by sorgelig** [comment]
to close OSD, simply press B button
Combo is only to open OSD.

**Comment by James-F2** [comment]
The bug is still present even when I use a Dualshock 4 and Menu is mapped to the PS button.
Down+Select creates a bug in the core osd menu.

**Comment by sorgelig** [comment]
Pressing "select" on item not related to open/mount switches paged OSD to flat mode and back. Has nothing to do with "down" button. You can do it with "Select" button.
It's a feature.

**Comment by James-F2** [comment]
Ah, it's a feature.
Thank you.
Sorry, closing.
