### ISSUE TITLE
Detect Paddles from Mister Spinner

### ISSUE THREAD

**Issue by heatvent** [MiSTer-devel/Main_MiSTer#308]
As discussed towards the end of this thread (https://misterfpga.org/viewtopic.php?p=14019#p14019), I was having issues with Atari paddles being identified in Mister.  Apparently, if you have a spinner, Mister will detect the spinner movement to identify the spinner (and paddle).  However, if you don't have a spinner (just paddles), Mister does not detect paddle movement.  

A helpful user modified the PaddletwocontrollersUSB code to send a small spinner movement to Mister when the paddle button was pressed so that the paddles would be identified and used as the controller.  

Is it possible to have Mister identify paddles based on a press of the paddle button or a paddle movement or somehow identify when a paddle is to be used (and there is no spinner)?

**Comment by sorgelig** [comment]
will be fixed in next release

**Comment by heatvent** [comment]
Great thanks!

**Comment by sorgelig** [comment]
fixed
