### ISSUE TITLE
MIDI Uart via usb not working with  20201213 version

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/Main_MiSTer#311]
I had it working perfectly before (using Otraki USB to MIDI device):
https://www.youtube.com/watch?v=iGVkHInKC1A
Device is detected, as notes are sent but just as random piano notes. 
I tried same device with my Windows PC and MIDI is perfectly played.

But I tried yesterday (19/Dec) after update and now it shows this error coming from Mister:
![WhatsApp Image 2020-12-20 at 10 13 42 (1)](https://user-images.githubusercontent.com/447481/102709561-4dae2a80-42ac-11eb-8065-0b79ad33ef42.jpeg)

And notes are totally wrong.

**Confirmed I rollbacked to MiSTer_20201123, and it worked as a charm... **

**Comment by sorgelig** [comment]
Wait for new version of MIDI supporting cores. It will work through USER_IO.

**Comment by jsmolina** [comment]
but,  it will keep compatibility with USB-MIDI devices?

**Comment by sorgelig** [comment]
basically, it should. 
Actually i don't like how midilink grew to monstrous non-midi related tool. It's harder and harder to support it.

**Comment by sorgelig** [comment]
i've just bought USB-Serial with FT232 chip, it seems the only chip supporting non-standard baud rates.
So i set 31250 and get the same Unexp. MIDI status message.
I have no idea what is that. Probably you need to ping midilink developer. 
USER_IO connection is much simpler and basically zero-hassle. It also mixes MIDI audio in the core.

**Comment by jsmolina** [comment]
Mine is:

![WhatsApp Image 2021-01-01 at 13 20 55](https://user-images.githubusercontent.com/447481/103438546-34a26380-4c34-11eb-8747-545d663e066f.jpeg)
Curiosly it failed after main update, and repaired after rollback.
I have anyway pi-midi, so pinouts might work later.

Anyway, I'll wait for next release as I saw you nicely did some commits related to UART.

**Comment by sorgelig** [comment]
I don't know why, but somehow UART speed settings are forgotten in midilink. I've added workaround in midilink repo.

**Comment by jsmolina** [comment]
Last release seems to fix it, thank you very much @sorgelig  !!
