### ISSUE TITLE
Request: support for input to P2 in Amiga games expecting two mice.

### ISSUE THREAD

**Issue by Aastedet** [MiSTer-devel/Main_MiSTer#312]
Currently, multiple mice all merge to Player 1, and mouse emu mode merges inputs from all controllers to Player 1. As far as I know, there’s no way to provide controls to Player 2 in games with this control design, such as The Settlers/Serf City and Lemmings 1.
MiST looks to have fixed it with a minor [firmware update](https://github.com/mist-devel/mist-firmware/commit/42fbeaa7cca9d4d1b72502192e9ca781a01fa6d5#diff-8c63ff8749d11a15861988b0a736a7bb50d051ba9db642d3ddff689861e87eda), but I don’t know if MiSTer handles control inputs in a way that is compatible with that implementation.

Would it be feasible to replicate this feature of the original Amiga on the MiSTer in a similar way? Whether with two USB mice or (even better) with separate mouse emu mode from two controllers, I’d love multiplayer support for these great games.

**Comment by sorgelig** [comment]
No. There won't be 2 independent mice in MiSTer.
Mice and Keyboards are aggregated devices like on PC. There is no point to break this in favor of couple games developed before mouse became a common standard.
