### ISSUE TITLE
New dip condition found in arcade cores

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Main_MiSTer#313]
Hi

just found another issue (dont know in how many games this happen but...) in dips.

Looking at xml for the game we have:
```
        <dipswitch name="Flip Screen" tag="DSW0" mask="2">
            <diplocation name="DSW-A" number="2"/>
            <dipvalue name="Off" value="2" default="yes"/>
            <dipvalue name="On" value="0"/>
        </dipswitch>
        <dipswitch name="Mode" tag="DSW0" mask="5">
            <diplocation name="DSW-A" number="1"/>
            <diplocation name="DSW-A" number="3"/>
            <dipvalue name="Game, English" value="4" default="yes"/>
            <dipvalue name="Game, Japanese" value="5"/>
            <dipvalue name="Test (Grid and Inputs)" value="1"/>
            <dipvalue name="Test (RAM and Sound)/Pause" value="0"/>
        </dipswitch>
```
even if i do this:
```
        <dip name="Flip Screen" bits="1" ids="On,Off"/>
        <dip name="Mode" bits="0,2" ids="Test / Pause,Test,Game English,Game Japanese"/>
```

mister thinks i'm using bits 0,1,2 for mode and not only 0 and 2.
even if this was possible, dont know if the rest would work.

this issue and also conditional dips (dont know if I already opened an issue but i could do it with examples) could be solved?

Thanks

**Comment by sorgelig** [comment]
just hardcode "Game, English" in default value and problem is solved.
I didn't see such issue in other arcades. So it it happened in couple - it's not a problem to hardcode it.

**Comment by eubrunosilva** [comment]
ok. until now i only found this in one game (didnt check all dips in all arcade games released so far)
