### ISSUE TITLE
NBA JAM on Genesis core doesn't keep the saved records

### ISSUE THREAD

**Issue by Alex-Catalin** [MiSTer-devel/Main_MiSTer#323]
Hi guys,

I thought I bring this issue up since it's happening for as far as I've been using MiSTer which is about 1 year now. The NBA JAM game on Genesis has a save feature that doesn't rely on a battery, instead I believe it's using some sort of an FRAM chip. There is a difference on how the save feature works between the Genesis and SNES versions of this game (this is to give you more insight):

- SNES is using a combination of 3 letters (name of the profile) plus some numbers to keep the records
- Genesis on the other hand, doesn't require the numbers part, it only relies on the 3 letters (name of the profile) to save the records; each time you play a match, you are asked to input your profile name (the said 3 letters) so that the game can save the match results

So, these are the repro steps on my MiSTer:

- I load up the Genesis core
- I make sure that I have Autosave feature turned on
- I start NBA JAM (doesn't matter which version, I tried all rom versions of the game)
- I press Start, go to Options and select the "View records" entry in the menu - no records are shown - this is ok
- I go back to the main screen and select "Head to head" then I select "Yes" to entry my initials which creates my profile for the first time
- I then select a team, start a match, finish it and I can see at the end that the game will record my match under the initials that I typed before I began the match
- I go to Options again and select "View records" and this time I can see my record here - this is ok
- I press the button combo on my controller to bring up the MiSTer OSD so that the save file is actually written on the SD card - this does happen, there is an NBA JAM.sav file in the Saves folder
- I then reboot MiSTer from its menu and go load again the Genesis core and the same NBA JAM rom as before. This time, when I go to Options/View Records, there is nothing there. Records that have been saved previously, should show up here without the need to input the 3 initials.

For example, on the Mega SD flashcart, this issue doesn't occur, I get the records saved properly. On MiSTer, it's like the save file is created, but it is empty or it gets emptied when I reboot MiSTer.

**Comment by birdybro** [comment]
i'll look at the Genesis core stuff for this later to see what's going on. I'm no expert, but I think this isn't related to Main repo (which is th elinux side of things primarily) as it is related to Genesis core's repo as an issue. Going to see if this is brought up there, and I'll link to this thread in a new issue there.

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/Genesis_MiSTer/issues/2

Just found this issue. Are you using NBA Jam or NBA Jam Tournament Edition btw? Just so I can test your situation accurately.

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/Genesis_MiSTer/issues/163 - Basically moving discussion there.

**Comment by jotego** [comment]
> [MiSTer-devel/Genesis_MiSTer#163](https://github.com/MiSTer-devel/Genesis_MiSTer/issues/163) - Basically moving discussion there.

@Alex-Catalin please close the issue here as @birdybro moved it away.
