### ISSUE TITLE
MegaCD bug since CHD supported added to main release

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Main_MiSTer#324]
https://github.com/MiSTer-devel/MegaCD_MiSTer/issues/59

Could very well be related to Main as Lunar Silver Star was working just fine before main was updated on my system. Many other users reporting the same thing.

**Comment by birdybro** [comment]
Tested this out with Rysha. When she reverted the commenting out of this line --> https://github.com/MiSTer-devel/Main_MiSTer/blob/20f9ab40786a2c4d65d97011b5077a9e1478ab31/support/megacd/megacdd.cpp#L423 - the bug went away completely, but CHD in megacd failed to work.

Important to note, opening the OSD as well after some time gets a loud buzzing noise in MegaCD. So it's definitely tied to this file in some way at least.

**Comment by zakk4223** [comment]
What a dumb bug on my part. The ReadCDDA function was only incrementing the lba for chds. Oddly enough it only seemed to cause an issue for the data reads...

On top of that it helpfully worked on every bin/cue I tested, so unlucky me.
Try that commit referenced above, it's a super tiny change. It fixed Lunar Silver Star for me, but I'd like some verification please.
I'll submit it as a PR once you confirm it works for you too.

**Comment by birdybro** [comment]
I don't have the toolchain to build main, kitrinx did it for me. Can you attach the beta binary for me? Bugs were also seen in multiple games, namely earthworm jim and ecco the dolphin off the top of my head. After 10-15 minutes of gameplay, the OSD being opened would result in a loud buzzing noise.

**Comment by zakk4223** [comment]
Try this
[MiSTer_mcdfix.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/5788933/MiSTer_mcdfix.zip)

**Comment by birdybro** [comment]
Lunar CUE/Bin = It loads the video and audio just fine.

Lunar CHD = Video and audio still fine, no 2x speed this time (regarding the quick uncomment we tried before you got back to me :P).

Ecco Tides of time - it loaded the video when going to the crystal this time (it didn't before), so it looks good!

Looks like that fixed it!
