### ISSUE TITLE
Last rom played feature ?

### ISSUE THREAD

**Issue by vinz2k** [MiSTer-devel/Main_MiSTer#325]
Hi

maybe it has already been asked, but what about a new feature to enable on core to launch the last played game when launching the core, or maybe something more easy, displaying the 5 last played roms on core.

thanks for all your work on this awesome platform 🙏🏻🙏🏻🙏🏻

**Comment by sorgelig** [comment]
Press Select button on game pad being on appropriate OSD item to see/run last 16 opened ROMs

**Comment by birdybro** [comment]
The `/~ key on your keyboard does this too if you don't have the select button mapped on your controller, last I remember.

Also, I think to use the feature we are both talking about you need to turn on recents=1 in your mister.ini:

```
; 1 - enables the recent file loaded/mounted.
; WARNING: This option will enable write to SD card on every load/mount which may wear the SD card after many writes to the same place
;          There is also higher chance to corrupt the File System if MiSTer will be reset or powered off while writing.
recents=0
```

Only change that if you can't get it to work.

**Comment by thehughhefner** [comment]
This ticket can be closed since its already possible to launch "last rom played"
