### ISSUE TITLE
Within the file browser have the "Back" button navigate up one level in the directory structure

### ISSUE THREAD

**Issue by retrocaster** [MiSTer-devel/Main_MiSTer#329]
Currently when in the file browser if you push the Back button it does the same thing as the Menu button and takes you to the root core menu. The only way to navigate up a directory is to move to the "..." at the top of the current directories listing and select it. It would be more convenient and intuitive if the Back button navigated up one level in the directory structure (ie. make it equivalent to selecting "..."), especially in situations where the user has a large number of roms or folders.

**Comment by sorgelig** [comment]
that's arguable. For example not all gamepads have dedicated MENU button which will make navigation complicated (if ever possible). So back button for such gamepads is important to go out from navigation. 
I give you a hint how to navigate more convenient: left/right buttons have no roll over, so you press right button and wait till it quickly scroll to top without worry to go to bottom of list. Then simply press "A" to go to parent directory.

**Comment by retrocaster** [comment]
True, most game pads don't have a dedicated MENU button. But isn't that what the ability to define a two button combo is for? There needs to be some way to access the MENU button because if not there wouldn't be a way to switch roms. 

In the approach I'm suggesting above BACK would still go to the top level core menu, it would just take a few additional presses to navigate through any existing directory hierarchy first.

**Comment by sorgelig** [comment]
The way to open OSD by key combo may not work inside the OSD do to same buttons used for other navigation function inside OSD. Primarily it's to open OSD, not navigate inside.
Navigation in browser is not hardly limited by home directory, so you can navigate upper than home folder.
Anyway, i've explained you the real purpose. It's not a bug. It's a feature.

**Comment by retrocaster** [comment]
To be clear, what I'm suggesting doesn't remove your intended behavior, it just makes it more consistent. Pressing BACK would still "go out from navigation". It would just only happen when in the root of the file browse area. 

For example if you had:

**Root core menu**:
```
LOAD *.SFC,...
etc
```

**Root file browse menu**:
```
...
US A-E
US F-M
etc
```

**Sub file browse menu** (US A-E):
```
...
3 Ninjas Kick Back (USA).sfc
7th Saga, The (USA).sfc
etc
```

And you're currently navigating within the "sub file browse menu", hitting BACK would take you to "Root file browse menu". And then hitting BACK again would then take you to the "Root core menu". Doing it this way would make BACK consistent throughout the UI.
