### ISSUE TITLE
Feature: Block OSD during auto save

### ISSUE THREAD

**Issue by paulb-nl** [MiSTer-devel/Main_MiSTer#331]
After the OSD is opened and while it is auto saving backup ram then don't allow OSD navigation and show only "Saving..".

If you are quick then you can load a new game/core before it is done auto saving and corrupt the save. Especially when the save is large.

**Comment by sorgelig** [comment]
Hmm.. Need to think how to do it as there is no such thing as "end of save".

**Comment by paulb-nl** [comment]
Thanks for adding this! It works great. I have also tested it with games that write to save ram constantly like Super Mario RPG and Super Mario World SA-1 Hack.

**Comment by sorgelig** [comment]
great!

**Comment by birdybro** [comment]
This is a great feature, it will also alleviate the newbie confusion over when saves occur with the autosave turned on!
