### ISSUE TITLE
Scale filter - Custom can cause vercital blur even when vscale_mode=1

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Main_MiSTer#334]
Activating Scale filter - Custom (e.g. Gaussian_Sharp_06) can cause vertically blur even though integer vertical scaling is turned on (vscale_mode=1).

I'm experiencing this on a 1280 x 1024 flatpanel.

**Comment by sorgelig** [comment]
Integer scaling has no difference for filter. It's always applied.
There are special filters applied only vertically or horizontally. Or you can combine filters manually by editing filter file.

**Comment by dfilskov** [comment]
OK, thanks! - I think I can now understand how horizontal lines on the screen can actually be blurred even when horizontal scaling only is applied.
