### ISSUE TITLE
Feature: Mouse Sensitive Option for Zapper Games

### ISSUE THREAD

**Issue by diettelo** [MiSTer-devel/Main_MiSTer#336]
An Option to set Mouse Sesitive to be more accurate in Zapper Games.

**Comment by sorgelig** [comment]
Main doesn't know how mouse is used in cores.
It's core specific feature.

**Comment by jotego** [comment]
I have to agree that different systems will have very different sensitivities so it's hard for the MiSTer central firmware to handle this in an effective way.

I propose to close this issue as *won't do/not planned now*
