### ISSUE TITLE
Feature: Option to set different Roms as Favourite

### ISSUE THREAD

**Issue by diettelo** [MiSTer-devel/Main_MiSTer#337]
Option to set Fav Roms through Core or Main Menu.

**Comment by sorgelig** [comment]
It's too complex to manage favorites through limited OSD functionality.
"Recents" option is made to be a favorite with automatic management.

**Comment by thehughhefner** [comment]
This is semi-supported by the MGL format. 
Create a _Favourites folder in root and you can create .mgl files that contains the following information:
<mistergamedescription>
    <rbf>_console/snes</rbf>
    <file delay="1" type="f" index="1" path="1 US - A-E/ActRaiser (USA).sfc"/> 
</mistergamedescription>

You can see that my ActRaiser rom is in the folder "1 US - A-E/ActRaiser(USA).sfc"

What could be "nice to have" feature is to have some sort of an MGL creation tool in the framework. @sorgelig what is your opinion here?

**Comment by sorgelig** [comment]
yes, MGL is pretty much what this request asks.
