### ISSUE TITLE
OSD timeout bug

### ISSUE THREAD

**Issue by Paradox** [MiSTer-devel/Main_MiSTer#340]
When set to 0 it should never timeout, but, it seems to be timing out, almost immediately, instead. (About 4 seconds)

**Comment by littlegamer87** [comment]
Confirmed, there is no way to disable the timeout it seems

**Comment by sorgelig** [comment]
```
osd_timeout=30         ; 5-3600 timeout (in seconds) for OSD to disappear in Menu core. 30 seconds if not set.
```
where is the bug? description doesn't mention 0 as an option.

**Comment by sorgelig** [comment]
i will add 0 option.

**Comment by Paradox** [comment]
After I created this issue somebody changed the description to say 30 was the least you could do before that setting it to zero should have made it not time out

**Comment by littlegamer87** [comment]
Feature is added in latest release. Please close issue.
