### ISSUE TITLE
MegaCD - Lunar: The Silver Star issue

### ISSUE THREAD

**Issue by tondagossa** [MiSTer-devel/Main_MiSTer#345]
The game loads up fine, intro and all. However, it appears to lock up the game when I bring up the game menu. Music still plays and character idle animations are still moving. Just can't leave the menu or change the menu selection once it's brought up.

Using the Un-Worked Designs version, US Bios 2.0. Also happens on the original CUE/BIN. Tried a few versions and it happens on all of them.

**Comment by birdybro** [comment]
Does this happen on the previous release of the MegaCD core? If not, then it's related to the timer fix being rolled back for the MegaCD core, and an issue should be opened there. That timer fix was rolled back because it was breaking other games' functionality.

**Comment by tondagossa** [comment]
Yes, it appears to be occurring in the 21.02.03, 21.01.24, and 20.06.20 MegaCD cores. The 20.04.08 core appears to be working fine. I haven't tested others.

**Comment by birdybro** [comment]
If it's occurring in 20210203 + 20210124 + 20200620 that doesn't make sense then because I have played Lunar Silver Star for hours since then. Can you let me know which BIOS you are using and/or if your CUE+BIN matches this redump entry:

http://redump.org/disc/29312/

Because it "should" work on at least 20200620... Unless the recent changes to the Main did something...

**Comment by SwedishGojira** [comment]
It is working well for me too. I have tested both the Unworked Design one and the regular one in CHD with no problems at all.

**Comment by birdybro** [comment]
> 
> 
> It is working well for me too. I have tested both the Unworked Design one and the regular one in CHD with no problems at all.

Can you test in cue/bin?

Also can @tondagossa let me know if their cue/bin matches the redump listing, and what the hash of their BIOS they are using is?

**Comment by tondagossa** [comment]
Apologies for the late reply. I finally had some time to do more testing and found that I had Gun Control enabled in the options for some reason. That was interfering with the input, causing the game menu navigation to be inoperable (even though I had Mouse set to None). It was strange because I was able to move the character around. The older core probably worked because Gun Control wasn't added back then. Sorry for the mixup!
