### ISSUE TITLE
Feature: extending screen_rotate module to include 180° option 

### ISSUE THREAD

**Issue by mapfde** [MiSTer-devel/Main_MiSTer#346]
Hello,

arcade_video.v contains the "screen_rotate" module that allows cores written for monitors in vertical orientation to be played on setups with monitors in horizontal orientation. Currently only a +/-90° rotation is implemented that can be switched via the osd menu. 

In setups with a monitor/LCD in fixed vertical orientation, extending the screen_rotate module to include a 180° option would be very useful. In my case, I can only turn the LCD 90° clockwise, and not the other way. 

Some cores have internal logic to flip the image, but depending on the core this might be very hard to implement. Using the scaled output and adding 2 frames of lag would be a compromise for these cases, as the games cannot be played otherwise. 

For reference, the affected arcade games are: 

centipede
dorodon
gorf
lady bug
mister viking 
playball
raflesia
regulus
shuttle invader
sinistar
star jacker
super breakout
swat
up'n down
victory
water match
youjuden
qbert

**Comment by mapfde** [comment]
Small update: I got another 4:3 LCD with a better panel, but this one turns only counter-clockwise. So now all the above arcade games work, but several from the "clockwise" selection do not. I think an option in the framework to flip the screen would be really helpful for everyone who uses a monitor in "tate" position.

**Comment by jotego** [comment]
This was done in this commit https://github.com/MiSTer-devel/Template_MiSTer/commit/7180cd7cffa84a98fcca04ee842ef8bf466f9fcf
You can close the issue :-)

**Comment by mapfde** [comment]
Thanks, I will try it on the weekend.

**Comment by sorgelig** [comment]
This is not a definitive solution. It doesn't work on VGA native video mode. So you have to use either HDMI output or vga_scaler=1 for VGA. 
It also doesn't immediately affects mentioned cores/games as it has to be updated in each core.

**Comment by mapfde** [comment]
Thanks for the additional info. I understand that this needs the scaler (so either HDMI out or activating it for analogue) and I am quite happy to trade minimal lag for the ability to play the affected games. Like I wrote before, I use an LCD for the "tate" games anyway, but the issue is more pressing for people with a CRT in a game cabinet.

With the code now available, I can patch the cores for the games that I am interested in playing myself (or wait for the change to propagate).
