### ISSUE TITLE
MIDI/UART TCP option gone?

### ISSUE THREAD

**Issue by neutralinsomniac** [MiSTer-devel/Main_MiSTer#348]
I used to be able to connect to the net with the C64 core by changing the UART mode to MIDI/TCP. I updated this core yesterday, and now that setting is gone. Only MIDI/UDP is available (and the modem appears to not respond to AT commands at all). Choosing "Modem" actually ends up selecting "None", and "PPP" doesn't allow me to communicate with the modem either. Is there a new way to do TCP modem stuff with this core now?

**Comment by sorgelig** [comment]
midilink and uartmode script need to be updated. It will be updated soon with linux update.
