### ISSUE TITLE
Xbox 360 Wireless Receiver paired controllers are reported as the same one to MiSTer

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/Main_MiSTer#350]
Paired 3 wireless X360 controllers to the Xbox 360 Wireless Receiver connected to MiSTer via USB. On the SNES core, for example, all of them are being recognized as the first player.

Main MiSTer log during main menu (pressing down on each controller, in sequence):

> Minimig by Dennis van Weeren
> ARM Controller by Jakub Bednarski
> MiSTer code by Sorgelig
> 
> Version 210207
> 
> Looking for root device...
> FileOpenEx(open) File:/media/fat/config/device.bin, error: No such file or directory.
> Using SD card as a root device
> Identified 8BIT core
> Core name is "MENU"
> *** Found SDRAM config: 3
> ** altcfg: no cfg
> INI_PARSER : Start INI parser for core "MENU".
> INI_PARSER : Opened file MiSTer.ini with size 1199 bytes.
> INI_PARSER : line(0): "[MiSTer]".
> INI_PARSER : Got SECTION 'MISTER'
> INI_PARSER : line(0): "vsync_adjust=0".
> INI_PARSER : Got VAR 'VSYNC_ADJUST' with VALUE 0
> INI_PARSER : line(0): "video_info=5".
> INI_PARSER : Got VAR 'VIDEO_INFO' with VALUE 5
> INI_PARSER : line(0): "video_mode=8".
> INI_PARSER : Got VAR 'VIDEO_MODE' with VALUE 8
> INI_PARSER : line(0): "video_mode_ntsc=8".
> INI_PARSER : Got VAR 'VIDEO_MODE_NTSC' with VALUE 8
> INI_PARSER : line(0): "video_mode_pal=9".
> INI_PARSER : Got VAR 'VIDEO_MODE_PAL' with VALUE 9
> INI_PARSER : line(0): "vscale_mode=0".
> INI_PARSER : Got VAR 'VSCALE_MODE' with VALUE 0
> INI_PARSER : line(0): "browse_expand=0".
> INI_PARSER : Got VAR 'BROWSE_EXPAND' with VALUE 0
> INI_PARSER : line(0): "ypbpr=1".
> INI_PARSER : Got VAR 'YPBPR' with VALUE 1
> INI_PARSER : line(0): "logo=0".
> INI_PARSER : Got VAR 'LOGO' with VALUE 0
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "custom_aspect_ratio_1=10:7".
> INI_PARSER : Got VAR 'CUSTOM_ASPECT_RATIO_1' with VALUE 10:7
> INI_PARSER : line(0): "custom_aspect_ratio_2=8:7".
> INI_PARSER : Got VAR 'CUSTOM_ASPECT_RATIO_2' with VALUE 8:7
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[GBA]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "vscale_mode=1".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[GameBoy]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "vscale_mode=1".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[MSX]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[SMS]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[NeoGeo]".
> INI_PARSER : line(0): "vsync_adjust=0".
> INI_PARSER : line(0): "custom_aspect_ratio_1=40:27".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[SNES]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "custom_aspect_ratio_1=32:27".
> INI_PARSER : line(0): "custom_aspect_ratio_2=64:45".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[Genesis]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "custom_aspect_ratio_1=64:45".
> INI_PARSER : line(0): "custom_aspect_ratio_2=40:27".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[MegaCD]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "video_info=0".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "custom_aspect_ratio_1=64:45".
> INI_PARSER : line(0): "custom_aspect_ratio_2=40:27".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[NES]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "custom_aspect_ratio_1=32:27".
> INI_PARSER : line(0): "custom_aspect_ratio_2=64:45".
> INI_PARSER : line(0): "".
> INI_PARSER : line(0): "[TGFX16]".
> INI_PARSER : line(0): "vsync_adjust=2".
> INI_PARSER : line(0): "custom_aspect_ratio_1=3:2".
> INI_PARSER : line(0): "custom_aspect_ratio_2=4:3".
> INI_PARSER : line(4): "".
> Set predefined video_mode to 8
> Calculate PLL for 148.5000 MHz:
> Fvco=445.500000, C=3, M=8, K=0.910000(3908420239) -> Fpix=148.500000
> Set predefined video_mode to 9
> Calculate PLL for 148.5000 MHz:
> Fvco=445.500000, C=3, M=8, K=0.910000(3908420239) -> Fpix=148.500000
> Set predefined video_mode to 8
> Calculate PLL for 148.5000 MHz:
> Fvco=445.500000, C=3, M=8, K=0.910000(3908420239) -> Fpix=148.500000
> FileOpenEx(open) File:/media/fat/config/MENU_gamma.cfg, error: No such file or directory.
> FileOpenEx(open) File:/media/fat/config/MENU_scaler.cfg, error: No such file or directory.
> Send HDMI parameters:
> video: 1920(1920), 88(88), 44(44), 148(148), 1080(1080), 4(4), 5(5), 36(36),
> PLL: 0x4, 0x404, 0x3, 0x10000, 0x5, 0x20201, 0x9, 0x2, 0x8, 0x7, 0x7, 0xE8F5C28F, Fpix=148.500000
> FileOpenEx(open) File:/media/fat/config/MENU_afilter.cfg, error: No such file or directory.
> sending keymap: 20
> Loading config MENU.CFG
> Found config: 00000002-00000000
> get cfgstring 0 = MENU
> get cfgstring 1 = (null)
> get cfgstring 2 = V,v210127
> get cfgstring 3 = (null)
> **** BG DEBUG START ****
> n = 1
> Logo = 0x3ed3c8
> ** altcfg: no cfg
> menubg: src_w=2560, src_h=1440
> vs_wait(us): 16653
> **** BG DEBUG END ****
> Switch to HPS frame buffer
> HPS frame buffer: 960x540, stride = 3840 bytes
> 0
> 0
> Open up to 30 input devices.
> pFileExt = (null)
> Start to scan dir: /media/fat/
> Position on item:
> Got 6 dir entries
> *** Got SDRAM module type: 7
> INFO: Video resolution: 529 x 240, fHorz = 15.7KHz, fVert = 59.8Hz, fPix = 10.00MHz
> INFO: Frame time (100MHz counter): VGA = 1671559, HDMI = 1666666
> **** BG DEBUG START ****
> n = 1
> menubg: src_w=2560, src_h=1440
> vs_wait(us): 16661
> **** BG DEBUG END ****
> Switch to HPS frame buffer
> HPS frame buffer: 960x540, stride = 3840 bytes
> The file js0 was created.
> Close all devices.
> Open up to 30 input devices.
> The file event1 was created.
> Close all devices.
> Open up to 30 input devices.
> opened 0( 0): /dev/input/event1 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> The directory by-id was created.
> Close all devices.
> Open up to 30 input devices.
> opened 0( 0): /dev/input/event1 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> The directory by-path was created.
> Close all devices.
> Open up to 30 input devices.
> opened 0( 0): /dev/input/event1 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> The file js1 was created.
> Close all devices.
> Open up to 30 input devices.
> opened 0( 0): /dev/input/event2 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> opened 1( 0): /dev/input/event1 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> The file event2 was created.
> Close all devices.
> Open up to 30 input devices.
> opened 0( 0): /dev/input/event2 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> opened 1( 0): /dev/input/event1 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> The file js2 was created.
> Close all devices.
> Open up to 30 input devices.
> opened 0( 0): /dev/input/event3 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> opened 1( 0): /dev/input/event2 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> opened 2( 0): /dev/input/event1 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> The file event3 was created.
> Close all devices.
> Open up to 30 input devices.
> opened 0( 0): /dev/input/event3 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> opened 1( 0): /dev/input/event2 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> opened 2( 0): /dev/input/event1 (045e:02a1) 0 "usb-ffb40000.usb-1.5/input0" "Xbox 360 Wireless Receiver"
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=0, ID:045e:02a1:02
> Device usb-ffb40000.usb-1.5/input0 assigned to player 1
> FileOpenEx(open) File:/media/fat/config/kbd_045e_02a1.map, error: No such file or directory.
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> **** BG DEBUG START ****
> n = 1
> menubg: src_w=2560, src_h=1440
> vs_wait(us): 16660
> **** BG DEBUG END ****
> Switch to HPS frame buffer
> HPS frame buffer: 960x540, stride = 3840 bytes
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:02
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:02
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:02
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:02
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:02
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:01
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:01
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:01
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:01
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:01
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:01
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:00
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:00
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:00
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:00
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:00
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:00
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:02
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:02
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:02
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:02
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:02, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:01
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:01
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:01
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:01
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:01, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:00
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:00
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=1, jnum=1, ID:045e:02a1:00
> PS2 code(make)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=1, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> Input event: type=EV_KEY, code=707(0x2c3), value=0, jnum=1, ID:045e:02a1:00
> PS2 code(break)(ext) for core: 114(0x72)
> Input event: type=EV_ABS, Axis=17, Offset=0, jnum=1, ID:045e:02a1:00, abs_min = -1, abs_max = 1
> ^C
> Exiting...
> 
>

**Comment by bootsector** [comment]
Solved by:

`
no_merge_vid=0x045E
no_merge_pid=0x02A1
`

Quick question: what if I get another device, from another vendor, that behaves the same? Maybe we should have multiple entries for the no_merge_* config in the .ini? Or just hardcode them on input.cpp?

**Comment by sorgelig** [comment]
i will add it into input.cpp
