### ISSUE TITLE
Force RBF reload

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#353]
It looks like the same RBF is kept in the FPGA when changing from one MRA to another, provided both MRA files refer to the same RBF. I think this behaviour is good for regular use. 

However, if you are developing a core, you may have changed the RBF file. In that case, you want MiSTer to reload the RBF when selecting a new (or even the same) MRA file from the OSD menu.

Is there a way to force RBF loading in the .ini file or somewhere else?

Thank you

**Comment by sorgelig** [comment]
RBF is always reloading when new MRA is loaded. Not only RBF but also Main gets reloaded.

**Comment by jotego** [comment]
I was very confused then, apologies.
