### ISSUE TITLE
fb_size=0, fb_size=1, fb_size=2 is same tiny font-size on 1920x1920

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Main_MiSTer#356]
Setting fb_size=4 make the script / terminal font huge on 1920x1920 but 0, 1 and 2 have the same tiny size :)

**Comment by sorgelig** [comment]
0 means "auto", so depending on resolution it can be equal to 1 or 2.
maximum possible frame buffer size is 1920x1080. Any higher resolution will automatically half the frame buffer, so 1 will be forced to 2. So in your case 0,1 and 2 give the same frame buffer size equal to 2.

This is correct.

**Comment by dfilskov** [comment]
Ah - I see. So frame buffer is used for the text output of the scripts? - I thought I was merely adjusting the font-size of the terminal (the text output from the scripts).

Is there another way to get a slightly larger font for script text output?

**Comment by sorgelig** [comment]
use fb_size=4

**Comment by sorgelig** [comment]
also script can set specific frame buffer resolution, so text size will be scaled as well.

**Comment by dfilskov** [comment]
Oh - cool! - thanks! - size 4 is huge so perhaps it'd be best to specify another resolution.
