### ISSUE TITLE
Minish Cap does not load file select screen fully

### ISSUE THREAD

**Issue by exodvs** [MiSTer-devel/Main_MiSTer#357]
When trying to play _The Legend of Zelda: The Minish Cap_, the three slots of the file select screen are stuck on the left side, fluttering up and down. User input does nothing. The ROM was taken from the Wii U virtual console and is bit-for-bit identical to the one on Vimm. _Sonic Advance 2_ and _Ultimate Spider-Man_ are the exact same size and exhibit no issues.

https://user-images.githubusercontent.com/36355339/109369777-61a17a00-7863-11eb-86eb-ad5c737d36f8.mp4
![MinishCapIssue](https://user-images.githubusercontent.com/36355339/109369875-dc6a9500-7863-11eb-808d-1413aba4cfac.png)

**Comment by sorgelig** [comment]
Main has nothing to do with ROMs.
Please open issue in corresponding core.
