### ISSUE TITLE
Input: Analog Y position is not updated with "analog d-pad" controllers

### ISSUE THREAD

**Issue by steven-a-wilson** [MiSTer-devel/Main_MiSTer#359]
(Continuing from https://github.com/MiSTer-devel/Apple-II_MiSTer/issues/4)

When analog axes are mapped as the d-pad in Main/Menu (as with some controllers/adapters that report the d-pad as analog axes instead of buttons or hat switch), the analog Y axis position sent to the core is not updated.

To reproduce this with a modern game pad, use the left stick in place of the d-pad and skip the analog inputs when mapping the pad.

This shows up in the Apple II core as left and right working, but up and down being unresponsive, as can be quickly tested with the following in BASIC (use the user button or LCTRL + LALT +RALT to skip booting from disk):

```
10 PRINT PDL(0)" "PDL(1)
20 GOTO 10
RUN
```

I also see strange joystick behavior in the ao486 core in this case, although it's not as simple as the Y axis not working. For example, Jumpman Lives seems to be fine, while ZZT fails calibration (but works with a modern pad mapped in the normal way). It seems that for ao486, the core itself does some mapping of d-pad inputs to analog axes, which might explain the difference compared to the Apple II core (which, as far as I can tell, doesn't actually use the d-pad inputs even though they are connected).

I've added logging and it appears that the following condition is never true in such configurations, although I'm not sure why:
https://github.com/MiSTer-devel/Main_MiSTer/blob/1844709a00231f07e27c157060bfa84becfcb58e/input.cpp#L2611

**Comment by sorgelig** [comment]
i followed your instructions. I'm using M30 BT gamepad which generates analog stick values by d-pad. 
Your basic code shows 0/255 for both X and Y axes when i press d-pad (which generates analog stick events). So i can't reproduce your issue.
It seems issue relates to specific gamepad.

**Comment by sorgelig** [comment]
oh, i've reproduced it.
will investigate it.

**Comment by sorgelig** [comment]
in Menu core, when it asks for "Analog X" and "Analog Y" and the end of gamepad definition, you HAVE TO press RIGHT on d-pad for "Analog X" and DOWN for "Analog Y". If you skip these steps then MiSTer won't send analog (even emulated) values.
