### ISSUE TITLE
Feature : Add the possibility to mount floppy disk image on read only mode for cores using floppies

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Main_MiSTer#360]
Hi,

Previously on core ao486, I put floppies in zip file to be sure the core will not write on the floppy disk image.
Since a change on Main or Ao486, this solution is no longer possible  (c.f. https://github.com/MiSTer-devel/ao486_MiSTer/issues/60). It will be great to have  an option to mount floppy on Read Only for Ao486 and other cores.

Thanks,

**Comment by sorgelig** [comment]
You can set "read-only" flag for file, so it will be read only
This works not only for ao486 but for all cores. You can even open HDD in read-only mode.

**Comment by wwark** [comment]
Previously I tested to set "read-only" flag for file but it is not keep. I will try again.
Nevertheless, it will be more convenient to have this option to mount floppy on read-only on the OSD.

Thanks !

**Comment by wwark** [comment]
I see on the Atari ST core it was already implemented with the option "write protect" in the osd.

**Comment by sorgelig** [comment]
i will add it

**Comment by wwark** [comment]
Thanks a lot @sorgelig !

**Comment by wwark** [comment]
Thank you for adding this feature on Ao486 :+1:
