### ISSUE TITLE
Idea Rclone asking file overwrite if newer date.

### ISSUE THREAD

**Issue by diettelo** [MiSTer-devel/Main_MiSTer#365]
Idea if you made a mistake and choose Rclone save download jnstead of Rclone save upload, that Eclone asks: There is a newer File would you like to Overwrite this or all file or none?

I overwrited a Save by Mistake , i wanted to backup it but choosed download instead of upload.

**Comment by sorgelig** [comment]
i think you accidentally posted this issue in wrong repository.
I have no idea what you are talking about.

**Comment by diettelo** [comment]
ohh sorry i did not know.I am a github newb

**Comment by birdybro** [comment]
@diettelo  https://github.com/MiSTer-devel/Scripts_MiSTer/issues/new <-- This is the repo you are looking for. :)

The Scripts you are referring to are the rclone ones in there. Good luck!
