### ISSUE TITLE
Feature: File Core configuration option that saves the filename

### ISSUE THREAD

**Issue by paulb-nl** [MiSTer-devel/Main_MiSTer#366]
For example Gameboy and Nes can load a custom palette but it is not possible to save it.

I suggest something like this:
"FC2,palette,GBP,Choose Palette;"

2 is index same as normal
"palette" is appended to the core cfg filename so with Gameboy it will save the chosen filename to Gameboy_palette.cfg and then auto load it at core boot.

**Comment by sorgelig** [comment]
Added to both Main and NES.
I think additional name is redundant since index number is always available.

**Comment by paulb-nl** [comment]
Thanks Sorgelig! It works well.

The name is not necessary but it does make the filename better. The config folder has good filenames like NES_gamma.cfg, NES_scaler.cfg and NES_volume.cfg but for this it's now NES.f3 which is not very clear what it is.
