### ISSUE TITLE
F core option without d/h freezes Main

### ISSUE THREAD

**Issue by paulb-nl** [MiSTer-devel/Main_MiSTer#368]
I am trying to add a new F option to the Gameboy core like below:

````
"ONO,Super Game Boy,Off,Palette,On;",
"F2,SGB,Load SGB border;",
````
Main freezes with `Kbd mode: Joystick1` staying on screen. If I use d5F2 or h5F2 it works.

I have changed Load palette from F2 to F3. Same thing happens when removing h1 from Load Palette

**Comment by sorgelig** [comment]
it's about counter overflow. I will fix it.
