### ISSUE TITLE
Browser proxy for classic computer cores

### ISSUE THREAD

**Issue by limi** [MiSTer-devel/Main_MiSTer#373]
When using computer cores that are Internet-capable, it can be hard to use the modern internet because of outdated browser layout engines and SSL requirements, etc.

The HPS side of things could offer a proxy that abstracts away these modern requirements using [Browservice](https://github.com/ttalvitie/browservice).

A way to do this would be to turn this on via the Scripts menu similar to how MiSTer offers FTP, SMB etc services.

This way, cores like the Amiga, ST, Mac and ao486 could browse the modern web and it even supports file downloads — which comes in super handy when setting up these cores.

CC: @alanswx

**Comment by sorgelig** [comment]
MiSTer provides tiny and basic internet connectivity not for luxury browsing. Adding proxy on HPS side is definitely not going to happen due to resources.
