### ISSUE TITLE
Hyperkin Duke controller is not recognized

### ISSUE THREAD

**Issue by Mellified** [MiSTer-devel/Main_MiSTer#375]
The [Hyperkin Duke controller](https://www.hyperkin.com/hyperkin-duke-wired-controller-for-xbox-one-windows-10-pc-green-limited-edition-hyperkin-officially-licensed-by-xbox.html) is a recreation of the original Xbox controller. It behaves as a standard Xbox One controller, except that it uses the Hyperkin USB vendor ID rather than Microsoft's. It is not detected by the Linux xpad driver currently, although an [issue has been open since August 2018](https://github.com/paroj/xpad/issues/106).

Fortunately there is a working method to enable support for unknown USB Vendor IDs in xpad, as outlined in the xpad issue:

1. `echo "2e24 0652" > /sys/bus/usb/drivers/xpad/new_id`
2. `modprobe xpad`

Unfortunately this must be done each cold reboot of the MiSTer for the controller to function. Having this built-in would improve the out-of-the-box experience for any user attempting to use this controller.

**Comment by sorgelig** [comment]
before it will be merged to kernel, you always can add that script into init.d and it will be executed on every start.
It has nothing to do with Main (this repository).

**Comment by Mellified** [comment]
My apologies for putting this in the wrong repo.
