### ISSUE TITLE
Feature: Support the spinner on Atari VCS Classic Controller 

### ISSUE THREAD

**Issue by dot-bob** [MiSTer-devel/Main_MiSTer#376]
I am trying to get the Atari VCS Classic controller working with the Mister.  [https://atarivcs.com/wireless-classic-joystick ](https://atarivcs.com/wireless-classic-joystick ) [https://atarivcs.medium.com/the-atari-wireless-classic-joystick-and-atari-vcs-vault-677945d3d8d2](https://atarivcs.medium.com/the-atari-wireless-classic-joystick-and-atari-vcs-vault-677945d3d8d2)

This controller has a d-pad, 5 buttons, and an encoder integrated into the joystick that is designed to be used as a spinner.  The controller has two modes VCS and PC mode.  In pc mode the encoder is disabled so I have been testing primarily in VCS mode.  I can get the d-pad and buttons to map fine as a conventional joystick and it works great as an Atari 2600 joystick but I haven't been able to do much with the encoder.

Capturing data from the serial console the encoder comes in as Axis 7 and turning clockwise goes from 0 to 1023 then loops back to zero, counter-clockwise is just the opposite direction 1023 to 0.  It behaives the same wither it is mapped bluetooth or via wired USB.

Input event: type=EV_ABS, Axis=7, Offset=0, jnum=1, ID:3250:1001:00, abs_min = 0, abs_max = 1023, fuzz = 3
Input event: type=EV_ABS, Axis=7, Offset=1023, jnum=1, ID:3250:1001:00, abs_min = 0, abs_max = 1023, fuzz = 3

I assume it needs support added to detect the encoder as a spinner.  Would it be possible get spinner support added for the encoder?  If so is there anything other information needed than the information I provided above?

-Rob

**Comment by sorgelig** [comment]
is it possible to buy it now? When they supposed to ship if preorder on site?

**Comment by sorgelig** [comment]
Hmm.. it seems they don't ship to Taiwan.

**Comment by dot-bob** [comment]
Last I heard on the Atari discord preorders through the website were to ship end of the month or the first of next.  Gamestop seems to be showing a release date of 04/30/2021 but some of their pages also show TBD.  I received mine through the original Kickstarter but plan to buy a few more when it is generally available.

**Comment by dot-bob** [comment]
I noticed today on Patreon support for the VCS Classic Controller was added in a recent update.  I can confirm it works as paddle and driving controller in the Atari 2600 core and as spinner in other cores.
Thanks for the great work.
-Rob

**Comment by skooterblog** [comment]
Is this working on current version? I can't get the spinner to work in any core. I can't map it either in the mapping menu option. I don't know if it is needed.

**Comment by sorgelig** [comment]
while holding two red and back buttons down rotate the spinner: left -> disable, right -> enable
It's disabled by default because cores supporting both spinner and joystick get confused

**Comment by skooterblog** [comment]
Thank you. I read the changelog when this update was released. But I completely forgot about the combo by the time my joystick arrived.
