### ISSUE TITLE
Feature: add rivalcfg tool for mouse sensitivity configuration

### ISSUE THREAD

**Issue by mapfde** [MiSTer-devel/Main_MiSTer#380]
Hi,

I am using a steel series mouse with MiSTer. Its color and - more importantly - its sensitivity can be configured on linux with the rivalcfg tool. Available here: https://github.com/flozz/rivalcfg

Please consider adding it to the linux environment.

**Comment by sorgelig** [comment]
MiSTer cannot support specific option for wide variety of devices. MiSTer even not a PC and doesn't have traditional GUI.
I recomend to use mouse with configs stored inside the mouse, so you can pre-configure button map and sensitivity in multiple configs switched by button on mouse. Then you can plug it to MiSTer and switch your configs directly on mouse without using any specific tool.
As for that tool - probably it can be compiled and used from linux environment on MiSTer - that's up to users with specific needs.

**Comment by mapfde** [comment]
Thanks for the reply. I understand that MiSTer cannot support all kinds of devices. I tried, but the tool cannot be compiled in the linux environment on MiSTer. The libraries it needs are there, so I will try something on my own.
