### ISSUE TITLE
Feature: support for the SNES XBAND keyboard

### ISSUE THREAD

**Issue by tjanas** [MiSTer-devel/Main_MiSTer#381]
Would it be possible to use this as an alternative to a USB keyboard?
![image](https://user-images.githubusercontent.com/20304619/114213408-8b50c500-9928-11eb-8a15-31a891e3d7ff.png)

**Comment by sorgelig** [comment]
Linux side (To which Main belongs) supports only USB devices. Find an USB adapter for this keyboard and you will be able to use it on MiSTer as a generic keyboard.
Basically this is useless option since you have thousands USB keyboard models you can choose.

**Comment by tjanas** [comment]
Thank you. I will give it a try with a Raphnet USB-SNES adapter.
