### ISSUE TITLE
Feature Request: User defined field in OSD

### ISSUE THREAD

**Issue by lymandev** [MiSTer-devel/Main_MiSTer#388]
The request is to add a user defined field to the OSD that anyone could populate with what ever text they want for a specific core/rom. This would allow users to add information, cheat sheets, move lists, help/guides to a core/rom so they can access that information quickly and easily.

**EXAMPLES:**
1. You're playing Street Fighter II and want to know how to preform a characters moves, you're able to go into the OSD and look at them there.
2. While using a Computer core you're having issues accessing files, you can go to the OSD and have a guide for how to do that on the MiSTer for that core and its quarks.

If no file was found the option would be greyed out. The text files can be maintained without requiring a binary compilation into the RBF file and would instead be maintained by the user. For the user they would only require the correct format and location to work. You can have a text file for each core and then a header for each game, like the ini file or just mix the core-set name in the file name.

This could benefit all cores and users could develop scripts that others could use to quickly and easily populate their cores/roms.

I know that some form of this has been requested in the past but most likely the use case was too narrow/specific to add. That said I believe this approach resolves the issues of the previous requests as it is broad enough to meet many of the desired use cases while remaining narrow enough in scope.

**Comment by sorgelig** [comment]
May be something like this will appear later.
Reading a guide in 32x16 char window with Latin-only charset isn't convenient way..

**Comment by thehughhefner** [comment]
Hi,
What about an option in the OSD called "Manual" and you can change pages by pressing either right or left. That could be a workaround regarding the limitation?

**Comment by sorgelig** [comment]
Sure, manual will require page/line scroll. It's still very small screen for manuals.
Probably i will add it later.

**Comment by thehughhefner** [comment]
I think this is already implemented. There is a "Help" section in the OSD for the core where you can read a text file pretty much

**Comment by sorgelig** [comment]
Yeah, can be considered as implemented.
