### ISSUE TITLE
Empty "inputs" folder is still being generated on root of SD card

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Main_MiSTer#391]
Small issue I noticed:

inputs folder was moved to "config/inputs" a while ago, but even if you delete "inputs" folder from the root of the SD card, the system still auto-generates an empty one on the root, even though it is unused.

**Comment by sorgelig** [comment]
will be fixed in next release

**Comment by M-Walrus** [comment]
I saw that a fix was included for this today, but after updating I still have the empty folder being generated.

I loaded the GBA core and mapped buttons to test, and I noticed the folder is created again after rebooting.

**Comment by sorgelig** [comment]
hmm.. can you give me stpb by step to reproduce it?

**Comment by mirkorean** [comment]
Is it possible that you just didn't include that commit with the release "MiSTer_20210504"? I can reproduce the "input" folder getting created with that release, but when i build from source myself there is no "input" folder created anymore.

**Comment by M-Walrus** [comment]
> 
> 
> hmm.. can you give me stpb by step to reproduce it?

-Update to current build via updater 

-Delete inputs folder from SD root if it's there

-Load GBA core

-Map controller and save

-Reboot

-Check SD card root for inputs folder

Each time I do this, the empty inputs folder is on the root.

**Comment by sorgelig** [comment]
try this version:
[MiSTer.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/6423476/MiSTer.zip)

may be it's really i've forgot to include that commit into release.

**Comment by M-Walrus** [comment]
Yes, that fixed it for me.  The folder is no longer appearing when I do the above steps.

**Comment by sorgelig** [comment]
So it's fixed actually but didn't go to release yet.
Will be in the next release then. It's not so urgent.
