### ISSUE TITLE
Inputs Occassionaly Incorrect with Hori Real Arcade Pro VX SA Kai FightStick for Xbox 360

### ISSUE THREAD

**Issue by joshuaryoung** [MiSTer-devel/Main_MiSTer#392]
The joystick directions will sometimes "stick" (controller reads seem to poll the direction that was being pressed) for 1 - 2 seconds every once in a while (every 10 - 20 seconds). Makes playing fighting games a no go

![image](https://user-images.githubusercontent.com/10542661/117067688-90b2ec80-ace7-11eb-9309-a254dade222d.png)

**Comment by sorgelig** [comment]
Try to use other USB port on hub. Also try to disconnect other USB devices. Sometimes it may conflict.

**Comment by joshuaryoung** [comment]
I redefined it in the main menu and it seems to have fixed it. Thanks!
