### ISSUE TITLE
Only show folders that has roms in it

### ISSUE THREAD

**Issue by thehughhefner** [MiSTer-devel/Main_MiSTer#393]
Hi,
I wonder if it would be possible to add a feature to only show folders that actually have ROMs in it, and hide the ones that are empty? For example, I don't use computer cores and I have to scroll down and find the core I want to play and it takes time. I am specifically talking about games/ folder and not other ones. 

Kind regards

**Comment by sorgelig** [comment]
Don't download the cores you don't want.
Update script has settings to skip unwanted cores.

**Comment by thehughhefner** [comment]
Hi,
While this is true, I would have to specify the cores that I don't want to download/update. It's a long list. Hence my "suggestion" of making it possible through an option to hide the cores that are not populated. And only show up when they have a rom in them

**Comment by mirkorean** [comment]
Hi @thehughhefner,

the update script has whitelist and blacklist options and also supports categories.

https://github.com/MiSTer-devel/Updater_script_MiSTer/blob/ef7593624c672309c78d5acc57018d689de37f82/mister_updater.sh#L129

So you could just have an update.ini with the following setting and only arcade and console cores would updated and created:
```
REPOSITORIES_FILTER="arcade-cores console-cores"
```

Besides that, i don't really get your problem to be honest. If you are in a console core you and want to load a rom it automatically starts in the `games/${core}` and not in the parent, right? Where do you need to scroll through computer cores exactly?
