### ISSUE TITLE
Running HTGDB scripts in MiSTer

### ISSUE THREAD

**Issue by thehughhefner** [MiSTer-devel/Main_MiSTer#394]
Hi,
Would it be possible to add functionality to run the Hardware target gaming database scripts through MiSTer? Having to set it up on my PC seems complicated and it would be really nice to have scripts for it to sort the roms. It is similar to the arcade organizer.

**Comment by sorgelig** [comment]
You can run scripts from OSD in Menu core.

**Comment by sorgelig** [comment]
python script can be run from shell script. And shell script can be run from OSD.

**Comment by thehughhefner** [comment]
Hi,
So I can run those HTGD scripts on my MiSTer?

Kind regards

**Comment by mirkorean** [comment]
Not sure if that's actually a good idea, but you can, yes. Feel free to join the discord to get help on this. Better suited for theses questions, i guess.
