### ISSUE TITLE
[Feature Request] CRT H/V Adjustment

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/Main_MiSTer#396]
Hi! recently Jotego published on twitter one opction to add to all cores for adjust H/V on CRT.
Many cores are disajusted when its shown in screen using a CRT monitor, like sony trinitron, phillips, etc.
It would be wonderful if this option can be add to all cores in mister framework.

The link to the Jotego's tweet is here: https://twitter.com/topapate/status/1391115446515126273?s=09

**Comment by sorgelig** [comment]
it was already discussed here:
https://github.com/MiSTer-devel/Genesis_MiSTer/issues/178#issuecomment-835829157
