### ISSUE TITLE
Using a USB absolute mouse as lightgun

### ISSUE THREAD

**Issue by sonik-br** [MiSTer-devel/Main_MiSTer#399]
Hi.
I'm trying to use a Guncon (PS1 Lightgun) adapted to work as a absolute mouse.
Mister detects it but the movement seems to be relative.
There's any way to enable absolute mode for mouse?
It works as desired in windows and linux (ubuntu) with the default usb hid driver.

**Comment by sorgelig** [comment]
i don't have such device, so it's hard to understand how it works.
But anyone having such device can add support.

**Comment by sonik-br** [comment]
The guncon is connected to a arduino.
The arduino acts as a USB HID Mouse with absolute positioning.
It's expected that the OS translates absolute positions to screen position.
This translation should work as in a analog joystick (this one works).

Last night I got it working by emulating a joystick instead of a mouse. But it's hard to use as it will move the menus in the OSD. Not the best way to experience it.
Any help getting this to work would be much appreciated.

**Comment by sorgelig** [comment]
if you can simulate VID/PID as well, then i suggest to simulate RasPad3 touchscreen - it already supported as gun. 
The only trick will be to switch to gun mode as it requires multitouch of 4 fingers.

**Comment by sonik-br** [comment]
Thanks.
I don't think it's safe to change the VID/PID of the arduino but I will look into it.

Another question... How to simulate the gun pointing out of screen (for reload) when using a mouse? Mister implements it?
I think Mame it uses the bottom left coords.

**Comment by sonik-br** [comment]
Tested. Does not work.

Using the VID/PID found on the input.cpp file...

**RasPad3**
No mouse move.
Can open calibration screen by pressing F10.

**Mayflash Dolphinbar**, **Ultimarc Aimtrak** and default **Arduino Leonardo**
Mouse moves but seems too sensitive.
Can not open calibration screen.

If anyone with a 15K CRT screen and a PS1 Guncon45 wants to build the adapter and test in Mister:
https://github.com/sonik-br/GunconDuino

**Comment by sorgelig** [comment]
is it only for CRT?
I can acquire PS1 Guncon from ebay - it seems not a problem. But i don't have CRT, so not sure if i can use it. What is the principle of its work?

**Comment by sorgelig** [comment]
btw, may be try to mimic WiiMote VID/PID and events? It should be the best way.

**Comment by sorgelig** [comment]
it seems guncon 3 should be the right version for MiSTer

**Comment by sonik-br** [comment]
Hi. Guncon 1 and 2 only for CRT. They need to be connected to a csync signal and pointed to a CRT as they can "see" the tube's drawing each line.
1 is for ps. I can emulate it as USB mouse or joystick using a arduino.
2 is for ps2 and uses usb. Some kernel drivers exists for it.

Now, Guncon3 is for ps3 and not requires a CRT. Wors kind like a wiimote with IR LEDs over the display. One guy have [reverse engineering](https://www.beardypig.com/2016/01/06/guncon3/) it's protocol and wrote a kernel [driver](https://github.com/beardypig/guncon3)
With help we can make it work on mister.

I would love to have the possibility of using a CRT lightgun and a LCD lightgun on Mister :)
Gcon1 and 2 have very fast response time compared to Gcon3. And Gcon3 is way better than a wiimote ;-)

**Comment by sonik-br** [comment]
Got the Guncon2 working by using Python to access the usb device and to emulate event device (using evdev).
Not practical but works.
Next step is to get the Guncon3 working. Then port the code to C and write as a kernel driver.

**Comment by sorgelig** [comment]
All guns need special support in MiSTer as there is no standard how they represent themselves.

**Comment by sonik-br** [comment]
The gun is working on mister. But it's using a python script and not a proper kernel driver.
Python reads the usb and reports as a analog joystick.
I want to integrate the driver kernel on mister but I have no clue about how the licensing works.

**Comment by sonik-br** [comment]
Hi @sorgelig 

I lost my controller mapping file and now I'm having a bad time trying to map my guncon to the analog axis. It's hard (almost impossible) to hold it still and do the proper mapping.

How the mapping file works? Wold be possible properly to create one manually outside of mister?

**Comment by sorgelig** [comment]
it's simple 4 16bit values Y min/max and X min/max.

**Comment by sonik-br** [comment]
But about the mapping? Like:
USB controller X and Y axis to mister analog stick?
USB controller buttons to mister buttons?

**Comment by sorgelig** [comment]
it's much more complicated.
you can check input.cpp

**Comment by sonik-br** [comment]
Got an easier way to map the gun axis in mister... By connecting a dualshock controller and using the analog. Then swapping to the guncon.

@sorgelig right now my guncon adapter is working fine on mister by reporting as an analog joystick.
Would be possible to enable gun calibration with any analog input device when emulating a lightgun?
See, some games have a calibration screen (like Yoshi Safari on SNES), but others don't.

**Comment by sorgelig** [comment]
can you mimic Wiimote using it's VID/PID? Then you can emulate IR coordinates and it will have standard WiiMote calibration dialog.

**Comment by sonik-br** [comment]
I can change the VID/PID... but I have no idea how to send the IR coordinates to mister over usb.

**Comment by sorgelig** [comment]
it's absolute (EV_ABS) coordinates. You can check input.cpp QUIRK_WIIMOTE

**Comment by sonik-br** [comment]
Oh! It's really that simple?
 I thought that the wii remote returned the position of the two IR LEDs and the software had to calculate the screen coordinates..

**Comment by sorgelig** [comment]
everything is calculated inside wiimote

**Comment by sonik-br** [comment]
By using the wiimote's VID and PID I can get mister to show the lightgun calibration screen by pressing F10.
But the calibration screen does not register any movement. All values are "0000".

By looking at the input.cpp file, there's support for the Ultimarc lightgun. The Ultimarc reports a mouse and a joystick.
So I also tried to use the VID and PID from the Ultimarc lightgun but can't open the calibration screen. It should work right?

**Comment by sorgelig** [comment]
calibration is supported for wiimote only. I will re-check calibration. Currently i'm busy by bluetooth update on MiSTer. Then will refresh my memory about wiimote work.

**Comment by sonik-br** [comment]
Finally got it working by setting it's vid:pid:serial in input.cpp and assigning it as a lightgun.
Submitted a PR for it #573 
Also thanks to @NolanNicholson for the help :)
