### ISSUE TITLE
addition to advanced setup guide

### ISSUE THREAD

**Issue by jcw** [MiSTer-devel/Main_MiSTer#4]
On my setup, the µSD card shows up as `/dev/mmcblk0` and partitions as `/dev/mmcblk0p1`, etc. This breaks the `create_sd.sh` script, which assumes `/dev/sdX` and `/dev/sdX1`, etc. Note the subtle difference: an extra `p` inserted for partitions in my case.

I worked around this with `cd /dev/ && ln -s mmcblk0 mmcblk0p` and then specifying the latter symlink as device name to the script.

**Comment by sorgelig** [comment]
Because script is supposed to be used with USB devices, not native card readers.
You can use any USB SD card reader and it will be shown as /dev/sdX

**Comment by jcw** [comment]
I placed the µSD into the slot on my Intel NUC box. Anyway, the same issue has been reported [before](http://www.atari-forum.com/viewtopic.php?f=117&t=31825&hilit=ddr3&start=250#p323405) (perhaps a note on the wiki page will be of help to future visitors?). Closing this issue - thx.

**Comment by sorgelig** [comment]
Ok. I've added the note into guide.
