### ISSUE TITLE
Controller mapping issue

### ISSUE THREAD

**Issue by Pasha-From-Russia** [MiSTer-devel/Main_MiSTer#401]
The controller that is recognized as two devices cant be mapped properly.
Say, when we plug in the controller, the Linux recognizes the devices:
1234:5678:1
1234:5678:2
but MiSTer ignores the device id when the user is doing the mapping, it only uses ProductId and VendorId (it registers the same buttons for both devices)

**Comment by sorgelig** [comment]
Devices with same VID and PID are considered as same device and same button mapping applied.
For example: when you plug 2 Dual Shock controllers then they will have the same button mapping for both players. It's not an issue, it's how MiSTer supposed to work.

May be if you will tell more about this device, there is a solution (depending on what you want to achieve).

**Comment by Pasha-From-Russia** [comment]
My device is Daemonbite Sega2Usb adapter that supports 2 controllers. It works fine in Windows and Linux and I would like it to work with MiSTer too

**Comment by Pasha-From-Russia** [comment]
My device is Daemonbite Sega2Usb adapter that supports 2 controllers. It works fine in Windows and Linux and I would like it to work with MiSTer too so I could map 2 players at the same time

**Comment by sorgelig** [comment]
I see what you mean now.
You can add to MiSter.ini file:
```
no_merge_vid=0x1234
no_merge_pid=0x5678
```
then MiSTer won't merge gamepads from this adapter.

**Comment by paulb-nl** [comment]
Is this a real Daemonbite adapter or clone? The adapters description says they should be compatible with Mister so they shouldn't need the no_merge ini options.

**Comment by Pasha-From-Russia** [comment]
> I see what you mean now.
> You can add to MiSter.ini file:
> 
> ```
> no_merge_vid=0x1234
> no_merge_pid=0x5678
> ```
> 
> then MiSTer won't merge gamepads from this adapter.

Thank you, Alexey! I will check that in the evening

**Comment by Pasha-From-Russia** [comment]
> Is this a real Daemonbite adapter or clone? The adapters description says they should be compatible with Mister so they shouldn't need the no_merge ini options.

I made this adapter by myself using the schematics and sources by MickGyver

**Comment by Pasha-From-Russia** [comment]
> Is this a real Daemonbite adapter or clone? The adapters description says they should be compatible with Mister so they shouldn't need the no_merge ini options.

A single controller adapter works just fine. Perharps, a two controller adapter is not popular among MiSTer users

**Comment by paulb-nl** [comment]
Sorgelig and MickGyver did some work in the past to get 2 player working with Arduino so it should work. Did you change the Vid/Pid of the arduino?

What do you get in the serial log when you connect the Arduino? https://github.com/MiSTer-devel/Main_MiSTer/wiki/Console-connection

**Comment by sonik-br** [comment]
I was having the same problem. (trying to use a single arduino with multiple controllers)
Just setting the no_merge parameters in INI have not fixed.
To make it work I had to also edit the file "u-boot.txt" and add a usbhid.quirks setting.
Got the solution on this [post](https://misterfpga.org/viewtopic.php?t=115)

**Comment by Pasha-From-Russia** [comment]
Thanks to everyone and sorry for the late reply...
I had to reprogram the adapter to change some mapping (i.e. BTN_A for player 1 was not equal to BTN_A for player 2, etc)
Now the adapter works just fine in 2 player mode
