### ISSUE TITLE
Ability to set audio as mono

### ISSUE THREAD

**Issue by manast** [MiSTer-devel/Main_MiSTer#402]
Not sure if this is something that can be done in the firmware or if it must be done for every core, however I think it would be quite useful if it was possible to configure the output audio as mono. The reason is that some Arcade cabinets are mono, and while it works well with older arcades, the new ones that are stereo only will reproduce left or right. Yes, this can be solved at the hardware level by mixing the signals but still it would be quite convenient to have it as a configuration setting in mister if it is not very hard too implement.

**Comment by manast** [comment]
or maybe it can be implemented as a custom audio filter :/

**Comment by sorgelig** [comment]
this is needed to be implemented per core. 
Most cores are originally mono. Cores with stereo audio usually have Audio mix option.
