### ISSUE TITLE
refresh_max seems to be off by 1

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Main_MiSTer#404]
In the **nrallyx** core you need to set refresh_max=59 to get 60 Hz.

It's like MiSTer extracts 1 Hz from the max frequency.

If you set refresh_max=60 the core runs above the max requency - at 60.3 Hz I think.

**Comment by sorgelig** [comment]
It's max refresh rate supported by TV, so MiSTer won't try higher frequencies but will fall back to standard frequency according to current video_mode parameter. 
It doesn't control the original core frequency. Core still outputs its own refresh, but TV will not follow it and will use fail-safe refresh, so it won't be synced but at least will show the video.
It's not supposed to be precise as you may think. Since fractional part of refresh isn't used, it's simply truncated. Also due to some calculations it can be a little (-/+1Hz) different. 
So, it's not an issue actually.

**Comment by dfilskov** [comment]
Hmm I don't understand why you would want MiSTer to convert the core signal of 60.9 (which doesn't work on my monitor) to to 60.3 (which also doesn't work on monitor) when I set refresh_max=60

What should I write as

**Comment by sorgelig** [comment]
use vsync_adjust=0
In this case the the output will always have refresh from video_mode you use.

**Comment by dfilskov** [comment]
Thanks! - I've found that having set refresh_max=59 in the **nrallyx** core section of MiSTer.ini for some reason seems to enforce the core to use 60 Hz on the HDMI. That way I can keep using vsync_adjust=2 and perhaps get lower latency?

**Comment by sorgelig** [comment]
Sometimes explanation may be confused. in this context i call as "core" everything in FPGA except the framework. So core implementing original HW always outputs video with refresh it needs, and framework cannot change it. Framework can only change the output refresh from scaler.

**Comment by dfilskov** [comment]
Thanks for the explanation! :) - I think I understand. That's why I wonder why the MiSTer framework / scaler converts the original HW to 60 Hz instead of 59 when I write this in the core section of MiSTer.ini:

[NRALLYX] ; 289:224
refresh_max=59
vscale_border=48
custom_aspect_ratio_1=1734:1344

Here's my entire MiSTer.ini with video_mode, overall min/max etc. - (I use 1920x1440 for normal cores and 1920x1920 for vertical) ... not sure if I have set something wrong which makes 59 into 60 herz:

https://www.dropbox.com/s/84firpbfq7l0kxl/mister.ini?dl=0

**Comment by sorgelig** [comment]
refresh_max/min is applied only to vsync_adjust 1 and 2. If refresh is outside limited range, then refresh from  video_mode is used which can be 60 or whatever is configured there.

**Comment by dfilskov** [comment]
Hmmm if I had used vsync_adjust 1 of 2 with max_refresh=60 the scaler would have used 60 Hz for the 60.9 Hz core as I expected.

But I have tried vsync_adjust=0 and max_refresh=60 - then 60.3 is used for the 60.9 Hz core - and
