### ISSUE TITLE
I2S signals skew

### ISSUE THREAD

**Issue by ajefr** [MiSTer-devel/Main_MiSTer#409]
Hello,
I just got trouble with the I2S signals and some DAC.
After some investigation, I found that there is skew in the I2S signals generation.
![MISTER_I2S_1](https://user-images.githubusercontent.com/19753516/122123956-ec1be280-ce2e-11eb-8fdb-47a388b77fe8.png)
You can see that either LRCK or DATA signals change before the clock while it should not do so.
LRCK and DATA should be syncrhonise with falling edge of MCLK.
The difference is near 50ns but it's enough to make some Texas DAC failed and don't decode any sound.

Here is an I2S signals took from a Raspberry Pi :
![RPI_I2S_4](https://user-images.githubusercontent.com/19753516/122124334-6c424800-ce2f-11eb-9bac-fe3c8ec552da.png)
You can see that LRCK and DATA are synchronized with MCLK
Thanks

**Comment by sorgelig** [comment]
in i2s data is latched when CLK goes from low to high. Only during this stage data and ws must be stable. 
If you have troubles then either: either CLK is too smooth due to not enough pull up or cable is too long making signals delay from each other beyond acceptable time.
Or simply your DAC uses inverted clock.

**Comment by ajefr** [comment]
Thanks for your message.
This is not an hardware problem (cable, clk level, ...), I use the exact same configuration/board between the pi and the mister.
And the only difference I see is this clock shifting.
If needed I can make some test by recompiling a core. I have all the necessary tool.

**Comment by sorgelig** [comment]
Clock is NOT shifted. You are talking about irrelevant clock transition from high to low. If your DAC depends on it, then something wrong with your schematics. The fact that DAC works with Pi has no indication of bug. DATA and WS must not change the state at the same time as active transition of clock. So chip should not relay on high-to-low clock transition. If it does, then schematic is wrong.

**Comment by ajefr** [comment]
I'm developing a board for the mister, so, yes my first thought was I made an error in the hardware.
I spent many hours trying to find which one without success.
Then I ordered a raspberry pi shield with the same chip and got the same behaviour.
So I'm almost sure it's a core problem.

Fyi, I'm not an electronic noob ;-)

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by sorgelig** [comment]
check the spec of your chip. Probably it uses inverted clock. May be it either has config for clock or you need an inverter.

As i've told above above, the clock transition where data signals change their states cannot be used. If you design the board which uses that clock transition then it's badly designed board.

**Comment by ajefr** [comment]
Hello,
After many investigations, it looks like you were not far from the truth.
It's nearly an hardware error, but most a chip error.
In fact Texas chip are one of the rare chip that canno't run I2S in 32FS mode at 48khz in 3 wire mode. 
Usually I2S chip can generate their own MCLK (like PCM5102), but this TI is unable to do this by it's own at a so low input frequency.
My first option was to speed up this, but it's also unable to decode 92khz audio...
So it leads me to two questions to solve my issue :
- May it be possible to chose the 24 or 32 bits mode I2S by parameter/config file, like the 92khz audio option ?
- Or may it be possible to output the MCLK signals to any free pin of the de10 I/O ?
Thanks

**Comment by sorgelig** [comment]
I think there should be a 3rd option: find a compatible DAC ;)
There are no free pins left. Even if you see some pins looked as unused, they are used on other circumstances. 
I think there is a big choice of i2s dac chips to choose from. 
96KHz option has an advantage, so it's added for systems support it. 
24/32bit mode gives nothing than just support some chips.
