### ISSUE TITLE
Feature request: Allow multiple keys per mapping

### ISSUE THREAD

**Issue by dukesilverfan** [MiSTer-devel/Main_MiSTer#41]
Currently you can only map one key to one action. Often I use 'select' **OR** 'left shoulder' as the MiSTer Menu action, but this is an issue with games that use the 'select' or 'left shoulder' buttons. Retroarch solved for this by allowing multiple keys to be mapped, so that you can press 'select' **AND** 'X' at the same time to access the menu.

Does this make sense? I think this could be very useful for users like myself that primarily use controller-based cores without a keyboard attached.

**Comment by sorgelig** [comment]
Current input processing is already very complex. Adding multiple keys will only add complexity more.
Also processing of multiple keys combination is too ambiguous. If you press the first key, then it's unclear should MiSTer wait some time for another key before set the action, or it should be processed as single key and then with second key the current action should be canceled and multipress action should be started. Process of cancellation adds new feature - the queue which is not implemented. Currently there is one press - one event. 
So, instead to choose controller with more buttons, you move this problem to developer and ask for more complexity.

Solution is easy: buy a gamepad with enough buttons. Many gamepads add special button similar to PS-button or XBox-button.

**Comment by dukesilverfan** [comment]
I am sorry that my well-intentioned feature request came off sounding like I was lazy and passing more work onto the developer. This was intended to go in tandem with development of the LL Cool Joy and other hardware adapters for us that use real hardware for controllers, where simply changing to a gamepad with more buttons is not an option. The PS and Xbox directional buttons are subpar, so in the meantime I will just continue to keep a keyboard wired up to the unit, or attach a microswitch to my case for the menu.

I hope I did not offend you, I legitimately believed this was a good feature request.

**Comment by sorgelig** [comment]
This topic has been discussed in forum.
So, you just confirm that old 1-2 button joysticks are not suitable for MiSTer.

Some games are good to control by dpad for precise move. Some games are good to control by stick. Modern USB gamepad have both dpad and stick, so it's pretty much convenient just use one gamepad and quick switch between controls even in one game.
