### ISSUE TITLE
HDMI to VGA direct video compatibility

### ISSUE THREAD

**Issue by manast** [MiSTer-devel/Main_MiSTer#410]
I hope this is the correct place to post an issue regarding the HDMI to VGA converter in order to use the direct video feature. 

I had an old HDMI to VGA (3-4 years old) that I tested with my first Mister with direct video and it worked as a charm. Now I bought a new Mister for a second arcade and I am having the worst time finding an HDMI to VGA adapter that works, bought 3 different models but none work (the last one I bought is from the same place as the first one but it seems they changed the chipset or something because it is not working either). So basically what I wonder is if we could keep a list of known to work HDMI to VGA adapters, 100% verified or something... 

The ones that I have tested that do not work (Swedish sites):

https://www.amazon.se/gp/product/B08HXRQGXM/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
https://www.amazon.se/gp/product/B00ZMV7RL2/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
https://www.24.se/mobiltillbehor/samsung/samsung-datakablar/hdmi-till-vga-ljud-adapter

One of the devices is of brand Rookie as it was recommended here: https://www.retrorgb.com/mister-240p-over-hdmi.html

**Comment by rikard-softgear** [comment]
This one works, as I have one myself. https://www.jula.se/catalog/hem-och-hushall/hemelektronik/datortillbehor/usb-kablar-och-adaptrar/hdmi-vga-adapter-003087/

**Comment by sorgelig** [comment]
It's better to use Wiki, not an issue. It will be more visible.

**Comment by manast** [comment]
> It's better to use Wiki, not an issue. It will be more visible.

yes, ultimately that would be the place to show the information, but how/where can we ask the community to update the wiki with the list of devices?

**Comment by sorgelig** [comment]
Wiki is filled by the ones who like to fill. So if you are willing to add such info, then you can do it yourself.

**Comment by manast** [comment]
Yes, I will. My problem was that I did not find any that worked! :). I will test the one suggested by @rikard-softgear. 
I will close the issue then and hopefully people that find working devices will update the wiki.

**Comment by sorgelig** [comment]
basically any converter using AG6200/AG6201 chip should work fine, although it's not always possible to tell which adapter uses this chip till you open it up. Even manufacturer may silently swap the chip to another one keeping the same adapter name and look.

**Comment by manast** [comment]
@rikard-softgear unfortunately the device that you recommended did not work either. Spent over 100eur now on 4 devices, none works... maybe the devices are with the compatible chip are not produced anymore, I will update the wiki so that people are aware of it, maybe it is not an option anymore.

**Comment by manast** [comment]
Ok, I made some more experiments and actually learned a couple of things. With my old HDMI to VGA, this VGA to SCART works perfectly: https://www.antoniovillena.es/store/product/vga-scart-adapter/ but ```composite_sync``` must be 0 in mister.ini since the device mixes hsync automatically. I assumed that this meant that all HDMI to VGA will be compatible with Antonio Villenas device, but this is not the case. Of the 4 new HDMI to VGA that I bought, the 3 first works with the standard VGA to SCART from the Mist FPGA (not mister, https://github.com/mist-devel/mist-board/wiki/ScartCable), but then we need the ```composite_sync``` otherwise the image does not sync properly. 
Finally, the last device recommended by @rikard-softgear does not work with neither Antonios device nor Mist cables... no idea why.

**Comment by butterrsoft** [comment]
The Vention AIDB0 model adapter on ebay lists the AG6200 chip specifically. Only one i've found that does. Not the cheapest, but it works with composite sync at 15kHz, and eBay's refund policy means money back if they substitute.

**Comment by rmueller83** [comment]
I got this one, which claims to use an AG6200 in the description: https://www.amazon.de/dp/B09MF2HXGF

Using a phone opening tool (called Jimmy at iFixit) it was pretty easy to open it:

![vga1](https://user-images.githubusercontent.com/2698076/182878588-ae03f517-7db5-4c26-b258-55cd35626a0f.jpg)
![vga2](https://user-images.githubusercontent.com/2698076/182878621-1da91fd7-9544-4c26-959d-be08e9417b35.jpg)

Can someone identify this chip?

**Comment by birdybro** [comment]
Yes I have heard from some users that non-AG620x chips have been circulating, this is known. They must either be some kind of knockoff of the AG620x (if it's working) or a totally different chip doing a different kind of conversion method (if it's not working). I have seen ones with chips that have no datasheet on the internet. Looking online for a `cm6616se` on google reveals only 4 results, but multiple point to it being some other kind of hdmi-vga chip. I would let the seller know and try and get it replaced since they advertised it as being an AG6200 chip.

**Comment by hughobrien** [comment]
![IMG_20220808_221358](https://user-images.githubusercontent.com/3400690/183516229-bceacd78-d7aa-40a2-8642-ed3c80fac7ef.jpg)

This is what the AG6200 should look like

**Comment by Slamy** [comment]
I know that this is closed but it doesn't really feel like it concluded to something. I've added a feature branch which adds a table to the wiki.
The reason for this particular time is that I wasn't able to find something online and today went to a MediaMarkt to buy two. I wanted to at least provide some help for others trying to find an HDMI-VGA converter that works.
PS: It somehow isn't possible to make pull requests on Wikis. Or is it?

**Comment by birdybro** [comment]
Pull requests can't be made on GitHub wiki's like that. The Main_MiSTer wiki was locked only to people with edit privileges on that whole repo due to abuse. There is a new repo called Wiki_MiSTer which you would need to be granted edit privileges to in order to get it updated.

If you'd like you can add the information to the MkDocs site with a pull request instead and I'll merge it. :)

A guide I wrote that shows you how to edit the MkDocs site --> https://mister-devel.github.io/MkDocs_MiSTer/editing/

The repository --> https://github.com/MiSTer-devel/MkDocs_MiSTer/

**Comment by sorgelig** [comment]
Anyone who wants to edit wiki can ask for that and i will give rights.
