### ISSUE TITLE
Setting NVRAM size to 65536 produces a dump of internal MiSTer firmware data

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#418]
The NVRAM size is specified in the MRA file like:

```
<nvram index="2" size="256"/>
```
This works correctly. But if you try to make a larger dump, the firmware breaks and instead of producing a dump from the FPGA, it just dumps its own internal data. The barrier seems to be at exactly 65536 bytes, i.e. 64kB.

```
<nvram index="2" size="65536"/>
```
Please find attached two files, one generated with `size="65535"` and the other with `size="65536"`. If you open them with a hex editor, you will see that the second one contains MiSTer's the last opened MRA file text. That text isn't in the FPGA and can only come from the firmware memory. 

[nvram_bug.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/6745637/nvram_bug.zip)

**Comment by sorgelig** [comment]
I didn't think nvram will be so big. I've pushed the fix.

**Comment by jotego** [comment]
Thank you. The commit looks good :-)
