### ISSUE TITLE
Minimig HDF Files not working

### ISSUE THREAD

**Issue by DeGr666** [MiSTer-devel/Main_MiSTer#419]
The HDF files stopped working for me when the new IDE drivers were implemented.

The files were made with WinUAE and are the size of 4GB. Have been working fine until now.

**Comment by sorgelig** [comment]
Read this topic. https://misterfpga.org/viewtopic.php?f=4&t=2863
Solution is also there.

**Comment by DeGr666** [comment]
Sorry about that. I reconfigured my HDF files and everything seems to be running fine now.

Maybe a „create hdf“ option in the OSD menu would make things more comfortable / understandable in the future?
