### ISSUE TITLE
Smb conf and Password

### ISSUE THREAD

**Issue by diettelo** [MiSTer-devel/Main_MiSTer#428]
Whenever a linux update is from Mister (i think), password changes to default and smb conf also.

I play most games from USB Hard Drive, so i have allways to edit smb.conf so i can acess it from pc again.

Can you make it so that if password and smb or any file is moded, it wont be replaced?

**Comment by sorgelig** [comment]
password for samba should be set in `/media/fat/linux/samba.sh`
example is in `/media/fat/linux/_samba.sh`
