### ISSUE TITLE
Atari Branded USB Spinner Not Supported

### ISSUE THREAD

**Issue by 98PaceCar** [MiSTer-devel/Main_MiSTer#431]
I picked up one of the Atari branded USB button spinners to use with the cores that support spinners: https://www.microcenter.com/product/624264/atari-usb-spinner

I believe this is the same as the GRS spinner which seems to work on the Mister. Initial testing on the Mister with the analog I/O board v6.1 has no response from the spinner/mouse rotate in Arkanoid, Tron, or the InputTest core. In all 3 of those cores, it does show that both of the supported buttons on the spinner report as the same button, but it does report the button presses. 

In WIndows 8, it shows up as a HID compliant mouse and controls the cursor fine. In the shell on the Mister, lsusb shows the same VID: PID as Windows.

VID: PID = 32be:1420

I've added these values as well as ffff:ffff to the mister.ini settings for using a mouse as a spinner. No difference.

lsusb from the Mister outputs the following:

Bus 001 Device 007: ID 32be:1420  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x32be 
  idProduct          0x1420 
  bcdDevice            2.00
  iManufacturer           1 Baolian industry Co., Ltd.
  iProduct                2 BL button spinner # 1
  iSerial                 3 A03C304C4252
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 
      bInterfaceSubClass      1 
      bInterfaceProtocol      2 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      74
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              10
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered

Connection to the serial uart on the Mister and subsequent attempts to rotate the spinner shows this:

The file mouse0 was created.
Close all devices.
Open up to 30 input devices.
make_unique(289B,0057,-1)
make_unique(0E8F,3013,1)
make_unique(16C0,05E1,1)
make_unique(045E,02A1,1)
opened 0( 0): /dev/input/mouse0 (0000:0000) 0 "usb-ffb40000.usb-1.6/input0/A03C304C4252" ""
The file event1 was created.
Close all devices.
Open up to 30 input devices.
make_unique(289B,0057,-1)
make_unique(0E8F,3013,1)
make_unique(16C0,05E1,1)
make_unique(045E,02A1,1)
opened 0( 0): /dev/input/event1 (32be:1420) 0 "usb-ffb40000.usb-1.6/input0/A03C304C4252" "Baolian industry Co., Ltd. BL button spinner # 1"
opened 1( 1): /dev/input/mouse0 (32be:1420) 10 "usb-ffb40000.usb-1.6/input0/A03C304C4252_sp" "Baolian industry Co., Ltd. BL button spinner # 1"
The directory by-id was created.
The directory by-path was created.
Close all devices.
Open up to 30 input devices.
make_unique(289B,0057,-1)
make_unique(0E8F,3013,1)
make_unique(16C0,05E1,1)
make_unique(045E,02A1,1)
opened 0( 0): /dev/input/event1 (32be:1420) 0 "usb-ffb40000.usb-1.6/input0/A03C304C4252" "Baolian industry Co., Ltd. BL button spinner # 1"
opened 1( 1): /dev/input/mouse0 (32be:1420) 10 "usb-ffb40000.usb-1.6/input0/A03C304C4252_sp" "Baolian industry Co., Ltd. BL button spinner # 1"
Input event: type=EV_REL, Axis=1, Offset=1, jnum=0, ID:32be:1420:00
FileOpenEx(open) File:/media/fat/config/inputs/input_32be_1420_v3.map, error: No such file or directory.
FileOpenEx(open) File:/media/fat/config/input_32be_1420_v3.map, error: No such file or directory.
FileOpenEx(open) File:/media/fat/config/inputs/input_32be_1420_v3.map, error: No such file or directory.
FileOpenEx(open) File:/media/fat/config/input_32be_1420_v3.map, error: No such file or directory.
/dev/input/mouse0: xval=0, btn=0, spinner=0, paddle=0
Input event: type=EV_REL, Axis=1, Offset=-1, jnum=0, ID:32be:1420:00
/dev/input/mouse0: xval=0, btn=0, spinner=0, paddle=0
Input event: type=EV_REL, Axis=1, Offset=-1, jnum=0, ID:32be:1420:00
/dev/input/mouse0: xval=0, btn=0, spinner=0, paddle=0
Input event: type=EV_REL, Axis=1, Offset=-1, jnum=0, ID:32be:1420:00

**Comment by sorgelig** [comment]
in windows when you rotate the spinner, mouse moves horizontally or vertically?

**Comment by 98PaceCar** [comment]
It moves vertically under windows.

**Comment by sorgelig** [comment]
spinner manufacturers cannot agree on common standard, sigh... 
previous spinners used horizontal movements.
Ok, i will add vertical one too.

**Comment by sorgelig** [comment]
it's is more weird because VID: PID = 32be:1420 is used in BSP Arcade Spinner where X movement is used.

**Comment by sorgelig** [comment]
try this build:
[MiSTer.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/6874139/MiSTer.zip)

in MiSTer.ini you need to add:
```
spinner_axis=1
```

**Comment by 98PaceCar** [comment]
It's recognizing the spinner now, but the left/right motion is reversed. Other than that it feels really good!

**Comment by sorgelig** [comment]
add:
```
spinner_throttle=-1
```

**Comment by 98PaceCar** [comment]
I was just pulling up the .ini to see if there was a setting. -1 made it pretty twitchy, but going to -50 made it very playable. 

Thanks for making this change!

**Comment by 98PaceCar** [comment]
Latest version has the changes to support the Y axis on a spinner as requested. Closing issue. Thanks Sorgelig!
