### ISSUE TITLE
Unreliable wifi connectivity with shared SSID for 2.4Ghz and 5Ghz networks

### ISSUE THREAD

**Issue by goldenegg** [MiSTer-devel/Main_MiSTer#432]
I've been having an ongoing issue with wifi, where the MiSTer won't connect to my wifi network reliably on every boot. I'd have to keep power cycling it until it finally connected. This could sometime take upwards of 30min to finally get a connection. After a bunch of troubleshooting, I believe the cause of the problem is when trying to connect to a router that uses a single SSID for both the 2.4Ghz and 5Ghz bands.

I'm currently using an Orbi RBR850/RBS850 mesh system, but this issue also occurred with my previous Asus AI Mesh setup that also used a single SSID. The single SSID configuration is becoming the default on most new routers. While it can be split on some routers, it can't easily be split on routers such as the Orbi or Google Mesh.

Orbi does have a hack to split the SSID, which has the unfortunate effect of breaking other things, but I confirmed that splitting the SSIDs fixes the connectivity issue. After splitting the SSIDs, wifi connects reliably on every boot.

I will be confirming if the same is true with the Asus configuration tomorrow.

If there are any logs that could help, I'd be happy to provide them.

This problem is reproducible on 4 MiSTer builds I have, with every wifi adapter I've tried. I've used separate power supplies for the DE10 and USB hub, just to take the power splitter out of the equation. Here are the wifi adapters I've used:

ASUS USB AC53 rev A1
Comfast CF-812AC 
Edimax EW-7811UN V1
Edimax EW-7822ULC
Netgear A6100
TP-LINK TL-WN823N V2

These wifi adapters have no trouble connecting to the single SSID when used on other devices.

CURRENT BUILD: MiSTer v210724, OS v210711

**Comment by goldenegg** [comment]
I can confirm that splitting SSIDs also fixed the issue on the Asus AI Mesh setup (AC5300 + AC3200).

**Comment by sorgelig** [comment]
Nothing can be done here. Use different SSID on different bands. I also do this. Same SSID confuses other devices too.

**Comment by birdybro** [comment]
I'll add that general Linux machines have this problem as well, usually associated with specific models of Intel WiFi adapters or certain other manufacturer's wifi chips. I've added troubleshooting to the Wiki for the wifi page at the end to hopefully point people in the right direction as I've helped a handful of people with this in the past, it comes up frequently enough anyways.

https://github.com/MiSTer-devel/Main_MiSTer/wiki/WiFi-setup

**Comment by goldenegg** [comment]
I just want to note that the recent Linux update with all the wifi and BT changes has fixed this issue for me.
