### ISSUE TITLE
Unable to map controls for 8bitdo N30 Bluetooth

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Main_MiSTer#436]
This is the controller I'm currently having issues with: https://www.8bitdo.com/n30-ns/

My controller works as intended with my Switch and my 8bitdo bluetooth receiver (NES).

The problem: it pairs on MiSTer, but no inputs are detected when trying to map controls. Controller is currently at firmware 6.14. Contrary to other 8bitdo controllers, this one only has one way to pair: 

![image](https://user-images.githubusercontent.com/7781739/128210300-93f1c487-462f-40af-9903-3f9c6c73cdf3.png)

Info about my MiSTer setup:
- Mister V210803
- OS v210711
- I use this bluetooth dongle (which works with all my other bluetooth controllers): https://www.amazon.ca/Bluetooth-Adapter-Receiver-Transfer-Wireless/dp/B0775YF36R

![image](https://user-images.githubusercontent.com/7781739/128209973-a02c22ef-d5e8-44c7-8bd7-172b113d3b34.png)

**Comment by sorgelig** [comment]
all 8bitdo controllers have bad compatibility in Switch mode (blame crappy 8bitdo firmware), so make sure you use X-Input or D-Input mode with MiSTer.

**Comment by felleg** [comment]
> all 8bitdo controllers have bad compatibility in Switch mode (blame crappy 8bitdo firmware), so make sure you use X-Input or D-Input mode with MiSTer.

Thanks for the reply Sorgelig. Looking at the manual (pictured above), there seems to be no way to choose between a Switch mode and D-input mode. So I will assume this means the controller requires switch mode...

You confirm there is no way to captures the inputs on the MiSTer in Switch mode?

**Comment by diettelo** [comment]
Try Start and A or Start and B.

I got also that issue.

all my 8bitdo Controllers works fine

**Comment by diettelo** [comment]
You must try it until it shows the 8bitdo name.

ihave following controllers from 8bitdo:

SFC30
N30 Modkit
SN30 Modkit
P30 Modkit
Zero 2 Gamepad
Arcadestick

and all of th working fine.

Best way you can do is asking 8bitdo if there is an x or d mode for your controller.
They respond very fast and with most good info.

In the manual i couldnt dind anything.

**Comment by diettelo** [comment]
Ok found something, if N30 NS is your Controller then you might have a problem:

https://support.8bitdo.com/faq/n30-ns.html

**Comment by sorgelig** [comment]
If it only supports Switch mode then i'm afraid you can't use it.
MiSTer supports switch controllers - i have many. Official Switch controllers work fine. 3rd party switch controllers is a hit and miss. Most of them are working. The problem is in exactly 8bitdo firmware.

**Comment by felleg** [comment]
That is unfortunate. Thanks for the explanation!
