### ISSUE TITLE
Screen size issue with Sharp Aquos LC37D40U

### ISSUE THREAD

**Issue by buvk** [MiSTer-devel/Main_MiSTer#440]
Sharp Aquos LC37D40U resolution is 1366x768.  When MiSTer is connected via HDMI using 1280x720@60 (selecting 1366x768@60 shows unsupported resolution), output is zoomed in and the top/bottom/sides are cut off.  This can be circumvented in the menu by adjusting vscale_border, however, the cores themselves are still zoomed in.

Is there any way to address this aside from using analog output?

**Comment by sorgelig** [comment]
probably try to make a custom resolution. Besides the visible 1366x768 resolution there are invisible fields which may require of specific size by this TV/Monitor. Probably you need to google to see if some people have more info about supported resolutions of this display.

**Comment by buvk** [comment]
I found an interesting thread where someone experienced a similar issue with their TV:

https://www.sevenforums.com/graphic-cards/104010-no-1366x768-resolution-my-tv.html

As for my TV, it will apparently only accept 1080i/720p/480p/480i signals even though native pixel resolution is 1366x768, so I am not sure a custom resolution will help in this case.

Is it possible to prevent upscaling a 720p output to the pixel resolution (1366x768)? Maybe some kind of zoom/overscan/underscan setting on MiSTer since this cannot be adjusted on the TV.

I did try 640x480@60; everything fits on the screen in this mode, however, using this resolution is not ideal.

**Comment by boogermann** [comment]
@buvk try using this video mode
```ini
video_mode=1360,48,32,80,768,3,10,9,72048
```
as the settings on MiSTer for that resolution is targeted towards monitors at 85.5Khz (CVT), the one I gave you is more suitable for TV's (CVT-RB)

**Comment by buvk** [comment]
I just tried this.  The TV did not accept this video mode (unsupported resolution).

**Comment by boogermann** [comment]
@buvk my bad, I just notice the line I gave you is 1360 and not 1366. I have a tool to generate the modelines for mister but they will round the value to the closest even number divided by 2. So it won't accept 683 as valid and round to 680.
I can fine tune the application to generate the correct value, but If you can plug the screen to a PC (Windows/Linux) and run an edid program to read what your screen will report back as valid resolutions would help a lot.
On windows you can use this application: https://www.nirsoft.net/utils/dump_edid.html and just run the executable on the command prompt so you can see the output.
On Linux you can install the package `read-edid` and run with `get-edid | parse-edid`.

**Comment by buvk** [comment]
dumpedid returns the following:

> Supported Display Modes  :
>     1920 X  540  60 Hz

**Comment by boogermann** [comment]
It showed only one resolution!? that's odd, here's an example of what my is dumping.
Either way I made one fitting that resolution so you can check the results, try one at the time
```ini
;CVT
video_mode=1920,64,192,256,540,3,10,9,82007
;CVT-RB
video_mode=1920,48,32,80,540,3,10,6,69763
```

```
Active                   : Yes
Registry Key             : DISPLAY\ACI2493\5&11eaf8b8&0&UID4352
Monitor Name             : VE247
Serial Number            : DBLMQS034540
Manufacture Week         : 46 / 2013
ManufacturerID           : 26884 (0x6904)
ProductID                : 9363 (0x2493)
Serial Number (Numeric)  : 16843009 (0x01010101)
EDID Version             : 1.3
Display Gamma            : 2.20
Vertical Frequency       : 50 - 76 Hz
Horizontal Frequency     : 30 - 83 KHz
Maximum Image Size       : 53 X 30 cm (24.0 Inch)
Maximum Resolution       : 1920 X 1080
Support Standby Mode     : Yes
Support Suspend Mode     : Yes
Support Low-Power Mode   : Yes
Support Default GTF      : No
Digital                  : Yes

Supported Display Modes  :
     720 X  400  70 Hz
     640 X  480  60 Hz
     640 X  480  67 Hz
     640 X  480  72 Hz
     640 X  480  75 Hz
     800 X  600  56 Hz
     800 X  600  60 Hz
     800 X  600  72 Hz
     800 X  600  75 Hz
     832 X  624  75 Hz
    1024 X  768  60 Hz
    1024 X  768  70 Hz
    1024 X  768  75 Hz
    1152 X  864  75 Hz
    1280 X  960  60 Hz
    1440 X  900  60 Hz
    1280 X 1024  60 Hz
    1280 X 1024  75 Hz
    1680 X 1050  60 Hz
    1600 X 1200  60 Hz
    1920 X 1080  60 Hz
```

**Comment by buvk** [comment]
Yup, here is the full output:

```
Active                   : Yes
Registry Key             : DISPLAY\SHP0FBE\4&4d3e7d6&0&UID198171
Monitor Name             : SHARP HDMI
Manufacture Week         : 0 / 2006
ManufacturerID           : 4173 (0x104D)
ProductID                : 4030 (0x0FBE)
Serial Number (Numeric)  : 16843009 (0x01010101)
EDID Version             : 1.3
Display Gamma            : 2.20
Vertical Frequency       : 59 - 61 Hz
Horizontal Frequency     : 15 - 46 KHz
Image Size               : 61.5 X 46.1 cm (30.3 Inch)
Maximum Image Size       : 82 X 46 cm (37.0 Inch)
Maximum Resolution       : 1920 X 540
Support Standby Mode     : No
Support Suspend Mode     : No
Support Low-Power Mode   : Yes
Support Default GTF      : No
Digital                  : Yes
 
Supported Display Modes  :
    1920 X  540  60 Hz
```

I tried both of those video modes.  I get a picture, but it is not centered.  Using the first one you listed, the image is shifted to the right.  Using the second, it is shifted to the left.

**Comment by boogermann** [comment]
what a weird display, there's another line I didn't include because rarely works, but due to all those weird behaviors it won't hurt trying
```ini
;CVT-RB-2
video_mode=1920,8,32,40,540,2,8,6,66720
```
I've also generated with margins but I don't think it would help
```ini
;custom mode:hact,hfp,hs,hbp,vact,vfp,vs,vbp,Fpix_in_KHz
;CVT
video_mode=1984,64,200,264,540,3,10,10,84855
;CVT-RB
video_mode=1984,48,32,80,540,3,10,6,71910
;CVT-RB-2
video_mode=1984,8,32,40,540,2,8,6,68855
```
and here is the 1366x768 with margin
```ini
;custom mode:hact,hfp,hs,hbp,vact,vfp,vs,vbp,Fpix_in_KHz
;CVT
video_mode=1408,72,144,216,768,3,10,18,88210
;CVT-RB
video_mode=1408,48,32,80,768,3,10,10,74417
;CVT-RB-2
video_mode=1408,8,32,40,768,9,8,6,70620
```

**Comment by boogermann** [comment]
Ok, so that mode is actually interlaced!
I found information on your display here: https://edid.tv/edid/891/ the serial number helped track it down and it seems to support 1080i and 720p

I generated this one with the tool, but if doesn't work your best bet will be to create a modeline with the numbers that came from the edid to match exactly what your monitor wants.

``` ini
;custom mode:hact,hfp,hs,hbp,vact,vfp,vs,vbp,Fpix_in_KHz
;CVT
video_mode=1920,64,192,256,270,3,10,10,42755
;CVT-RB
video_mode=1920,48,32,80,270,3,10,6,36067
;CVT-RB-2
video_mode=1920,8,32,40,270,2,8,6,34320
```

**Comment by buvk** [comment]
> ```ini
> 1920,8,32,40,270,2,8,6,34320
> ```

TV returned incompatible video mode for all 3 of these.

I also tried the ones above that; I either get incompatible video mode or a shifted image.

Ideally I would like to use 720p resolution as opposed to 1080i.  I tried using the following, but it just gives me the same problem I had when I selected video_mode=0 where the sides and top/bottom are cut off (image appears zoomed in)

`video_mode=1280,110,40,220,720,5,5,20,74250`

**Comment by boogermann** [comment]
here is the trio with 1280x720 if you want to give it a try
```
;custom mode:hact,hfp,hs,hbp,vact,vfp,vs,vbp,Fpix_in_KHz
;CVT
video_mode=1280,64,128,192,720,3,5,20,74680
;CVT-RB
video_mode=1280,48,32,80,720,3,5,13,64022
;CVT-RB-2
video_mode=1280,8,32,40,720,7,8,6,60466
```

@sorgelig, Grabulosaure had a fork with the EDID implemented, would it be possible to add that into the framework?
https://temlib.org/pub/mister/edid/, I've noticed not long ago you opened
I've already have the code that deals with the I2C on my fork of main to program the TDA19988, I can easily add the code to read and parse the EDID information and calculate the modeline for what the monitor replies as "preferred timing".
This is the output of the `edid` running on MiSTer with his code in place

**Comment by sorgelig** [comment]
As you've already mentioned, i2c from HDMI is already implemented quite some time ago. So it's up to specific application which may generate compatible modes to specific TV.
Probably it can be done by a python scrips with direct access to i2c. 
Currently i don't have an idea how this should be implemented. MiSTer is not computer with GUI where you can have extensive dialogs with many options. 
Also 99.9% users need just standard resolutions already implemented. 
But for fine tuning for very specific case an utility or script should be fine

**Comment by sorgelig** [comment]
What i've gathered from this topic, this TV is not good for computer/console display as it doesn't support native resolution of its LCD panel (1366x768), so video always will be scaled. Additionally it will be scaled by MiSTer. So 2 scalers are probably too much. 
Keep this TV for movies. Get another more modern one for games.
