### ISSUE TITLE
Controller Fails With Input Display and SNAC Adapter (NES Core)

### ISSUE THREAD

**Issue by xexzy** [MiSTer-devel/Main_MiSTer#441]
When attempting to use an input display, such as retrospy, and a SNAC adapter with the NES core all buttons are read as being pressed. If an input display is not in place, the SNAC adapter works. If the input display is plugged into a device to convert it to a USB controller, the input display works. The input display also functions properly when plugged into my NES. Three different controllers have also been tested and the results were the same.

Additionally, the Genesis and SNES cores do not have this issue and I am able to utilize an input display and the SNAC adapter on these cores.

**Comment by sorgelig** [comment]
You should report issue in corresponding core. Main has nothing to do with SNAC.
Also i have no idea what is "Input Display" means.

**Comment by sorgelig** [comment]
https://github.com/MiSTer-devel/NES_MiSTer/issues/260
