### ISSUE TITLE
Feature Request: Custom Aspect Ratio Per Arcade Core

### ISSUE THREAD

**Issue by atrac17** [MiSTer-devel/Main_MiSTer#442]
Hello @sorgelig, would it be possible to set custom aspect ratios per core? Example, the Irem M62core when I utilize the following on my iPad display I have to manually set the aspect ratio with my custom video mode for the core.

```
video_mode=1536,48,32,80,1020,3,10,15,106644
Aspect Ratio: Full Screen (same as video mode above) or 128:85 (384x255)
```

To get the correct aspect ratio on the iPad display for anything other than console cores I either need to set full screen to the custom video mode or provide the aspect ratio for the custom video mode. 

Since cfg's are saved by setname (mra) or machine name (mame) it would take time to configure arcade cores. It would be very helpful if I could create a cfg per arcade core with the save configuration for aspect ratio (or any other settings) that would apply to any mra I launch for that core.

Thank you for your time. I do not know if it is possible. I appreciate your hard work! 

Here is an example of the settings above mirroring my CRT on one of my iPad displays 😄.

![PXL_20210818_065052203](https://user-images.githubusercontent.com/32810066/129852977-f0aeaed6-f8a6-46a1-a84d-e91602317b90.jpg)

**Comment by sorgelig** [comment]
all options in INI file can be used per-core.
So it's already available.

**Comment by atrac17** [comment]
@sorgelig I apologize, I was not clear in my request. What I meant was setting it as default when saving a cfg file.

For instance `A.IREMM62.CFG` when I create a cfg with Full Screen set as the aspect ratio in the OSD and then launch the mra file that setting isn't applied.

I was asking if there was a way to make these cfg files per core supersede settings per mra when launching. That way I do not have to save a cfg file for every setname I launch when using a custom aspect ratio or switching to full screen.

**Comment by sorgelig** [comment]
it's impossible as Arcades treated as separate cores if setname are different. There is no such functionality when some settings applied per-core and other per-setname. And it's quite hard to implement as it will be hard to manage such dual settings.

**Comment by atrac17** [comment]
Thank you, I understand. I was not sure if it would be in the realm of possibility.

**Comment by atrac17** [comment]
Thank you, I understand. I was not sure if it would be in the realm of possibility.
