### ISSUE TITLE
Feature Proposal : Showing "display video info" with a Fx keys on the Keyboard

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Main_MiSTer#444]
Hi @sorgelig,

In the Mister.ini, we set video_info to display video info just when the core start or if the resolution changed:
; set to 1-10 (seconds) to display video info on startup/change
video_info=10

Do you think it would be possible to map a Fx key on a keyboard  to  show an to hide this "display video info" during a core is running ?

Thanks,

**Comment by sorgelig** [comment]
MiSTer tries to avoid of hijacking the keys. If it's available to MiSTer system function, then it's not available to core. 
What is the purpose of it? You can connect to USB console where debug log gets printed, so you can monitor resolution changes there. For generic user such info gives nothing.

**Comment by wwark** [comment]
The purpose is just to access this data more easily on the screen.
I didn't know this information was log I will use this way.
Thanks for your time !
