### ISSUE TITLE
Bluetooth / Wireless Connection

### ISSUE THREAD

**Issue by neosquid** [MiSTer-devel/Main_MiSTer#447]
Bluetooth keyboard is not detected on startup since recent linux update, along with wireless gamepad.

I have to remove the bluetooth dongle and wireless dongle, reboot mister and replug to get it detected, every-time I switch on the Mister. Previous to the new update, there were no connection issues.

**Comment by sorgelig** [comment]
open BT pairing dialog and press backspace key (or long press OSD button on I/O board). It will delete old pairings. Then pair again.

**Comment by neosquid** [comment]
By pressing the middle button on my I/O board, I can get a screen up which says "Switch Input Devices , searching......" , which lasts a few seconds. The keyboard still does not pair with Mister.

**Comment by neosquid** [comment]
Also of note, my devices are plugged into an OTG Usb hub. I can occasionally get the keyboard to be recognised if I unplug and replug the bluetooth dongle/receiver, but if Mister is switched off, the the keyboard is no longer detected next time the Mister is rebooted.

**Comment by neosquid** [comment]
Issues seem resolved with latest Mister Update.
