### ISSUE TITLE
MiSTer doesn't register its name anymore since last update

### ISSUE THREAD

**Issue by starquake** [MiSTer-devel/Main_MiSTer#448]
Since last update the device doesn't register itself anymore with the DHCP/DNS server. I found an easy fix by uncommenting `#hostname` like this in dhcpcd.conf:

```
# Inform the DHCP server of our hostname for DDNS.
hostname
```
Maybe make it uncommented by default?

**Comment by sorgelig** [comment]
Thanks for pointing out. 
Switched to dchpcd but not all settings have been corrected.

**Comment by starquake** [comment]
AFAIK fixed in latest release
