### ISSUE TITLE
Core-specific joystick button mapping does not work for ambiguous vendorId/productId

### ISSUE THREAD

**Issue by bzeiss** [MiSTer-devel/Main_MiSTer#449]
**Prerequisites:**
Setup:
- 8bitdo Arcade Stick
- 8bitdo Wireless USB adapter (brown brick adapter)
- 8bitdo SF30 Pro

All devices are setup using X-Input.
SF30 Pro is connected to Mister via the Wireless USB adapter.
Arcade Stick is connected via USB cable.

Both devices (Arcade stick via USB cable and SF30 Pro via Wireless USB adapter) identify to Linux as vendorId: 0x045e and productId 0x28e.

**Steps:**
1. Setup SF30 Pro in Mister OSD as joystick
2. Setup Arcade Stick in Mister OSD as joystick
3.  Start Double Dragon 2 arcade core
4. Create custom core button mapping for SF30 Pro. Place "Coin" at R2.
5. Test that coin works on SF30 Pro --> should work
5. Create custom core button mapping for Arcade Stick. Place "Coin" at P2 (previously mapped to a unique key using 8bitdo Ultimate Software)
6. Test that coin works on Arcade Stick --> should work
7. Test that coin still works on SF30 Pro

**Expected result:**
Coin mapping works on both devices

**Actual result:**
Core-specific mapping (and I suspect also the mister mapping) only works as expected on the joystick configured last. Due to the matching vendorId and productId, there is only one input*.map and one JTDD2*.map file in /media/fat/config/inputs.

I have tried to mess around with the no_merge_vid/pid and jamma_vid/pid settings in the MiSTer.ini, but the problem is not that the player 2 stick isn't recognized for player 2, but the problem is rather that the same mapping file is used for both devices although behind the same vendor and productId, there is actually an entirely different joystick with different buttons and sticks. So I guess each need their own mapping file. After taking a look at the input.cpp (which I do not entirely understand with all its exceptions and special cases), it seems there is already a special case for Arduino/Teensys where the .map filename is extended by a uniq flag. However, if I take a look at  /proc/bus/input/devices, I believe the uniq field cannot be used to differentiate them. Maybe, the only way to differentiate them is the usb port number (lie 1-1.6:1.0) they are plugged into.

In any case, I suspect that this is likely to also happen if you use multiple of those Wireless USB adapters and pair, for example, one adapter with a PS4 controller and the other with an xbox controller or whatever controller that is different. If I understand the code correctly and the .map file name differentiation is only used for Arduino/Teensy devices, so I suspect this may happen with any 8bitdo-like adapter dongle (like mayflash magic-s pro) that pairs exactly one controller and that identifies as a non-wireless controller device to the connected system.

I guess it is somewhat of a special case, as most people probably pair their blueooth controllers with a bluetooth dongle. The thought process behind using a dedicated dongle was to be able to easily switch controllers between the Mister and the Nvidia Shield for unsupported emulations like N64 without repairing them and possibly lower latency than using a BT dongle that is paired to multiple controllers (not sure about that).

**Comment by sorgelig** [comment]
This is not an issue of MiSTer. According to general rule, if 2 devices have same VID and PID then they are the same devices. 
Devices you mentioned are mimic Microsoft gamepad and don't provide their own ID, so there is no way for MiSTer to distinguish them from original Microsoft game controller.

As a workaround, i suggest to switch some of these devices to different mode. 8bitdo usually provides several modes: X-input, D-Input, Switch and Apple. Switch mode, btw, is not fully implemented (this tell pretty much all about quality of 8bitdo), so won't work with MiSTer. Other 3 modes if i remember right work. AT least D-Input is fully working. In each mode 8botdo provides different VID/PID so MiSTer will be able to distinguish them.

Another option - use only one kind of 8bitdo gamepad.

Please complain to 8bitdo, not to MiSTer.

**Comment by bzeiss** [comment]
Ok, thanks for looking at this!

**Comment by sorgelig** [comment]
i wish 8bitdo could provide an unique VID:PID in some mode, so other systems may distinguish specific 8bitdo gamepads. For example windows (biggest gaming platform) doesn't require specific VID:PID.. I also have several different 8bitdo gamepads, so it would be good to have mapping specific to each model.

**Comment by bzeiss** [comment]
Yes, I have written to 8bitdo about this and have received the message that it'll be forwarded to the development team. We'll see if they can find a solution for this.

So I have managed to reconfigure the wireless adapter to d-input and that indeed works fine with its different pid/vid. Thanks for that workaround pointer. It'll likely work for one single wireless adapter on the Mister. I don't have a second wireless adapter, but I expect that it reports the same pid/vid twice also in d-input mode likely causing a conflict again with the first adapter when different controllers are used.

The setup as it is probably works fine as long as I don't use my actual xbox360 controller through a wire. Then the Arcade stick will probably conflict with it again on 0x045e/0x28e. I guess the biggest actual issue is that 8bitdo don't even offer a product specific d-input mode with a unique pid/vid for the arcade stick v3 through a wire, but only the x-input mode. So the new arcade stick v3 through wire is in my understanding unfortunately prone to cause conflicts with other x-input devices or the xbox controller.
