### ISSUE TITLE
Feature request .7z support

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/Main_MiSTer#450]
Since 7zr is integrated into the latest linux lib updates and in anticipation of the coming cores and the size limitation of sd cards, where every megabyte will count, wouldn't it make sense to include .7z as a compression method for ROM's?

For example: My SNES collection alone would be reduced from 1.3GB (zip) to 1.05GB (7zip). (250 MB gain)
That adds up mightily on all systems combined.

Thoughts?

**Comment by PhantombrainM** [comment]
I know the technical aspects you listed.

And of course there is a trade-off in CPU time. With small systems it will only take a second and with the big ones like Neogeo maybe a few seconds more, but the user can still decide whether to use zip or 7zip.

In total, the advantage could certainly add up to 1000MB. The arcade cores will also grow strongly. So if you already clean up the Linux library, one could also start here again, especially since it is only a call of the parameters via the Mister Binary to the library.

I already have a 512GB SD card and will change to a 1TB. However, they are still limited and every megabyte is valuable.

If there is no interest, I will close the request. I still think this is a good plan with foresight.

**Comment by sorgelig** [comment]
7zip is not suitable for this. Advantage of 1GB on 512GB is nothing comparing to drawbacks. zlib is fast portable and well maintained over many years. You can find a lot of zip files while 7z is marginal. It took some time for me to find a linux version of 7zip. It's very experimental btw. It's basically Windows-only archiver, not cross-platform. I don't even talk about linux library to work with 7z. 
Not worth.
