### ISSUE TITLE
Blisster Issues

### ISSUE THREAD

**Issue by stagnor** [MiSTer-devel/Main_MiSTer#452]
After using the update_all script I noticed right away that my controller connected to the blisster board was malfunctioning, same with my keyboard.  The control responses are now delayed or at times do not read my inputs when the buttons are being pressed.  I happened to have another sd card with an older update from the beginning of the week and once I plugged it in the controller worked perfectly.  I then updated the 2nd SD card using the update_all script and the same issue with the controller started again.  Does anyone have any idea what is going on or how I can fix this?

**Comment by sorgelig** [comment]
i've saw on FB group that FW update of blisster solves this issue.

**Comment by matthutchinson** [comment]
I have this issue too, will try a blister FW update

**Comment by matthutchinson** [comment]
That worked for me 👍

I ran downloaded and ran this script, resetting on both ports as this video explains.
