### ISSUE TITLE
Bluetooth pairing issues after Linux/Main update

### ISSUE THREAD

**Issue by wackowelsh** [MiSTer-devel/Main_MiSTer#456]
After the 2021/8/29-2021/8/31 Linux / Main update, I’m finding that attempting to pair Nintendo Switch Online NES controllers cause the system to freeze and occasionally outright crash.

Pairing via F11 as well as the Bluetooth script cause the system to lockup after reporting a successful pairing. Controllers show a connected / solid light. Turning the controller off has no effect on the system. Once the system is rebooted, the controllers are unable to connect.

I’ve attempted BT pairing with other controllers (including Nintendo Switch Online SNES controllers) and have no issue. The system successfully removes a previous pairing of the NES controllers prior to the pairing. I’ve also attempted this with a vanilla install of the MiSTer main and have the same issue with freezing.

**Comment by sorgelig** [comment]
https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/issues/7
will be fixed soon
