### ISSUE TITLE
Pixelcade Arcade Marquees Not Working

### ISSUE THREAD

**Issue by alinke** [MiSTer-devel/Main_MiSTer#458]
hi @sorgelig 

Had a few Pixelcade customers reach out with some problems with their Pixelcade marquees and MiSTer. Can you check if this PR https://github.com/MiSTer-devel/Main_MiSTer/pull/416 is in the latest release and functioning as I did upgrade to the latest MiSTer on my end and I don't see the FULLPATH and CURRENTPATH files in /tmp as I'm scrolling through games in the menu. Pixelcade needs those to function correctly. Thanks so much for your help in advance.  

Best, Al 
Creator of Pixelcade Marquees
http://pixelcade.org

**Comment by sorgelig** [comment]
There were no changes in this part. By default it's disabled.
To enable it add `log_file_entry=1` is in MiSTer.ini, and it should be in [MiSTer] section to be active for all cores.

**Comment by alinke** [comment]
Ah , awesome thx ! Will try this out tonight

**Comment by alinke** [comment]
that worked! thanks much @sorgelig ! There are a couple tweaks I need to make on my end and will knock out this weekend and then Pixelcade will be back up and running for MiSTer, much appreciated!!! Also let me know if you can use a LED Pixelcade marquee, I'll be more than happy to send you one on me.

**Comment by sorgelig** [comment]
I'm using PiCade upper panel is 21cm x 5.5cm. It seems there is no such small size of Pixelcade marquee.
Anyway, thanks for offer!

**Comment by alinke** [comment]
@sorgelig might be possible, Pixelcade can also do a single panel for 64x32 vs. the normal 128x32 so the smallest possibility would be a single P2.5 LED panel which would be 15.9 cm x 7.9 cm so it would be a little taller than the PiCade's current marquee but may still be ok. If the laser cut files are available for PiCade , I might be able to design a mount for it. Downside is most of the LED artwork is 128x32 and hence will look a bit scrunched on 64x32 but it's actually not too bad, here's an example build in 64x32 for reference https://www.instructables.com/Vertical-Bartop-Arcade-With-Integrated-PIXEL-LED-D/. Anyhow, I'll poke around and ping you if it's feasible. thx again for your help on this one!
