### ISSUE TITLE
Updating MiSTer OS deletes Wi-Fi adapter config

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Main_MiSTer#459]
I noticed this behavior every time I performed a MiSTer OS update (through update_all.sh) in the past year.

My Wi-Fi adapter is "TP-Link TL-WN725N", and I used this procedure to make it work with MiSTer: https://misterfpga.org/viewtopic.php?p=10006#p10006

Every time a new version of the MiSTer OS is installed, I notice that some files relating to my Wi-fi adapter are deleted:

- `/lib/modules/4.19.0-socfpga-r1/rtl8188eu.ko`
- `/lib/firmware/rtlwifi/rtl8188eufw.bin`

Thus, after a reboot, the Wi-Fi adapter no longer works and requires a manual fix to put back the deleted files.

---
EDIT: 

These instructitons don't even seem to work anymore when performed manually. The `4.19.0-socfpga-r1` folder is gone (does this make the wifi installation instructions out of date? https://github.com/MiSTer-devel/Main_MiSTer/wiki/MISTER-CUSTOM-WIFI-DRIVER-COMPILATION-GUIDE). When I copy `rtl8188eu.ko` to a newly created `/lib/modules/4.19.0-socfpga-r1` folder, I get an error `modprobe: FATAL: Module rtl8188eu not found in directory /lib/modules/5.13.12-MiSTer`. 

I tried to experiment by saving the `rtl8188eu.ko` file in `/lib/modules/5.13.12-MiSTer/kernel/drivers/net/wireless/realtek/rtl8188eu` or `/lib/modules/5.13.12-MiSTer/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8188eu`, and in botth cases I get an error `modprobe: ERROR: could not insert 'rtl8188eu': Exec format error` when running `modprobe rtl8188eu`.

**Comment by felleg** [comment]
[rtl8188eu.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/7122774/rtl8188eu.zip)

For reference, here are the firmware files I am using for my Wi-Fi adapter.

**Comment by sorgelig** [comment]
rtl8188eu driver and firmware is already included in new Linux.
It's possible that your specific dongle VID:PID is not included.
Provide me lsusb command output from your MiSTer, so i will check VID:PID

**Comment by sorgelig** [comment]
As for "Updating MiSTer OS deletes Wi-Fi adapter config" - this is obvious as your changes done inside linux.img which is replaced by new version. Nothing to do with this.

**Comment by felleg** [comment]
> rtl8188eu driver and firmware is already included in new Linux.
> It's possible that your specific dongle VID:PID is not included.
> Provide me lsusb command output from your MiSTer, so i will check VID:PID

Here it is:

```
/root# lsusb
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 005: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 004: ID 248a:8367 Maxxter Wireless Receiver
Bus 001 Device 003: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter
Bus 001 Device 002: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
/root# 
```

**Comment by sorgelig** [comment]
0bda:8179 is already supported in latest Linux release.
You don't have to add anything.

**Comment by felleg** [comment]
I have just tested once more, you are correct! Thank you Sorgelig.
