### ISSUE TITLE
Updated Linux kernel 4.19

### ISSUE THREAD

**Issue by makigumo** [MiSTer-devel/Main_MiSTer#46]
The currently used kernel is already 2+ years old, and I was missing the `usbip` (USB over IP) functionality while waiting for my USB hub to arrive. So I ported the changes to the currently latest socfpga-4.19 branch (https://github.com/makigumo/linux-socfpga/).

I cherry-picked all  relevant changes made to socfpga-4.5, without the backported fixes or modules.

But I needed to update to more recent versions of exfat, which is working fine, and rtl8812AU modules. Unfortunately I don't have such a wireless card, so I could not test this, so this might require some work.

I'm not sure how to proceed, because a pull-request would be massive.

**Comment by sorgelig** [comment]
It seems i cannot fork your branch as current kernel version is the fork of the same repo.
Probably i will re-up my current kernel as a separate non-forked repository, so i will be able to fork the new one.

**Comment by makigumo** [comment]
You could probably just checkout my branch into your working repository and push it back to the MiSTer-github repo. Something like the following:
```sh
git remote add makigumo git@github.com:makigumo/linux-socfpga.git
git fetch makigumo socfpga-4.19-MiSTer
git checkout -b socfpga-4.19-MiSTer makigumo/socfpga-4.19-MiSTer
git push -u origin socfpga-4.19-MiSTer
```

I have been using the 4.19 kernel for a week or so without an issue using the standard linux image, because I could not successfully build a custom one with some modules und binaries added. I probably messed up the `/dev` directory.

I can later have a look at rtl88x2BU support.

**Comment by sorgelig** [comment]
I've already did it. So from now you can use PR to 4.19 branch.

**Comment by makigumo** [comment]
OK, thank you.
