### ISSUE TITLE
Feature request: raw or .ini list of mame zip file names that work.

### ISSUE THREAD

**Issue by undeadindustries** [MiSTer-devel/Main_MiSTer#461]
Hi there. I couldn't find a list of mame zip files of arcade games that work with the Mister.

I could see a few situations where it would be useful.

But for me, I'm almost done creating a rom organizing app and would love to have a "Mister supported" check box.

Possibly there is a list that I couldn't find?

Thanks so much for the consideration!

**Comment by sorgelig** [comment]
it's not task of Main. 
It can be done by some script walking through all MRA files then output list of mentioned zip files.
