### ISSUE TITLE
Having a back button that goes back one step instead.

### ISSUE THREAD

**Issue by thehughhefner** [MiSTer-devel/Main_MiSTer#463]
Hi,
It would be really nice and user-friendly if there could be a "one-step" back button. Right now when I am inside the core, and if I am deep into a folder structure, pressing the "OSD BACK" button on my controller takes me back all the way to the main menu of the core instead of jumping one step back. The only way to go one step back is to select the ".." top of the menu.

**Comment by sorgelig** [comment]
When you open file browser it goes in the "middle" of tree, so you still can go to upper folder outside of home path. Thus using back button as you described will go up till the root folder which may be several parent folders upper than home path.
Actually, you may press and hold "right" button which will autorepeat and quickly bring you to ".." entry.
So it's not that hard as described.

As a workaround i will think to use other buttons like X or Y as a "go to parent" action. Which will be optional feature used for joysticks defined those buttons.

**Comment by thehughhefner** [comment]
Hi Sorge,
Thank you for the quick reply.
Yes since we have "OSD OK" and "OSD BACK", maybe we can instead call them "OSD OK", "OSD GO BACK TO PARENT", "OSD BACK". Hopefully this is not too much cumbersome to implement

**Comment by thehughhefner** [comment]
Hi Sorge,
Thank you for implementing this feature. It works really well and as expected.
If there is one thing that could be better is if the user can define it to any button. For instance, in the define joystick.

**Comment by thehughhefner** [comment]
Hi Sorge,
Respectfully, I don't think that would end up in a good way, to be honest. As a user, it would be easier to define those buttons to any non-assigned buttons. Every user has their own set of controllers with their own amounts of buttons available.
