### ISSUE TITLE
Feature Request: Additional information for what is being played so tty2oled can display arcade image loaded within another core

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/Main_MiSTer#469]
The inclusion of Sega System E arcade game support within the Master System core has raised an issue with tty2oled displaying images.

The problem hereby is that when you start the core the MiSTer system informs us that core X has been started.  As long as you don't start another MiSTer core (i.e. NeoGeo) no internal system message inform us about what you're playing in detail.  This means for Sega System E arcade games that are loaded from within the Master System core cannot have bespoke Images for these games displayed on a tty2oled screen, like the other arcade cores, it will just display the Master System image.  

Is there a way for additional information to be passed of what is being played so that these games could have the correct images displayed?

Was discussed on the forum here:
https://misterfpga.org/viewtopic.php?p=33288#p33288

**Comment by sorgelig** [comment]
How it's done on other arcade cores supporting different games?

**Comment by ojaksch** [comment]
One of the developers of tty2oled here.
> How it's done on other arcade cores supporting different games?

  Currently not at all. We are fetching the started MiSTer core by having an inotify at /tmp/CORENAME and that's all we are aware of. I think that every core has to do a similar thing what Menu is doing, ie by saving the started game/rom of the corresponding core. But I'm sure that we are asking too much of them...even though that would be a great thing.

**Comment by sorgelig** [comment]
i will add /tmp/STARTPATH file which will contain path to either rbf or xml. If it will be xml, then it will be up to your script which data you will get from it.

**Comment by ojaksch** [comment]
Oh, that would be fantastic! If it will be a MRA it would be an easy task to substract MAME's unique <setname> to know what rom is being played/picture is needed. Thanks a lot!

**Comment by ojaksch** [comment]
I can see that this feature is implemented in todays MAIN and seems to work with almost every core which can load ROM files.
You need to set **log_file_entry=1** in MiSTer.ini. Our most important file to watch for is /tmp/CURRENTPATH then, which contains the loaded ROM file, i.e. **A-Team, The (1992)(Probe)(proto).sms** (SEGA Master System) or **Pitfall - Pitfall Harry's Jungle Adventure.bin** (Atari 2600).
Alas, this opens the door for zillions of new logo pictures for the tyy2oled device.

Большое спасибо, Sorgelig!

**Comment by sorgelig** [comment]
good!
