### ISSUE TITLE
PAL TV and consoles alignment mismatch across MiSTer cores

### ISSUE THREAD

**Issue by MarkEire** [MiSTer-devel/Main_MiSTer#470]
**_(UPDATE: MiSTer is not at fault. I've been corrected that the natural shift is an RGB/Composite shift, not RF/SCART. My observation is likely just my cheap old consumer CRT, VHS test was redundant.
MiSTer XY adjustments would help all PAL CRT users, but not on the basis of any inaccuracy in MiSTer. Seems a common EU TV issue, but that would be a feature request at that point.
I'll leave this here so the issue can be closed by the team, and not just removed by me. Apologies for wasting anyone's time that may have started looking into this)_**

Difference in alignment observed comparing PAL consoles on PAL TV (all from UK) to MiSTer set to PAL region.
Outlined attempts to confirm behaviour is not the fault of the CRT, and consistent across two different CRT models.

![PAL_output_comparison](https://user-images.githubusercontent.com/55510982/135184296-be30fc98-f849-4098-b202-4db23649c644.png)

- **Console output, both SMS and MegaDrive via RF**
    - MegaDrive 2, Model MK-1631-50
    - Master System 2, Model 3006-05
- **MiSTer output, SCART from MiSTer IO Board v6.1**
    - Retrogamingcables UK SCART cable
    - IO Board VGA pin set to 5V

Horizontal shift in image noted in both Genesis and SMS cores, cutting off left hand side.
(_Vertical shift in SMS core understood to be a separate issue_).
The MiSTer horizontal shift is noticeable in all cores (eg. GBA, GameBoy).
**Whilst images clearly show my CRT with real hardware is not ideally centred, MiSTer is cropping the left side further still.**

**Researching the issue, I note reports that CRTs can offset from RF to SCART naturally.**
To confirm this was not the cause, I compared the output from a VHS Player that outputs both RF and SCART. The alignment appears identical on my CRT comparing RF to SCART (only interference pattern different in images).
![VHS_RF_SCART_comparison](https://user-images.githubusercontent.com/55510982/135186040-a40820e2-2e46-4144-97a3-baa371b970c5.png)

I have little knowledge of a comparison to NTSC, but overscan or some other offset difference may be responsible if similar behaviour has not been noted comparing NTSC TVs and console hardware.

**Could an alternative offset be implemented for PAL in order to match the output of real hardware?**

**Thank you very much for your time, greatly appreciate all the development on MiSTer.**

Additional info.
Grid pattern output from MiSTer, set to both PAL and NTSC:
![CRT_Test_Grid_Output](https://user-images.githubusercontent.com/55510982/135186468-0f79f1c2-9e60-4c1f-9950-ff1a11b8169d.png)
Confirmation of issue on alternative "BUSH" brand PAL CRT:
![Alternative_PAL_CRT](https://user-images.githubusercontent.com/55510982/135186561-1fb49378-e494-4477-bf1d-06a765be4060.JPG)

**Comment by sorgelig** [comment]
It has nothing to do with Main repository. Main has no control over the video.
Mostly consoles are developed in NTSC format. Not many developers have PAL console to work with. This is why consoles may have shifted video in PAL mode.
But again, it belong to each console. There is no such think where you change in one console and it will be automatically changed in other.

Please post issue in specific consoles repositories, so may be some developer will try to fix it.
