### ISSUE TITLE
Auto fire not working with Xbox controller 1708 via bluetooth

### ISSUE THREAD

**Issue by revoice1** [MiSTer-devel/Main_MiSTer#471]
I just recently noticed that auto fire was possible with the mister when looking at various hotkeys etc... When I went to try the function, nothing seemed to happen though.

**My controller setup**
Xbox One controller model 1708 via Bluetooth
OSD button mapped to Xbox button

**What I have tried**
Press and hold any mapped button while a console sore is active, then tap the OSD button.

**Result**
The OSD opens, and no auto fire seemed to be enabled.

I have tested an Xbox controller model 1708 wired, instead of Bluetooth, and auto fire is working as expected.
I have also tested with an Xbox controller, model 1914, and auto fire works completely as expected via Bluetooth.
It seems like this issue may be specific to Xbox controller model 1708 when connected via Bluetooth, but I obviously have no idea if other models/controllers might be affected in the same way.

Let me know if there is any additional information I can provide to be helpful. Very low priority, but wanted to report as a bug anyway, in case there are other users or controllers experiencing the same behavior.

Please see discussion here: https://misterfpga.org/viewtopic.php?f=32&t=3375

**Comment by sorgelig** [comment]
can you provide VID:PID of your gamepad?

**Comment by sorgelig** [comment]
i have XBox 1708 too, so tried through Bluetooth - autofire works fine. 
Are you using latest Main?

**Comment by revoice1** [comment]
Hi sorgelig!

Yes my mister should be completely up to date.
I actually have two of the same controller that exhibit the same behavior. 

045e:02ea Microsoft Corp. Xbox One S Controller

Both controllers were on the same firmware, 3.1.1221.0. This morning I've updated one to the latest, 4.8.1923.0, and the auto fire is now working....Sorry, should have done this before opening the issue. Hopefully it's still useful information to have out there in case anyone else runs into this.

Thanks!
