### ISSUE TITLE
Replace update.sh with MiSTer Downloader script in future MiSTer releases

### ISSUE THREAD

**Issue by michaelshmitty** [MiSTer-devel/Main_MiSTer#483]
Hi, [mrfusion](https://github.com/MiSTer-devel/mr-fusion) creator here.

I've received some requests to bundle the new [MiSTer Downloader](https://github.com/MiSTer-devel/Downloader_MiSTer) Python based script instead of the older update.sh script with the Mr. Fusion installation image.
However, the update.sh script is already packaged in the MiSTer release which I just embed in the Mr. Fusion image.
So instead of performing the unnecessary steps of unpacking the MiSTer release, replacing the update.sh with the new downloader script, repackage the release and embed it into the Mr. Fusion image, I'm proposing you replace the update.sh script with the newer downloader script when you feel the time is right to do so.
If you do, just ping me when that's done and then I will generate a new Mr. Fusion image with the latest MiSTer release containing the new downloader script.

Thanks for your time & kind regards,
Michael

**Comment by birdybro** [comment]
Just checking in with this issue again, downloader.sh seems to be mature and the preferred choice now among the users and expert users. We all suggest it and I think it should be integrated into the image in place of update.sh in the scripts folder, or at least alongside it.

**Comment by sorgelig** [comment]
It's already in plans for new Linux release.
