### ISSUE TITLE
potential vsync_adjust=2 tearing (stuttering) bug

### ISSUE THREAD

**Issue by Videodr0me** [MiSTer-devel/Main_MiSTer#484]
I just updated to the newest version of Mister - last update was over a year ago (maybe longer).
On many cores (SNES, TGFX16 and others) i noticed some tearing (every 5 seconds) which i never had before. If i then cycle through the Scandoubler Fx settings - arriving at the exact same setting that i started with - the tearing is gone and everything works as expected.

How to reproduce:

0) mister.ini settings differing from default: video_mode=8, vsync_adjust=2, video_info=10, controller_info=10
1) Cold Reboot Mister
2) Load TGFX16 core (will also happen with other cores, but might be harder to see)
3) Load SuperGrafx *SGX Rom: Darius Alpha (Japan) SuperGrafx Enhanced (others will work too, but here its easy so see)
4) Start Game (Press RUN) and watch background scrolling. I get a tear every 4-5 seconds.
5) Goto Menu->Audio & Video->Scandoubler FX cycle through all options once arriving back at "none" and leave Menu
6) Problem is now completely fixed and only returns reliably after a cold reboot. It might also sometimes return if you extensively playround with the scandoubler, scaling options and change between certain cores, but i could not reliably confirm this.

**Comment by icelaglace** [comment]
I can confirm this too. I was wondering if I was the only one. 
It's definitely a regression somewhere, could be the latest Linux kernel or the latest Main.

Been playing for over a year on vsync_adjust=2 and I now get tearing at some point over time. 

One thing though, since the latest update, my monitor never shows a black screen when I switch scandoubler (the monitor used to lose signal for a second and come back) same for borders on the Genesis. 

It could be HDMI related maybe ? I cannot try on a CRT to test. 

Also, it happens on every core. Even the Wonderswan at 75hz.

**Comment by Videodr0me** [comment]
I think I know whats causing it, after launching the core it displays a slightly different (wrong) refreshrate (display) as if vsync_adjust=2 did not initialize properly and uses a wrong refreshrate. The differential between the real (correct) core refreshrate and the adjusted refreshrate leads to the hick-up every 5 seconds. 

Interestingly after you cycle the scandoubler options it suddenly properly calculates the vsync_adjustment and both refreshrates match -> and the problem ist gone.

**Comment by sorgelig** [comment]
probably initial core loading process makes adjusting hiccup.. May be some time out will help.
Will see what can i do.

**Comment by paulb-nl** [comment]
MiSTer showing the wrong refresh rate happens sometimes but it doesn't affect the output refresh rate because the scaler is continuously adjusting the refresh rate with vsync_adjust=2.

I have not been able to reproduce this tearing issue.

**Comment by Videodr0me** [comment]
I tested this with the cores default settings, but it also happens with options that have been changed from default. It seems as if the vsync_adjuster ist stuck at the wrong refresh rate and does not continuosly adjust. It does adjust immediatly if you cycyle through the scandoubler settings - probably because of the resolution change it gets reinitialized and then just works.

**Comment by Videodr0me** [comment]
I tested with newest release 211127 and the newest TGFX-16 core 211126. The Problem seems to be fixed - but mister no longer displays video_info. I have still set it to 10 seconds in the ini file (see my settings in the first post), but they do not show up at all. Has something been changed in this regard or is this a minor bug? I find this info really useful  - is there a hotkey to display it or some other way to display video_info?

**Comment by sorgelig** [comment]
I've just tested - it shows video info for me.

**Comment by Videodr0me** [comment]
I retestet - and it seems inconsistent for me. Sometimes it does not show even though the display is already synced and its well below 10 seconds. But it only happens 1 out of 10 cold reboots - maybe less. If it happens, it seems to not show video_info until i load a different core.  Usually i can force the show of video_info by changing the scandoubler options from h2qx to none or from none to h2qx and then leaving the menu. But if Mister decided not to show video_info even that does not work. 

I must have been unlucky with my first tests, so its not a real problem - if it happens usually a reload of cores will fix it. I will keep an eye on it though. Thanks for checking!
