### ISSUE TITLE
Vsync always active 

### ISSUE THREAD

**Issue by synrais** [MiSTer-devel/Main_MiSTer#485]
MiSTer outputs RGBHV by default via the analog board.

When set to output Csync the Vsync pin is still active.

This is more of an incompatibility than anything, many VGA screens freak out from the extra Vsync signal and drop image or display erratically/nothing. 
I feel we need a jumper or ini setting to control the Vsync pin. It should be deactivated when Csync is active.

RGBHV works, RGB+Csync works as most monitors have a sync separator in them but RGB+Csync+Vsync wont work correctly  on most monitors.

**Comment by sorgelig** [comment]
CSync mode is NOT for VGA monitors. So you should not to use this mode if your Monotor/TV accepts separate sync signals. It's made for TV adapter and for SOG circuit.

**Comment by synrais** [comment]
Csync mode is fine for VGA monitors, not sure where you got the idea it's not. 
Nearly every single VGA monitor has a sync separator in it to handle Csync. More than what support SOG.
You need it for some monitors like a C64 1084s.
Sending Csync AND Vsync into a monitor can damage it, doubling up the voltage on the Vsync line.
RGB+Csync+Vsync is a bastard video mode that should not exist.

**Comment by paulb-nl** [comment]
The Vsync signal is forced high when outputting Csync for use with SCART to enable RGB. Sync signals are active low so signals that are high shouldn't affect anything.

A VGA monitor that gets damaged by sending an always high Vsync signal would be very dumb when that signal is supposed to be high most of the time.

If you are so worried then don't use Csync on a VGA monitor.

**Comment by synrais** [comment]
It cant be left floating or isolated because of an internal resistor keeping it high by default?
I've had 3 PC CRT so far that drop image rapidly without warning if this high Vsync signal is present.  
Mostly for arcade cores and the menu, for some reason the console cores run fine. I'm not sure why.
These monitors wont show OSD and the standby lights will flicker randomly.

**Comment by prrole** [comment]
I don't see any issues with vsync always being active.  If you configure and intend to use csync, you should ignore whatever is happening on the vsync pin (as you would not feed it to your monitor).
