### ISSUE TITLE
Cores ignoring keybinds

### ISSUE THREAD

**Issue by Mortvert** [MiSTer-devel/Main_MiSTer#489]
Hello,
After last update cores have began to ignore directional input (up/down/left/right) set directly in the core.
The only way to play things for now is to set the keybinds in the menu core via the 'setup gamepad' option - that seems to work fine.

Any time you try to bind controls per-core basis - this issue starts to happen. If you have configured controls in the menu core and delete the core bindings .cfg - things start to work correctly again.

To reproduce: launch any core (I tried it on NES, C64, ATARI cores) and go through the keybind setting process. That's it. Directional buttons now show no input.

**Comment by sorgelig** [comment]
Do i have to bind directional keys differently to reproduce the issue? Or right-right, left-left, etc will produce issue as well?

**Comment by Mortvert** [comment]
> 
Any key to the directionals.
I tried binding WSAD and numpad keys to no avail.
Have not tested with gamepad as it is out of commision currently.

**Comment by sorgelig** [comment]
Ah, it's on keyboard.

**Comment by sorgelig** [comment]
fixed in new release

**Comment by Mortvert** [comment]
Thank you!
