### ISSUE TITLE
PSX Analog

### ISSUE THREAD

**Issue by blisstik** [MiSTer-devel/Main_MiSTer#491]
Hello,

I tested the latest build by Robert from Discord for the PSX core. It does have the Analog option.

I am using the latest unstable main 9c3510d.

When mapping my 8bitdo SN30 Pro, it does not ask to map the analog sticks. I am not sure if its supposed to or not.

I tried Crash Bandicoot Warped, the Analog sticks worked for LEFT and RIGHT only. The up and down does not work.

**Comment by sorgelig** [comment]
PSX core is in early stage. All issues you have specifically with this core must be posted here: https://github.com/RobertPeip/PlayStation_MiSTer

**Comment by blisstik** [comment]
No problem. Actually there is no issue. Had to re-map in main, not within the core.
