### ISSUE TITLE
Issue with Mega Drive 6 Button Controller with SNAC

### ISSUE THREAD

**Issue by neogeo81** [MiSTer-devel/Main_MiSTer#495]
I have an issue using SNAC in the Mega Drive and Mega CD cores.

All 6 button compatible Games work fine but none of the 3 button work and most of the time just keep pressing right on the dpad.

I tried swapping the controllers and turning on and off the 6 button option in the Input options. Nothing helps.

One more strange fact is that when I switch in the Input menu to 3 button while in the 240p test suite it works and shows the the controller as a 3 button one while still registering the button and dpad presses perfectly. This does not work in the 3 button games itself though. Why?

It seems that it comes down to the 3 Button games themselve somehow

**Comment by marceloMedeiros** [comment]
You have to hold mode button while starting/restarting the core to activate 3 button mode on a 6 button controller on certain (6 button controller incompatible) games, just like on real hardware.

**Comment by neogeo81** [comment]
> You have to hold mode button while starting/restarting the core to activate 3 button mode on a 6 button controller on certain (6 button controller incompatible) games, just like on real hardware.

ok, but what about the 6 button setting in the input settings in the OSD? Can't i just turn it off?

**Comment by sorgelig** [comment]
Controllers connected to SNAC are handled by core. Main has nothing to do with this controller.
So issue is originally in wrong repository.

6/3 button settings in OSD is related to normal controllers handled by Main, so the part of core converting plain buttons to Genesis gamepad protocol will be aware of the mode. SNAC controllers are unaffected by this setting.

**Comment by neogeo81** [comment]
> Controllers connected to SNAC are handled by core. Main has nothing to do with this controller. So issue is originally in wrong repository.
> 
> 6/3 button settings in OSD is related to normal controllers handled by Main, so the part of core converting plain buttons to Genesis gamepad protocol will be aware of the mode. SNAC controllers are unaffected by this setting.

Thanks for the Info. Although the setting "swap Joysticks" affects also the SNAC connected controller.

**Comment by sorgelig** [comment]
6/3 buttons mode is handled inside the controller. Core (as well as real console) cannot affect this behavior.

**Comment by neogeo81** [comment]
> 6/3 buttons mode is handled inside the controller. Core (as well as real console) cannot affect this behavior.

i think i found a hint what i am doing wrong. I thought that i need to download the alternative DB9 cores and switched to them in the update_all script. I will switch it back today at home and hope that this solves the issue.

**Comment by neogeo81** [comment]
> 6/3 buttons mode is handled inside the controller. Core (as well as real console) cannot affect this behavior.

So the option to switch to 6 button in the INPUT OSD menu is only for USB or BT Controllers?

**Comment by neogeo81** [comment]
> Controllers connected to SNAC are handled by core. Main has nothing to do with this controller. So issue is originally in wrong repository.
> 
> 6/3 button settings in OSD is related to normal controllers handled by Main, so the part of core converting plain buttons to Genesis gamepad protocol will be aware of the mode. SNAC controllers are unaffected by this setting.

So I checked now and see that I ha e the standard core after all. I will order a Sega SNAC adapter from Mister UK and test it as soon as I have it. I hope it is the issue or else I am am helpless.
It is still hela strange that when I use a Mega Drive Bluetooth Receiver with a Retro-Bit MD Bluetooth Controller on the SNAC Adapter every game works perfect. Don't even need to use the Mode button for the 3 Button Games.

**Comment by neogeo81** [comment]
Solved.
At the end it was the core settings. After deleting everything and re-download it it runs as it should now. Thank you all for helping.
