### ISSUE TITLE
Feature Request: MT32-PI Menu - Enable the soundfonts index > 7

### ISSUE THREAD

**Issue by Negsol** [MiSTer-devel/Main_MiSTer#498]
Selecting Fluidsynth the soundfonts selection is limited to the first 8 (index 0-7) files (in alphabetical order) found in the soundfonts folder of the MT32-PI. More soundfonts (.sf2 files) are actually found and can be accessed using external buttons on the MT32-PI or SysEx tools. (also see [https://github.com/dwhinham/mt32-pi/discussions/222]. 
Apparently this is a limitation of the MiSTer OSD framework. As I have fully integrated my MT32-PI and like using the OSD selection method I wonder if something could be done to increase the selection above 8. Maybe by using an additional value/byte so that we could at least count to 64 just using the OSD.  :)
Maybe there is also an easier why to fix it...

**Comment by sorgelig** [comment]
It's limited by both reasons: 1) save config bits 2) it's impossible to remember 64 soundfonts in mind. For MiSTer, MT32pi is a mainly a game companion. So up to 7 soundfonts (in practice 2-3) are enough. If you are musician and use it for writing music then it's advised to make MT32pi with control panel and display where you can choose soundfont by name.

**Comment by Negsol** [comment]
Fair enough - I guess MT32-PI-Control is also a good workaround should one want to manage more soundfonts.
[https://github.com/gmcn42/mt32-pi-control](url)

Thank you for your insights on this!
