### ISSUE TITLE
ARM and latency question

### ISSUE THREAD

**Issue by jan-kleks** [MiSTer-devel/Main_MiSTer#5]
It looks like [some people are worried about latency issues](http://atariage.com/forums/topic/262816-its-fun-to-play-on-the-f-p-g-a/?p=3880184). You may want to add this question to FAQ or something.

Actually, how tight is the ARM's integration with FPGA in this case?

Regards

**Comment by sorgelig** [comment]
I think it's better to provide some proof of big latency in control first. Windows, Linux, most modern consoles use OS to handle USB and the whole route of control - and it satisfies everybody.
Why in MiSTer case it should be different?
I've played on most MiSTer cores and didn't notice any latency.

**Comment by jan-kleks** [comment]
Well... I guess some users are afraid of [this situation](https://byuu.org/articles/latency/). And these issues are supposedly solved by using FPGAs, but when an ARM is there too... It looks like a kind of a hybrid, and they don't know what to expect.

**Comment by Newsdee** [comment]
Just need to measure it objectively. I'm convinced it's not an issue.

**Comment by sorgelig** [comment]
I would like to see the message "i've played the pacman and suffered input latency issue." ;)

**Comment by smokku** [comment]
Typical armchair philosopher. MiST also uses ARM for I/O , yet I haven't seen anyone complaining on latency.

**Comment by sorgelig** [comment]
Closed for now.
