### ISSUE TITLE
Scanlines

### ISSUE THREAD

**Issue by snakeX79** [MiSTer-devel/Main_MiSTer#504]
Horizontal scalines doesn't work after update.

**Comment by sorgelig** [comment]
if you mean scanlines produced by video filter then you just need to apply separate filters for vertical and horizontal.

**Comment by snakeX79** [comment]
> if you mean scanlines produced by video filter then you just need to apply separate filters for vertical and horizontal.

Hello, I tried everything but without success. I can't to set nothing for clean horizontal lines. (I tried in minimig core).I see vertical ghosts together with small horizontal lines. Before update it worked well.

**Comment by sorgelig** [comment]
in video processing menu set:
horz filter: interpolation(medium)
vert filter: scanlines - Darker

this will give you one version of scanlines.

**Comment by snakeX79** [comment]
> in video processing menu set:
> 
> horz filter: interpolation(medium)
> 
> vert filter: scanlines - Darker
> 
> 
> 
> this will give you one version of scanlines.

Yes !

It works now for me !

Thanks ;-)

Half of my problem was in my Panasonic TV. I switched picture to THX and now it look beautiful :-)
