### ISSUE TITLE
Saves no longer loading/writing from/to network storage cifs mount

### ISSUE THREAD

**Issue by ghost** [MiSTer-devel/Main_MiSTer#508]
Noticing with the latest updates that cifs mounts to a different folder (fat/cifs/) instead of "replacing" the root of /fat, while roms can be loaded, saves stored on network are not seen by cores yet because cores still look in fat/saves.  Also true for savestates

**Comment by sorgelig** [comment]
it has nothing to do with Main. It saves/loads from correct /media/fat location.
You may edit script mounting cifs if you like.
