### ISSUE TITLE
Add Suspend/Hibernate support

### ISSUE THREAD

**Issue by TheRealYasri** [MiSTer-devel/Main_MiSTer#51]
Can you add menu options for hibernate to disk or suspend to ram. This would be great sense the de10-nano does not come with a on/off switch by default. It would let you "turn off" and resume mister from your keyboard/mouse/joypad. If you add this it might also be good to add a ini option to set a idle timer for like 30 minutes.

/cheers

**Comment by sorgelig** [comment]
This is complete nonsense.

**Comment by TheRealYasri** [comment]
I am confused why you consider this nonsense? Linux supports this and it seems to be in the build files you got on here for the Linux kernel. Just asking for the options to use them to be added to the OSD next to the reset system one. Would be handy to let the system go into a low power mode and be woken up next time you use the keyboard or joystick.
https://wiki.debian.org/Hibernation
https://en.wikipedia.org/wiki/Hibernation_(computing)

**Comment by alfishe** [comment]
Cyclone V doesn't support any of power-saving modes. Please address your questions to Intel

**Comment by sorgelig** [comment]
And there is nothing to hibernate on MiSTer. 
Trust me, I know more than you may think. So your Wikipedia is not suitable here.

**Comment by smokku** [comment]
Next, they'll ask their washing machine manufacturer to add hibernate to disk options, just because there is Linux inside. :-D

**Comment by TheRealYasri** [comment]
> Cyclone V doesn't support any of power-saving modes. Please address your questions to Intel
Going by the documents I have found, it seems to support turning off/resuming the fpga. I would think sense your running linux on the arm processor you could sleep that side of it, and when it wakes up you resume the fpga.
https://www.intel.com/content/dam/www/programmable/us/en/pdfs/literature/an/an734.pdf

> And there is nothing to hibernate on MiSTer.
> Trust me, I know more than you may think. So your Wikipedia is not suitable here.
Just thought their might be a language barrier sense you did not respond with anything that I could work from, so I posted links to what I was talking about. I have no clue what you know or dont know, Just posting a feature that I thing people could use. 

Another use case is if you are using this in a bartop, when the mister goes into a sleep mode that turns off hdmi, and the screen sees no display signal anymore, it could auto turn off the display or switch to another input, if it supports it. Then when it wakes up and hdmi resumes it could do the reverse.


> Next, they'll ask their washing machine manufacturer to add hibernate to disk options, just because there is Linux inside. :-D
Do not see why this would not be a desirable thing to request. It is not a washing machine, its a device programmed to play games under a tv or in a cabinet in most cases. Being able to have it go into a low power mode and turn off things like hdmi/wifi/etc till you press a button on a input device. and it wakes up. Even just disabling tons of stuff till it receives a input device interrupt to make it auto reboot and get back to a working state, would work. 

If a washing machine used linux for some reason, I would assume it would be in a low power mode like 99% of the time to use less energy and to have less wear and tear because of extra heat made by any chips it has to run.

**Comment by sorgelig** [comment]
Turn on the MiSTer when you want to play. Turn off the MiSTer when you don't wont to play. The best power saving method 8-)
