### ISSUE TITLE
Alternative buttons can no longer be assigned in Cores

### ISSUE THREAD

**Issue by Atmosfear1968** [MiSTer-devel/Main_MiSTer#511]
Every Main Mister Binary after MiSTer_20210803 no longer let you assign Alternate Buttons on any Core and says that the Joystick need to be defined in Menu Core. I have the Joystick defined in the Menu Core. I stumbled about this bug because i did made a new SD card and could no longer assign a 2nd Set buttons. I have tried XBox One Controller with microsoft Dongle and also several wired XBox Clones which all did work before. So i did check backwards from today all Mister Binary until 20210803 which did work. I even triple checked this and to be absolute sure only with the Wired XBox Controller which works since Years on the Mister. I even mad a new SD with SD Card Installer and also with Mr. Fusion. Its always the Same. MiSTer_20210825 and later no longer let me assign alternate Buttons.

**Comment by birdybro** [comment]
I was able to assign L2 on my 8BitDo SN30 Pro 2 to the A button in the SNES core as an alternate mapping, just a few days ago with the latest MiSTer binary for reference.

When you made a new SD Card, did you transfer any files over from your previous installation that were in the `/config/` folder?

**Comment by Atmosfear1968** [comment]
Did make another New SD Card with SD Installer 20211112
I only made a _Console Folder and put Inside the Gameboy Core. No other Files was added/Edited.
I did define the Joystick Buttons in Menu Core and fired up the Gameboy Core and did define Gameboy Buttons and after the Question for alternative Buttons the same Behavier again, it tells me that this joystick must defined in Menu Core first which was already made. So i can completly reproduce this each Time with Mister Binarys after MiSTer_20210803. And this Time i used a Wired F310 Logitech Gamepad and it doesnt matter if i use X or D-Input.

The exact same Procedure with SD Installer 20210711 has no Problem with alternative Button Mapping and works as excepted.

**Comment by birdybro** [comment]
What is your USB hub you are using?

**Comment by Atmosfear1968** [comment]
USB Hub v2.1 For MiSTer from Misterfpga.co.uk from Feb.2021.
i tried it several times first with update script so all cores was there and also linux was updatet. the last 2 tries was without update but since i have both SD Cards here i can also update these but i am pretty sure this wont change anything since i usualy update everytime when i made a new SD first.

**Comment by Atmosfear1968** [comment]
Now i did run the Update Script from the SD made from SD Installer 20211112 and no suprise, Alternative Buttons can not made. So no change on this one - with or without update script, Alternative Buttons can not created.

And I did run the Update script on the other SD too which was made with the SD Installer 20210711 and, i also except this, cannot longer make alternative Buttons because like before because the Main Mister File was updated. Replacing on this SD now the Main Mister with MiSTer_20210803 or earlierm, allows again Alternative Buttos mapped.

**Comment by birdybro** [comment]
Yeah, if you already ran the update and it updated both linux and the MiSTer binary, then that like rules out that being a root cause.

If you are a bit technically inclined can you connect a USB to MicroUSB cable to the console port on the front of the de10-nano (on the side the network jack is on). https://github.com/MiSTer-devel/Main_MiSTer/wiki/Console-connection - then you can see what the device ID of the joystick is, and get a log of what it says when you press the buttons that aren't working, and paste them here.

**Comment by Atmosfear1968** [comment]
I did try to connect via putty but with no success. Dont even know if this Mini USB cable is Power only or if USB3 Ports on the PC a re a Problem.
Only get a Cursor without text in the Terminal window and cant type anything there.

**Comment by Atmosfear1968** [comment]
Finaly found the nasty bug. 
Every Main Mister Binary after MiSTer_20210803 no longer let you assign Alternate Buttons on any Core IF
you Press the RETURN Key on keyboard while YES is highlighted when asked to setup alternative buttons. In this case The Main Menu tells you that the Joystick needs to be defined first in Main Menu what is wrong because it was already defined.

If you press the joystick (OK) Button while YES is Highligted then you can define the alternative Buttons without Problems.

**Comment by sorgelig** [comment]
Thanks for detailed info! I wouldn't never test using "Enter" on keyboard while defining buttons by joystick as it's easy to use joystick for navigation :)
will check it out.

**Comment by Atmosfear1968** [comment]
in the past i did press the wrong button to while asked for alternative Buttons a few times and so i "learned" that it was safer to use the Keyboard and the Return key for clumsy me ;)

**Comment by Atmosfear1968** [comment]
Fixed
