### ISSUE TITLE
Request for "~" to be included among CHAR_IS_SPECIAL

### ISSUE THREAD

**Issue by tonurics** [MiSTer-devel/Main_MiSTer#514]
https://github.com/MiSTer-devel/Main_MiSTer/blob/e504a972f1894ad27b5c07047ad65157352bd133/cfg.cpp#L107

The [ini_getline](https://github.com/MiSTer-devel/Main_MiSTer/blob/e504a972f1894ad27b5c07047ad65157352bd133/cfg.cpp#L131) function currently stops parsing lines when they contain the `~` character, this is due to a check on [CHAR_IS_VALID](https://github.com/MiSTer-devel/Main_MiSTer/blob/e504a972f1894ad27b5c07047ad65157352bd133/cfg.cpp#L113) which made up of CHAR_IS_ALPHANUM and CHAR_IS_SPECIAL.

This breaks settings within the mister.ini, mister_alt_1.ini, etc. that allow users to specify paths, i.e. `shmask_default='Sony PVM (Generic) (~1980).txt'` since `~` is a valid vFAT character. It's exclusion from CHAR_IS_SPECIAL may have been an oversight.

I'm aware `sh` will treat `~` as a shortcut to home if it appears as the first character of a path. Which I don't see as an issue: as we already allow path traversal "../../../" etc. I asked on Discord if anyone else could think of reasons why it was left out. No valid concerns were thought of. [wickerwaka suggested that it might have been excluded to prevent `~*$` in scripts. But `*` isn't a valid vFAT character or among CHAR_IS_SPECIAL.]

**Comment by tonurics** [comment]
I've made this as a Request instead of a fix to: give others a chance to think of reasons why `~` should be excluded and comment.

**Comment by sorgelig** [comment]
added
