### ISSUE TITLE
Issues with select cores on latest MiSTer version

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [MiSTer-devel/Main_MiSTer#515]
So I hadn't updated my mister in around a year. I decided that I should update to the latest versions / cores this week and tried the `update_all.sh` script. This resulted in a black screen on reboot, so I figured that a fresh install would be the right way to go (in an attempt to start fresh.)

So I now have a fresh installation of my MiSTer going with the latest cores and while SNES and Gameboy seem to be working perfectly (even some of the more difficult games, such as Mario RPG and Megaman X2 and more.) I'm having inexplicable issues with basically every other core (Genesis, NES, NeoGeo, Gameboy Advanced, probably more).

I would describe the issue as an instant lockup after the core boots a game. Often it will hold a color (like blue, white, etc.) accompanied with noise. In the case of the gameboy advanced, the GBA logo will play out as expected and lock up at the end of the sequence. With the NES, it will simply display a gray screen.

I've tried the following:
- 1) Full fresh reinstall
- 2) Deleting any bios and redownloading them using the update_all script.
- 3) Manually downloading an older version of a core (say, genesis) and trying to run that version.
- 4) Multiple roms available to me, multiple systems.
- 5) Enforcing a specific resolution in the Mister.ini setting
- 6) Changing vsync options to a few of the different options (none of them resulted in any change)
- 7) Even attempted to change some of the HDMI color settings, avoiding the one designed for VGA (since I'm on a basic, standard desktop monitor.)
- 8) Running a memory check, even reseating it despite having no failures reported.

So I'm basically out of ideas short of manually downloading an older version of the Mister system and downloading my cores again without the use of one of the scripts. I've tried a few fresh installs, some where I use the included `update` script and some with various community updaters -- none worked.

I installed using both the old installation method and also the new Mr-Fusion method -- neither presented different results.

Does anyone have any idea what might be causing this issue?

**Comment by paulb-nl** [comment]
Try another SD card and try to run the Genesis and GBA core without the SDRAM inserted.

**Comment by Eoin-ONeill-Yokai** [comment]
> Try another SD card and try to run the Genesis and GBA core without the SDRAM inserted.

I've tried removing the SDRam card and it still doesn't work. With regards to SD-Cards, I don't have one on me right now, but I can try that in the near future. With that being said, SNES games seem to all work as expected, so I'm not sure if a new SD card will change things (though I am planning an upgrade.)

Out of curiosity, I am using a relatively small SD card currently (8gb) and is there any chance that the size of the storage is causing some incompatibility with some cores?

**Comment by paulb-nl** [comment]
8GB should be fine. It doesn't make sense that it locks up after booting a game unless it can't read the ROM from the SD card properly.  

Try to reinstall and just copy 1 or 2 games from each console to the card. Verify that they are working outside of MiSTer.

**Comment by thehughhefner** [comment]
> > Try another SD card and try to run the Genesis and GBA core without the SDRAM inserted.
> 
> I've tried removing the SDRam card and it still doesn't work. With regards to SD-Cards, I don't have one on me right now, but I can try that in the near future. With that being said, SNES games seem to all work as expected, so I'm not sure if a new SD card will change things (though I am planning an upgrade.)
> 
> Out of curiosity, I am using a relatively small SD card currently (8gb) and is there any chance that the size of the storage is causing some incompatibility with some cores?

Any updates regarding this? Else it can be closed

**Comment by Eoin-ONeill-Yokai** [comment]
> Any updates regarding this? Else it can be closed

Yes this can be closed. After a few weeks I redid the SD card again and it seemed to be working as expected. I'm not sure what caused this though...
