### ISSUE TITLE
Saving presets

### ISSUE THREAD

**Issue by thehughhefner** [MiSTer-devel/Main_MiSTer#517]
Hi,
Thank you for the latest release and I'm really liking the preset function in the Video Processing menu.

I would love to see a feature where you can save presets as well in the menu. 

Kind regards

**Comment by sorgelig** [comment]
There is no such plans as OSD doesn't have text input for names and other things. 
Make it by hands. 
Retro style :)

**Comment by thehughhefner** [comment]
Closing this
