### ISSUE TITLE
Universal SD card image

### ISSUE THREAD

**Issue by michaelshmitty** [MiSTer-devel/Main_MiSTer#52]
If I succeeded in making a universal SD card image that people could write to their SD cards with any tool (dd, Etcher, Apple Pi Baker, Win32 Disk imager, ...) on any operating system, would you consider accepting something like that into the project?

The image would be small enough to contain the basic installation and reduce the download size. A script in the MiSTer interface would then resize the MiSTer_Data partition to the maximum free available space on the SD card. Just like Raspbian and other projects for the Raspberry Pi do.

According to my research the only caveat is that the MiSTer_Data partition has to be the last in the list so that it can be truncated to save space in the image. This may mean changing the partition scheme around which you may not want to happen.
Let me know your thoughts. If you don't like it, I won't waste time on it.

PS: I made a [macOS SD installer script](https://github.com/michaelshmitty/SD-Installer-macos_MiSTer) so that at least macOS users can create an SD card without having to boot into a Windows 10 VM.

**Comment by alfishe** [comment]
Main idea for current SD card deployment scheme - is to utilize full SD card without any resize-repartition operations/tools. None of image-based tools are capable to work with flexible size images / resize automatically.

**Comment by michaelshmitty** [comment]
> None of image-based tools are capable to work with flexible size images / resize automatically.

That's right. The resizing would have to be done by a script on the MiSTer board once it's booted.

> Main idea for current SD card deployment scheme - is to utilize full SD card without any resize-repartition operations/tools.

I respect that. Is there a particular reason why this is the currently the main idea?

**Comment by sorgelig** [comment]
Windows cannot see more than one partition on SD card, so Data partition must be the first partition.
If you can make the script which will move the boot partition to the end and then expand the data partition (which is by the way exFAT, not Linux format like on RPi, then it can be a good alternative.

**Comment by michaelshmitty** [comment]
No luck.
I created a 1 GB SD card image with the base MiSTer install on it (HPS OS, MiSTer binary and menu) which compressed to 100 MB only, which would be great for download and use in universal flashers on different operating systems.
It flashed fine to the SD card and booted the board no problem with about 650 MB free space.

Unfortunately the next step to resize the exFAT partition will not be possible. [Several sources](https://superuser.com/questions/393132/shrink-exfat-partition) indicate that resizing exFAT partitions is not possible.

Unless that information is incorrect and exFAT partitions can be resized, specifically under Linux on the MiSTer, there is no way to make this work without changing the partition type of the data partition.
I don't even think there is a better alternative to exFAT that is cross platform read writable and can be resized in Linux. NTFS? Probably not.

Anyway, leaving these findings here for future reference. It was a good effort. Thanks for the feedback!

**Comment by michaelshmitty** [comment]
For future reference:
I experimented with using FAT32 for the MiSTer_Data partition and did not immediately see any bad sad effects. FAT32 does have a limit of 2TB storage and a maximum individual filesize of 4GB, but I don't think that would be a big constraint for MiSTer in the near future.

A FAT32 data partition could presumably be resized by a script on the MiSTer using parted. But I found out the Linux OS on MiSTer comes with parted version 3.1. GNU parted supported the 'resize' command until version 3 and brought the functionality back in version 3.2.
Being able to resize a FAT32 partition on MiSTer would require an update of the bundled GNUparted tool to version 3.2.
Reference:
https://superuser.com/questions/494911/parted-has-no-resize-command-available

I will let this rest for now. Perhaps this can be of use in the future.

**Comment by sorgelig** [comment]
exFAT can be resized as any other file system. It's just Linux has very limited support for exFAT.
FAT32 is not an option because of:
1) 4GB file limit (actually 2GB due to different implementations). I use 7GB VHD for Minimig. And plan to use 16GB VHD.
2) FAT32 on big volumes (>32GB) is very ineffective as it needs to use huge cluster sizes. Currently adequate SD size for MiSTer is >64GB.

**Comment by michaelshmitty** [comment]
I read support for exFAT is limited because of licensing issues.
Ok on the no-go for FAT32. Closing this issue.
