### ISSUE TITLE
Retrofreak USB Adapter not working anymore

### ISSUE THREAD

**Issue by Donpachi76** [MiSTer-devel/Main_MiSTer#522]
I used this adapter until a week ago, it ran completely smoothly. https://www.amazon.co.jp/-/en/dp/B07657SQSD/
yesterday I ran update all and since then only the Digipad is recognized by PC Engine, NES, Mega Drive or SNES Controllers. All buttons no longer.Of course I have tried several times to reconfigure the buttons. Also I tried an older Mister file, but had no luck. Also with the old distribution it's out of function. So I think it is because of the updated Linux. Can this be fixed again?

PS: If this issue can only be solved with the actual hardware, I am willing to send it.

**Comment by sorgelig** [comment]
it's unclear which build you've used before update, so it's hard to say why it doesn't work.
You can test it in Menu core. Connect to USB console port with some terminal app then press working and non-working buttons and see if you have same feedback. Also it would be good to know VID:PID of this adapter.

**Comment by Donpachi76** [comment]
Had some free time today...so I tried the different builds.
Last working build with retrofreak Adapter is release_20210711.
Next build reelase_20210825 (and all later builds) are not working anymore with it.

**Comment by sonik-br** [comment]
Possible related to #561?

@Donpachi76 can you see whats reported using an windows program?
Please if possible download the trial version of [usblyzer](http://www.usblyzer.com/)

**Comment by Donpachi76** [comment]
@sonik-br: USBlyzer only gives me a "Unknown Device" when connecting MiSTer.

> If your file already have some info, append it to the end, line this:
v=loglevel=4 usbhid.jspoll=1 xpad.cpoll=1 usbhid.quirks=0x0413:0x502B:0x040

did not work. changed nothing.

**Comment by sonik-br** [comment]
Connect the Retrofreak controller to pc and take a print of it's report descriptor.

**Comment by birdybro** [comment]
I made a quick video to go along with the guide @sorgelig linked above awhile ago. Hopefully this helps with the console connection.

https://user-images.githubusercontent.com/16388068/157477036-700616a2-3857-468a-b17d-e9df37c34991.mp4

**Comment by Donpachi76** [comment]
> Connect the Retrofreak controller to pc and take a print of it's report descriptor.
![Zwischenablage02](https://user-images.githubusercontent.com/98900538/157638062-40d32e81-ec92-4b86-8544-789ad6ed239c.jpg)
![Zwischenablage03](https://user-images.githubusercontent.com/98900538/157638065-41e6b968-97cd-4bf0-ad3f-913c1063c627.jpg)

**Comment by Donpachi76** [comment]
> I made a quick video to go along with the guide @sorgelig linked above awhile ago. Hopefully this helps with the console connection.
> 
>  console-connection.mp4 
> The number on your COM port may vary, open device manager, expand ports (com & lpt), and take note of the ones there, then plug it into the mister, turn on the mister, and see what new COM## is added. That's the COM number you want to put into Putty.

Thanks a lot for your Video. Was very helpful, My COM Port is COM3. I did everything as described your video but Putty gives me only a black screen. Do i have to configure something  on Misters side (enable something?)
Thanks a lot for your help & time!

**Comment by sonik-br** [comment]
So it is a composite interface.

1. gamepad
x, y axis
4 buttons

2. gamepad
x, y axis
8 buttons

3. gamepad
x, y axis
8 buttons

4. gamepad
x, y axis
4 buttons

5. missing?

6. mouse
x, y axis
2 buttons

7. vendor specific

You can try again with the u_boot.txt trick and also the "no_merge" setting in the ini file.

Question: Back when it was working... Each controller maps to a different player on mister? or all controllers maps to player one?

**Comment by Donpachi76** [comment]
> So it is a composite interface.
> 
> 1. gamepad
>    x, y axis
>    4 buttons
> 2. gamepad
>    x, y axis
>    8 buttons
> 3. gamepad
>    x, y axis
>    8 buttons
> 4. gamepad
>    x, y axis
>    4 buttons
> 5. missing?
> 6. mouse
>    x, y axis
>    2 buttons
> 7. vendor specific
> 
> You can try again with the u_boot.txt trick and also the "no_merge" setting in the ini file.
> 
> Question: Back when it was working... Each controller maps to a different player on mister? or all controllers maps to player one?

5. is not missing (was my fault when screenshooting)
All Controllers mapped to player 1.

> and also the "no_merge" setting in the ini file.
what ini file? Mister.ini ? or where do I put "no_merge" ?

**Comment by sonik-br** [comment]
mister.ini
no_merge_vid=0x0413
no_merge_pid=0x502B

But this is optional. without it, mister will merge controllers with the same vid/pid as a single controller.

**Comment by Donpachi76** [comment]
> mister.ini no_merge_vid=0x0413 no_merge_pid=0x502B
> 
> But this is optional. without it, mister will merge controllers with the same vid/pid as a single controller.

@sonik-br unfortunately it did not help.

**Comment by sonik-br** [comment]
Sorry I can't help. :(

**Comment by sorgelig** [comment]
No problem. You may contact leave me message on FB or MiSTer forum, so i can give you my address.

**Comment by Donpachi76** [comment]
> No problem. You may contact leave me message on FB or MiSTer forum, so i can give you my address.

Thanks a lot! You have a message @facebook

**Comment by Donpachi76** [comment]
so, I got the changed u-boot.txt from sorgelig, with just this line

v=loglevel=4 usbhid.quirks=0x0413:0x502B:0x040

And now it works like a charm. Thanks a lot everybody!

**Comment by RudyAlbertoAcostaMarmalade** [comment]
Thank you!  This had been infuriating me for over a year!
