### ISSUE TITLE
Question: Disabling pop up messages?

### ISSUE THREAD

**Issue by HiroiSekai** [MiSTer-devel/Main_MiSTer#523]
Hiya,

Is it possible to disable the little pop up messages like "SAVED THE STATE" or the "MAP (P1)" when your controller reconnects? I stream using the MiSTer on Twitch and would prefer if those messages didn't appear when I take a break and my controller goes into sleep mode, for instance. I tried looking around for documentation on this, but I couldn't find anything (or it's there and I don't know the terminology it's set to).

Thanks!

**Comment by sorgelig** [comment]
"MAP .." message can be disabled by `controller_info=0` in MiSTer.ini.
"Saved the state" message up to specific core.

**Comment by HiroiSekai** [comment]
Thank you! Much appreciated.
