### ISSUE TITLE
Feature request: Menu entry in the "System status" screen to see the core and screen resolution

### ISSUE THREAD

**Issue by sromeroi** [MiSTer-devel/Main_MiSTer#526]
Would it be possible to have the Core Resolution and the Current Video Mode in a new entry in the "System" menu?

A new menu entry named "Video info" that provides the same information than the "video_info=X" box.

It would be nice to be able to see information about the video mode "on demand" at any moment and not just when the core starts. Also, video_info is very annoying for PSX core because several games switch between different resolutions when you're in the game or when you open the inventory (Castlevania SOTN, FF7, etc) and you get the video_mode dialog each time do move between the different game screens (I ended setting video_info=0 for [psx]).

Also, the video_info box does not appear when you move from a core to another one with the same resolution (there's no resolution change), or if the core starts directly in the UI (to be able to load a rom file)... I established for [snes] a video_mode different than the one in the mister menu, and when I open the snes core I don't get the video_info dialog because it starts in the UI (for arcade cores I always get it because it starts directly into the game).

Having it in the system menu would allow everyone to see the video values at any moment and disable it in the ini.

Thanks.

**Comment by thehughhefner** [comment]
I think this is already implemented. On the OSD you press left then you will get the video information
