### ISSUE TITLE
Feature Request : Enhanced KB Emulation adding Scancodes Set 1

### ISSUE THREAD

**Issue by naeloob** [MiSTer-devel/Main_MiSTer#527]
It will be a great enhancement to have the KB emulator answer more commands and be able to return Scancodes Set 1.

Mist Firmware supports it, it can be used as development base.

Regards

**Comment by sorgelig** [comment]
I'm not sure what you want. MiSTer uses linux input system and operates with codes linux provides.

**Comment by naeloob** [comment]
The kb Emulator provided by the Mist framework, supports PS2 Scancodes Set 1 (it has one array for set1 and another one for Set 2, i think it makes some sort of translation) and some more PS2 commands than Mister Framework.
It works more accurate to a real KB.
I'm having some problems with a core that only works with PS2 Scancodes Set 1 (the XT ones).

I can point you to Mist Firmware files to give more information.

**Comment by sorgelig** [comment]
> It works more accurate to a real KB.

statement looks weird. How keyboard can be more accurate or not? It either works or not. Each button has its own scan code. That's enough to work. Other scan codes can be made through a mapping. This is how it's done in different cores.

**Comment by naeloob** [comment]
Sorry, it was not my intention.

I mean it answer and process more PS2 commands and execute it. One of them is change the "Scancode Set" used to send the scancodes to the core.

In Mist here you have the array of Set1 : https://github.com/mist-devel/mist-firmware/blob/3409cfec476f9fa2ea48b6bbdd15ece126ad5e36/keycodes.h#L377
Here Set2 & 3 : https://github.com/mist-devel/mist-firmware/blob/3409cfec476f9fa2ea48b6bbdd15ece126ad5e36/keycodes.h#L261

In Mister here we have the array of ps2(But just Set2 & 3) : https://github.com/MiSTer-devel/Main_MiSTer/blob/ec174d41e95248b157e06a28c8cda6e55ef059bb/input.cpp#L299


You can see the commands processed by Mist Firmware in https://github.com/mist-devel/mist-firmware/blob/master/user_io.c#L927

In Mister we have https://github.com/MiSTer-devel/Main_MiSTer/blob/8c46d13d4f7df3d3eb42f58acf549437d7c93aba/user_io.cpp#L2895

We are not processing F0 (Scan Get/Set, wich allow to get or set wich "scancode set" use when sending keys) and F3 (typematic set, which allow so set the typematic rate) commands.

I hope I have explained myself better

Regards

**Comment by sorgelig** [comment]
it's fake replies to core which needs these commands to work properly. Same done in MiSTer for ao486 core.
It has nothing to do with real keyboard communication.

**Comment by sorgelig** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/blob/dfe224d6a7637a41736a5119c8a1a081d48d8d88/user_io.cpp#L2895

**Comment by naeloob** [comment]
Mist Firmware sends Set 1 Scancodes if the Host Ask with the F0 command, just like a real KB that has that feature.
If i'mp not wrong Mister firmware doesn't do that.

I will check AO486 Core to look what you're telling me.

**Comment by sorgelig** [comment]
Well, some codes can be emulated like repeat rate. Currently only one core uses this communication is ao486. I'm using this core and don't see problem. Even on real computer no one bothers to tinker with it. So it's just useless gimmick. Games don't use this feature - they just get only state of press/release.

**Comment by naeloob** [comment]
Is not only the typematic rate, is to honorate the F0 command that answers the Scancode Set used by the keyboard and let the Host change it.
The XT only knows Scancode Set 1, any core using XT bios will wait for that scancode and will not work correctly with scancode set 2.

Anyway i will look at AO486.

**Comment by spark2k06** [comment]
Scancode set 2 is the most used, but there are others. And if the BIOS of a certain core is prepared to use set 1, I don't see what would be wrong in supporting it as MiST... it's expanding the possibilities.

**Comment by sorgelig** [comment]
There is no XT core. If there will be an XT core then conversion table will be used in that core. 
Still no point to do it just for fun.

**Comment by naeloob** [comment]
Well... there's no core, but there could be... at least one...

We are trying to port this one https://github.com/spark2k06/next186lite_graphics_gremlin and althought the bios can be configured to user ScanCodes Set 2, and command.com works right, almost every software uses it's own keyboard rutines and it seems to identify the computer as XT one, and processes the ScanCodes as Set 1, so ie, if you load keyb.com and you press D you will see H, in fact two HH, as release code are not the same on Set 1 and 2.
Not to mention that very few games or advanced programs use the bios routine.

Regards

**Comment by sorgelig** [comment]
There are many computer cores already. Each computer uses its own scan codes or simple matrix array. That's why you can see a translation table in each computer core. So the same translation can be done in XT core, so it will get Set 2 and then convert it to Set 1 directly in FPGA.

**Comment by sorgelig** [comment]
Not sure if it's a good idea to make another x86 core which will be more limited. ao486 has HDD support where you can place many games inside and load them in convenient way.

**Comment by sorgelig** [comment]
Another point: i don't think XT will need both sets. Main is aware which core is running and can provide specific scancodes without special switches.

**Comment by spark2k06** [comment]
A PCXT core represents the first era of PCs. With the implementation of an authentic CGA with its original registers, its timings, etc... thanks to the Graphics Gremlin project on which it is based, all together it allows to play a great catalog of CGA exclusive and very old games in general, all currently incompatible with ao486. There are several threads in the MiSTer forum with users claiming something like this, like the one related to this core that I have made for the ZXUno, among others:

https://misterfpga.org/viewtopic.php?t=3682

On the other hand, the core does not need both sets, only 1. The BIOS is prepared to be able to use both, but really at a global level it only works well with set 1.

**Comment by spark2k06** [comment]
Moreover, in the future I would like to replace Next186 with MCL86 for this core, in order to get an exact cycle for 8088. But for now, the current state of the core is very valid for all those old games that I comment on.

**Comment by birdybro** [comment]
A PC-XT core would apparently help people play the games from that era that run too fast on ao486 as well. I just asked a few people that use computer cores in the community so this makes sense.

**Comment by sorgelig** [comment]
I will look at that core. Should be no problem to port it.

**Comment by spark2k06** [comment]
That's great. Only with MCL86 instead of Next186 would an exact cycle with an original PCXT 8088 be possible, but understanding that it powers an extra effort. 

As for the exact loop reason, maybe some older game would appreciate it without the need to apply throttle down, and especially the MPH8088 demo would run fine... well, the Graphics Gremlin might also require some tweaking to achieve this goal. , but it is already quite well developed today. 

Whatever you decide, good luck with it. Idea if you rely on Next186: Take the sdram and cache module from the existing project for Mist developed by gyurco, it will pave the way for you.

**Comment by spark2k06** [comment]
If you decide on MCL86 as CPU core, perhaps the perfect BIOS could be the one from Sergey Kiselev's Micro8088 project, with adjustments in the disk access routines.

**Comment by jsmolina** [comment]
The ones that I remember do not work properly on faster pcs: Test Drive, Livingstone Supongo, Robocop, ...

**Comment by sorgelig** [comment]
quick look into Next186 discovered it uses direct SD card access.. It means it will need a virtual image like ZX Next and some other cores. It means you won't be able to mount disks directly from MiSTer sd card. So you have to create a VHD image first where you can place disk images..
Not convenient use of such cores..

**Comment by mills32** [comment]
This is great. The problem with x86 is we don't have a core like minimig in which you can select several cpus and graphic cards. Maybe it is too difficult, but at least we should have an 8086-88 clone for the low end (16 bit) spectrum of the x86, including some CGA features not pressent in VGA/SVGA chipsets, like CGA composite mode. Also some SVGA cards like the one on ao486, won't dsplay correctly a lot of CGA programs. Just try a game called prohibit, it does not select the correct palette, and the cga hardware scroll (very choppy, but CGA has hardware scroll) does not work at all.

**Comment by flynnsbit** [comment]
On the bios swap discussion.  You can swap the ao486 video bios to a hand full of ones from the PCem library, unfortunately they are all VGA adapters.  Swapping them does fix the Mode 12h odd resolutions like in The Incredible Machines.  Swapping the default video bios with the Trident bios will fix games that use this mode.  There are only about 10 or so video bios that will boot with ao486, all VGA.  So no CGA.  The main bios is too far off from bochs to use different ones like you can in bochs/PCem.

Porting Next186 would be super cool and could open up some new pc core fun and development.

**Comment by spark2k06** [comment]
I have made a pull request to support the change of scancodes and specifically to SET 1. I have discarded the implementation of typematic considering that the cost and benefit in this case is not worth it:

https://github.com/MiSTer-devel/Main_MiSTer/pull/546

I also make a pull request for the ao486 core, making use of this new functionality, and removing the translation of scancodes to SET 1 from the same core:

https://github.com/MiSTer-devel/ao486_MiSTer/pull/94

**Comment by naeloob** [comment]
PR Merged, I can close this issue.

Thank You
