### ISSUE TITLE
Direct Video HDMI to VGA DIAGRAM

### ISSUE THREAD

**Issue by badass-boss** [MiSTer-devel/Main_MiSTer#540]
So using Analog Direct Video through HDMI requires a very specific direct cable adapter for connecting through VGA and another cable on top of that if you want to use SCART for instance so this will be another VGA->SCART cable on top of that. What I want to do is build a HDMI->SCART and HDMI->YPbPr (component) cables right away but here's a problem: where is the actual HDMI to VGA CABLE DIAGRAM??? I couldn't find it anywhere and this seems like a very important piece of information I couldn't find anywhere... I don't know how to connect VGA to YPbPr either. Anyone please help. Thanks in advance

**Comment by sorgelig** [comment]
HDMI to VGA isn't just a cable. It's HDMI-VGA converted based on AG6200/AG6201 chip.
More about it you may read on Wiki: https://github.com/MiSTer-devel/Main_MiSTer/wiki/Direct-Video
For discussion please go to MiSTer board: www.misterfpga.org.

Github is for bug reports and development only.
