### ISSUE TITLE
Issue with XBOX360 controller + Bluetooth Keyboard - Not detected until Mister is restarted

### ISSUE THREAD

**Issue by neosquid** [MiSTer-devel/Main_MiSTer#554]
I am using an OTG USB hub which used to have no problems until about 3-4 weeks ago.

Now, if I initially switch on Mister, the bluetooth keyboard and Wireless controller don't seem to respond. They are only detected after a reset of Mister.

**Comment by sorgelig** [comment]
it may happen with some HW configs like amount of connected USB devices, specific USB hub and so on. It's not that can be fixed easily.
