### ISSUE TITLE
FPGA Design

### ISSUE THREAD

**Issue by bparker06** [MiSTer-devel/Main_MiSTer#56]
Hi,

Can someone tell me where the HDL source is for the FPGA design for MiSTer? I was not able to find it searching through the repos on github.

Thanks

**Comment by alfishe** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/wiki "Arcade cores" on the right contains links to all HDL  Quartus projects available for MiSTer.

**Comment by bparker06** [comment]
Actually I found my answer from someone else... apparently all of the actual HDL code is duplicated (and potentially modified) across every single core, and it's in the /sys folder of those repos.
