### ISSUE TITLE
Multiple controllers on same usb device

### ISSUE THREAD

**Issue by sonik-br** [MiSTer-devel/Main_MiSTer#561]
I'm trying to output more than 2 controllers using a single arduino.
Only the first joystick works. Tested with both settings of "no merge" on the ini.

This worked previously on mister.
I can get it to work using older mister files. But does not work on the current version.

Works with these files from 20210711:
uboot.img
zimage_dtb
Mister Main

Something changed regarding this?

**Comment by sorgelig** [comment]
I suggest to check how 2 joysticks are working for example in this project:
https://github.com/MiSTer-devel/Retro-Controllers-USB-MiSTer/tree/master/SNESControllersUSB

Try to build this and check if you really have 2 controllers from a single adapter.

**Comment by sonik-br** [comment]
Yes, this one does work on current version. But it's limited to only output two controllers.
The arduino have some output endpoints for Serial, Keyboard, Mouse. This overrides the Keyboard and Mouse to output two controllers.

I use a single endpoint for multiple controllers. A big, combined hid descriptor. And it used to work at least until version 20210711.

The DaemonBite one:
![1](https://user-images.githubusercontent.com/16923826/156166482-a5f4d1d9-013c-4abd-a430-9e5a53cfe25e.png)


The one I'm using. Here outputting just 2 controllers on a single descriptor, but I can output up to seven:
![2](https://user-images.githubusercontent.com/16923826/156166619-69965805-fece-4265-82a1-e2abf177658f.png)
![3](https://user-images.githubusercontent.com/16923826/156166644-78922bff-dc7d-420f-a9a8-f8fd53077451.png)

**Comment by sorgelig** [comment]
try `no_merge_*` in MiSTer.ini

**Comment by sonik-br** [comment]
On older version no_merge works as expected.
When merged, multiple controllers works as a single one.
When not merged, all works independently.

On latest version no_merge makes no difference at all.
Only the first controller is detected with or without no_merge

**Comment by sorgelig** [comment]
i don't have your device, so i can't test. Source code of both kernel and Main are available, so you are welcome to provide a fix.

**Comment by sonik-br** [comment]
I have no idea where to look for it. I don't even know why support for it is broken.

I use this arduino library
https://github.com/MHeironimus/ArduinoJoystickLibrary

I can code it for you if you have an arduino and can test.

**Comment by paulb-nl** [comment]
If you can change the VID/PID of your usb device then you can set it to something that already uses that quirk in the kernel:
https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/blob/5bdbf2f7e65510acf8c4e2bf484c0be3b72c06d2/drivers/hid/hid-quirks.c#L70
https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/blob/8179ac736bda58801cd0fdf177f3f905e2c53635/drivers/hid/hid-ids.h#L1352

**Comment by sonik-br** [comment]
@paulb-nl I like the idea of keeping the arduino vid/pid as its easy to have multiple "serial id" on the same arduino and mister have great support for this.
Also it's easier for the end user to just edit a text file (u-boot.txt) on mister than to edit the vid/pid of the arduino board.

Got it working via u-boot.txt. Closing it for now but please respond if you have any other idea :)
