### ISSUE TITLE
Feature request: support multiple mounts in MGL files

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Main_MiSTer#562]
Think about PC games that require both some hard-drive installed files AND a mounted CD-ROM image, for example.  Or an Amiga game that uses two floppy disks.  For such computer games, an MGL needs to support mounting of multiple files to multiple devices simultaneously.  But right now, even if I specify multiple `<file>` nodes in an MGL file used for launching the ao486 core, only the last file listed actually gets mounted.

**Comment by sorgelig** [comment]
i plan to implement it.

**Comment by sorgelig** [comment]
implemented
