### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by kwodkore** [MiSTer-devel/Main_MiSTer#566]
Hi all, brand new to the MiSTer scene, arrived a few days ago and went to set it up using a Dell 1704fpt screen using a DVI to HDMi cable...no joy just blank screen, tried VGA to VGA cable next...blank screen, I'm assuming I need to change some ini files on the SD card for the image to appear? any help would be much appreciated, looks like a great community...

**Comment by sorgelig** [comment]
Please go to forum for discussions: https://misterfpga.org
