### ISSUE TITLE
All joysticks use joystick_0_rumble from HPS

### ISSUE THREAD

**Issue by zakk4223** [MiSTer-devel/Main_MiSTer#572]
When fetching the rumble values in  input.cpp, the spi_uio_cmd value is always sending UIO_GET_RUMBLE because the cmd parameter is only a uint8_t, so the 8 bit left shift of the player number does nothing.

It can be fixed by using spi_w() there instead. I opened this as an issue in case the real solution is to modify all the data types for the spi_uio_cmd* functions to be as wide as they are in hps_io

**Comment by sorgelig** [comment]
should be fixed now
