### ISSUE TITLE
Logitech Driving Wheels not working

### ISSUE THREAD

**Issue by thorr2** [MiSTer-devel/Main_MiSTer#575]
The PSX core, ao486 and possibly others have a ton of great driving games.  Many of us have Logitech driving wheels such as the G25 and G27 and want to use them with the MiSTer.  Currently, they show up with lsusb but do not respond when trying to map them in the MiSTer.  Please add support for these driving wheels.

There was this project to get it to work with Linux: https://github.com/TripleSpeeder/LTWheelConf

but as mentioned on the page:
"we managed to get most / all wheels supported directly by the kernel, so there is no need for this separate tool anymore"...

That said, I tried plugging in mine and I couldn't map any inputs, so I guess it may not be in the kernel used by MiSTer

/root# lsusb
Bus 001 Device 006: ID 046d:c294 Logitech, Inc. Driving Force

Thanks!

**Comment by GThrone** [comment]
You're right. This is a major issue. It's a standardised controller, used en-masse by the community. It's bizarre that it's not recognised...

**Comment by birdybro** [comment]
Hasn't added support for something yet != unintelligent omission. Be more respectful with your comments please. 

You can request device support at the Linux_MiSTer issues page --> https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/issues

https://mister-devel.github.io/MkDocs_MiSTer/advanced/console/#u-boot-command-prompt - use a console connection and provide the debug output when you use the inputs on your steering wheel, so you can help the devs add support for it.

The reason why there isn't as wide a device support as there are in regular desktop linux distros is because the project isn't using laggy SDL for input support. Most of the input handling is custom code, to ensure that there is very low latency.

**Comment by coolbho3k** [comment]
I'm currently trying to add support for racing wheels generically. However, I have a Fanatec wheel, and no Logitech wheel, so I may need that debug information from folks who do have other brand wheels. Can you do what @birdybro mentioned on your device?

`CONFIG_HID_LOGITECH=y` is set in the kernel, I don't understand why the MiSTer won't respond at all to the Logitech wheel.

**Comment by thorr2** [comment]
I hooked up the console port and hit escape and got the => prompt.  I am not sure what to do next.  Also, when the wheel is hooked up and the MiSTer fully/normally boots, the wheel calibrates itself like it normally does.  When using the console port and hitting escape to stop it before booting, the wheel does not calibrate itself at this point.  Pushing the buttons does nothing on the screen either.

Please let me know what to type at the => prompt to get the debug output and I will provide the output.  

Also, I have not compiled anything on the MiSTer before, but I am familiar with compiling in Linux.  It does not appear that gcc or any of the other compiling applications are there.  I wouldn't mind trying the berarma/new-lg4ff driver, but I am not sure how to proceed on the MiSTer.  I just need a list of commands to type to get everything installed, and I am happy to test.  

Thanks a lot for your helpcoolbho3k, and birdybro also!

**Comment by coolbho3k** [comment]
@thorr2 I actually have not debugged with console, however here is an alternative method that I've used:

1. ssh into MiSTer - `ssh root@<your_misters_ip>` (default password is `1` unless you changed it)
2. Run `top` and find the current PID of the `/media/fat/MiSTer` process - it is usually somewhere in the 500-600 range for me
3. Kill the MiSTer process - `kill <pid>`
4. Run `/media/fat/MiSTer` on your terminal and MiSTer process should restart you should see all the console output

Now plug in your Logitech wheel and turn the wheel, press the pedals, and you should see a lot of debug logging in your terminal related to the axis and values of the wheel/pedals. Each event should look like this:

```
0eb7:0004:00 P0 Input event: type=EV_ABS, Axis=0 [0...65535], Offset=51148
0eb7:0004:00 P0 Input event: type=EV_ABS, Axis=0 [0...65535], Offset=51050
```

The important values are the `Axis` for each input, the range (`0...65535`) and which direction it's going as you turn left/right and press the pedal down. These values would be great:

For wheel
Axis:
Range:
Center offset:
Full left offset:
Full right offset:

For each of throttle/brake/clutch
Axis:
Range:
Default offset:
Fully pressed offset:

**Comment by sorgelig** [comment]
i have Driving Force Pro, Driving Force GT and G29 wheels. i will see what can i do.
ao486 has input only for 2 analog axis and 4 buttons, so i don't think current implementation of joystick on ao486 will work with wheels.
The only core which may take advantage from wheel is PSX and couple games.
Yeah, so bizarre omission!

**Comment by coolbho3k** [comment]
Great that you have hardware! Some findings from my tweaking.

My solution has been to map the steering axis to left analog stick
left/right (already default on my wheel so no work needed).

Throttle axis maps to right analog stick up

Brake axis maps to right analog stick down

And this works with PSX core. But doesn’t work that well on the current UI
and some hard coded values. Here is my branch with ideas. Note: not ready
for review yet and needs lots of cleanup but basically working so far
https://github.com/coolbho3k/Main_MiSTer

You need to send an FF_SPRING force feedback signal to the wheel to enable
the centering force spring or else it won’t be very playable. I got this to
work. Once this is in place, plus some in-game calibration to remove
in-game deadzones, Gran Turismo feels great.

Most wheels don’t use FF_RUMBLE, but FF_PERIODIC so the default rumble
implementation doesn’t work. I haven’t gotten this to work yet with my
wheel as I can’t figure out how to use FF_PERIODIC properly yet without the
wheel reacting violently and turning all the way to the left…

**Comment by sorgelig** [comment]
I don't think we need to even touch FF for wheel as there is basically no support in games.
initialization with FF_SPRING to enable springy feeling is the only thing possible to do for wheels.

**Comment by sorgelig** [comment]
probably break/accel can be mapped to horz/vert axis of right stick so they can wok independently. Then it will be up to core how to treat it. 
Problem is that not many games where wheel can be used. It's possible to use wheel as a dummy analog left/right steering which is doubtful pleasure where you have to unpack a bulky controller to simulate analog stick of gamepad.

**Comment by thorr2** [comment]
Thank you everyone.  It is definitely worth the effort in my opinion and
probably many others, even if the game only supports it in a basic way.
The alternative is using a thumbstick or a joystick which is totally
terrible for driving games by comparison.  I used to play PC games with a
Thrustmaster steering wheel and it was left/right analog, and the two
pedals were up/down analog, and it had a springy mechanical return to
center.  This was pure joy back then compared to a joystick. The PSX seems
to support more options by changing the controller type in the core.  This
should support separate axis controls for the pedals.

Tonight (PST) I can provide the testing output if it will help.  Thanks
everyone!

**Comment by coolbho3k** [comment]
For pedals, I had a few ideas.

1. One alternative is to combine brake and throttle input by averaging them. It's in my branch above. Since the NeGcon on PSX core maps the analog buttons to right stick up and down, it works out of the box. It's not as realistic, as of course in a real car you can press both at the same time, but I'm not sure that's really relevant for any games that MiSTer will ever support.  

2. Mapping the other pedal to the horizontal axis is even better, as it would allow independent control and double resolution on the pedals, but it would require some minor change to the PSX core to work - probably a config option.

3. Yet another idea, which I actually prefer, is to add a mappable analog L2 and R2 input to the MiSTer virtual controller, then make that mappable to the analog NeGcon buttons in PSX core. This also allows you to map a regular controller with analog L2 and R2 and use these as throttle/brake like how modern racing games work. Today, I think you have to use right stick. 

I'm not sure which other cores would be relevant for wheels though and whether analog input is even possible for them - for example can you even get multiple analog axes into ao486?

**Comment by sorgelig** [comment]
currently i plan to use such mapping:
steering - Left Stick X
acceleration - Left Stick Y
break - Right Stick Y
(optional) clutch - Right Stick X

Pedals will be translated to positive-only values (0-127) giving half range but for pedals it's more than enough resolution. It also will be compatible with dual-stick gamepads where sticks are centered. I also will think about giving option for L/R analog triggers, but need to keep in mind that many gamepads have only digital triggers, so sticks are still preferred for wheel emulation.

Since accel/break will be sent as separate analogs, it will be up to core to average it or not.

**Comment by sorgelig** [comment]
Logitech Wheels have nice feature - multimode. So newer wheel can be switched into one of older model (on HW level it seems) with VID:PID of that wheel and mappings. So using G29 i can test MiSTer with DF-EX, DFP, DFGT, G25, G27 wheels.

DF-EX uses same axis for both accel and break pedals. It does subtraction inside wheel when both pedals are pressed. So both pressed pedals give 0 on that axis.

**Comment by thorr2** [comment]
steering - Left Stick X
acceleration - Left Stick Y
break - Right Stick Y
(optional) clutch - Right Stick X

This sounds like a good overall approach.  Each pedal should have its own axis.  PSX has the most driving games currently so this should work well as long as the core is updated to support the layout.  Choosing "Driving Wheel" or something similar as a plugged in controller.  

The above would be a compromise in ao486 because you would have to use one foot driving for acceleration and braking.  The midpoint of the pedal would be where it would change from acceleration to braking.  I am already used to this in my Tesla with regenerative braking, so it would be funny playing driving games the same way I drive my Tesla, lol.    It would be cool if there was a way in the MiSTer.ini under the [ao486] header (or others) to change the behavior of how to map the acceleration and brake pedals (single or dual axis).  

As I was typing this, sorgelig, your new comment came in.  I am not sure if my MiSTer.ini idea is needed or not or if there is another way to get it to work both ways for different cores.
Thanks!

**Comment by sorgelig** [comment]
I think making less amount axes is always easy. Core may simply subtract 2 axes to make a single one like it's done in DF-EX wheel.
Actually ao486 supports dual-analog joystick, so at least 1 wheel with 4 axes and 4 buttons should be possible. I need some game names of that age supporting wheels over standard joystick connection, then i will see how to implement it.

**Comment by thorr2** [comment]
Pretty much any DOS game works like a single analog joystick.  "Stunts" for DOS is an example.  Also Need for Speed.  I know Stunts works, and haven't tested Need for Speed yet.  https://www.youtube.com/watch?v=-hKK4_gvOS0

**Comment by sorgelig** [comment]
Being fan of racing games i have several wheel (as mentioned above) to play mostly GranTourismo series and some Forza Horizon games. Main purpose of wheels for me is feedback. Here we are talking about wheels without feedback, so it's pretty much a dummy big gamepad.. It doesn't resemble me a wheel experience, that's why i'm skeptical about usefulness of the whole this hassle even having compatible wheels...

**Comment by thorr2** [comment]
It's retro gaming, and games at that time didn't support it.  We can play modern games with our wheels too, but I miss the old games and want to use my wheel like I did back in the day with my Thrustmaster.  :-)

**Comment by thorr2** [comment]
The PSX is of most interest to me personally, so if only that gets fully supported, I would still be happy.  ao486 would still work with one foot driving and might be good enough if it is too much work to implement as a special case.

**Comment by thorr2** [comment]
Why we need wheel support: https://www.youtube.com/watch?v=UIFcVhRWWX4
It would be a shame to be limited to a thumbstick. ;-)

**Comment by thorr2** [comment]
[coolbho3k](https://github.com/coolbho3k) I tried your suggestion to get the debug output.  It worked to see things, but nothing I do with the steering wheel or its buttons shows up in the output.  Typing on the keyboard shows all kinds of stuff, so I know it is otherwise working.  Let me know if you want me to try anything else.  Thanks!
lsusb shows:
Bus 001 Device 007: ID 046d:c294 Logitech, Inc. Driving Force

**Comment by coolbho3k** [comment]
I also agree it's worth it to add wheel support. This would be a great "enhanced" way to play all PSX racing games. With my test branch and the PSX , playing Gran Turismo is quite good, even with no real FFB. We'll never have proper force feedback as it's just not in any of these games originally.  However, I can see simulating controller rumble with FF_PERIODIC being pretty cool. And, wheels without true FFB like Hori and PXN with just rumble and a physical centering spring sell a lot of units for modern racing games.

Wheel is also the native control scheme of many old arcade racing games, and not all of them had real force feedback either. It would be the only way to play these games with "authentic" controls on MiSTer.

@sorgelig If you want to take this on, I will pause my efforts. In my code I added a hard coded map of VID and PID for wheels, and add a QURIK to remap the axes on the devices that are found in the map. Not sure if that's a preferred way of doing it.

@thorr2 To me it sounds like an issue with kernel drivers. To my knowledge, it really should be working. It may be best to see if @sorgelig can get Logitech wheels working with the kernel. I would try it if I had the wheel.

**Comment by coolbho3k** [comment]
Here's a video of Gran Turismo on my test branch: https://youtube.com/shorts/uTh8pJ7a_Vk?feature=share

It's really not bad at all.

**Comment by sorgelig** [comment]
@coolbho3k i will add wheel support for logitech wheels i'm able to test. Then you can add your wheels too.

**Comment by sorgelig** [comment]
@coolbho3k i've pushed my changes for wheels. I didn't look into cores yet, but you can add your wheel to the same mapping.

**Comment by coolbho3k** [comment]
@sorgelig Great, I'll take a look tonight and see if I can I can add support for the 3 Fanatec wheels I can test, then I'll test functionality the best I can, probably using some debug logging if it doesn't work with cores yet.

**Comment by sorgelig** [comment]
i've tried Gran Turismo on PSX. I can steer by left analog stick but gas/break are on buttons, they aren't analog. Is it how Pedals should be mapped? What is control scheme of racing games on PSX?

**Comment by coolbho3k** [comment]
@sorgelig I set the controller type for Player 1 to NeGcon. 

By default, accelerate will be mapped to analog button I on NeGcon and brake will be be mapped to analog button II on NeGcon.

Right now, the PSX core maps right stick up to button I and right stick down to button II. 

You can also remap controls in-game. For example I mapped upshift and downshift to the paddle shifters.

**Comment by birdybro** [comment]
The original PS1 games didn't have that kind of axis-based acceleration support. It was just on-off. They added the analog axis-based accelerate and brake on PS2 and PS3 with official Gran Turismo racing controllers. PS1 race controllers just had the brake and gas mapped to the buttons, like the Mad Catz MC2 does, I'm pretty sure.

Pressure sensitive buttons (on dual shock 2) and analog stick brake/gas mapping came with PS2/PS3 racing games I thought.

**Comment by thorr2** [comment]
@birdybro This is incorrect.  What coolbho3k said is correct.

**Comment by sorgelig** [comment]
jogcon didn't have analog buttons, only jog itself.

NegCon control scheme doesn't look good as steering is digital, so either full left or full right. Analog gamepad with digital gas/brake is better. 
It seems there is no option for analog steering and analog pedals.

**Comment by thorr2** [comment]
@sorgelig I was able to use my DualShock 3 controller's two thumbsticks and set the core to NeGcon and have both analog steering and acceleration.  I think I tried it with R4 Ridge Racer Type 4, but it should work with everything.

**Comment by sorgelig** [comment]
yeah, steering in negcon mode is indeed analog, just very sensitive. I'm trying different options using gamepad. So negcon controls looks good.

**Comment by sorgelig** [comment]
i see core combines 2 analog buttons into a single axis which definitely not a good idea. Physically 2 buttons can be pressed at the same time.
Anyway, there is a way to add wheel with 3 analog axes.

**Comment by thorr2** [comment]
Yeah, I was wondering, worried about that.  I would recommend the core be changed to use the shoulder buttons instead of the thumbstick.

**Comment by coolbho3k** [comment]
For Gran Turismo:

NeGcon mode:
The "I" and "II" buttons on NeGcon are analog, Gran Turismo supports it by default for analog throttle and brake. The closest equivalent on modern controllers is the L2/R2 triggers. And yes, the core combines them into a single axis, so pressing them both fully will result in 0. 

DualShock mode:
You can actually get analog throttle/brake by mapping them to the right stick in the game settings. But the steering is not linear and it feels bad to me. The NeGcon mode feels much better.

**Comment by sorgelig** [comment]
> Yeah, I was wondering, worried about that. I would recommend the core be changed to use the shoulder buttons instead of the thumbstick.

MiSTer currently doesn't support analog triggers. I will think about it. Anyway, it doesn't prevent wheel implementation.

**Comment by sorgelig** [comment]
I've pushed wheel support in PSX core. Works ok, so far.
Now i want to find out pinouts for wheel connection to PC over gameport. And i cannot find it :(

**Comment by coolbho3k** [comment]
Ok. Will try it out after work, and I'll propose some further configuration for wheels (`wh_type` or similar) in a PR if axis doesn't work properly on the Fanatec wheels.

Next we should add Thrustmaster, expand Logitech and Fanatec wheel support, etc. but we need people to provide debug info.

**Comment by sorgelig** [comment]
I don't think we need to run in front of locomotive. The one who wants to add their wheel into supported can provide either PR (preferable) or at least some info. Probably some wheels will need special handling and physical access to device to discover all required setup procedures.

**Comment by thorr2** [comment]
> I've pushed wheel support in PSX core. Works ok, so far. Now i want to find out pinouts for wheel connection to PC over gameport. And i cannot find it :(

Just so I understand, does this mean if I run update_all, I can now try this with my Logitech wheel, or is it still in the staging pipeline for a later release?  

For the pinouts for wheel connection to PC over gameport, it is the same as a single analog joystick with either two or four buttons.  The steering wheel is X-axis analog, acceleration is the upper half of Y-axis analog, and breaking is the lower half of Y-axis.  There may be some games that support joystick 2's two buttons so there could be up to four, but generally I can't think of anything using joystick 2's analog joystick for driving games.  Here is the pinout: https://obrazki.elektroda.pl/6082738200_1640131129.png

**Comment by thorr2** [comment]
> I don't think we need to run in front of locomotive. The one who wants to add their wheel into supported can provide either PR (preferable) or at least some info. Probably some wheels will need special handling and physical access to device to discover all required setup procedures.

I am in no hurry at all, but eventually I would like to test my Act Labs Force RS.  It is basically the same as the G25 in terms of controls, except the stick shifter is a completely separate USB device.  I can't remember for sure, but the pedals may be a separate USB device also.  I have no idea if that would cause issues or not.  I certainly don't want to generate a lot more work for anyone and could live without support for this wheel.  I am just sharing the info in case it is helpful to think about for future support of wheels ideas.  

My plan is to use this with my arcade cabinet, and right now, there are not a lot of driving games for arcade on the MiSTer, so it will be used with Mame until the games come to the MiSTer (such as Outrun, Turbo, Pole Position, Hard Drivin', etc.).  In other words, I don't need it in MiSTer right now.  I sort of doubt there are any other MiSTer users still using that particular wheel also.

**Comment by coolbho3k** [comment]
@thorr2 Hmmm, separate USB devices are going to be a bit more complicated to add support for, because now MiSTer input framework is going to see them as separate players.

To test with your G25, you have to get the latest nightly for both Main_MiSTer and the PSX core. 

Everything looks perfect already with the Fanatec wheel! There's no need to tweak the axis stuff at all.

I can also hang around the issue tracker and help folks add support for other wheels when needed, if they cannot provide a PR themselves. Thanks @sorgelig!

**Comment by thorr2** [comment]
Thanks @sorgelig and @coolbho3k!  You guys are the best!  I will attempt to test right now...

**Comment by coolbho3k** [comment]
@thorr2 Oh, make sure you set the PSX core to NeGcon_Wheel for player 1 input

 When I mapped my buttons on the wheel, I also skipped all the mapping for any analog axis.

**Comment by thorr2** [comment]
Sorry for not knowing what I am doing, but I went here: https://github.com/MiSTer-unstable-nightlies/Main_MiSTer and I see that there was an update for the wheel, but I am not sure what to download.  The latest thing under releases is from April 13.

**Comment by coolbho3k** [comment]
> @coolbho3k Sorry for not knowing what I am doing, but I went here: https://github.com/MiSTer-unstable-nightlies/Main_MiSTer and I see that there was an update for the wheel, but I am not sure what to download. The latest thing under releases is from April 13.

You can get it from the #unstable-nightlies channel in the MiSTer Discord:

Main MiSTer: https://github.com/MiSTer-unstable-nightlies/Main_MiSTer/releases/download/unstable-builds/MiSTer_unstable_20220421_21e640 - download and replace /media/fat/MiSTer - you should back up your old MiSTer binary

PSX: https://github.com/MiSTer-unstable-nightlies/PSX_MiSTer/releases/download/unstable-builds/PSX_unstable_20220421_209849.rbf

**Comment by thorr2** [comment]
@coolbho3k  Thanks!  It's not working, but I think I know why.  I think I need the latest OS as well in order for it to work with my wheel.  Any suggestions on how to update the OS would be greatly appreciated.

**Comment by coolbho3k** [comment]
@thorr2 Hm it should be working if you replaced the main MiSTer binary with that version. There was no kernel update specifically for Logitech wheels.

046d:c294 should be supported.

If you try to map buttons, nothing happens?

**Comment by thorr2** [comment]
Correct.  Nothing I touch on the wheel does anything.  It calibrates the wheel after a power on or reset of the MiSTer, but that's it.  Is it possible @sorgelig updated his kernel, but didn't push it out?

**Comment by sorgelig** [comment]
For Logitech wheel need kernel update with logitech wheel driver included

**Comment by sorgelig** [comment]
> Here is the pinout: https://obrazki.elektroda.pl/6082738200_1640131129.png

Of course i know general joystick pinout for game port. Otherwise joysticks won't work on ao486 :)
I wanted to find how PC wheels were connected. I've saw instruction for one game with wheel connected as 2 analog joysticks. It seems i need to add option for ao486 with different wheel connections as there is no common standard.

**Comment by thorr2** [comment]
Thanks!  I will try this evening and report back.  Sorry, I wasn't sure what you were looking for because I didn't know there was a game that supported 2 analog joysticks.  I do know that my Thrustmaster wheel was the equivalent of one joystick and it worked with everything I played, so if you added support for only that configuration, it probably would work.  Also, whatever game you saw the instructions for, you could test with a gamepad and see how it behaves using the two thumbsticks to probably get your answer.  Thanks again!  I can't wait to test this evening (in about 9 or 10 hours from now).  I will be sure to report back.

**Comment by sorgelig** [comment]
Can you name some games working in ao486 and compatible with wheel? I want to test it.

**Comment by thorr2** [comment]
Here are some of my favorites (I have not tested all of these, but I am pretty sure Death Track works):
Death Track: https://www.youtube.com/watch?v=SEl_RvMIjeQ
Formula 1 Grand Prix: https://www.youtube.com/watch?v=uQwAE2EWdl0

And some oldies, but once goodies:
Test Drive: https://www.youtube.com/watch?v=FSbwSsjaJV0
Test Drive II: https://www.youtube.com/watch?v=R6hbfDihRQc

**Comment by thorr2** [comment]
@sorgelig I think Nascar might be a great option for additional controls.  See the video: https://www.youtube.com/watch?v=NErOeBnQhOw

**Comment by coolbho3k** [comment]
Do any of those games support force feedback? How did that work back in the day?

If they do, it would be very cool, and not entirely impossible, to get that working.

**Comment by coolbho3k** [comment]
ao486 is already pipelined. I took a look at if I could add some branch prediction to it and it's just too crazy. But I'm just a software guy.

**Comment by thorr2** [comment]
If you are a software guy, maybe you can look at PCEM and see if implementing it on the MiSTer is feasible.  I would love to see cores for each generation of computer (XT, 286, 386, etc.) with real BIOS screens, video cards, etc.  It's already coded in PCEM so it would just need to be translated to FPGA.  Like how I said "just"? ;-)

**Comment by thorr2** [comment]
@sorgelig I tested the wheel this evening, and it works while using the dpad and buttons, and I can keep using those for a long time without issue.  When I steer the wheel and press the pedals, it works for a short time, and then the wheel gets real loose, and the power light starts blinking and at that point, I need to unplug it and plug it back in to get it to work again.  So in other words, it looks like it works until it crashes shortly afterward.  I will do some testing in Windows to make sure my wheel is working fine there...

**Comment by thorr2** [comment]
In Windows, it works fine without crashing.  However, by default, it restricts the movement so I can't turn it as far.  The crashing occurs when I turn the wheel.  Perhaps turning it past the point that Windows is allowing is causing it to crash.

**Comment by thorr2** [comment]
I will try doing minimal mapping (no L1-3 or R1-3) and see if that helps...

**Comment by thorr2** [comment]
I fixed it! (sort of).  In my u-boot.txt, I used to have:
v=loglevel=4 usbhid.jspoll=1 xpad.cpoll=1 usbhid.quirks=0x0000:0x0000:0x040

Now I have:
v=loglevel=4

and it works with that.

If there is a way to change USB polling for just my G25, I think I will be in business.

**Comment by sorgelig** [comment]
fast USB polling is known as breaker for some USB devices. I don't think you can poll separately for each USB device.

**Comment by coolbho3k** [comment]
Yeah not possible in the kernel. You can set just the xpad.cpoll setting to at least keep the fast polling for your xinput controllers. You can try setting the jspoll to 2 for 500Hz

**Comment by thorr2** [comment]
Thanks @sorgelig and @coolbho3k !  Changing jspoll to 2 works:
v=loglevel=4 usbhid.jspoll=2 xpad.cpoll=1 usbhid.quirks=0x0000:0x0000:0x040

I had almost no time to do extensive testing, and I am leaving for my vacation, but I wanted to share my initial thoughts.  First, I am super happy to be able to play all these driving games when I return.  Second, thank you very much guys for all your efforts!  Third, the only technical issue is that I need to turn the wheel farther than I would like.  There are sensitivity adjustments in the games, but even on the most sensitive setting, it seems not sensitive enough.  I just tried a quick race in Need For Speed Porsche.  I think this may be due to my wheel being in 900 degree turning mode when the game is expecting less.  There might be a way to put my wheel in the shorter mode like how it behaves in Windows, but that isn't what I really would want.  It would be great if there was a steering wheel sensitivity setting in the MiSTer that could be adjusted where maybe the left and right distance can be reduced and turning further would need to be turned back before it would start going the other way in the game.  Or maybe having the option to turn off 900 degree steering might be an easy solution and then the wheel would physically prevent you from over-steering.  Or, maybe there is a non-linear setting in the 900 degree steering mode that can be adjusted so the centered wheel is more sensitive and it gets less so the more you turn it.  Making these adjustments could be in the ini file, or even better would be in the core menu so it could be adjusted per game.  While I am on the subject, I was thinking it would be great if there was a way to store joystick mappings at the per game level beyond just the per core level, in general.  There are some games where I like to remap the controls and I have to do that manually each time, like in the SNES, etc.  In the case of the wheel, so far the few games themselves that I tried so far have been allowing me to change the configuration, so it is not a big deal.  Thanks again for all your efforts!

**Comment by coolbho3k** [comment]
@thorr2 Btw - Sorg added support for configuring that. You can set the `wheel_range` param to set the range in degrees (ie. `wheel_range=200`) in MiSTer.ini. Try it out and see if it works.

**Comment by thorr2** [comment]
@coolbho3k That did the trick!  And it puts the tension on the wheel past that point, so it is perfect.  Thanks so much guys!  I am looking forward to coming home from my vacation, lol.

**Comment by thorr2** [comment]
Got to play a little today and I am really enjoying this.  Thanks again!  

Any chance of supporting "rumble" effects in the game at the same time as the wheel and have the wheel react to the rumble?  @coolbho3k mentioned FF_Periodic may be a way.  I am wondering if the game will send the rumble signal when the NeGcon is connected.  

Also, I am wondering if there are any updates with regards to ao486 that you want me to test.  I will be traveling again tomorrow, but I will be back for good Tuesday night and can start testing again.

**Comment by sorgelig** [comment]
NegCon has no vibration, so it shouldn't possible in this mode. In analog mode rumble is possible but i have no idea how to convert rumble to FF_Periodic. Also different wheels probably need different FF.

**Comment by thorr2** [comment]
Thanks.  Perhaps in the future we can support either mode and have the
possibility of rumble support for each known wheel once it is figured out
by someone.  For now, I am loving the current setup!

**Comment by M-Walrus** [comment]
I have a Thrustmaster wheel that had the pedals incorrectly assigned when I tried it in the PSX core.  I would also like to use it with Spy Hunter arcade but noticed it has a massive dead-zone in the wheel that makes it difficult.  Is there any way to change deadzone settings, or is that something that is coded into the core itself?

I recorded the following data via the console terminal to show what my wheel is reporting for the pedals:

Wheel:  Thrustmaster T300RS

[throttle]
Axis:5
Range:0...1023
Default offset (nothing pressed):1019
Fully pressed offset:1

[brake]
Axis:1
Range:0...1023
Default offset (nothing pressed):1019
Fully pressed offset:1

[clutch]
Axis:6
Range:0...1023
Default offset (nothing pressed):1019
Fully pressed offset:1

**Comment by atrac17** [comment]
> `CONFIG_HID_LOGITECH=y` is set in the kernel, I don't understand why the MiSTer won't respond at all to the Logitech wheel. Maybe https://github.com/berarma/new-lg4ff will work, but I have no Logitech wheel to test.

It works well with the G29 @coolbho3k. Steering tension seems tighter with this driver. The following referenced **[here](https://github.com/berarma/new-lg4ff#dkms)**:

```
[347092.750524] logitech 0003:046D:C24F.000B: Force feedback support for Logitech Gaming Wheels (0.2b)
[347092.750525] logitech 0003:046D:C24F.000B: Hires timer: period = 2 ms
```

Once DKMS was added with modules in the kernel I got it going in my fork. Going to make a PR with drivers updated for the Logitech Wheels. You can see at the end, it's using the `new-lg4ff` driver without editing the `u-boot.txt` and runs at 1000Hz polling. 

Tested with the PSX core on the following:
```
Gran Turismo 2 (USA) (Arcade Mode) (Rev 1)
Ridge Racer Type 4 (Europe)
```
`dmesg` output for the device:
```
[ 6089.286054] usb 1-1.5: USB disconnect, device number 8
[ 6092.285909] usb 1-1.5: new full-speed USB device number 10 using dwc2
[ 6092.381804] usb 1-1.5: New USB device found, idVendor=046d, idProduct=c294, bcdDevice=13.50
[ 6092.390165] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 6092.397484] usb 1-1.5: Product: G29 Driving Force Racing Wheel
[ 6092.403341] usb 1-1.5: Manufacturer: Logitech
[ 6092.414783] HID usage: 0x00010005, original interval: 10
[ 6092.420187] JS: endpoint->bInterval=10, interval=1
[ 6092.425015] HID usage: 0x00010005, applied interval: 1
[ 6092.430189] HID usage: 0x00010005, original interval: 10
[ 6092.435515] JS: endpoint->bInterval=10, interval=1
[ 6092.440321] HID usage: 0x00010005, applied interval: 1
[ 6092.445781] input: Logitech G29 Driving Force Racing Wheel as /devices/platform/soc/ffb40000.usb/usb1/1-1/1-1.5/1-1.5:1.0/0003:046D:C294.0008/input/input10
[ 6092.460577] logitech 0003:046D:C294.0008: input,hidraw0: USB HID v1.00 Gamepad [Logitech G29 Driving Force Racing Wheel] on usb-ffb40000.usb-1.5/input0
[ 6092.614057] usb 1-1.5: USB disconnect, device number 10
[ 6093.053902] usb 1-1.5: new full-speed USB device number 11 using dwc2
[ 6093.149641] usb 1-1.5: New USB device found, idVendor=046d, idProduct=c24f, bcdDevice=89.00
[ 6093.158010] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 6093.165328] usb 1-1.5: Product: G29 Driving Force Racing Wheel
[ 6093.171193] usb 1-1.5: Manufacturer: Logitech
[ 6093.182844] HID usage: 0x00010004, original interval: 2
[ 6093.188169] JS: endpoint->bInterval=2, interval=1
[ 6093.192906] HID usage: 0x00010004, applied interval: 1
[ 6093.198067] HID usage: 0x00010004, original interval: 2
[ 6093.203307] JS: endpoint->bInterval=2, interval=1
[ 6093.208025] HID usage: 0x00010004, applied interval: 1
[ 6093.213489] input: Logitech G29 Driving Force Racing Wheel as /devices/platform/soc/ffb40000.usb/usb1/1-1/1-1.5/1-1.5:1.0/0003:046D:C24F.0009/input/input11
[ 6093.228226] logitech 0003:046D:C24F.0009: input,hidraw0: USB HID v1.11 Joystick [Logitech G29 Driving Force Racing Wheel] on usb-ffb40000.usb-1.5/input0
[ 6093.242579] logitech 0003:046D:C24F.0009: Force feedback support for Logitech Gaming Wheels (0.3.3)
[ 6093.251710] logitech 0003:046D:C24F.0009: Hires timer: period = 2 ms
```

**Comment by coolbho3k** [comment]
Oh that’s great. I didn’t realize this is needed to get it working in ao486
but it makes sense now.
