### ISSUE TITLE
Without a controller Mister registers an up key command

### ISSUE THREAD

**Issue by mr-matthew-michael** [MiSTer-devel/Main_MiSTer#577]
When on the OS screen for Mister the console will move the selection highlight up at irregular intervals with or without a controller plugged in. This bug also occurs within the all the cores I've tested.

**Comment by birdybro** [comment]
Do you have anything plugged into it at all? It sounds like some other device is causing phantom inputs.

**Comment by sorgelig** [comment]
yeah, looks like some real or virtual input device generates that key
