### ISSUE TITLE
Request: Expand NVRAM support to more than MRA

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Main_MiSTer#581]
Currently NVRAM only saves firmware-like settings or saves per core for arcade cores. 

I'm not sure if this is the appropriate method, but there are systems that had per-system firmware settings (like Neo Geo AES unibios and the WonderSwan, for instance). If you load a rom in the WonderSwan core and press the start button repeatedly fast, it takes you into a screen to save your Birthdate, Name, Blood type, etc... There are some games that use this functionality (e.g. Super Robot Taisen Compact 1 and 2).

If possible could support of NVRAM be added for other cores? Or if there's a better way to have per-system saves for these special kinds of things to be added, that's fine too.

**Comment by sorgelig** [comment]
Cores have auto-mount ability of up to 4 VHDs which can be used as a read-write storage.

**Comment by birdybro** [comment]
Okay! That makes more sense to use. Closing request. :)
