### ISSUE TITLE
Genesis SNAC Lightgun issue

### ISSUE THREAD

**Issue by stormcrow56k** [MiSTer-devel/Main_MiSTer#592]
Most games require a controller in port 1 and the lightgun (I'm using the konami justifier) in port 2.  As far as I can tell, there is no way to make this work with SNAC.

**Comment by sorgelig** [comment]
Main has nothing to do with SNAC. SNAC is controlled solely by core. So you need to open issue in specific core. Many cores support joysticks swap.
