### ISSUE TITLE
Feature Request: MGL file creation tool in MiSTer

### ISSUE THREAD

**Issue by thehughhefner** [MiSTer-devel/Main_MiSTer#593]
Hi Sorg,
This is semi-related to this issue: https://github.com/MiSTer-devel/Main_MiSTer/issues/337

It would be nice to have an option in the OSD called "Bookmark" or "Save as favorite" where it creates an MGL file of the current loaded rom. MGL file is created and stored in a folder in root called "_Favorites". 
Today the user has to create an MGL file manually which can be tedious since the user has to specify the path to the rom,

Is this feasible to implement? 
Kind regards

**Comment by sorgelig** [comment]
MGL files is NOT the main way to launch. Relay on that will simply mislead the users as it has some caveats.
Also MiSTer doesn't provide full features OSD file browser where you can add/delete/rename the files.
So it supposed to stay this way as it is.

**Comment by marceloMedeiros** [comment]
Also, im pretty sure its already possible to achieve similar functionality using scripts. 

For example, one could create a script that , once ran, started a background watcher that tracked games opened/started by the user, and would create MGL files for each one as proposed by the OP.

When done adding games, the user would just do a cold reboot from the OSD.

**Comment by sorgelig** [comment]
Recent core and recent rom is basically favorite implementation.

**Comment by birdybro** [comment]
A script could also be made by a user skilled enough that would have a TUI where they can select roms from directories and press run, and it will generate the MGL's and place it in the correct place for them if they want.

**Comment by synrais** [comment]
I made something sketchy you can use on windows.
https://misterfpga.org/viewtopic.php?t=4359

**Comment by sorgelig** [comment]
> I figured it would be used to call artwork and other meta when highlighting titles in the future.

no, it wont.

**Comment by Paradox** [comment]
MiSTer_SAM has a feature that does this...

**Comment by pocomane** [comment]
With the last commit, [mbc](https://github.com/pocomane/MiSTer_Batch_Control) uses MGL to load roms from the command line. As side effect this tool is now able to generate MGL from the command line. It should be simple to use from script or other apps. 

The feature is quite new so I expect some bugs to pop out, but I performed some minimal tests, and it seems usable.
