### ISSUE TITLE
Logging causing problems in PC Engine game "Tanjou Debut"

### ISSUE THREAD

**Issue by dshadoff** [MiSTer-devel/Main_MiSTer#594]
During the opening sequence in Tanjou Debut, choppy audio occurs during the opening animation sequence where the characters introduce themselves.

This issue was initially brought to my attention in this thread:
[https://misterfpga.org/viewtopic.php?t=4667](https://misterfpga.org/viewtopic.php?t=4667)
I have verified the choppy audio portion of this description

Upon examination, the Main_MiSTer process showed excessive logging of a certain type of event during this sequence:
"PCECD: Command TESTUNIT, state = 3"

**Comment by sorgelig** [comment]
comment it out :)

**Comment by dshadoff** [comment]
Verified
