### ISSUE TITLE
Rumble doesn’t work on 8Bitdo SN30 Pro controllers

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/Main_MiSTer#597]
Rumble functionality doesn’t work on 8Bitdo SN30 Pro (wireless or USB) controllers.

Tried in both the GBA or PSX cores. Other users have also reported not getting any rumble with these controllers.

**Comment by birdybro** [comment]
Are you using it in Xinput mode or Dinput mode?

**Comment by AtomicShroom** [comment]
Hmmm that is weird. I seem to have a defective controller. I have a few SN30 Pro USB wired (no wireless) controllers, and the one I was using does not vibrate no matter what. I plugged in another and rumble works just fine. 🤷🏻‍♂️ I’ll close the ticket.

**Comment by birdybro** [comment]
> Hmmm that is weird. I seem to have a defective controller. I have a few SN30 Pro USB wired (no wireless) controllers, and the one I was using does not vibrate no matter what. I plugged in another and rumble works just fine. 🤷🏻‍♂️ I’ll close the ticket.

Run the firmware update from 8bitdo maybe.

https://support.8bitdo.com/firmware-updater.html

I guess according to the manual for the wired one it is always in X-Input. Just putting that her in case someone else brings it up:

[pro2-wired.pdf](https://github.com/MiSTer-devel/Main_MiSTer/files/8647374/pro2-wired.pdf)

**Comment by birdybro** [comment]
Adding here, apparently holding the B button on the Wired 8bitdo SN30 Pro 2 when plugging it in allows it to begin in xbox 360 mode, which will work with the MiSTer.
