### ISSUE TITLE
You might want to add a Line about Cooling to the MiSTer Wiki

### ISSUE THREAD

**Issue by UHU-ger** [MiSTer-devel/Main_MiSTer#6]
Hi,
I saw pictures with heatsink and fan everywhere so i assumed it is necessary, but i did not find any information(had not finished the 28 Pages thread in the Atari forum), so it took me quite a while to find the correct size. (got it from measuring the board from its pdf specs from teratec)

You do not mention the cooling in the wiki, and i thought you might want to add a line to the "How to start" section of the MiSTer wiki.

Something like:
A Heatsink (plus fan?) for the Cyclone V chip is recommended (because ...). The cyclone 5 is approximate 21,5mmx21,5mm, so the Heatsink should be minimum size of XXmmxXXmm and maxXXmmxXXmm because of other parts on the board. 
To fit in the MiSTer - Case a maximum hight of xxmm is recommened. (or maybe the hight shouldbe small in general because of io-board?

(i ordered 22x22x10mm, but i did not recieve board and heatsinks yet, so i can not test it yet)

regards Uwe

**Comment by sorgelig** [comment]
You are right. Still no info about cooling on the Wiki.
I will add it.
The best size for heatsink is 25x25x10mm 
22mm is also fine. 25mm is the biggest size which can fit without touching surrounding components.

**Comment by juri74** [comment]
I added some "cool infos" in "How to start" section in the wiki.

**Comment by sorgelig** [comment]
Thanks! Although the part about "Some cores like ao486 and Minimig make the FPGA chip very hot" is not correct. The chip gets constant heating regardless the running the core because the heating part in the chip is ARM part, not FPGA.

**Comment by juri74** [comment]
Thanks for making corrections, i forgot about the arm. i think the issue could be closed..

**Comment by sorgelig** [comment]
Ok.
And as always - everybody is welcome to improve the Wiki!
