### ISSUE TITLE
Directory name will not scroll if only the last character is cut.

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/Main_MiSTer#600]
There seems to be a bug in the name scrolling routine for (at least) Directories.  If exactly only the last character of the directory name is being cut by the max length displayed, then it will not scroll the name to display it.

For example, the directory for "Tony Hawk's Pro Skater" shows up as "Tony Hawk's Pro Skate &lt;DIR&gt;".   Since only the last letter is being cut, it will not scroll to show the missing "r".   It seems like it considers the full name is being displayed, when it isn't.

**Comment by sorgelig** [comment]
should be fixed in latest commit.

**Comment by AtomicShroom** [comment]
Confirmed fixed in latest update! Thank you!
