### ISSUE TITLE
Feature Request:  Option to automatically disable Vert filter (scanlines) when interlaced video modes are used.

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/Main_MiSTer#601]
I would like to request an option to automatically disable the Vert filter (scanlines) when an interlaced video mode is detected, and automatically re-enable it when a progressive video mode is detected.  (The Horiz filter should stay on to keep providing interpolation).

Currently, scanline filters remain active even when an interlaced video mode is used, which is incorrect as it ends up dimming half of the lines composing the 480p picture produced by the scaler. And worse, if you are using a 0% Scanline filter (pure black lines), then you end up with half the resolution missing from the final output at all times.

**Comment by sorgelig** [comment]
it should be addressed to specific core because "Scandoubler FX" option is controlled by core. So core knows when interlaced mode is activated and can automatically disable scanlines.

**Comment by AtomicShroom** [comment]
Actually I'm wondering if a better implementation would rather be to let users pick a different set of filters for both progressive and interlaced resolutions? That way, everyone can pick whichever combination of filters suit their preferences for both modes.

**Comment by wickerwaka** [comment]
I believe the request is for scaler scanline filters, not the scandoubler scanlines, so cores don't have control over that. I don't know how this desire would be best expressed. There is no way to tell that a filter is a "scanline" filter, so we couldn't just arbitrarily disable any vertical filter when the video signal is interlaced.

**Comment by AtomicShroom** [comment]
> I believe the request is for scaler scanline filters, not the scandoubler scanlines, so cores don't have control over that. I don't know how this desire would be best expressed. There is no way to tell that a filter is a "scanline" filter, so we couldn't just arbitrarily disable any vertical filter when the video signal is interlaced.

Correct, I meant for scaler scanline filters.

I think my suggestion in the previous post would be the best implementation (unless someone can think of something even better, of course).  Allow users to configure two filter sets:  One for progressive, one for interlaced.

**Comment by birdybro** [comment]
Here's a summary of how something like this could work:

1. Signal provided from framework to main when video is rotated (the hardest one since I think only arcade_video handles it this way).
2. Signal provided from framework to main when interlaced video is enabled (this already exists, see video_info in osd)
3. If video is not rotated and it is interlaced, only vert_filter is disabled.
4. if video is rotated and it is interlaced, only horz_filter is disabled.
5. Else, do nothing

**Comment by sorgelig** [comment]
HDMI output of MiSTer is always progressive, so strictly speaking filters should not affect it. Probably scaler need to be reworked so filter will be applied after de-interlacing.

**Comment by birdybro** [comment]
That's a great idea. I didn't know how possible that would be! :) That would be the best solution.

**Comment by Kitrinx** [comment]
the simplest solution is to just change vertical filter = horizontal filter when interlaced is active

**Comment by birdybro** [comment]
As I just discussed with Kitrinx, another workaround is to 2x the filters and shadowmasks for interlaced video. Whatever logic is used for shadowmasks' 2x mode could be applied to filters as well, right? That way you get a consistent experience upon progressive/interlaced switches.

**Comment by Kitrinx** [comment]
You cannot 2x the filters, that won't work. You can do it for shadow masks though.

**Comment by Kitrinx** [comment]
to clarify, since this is a fairly specific issue mostly with psx core, if interlaced is active, then make vertical filter (scanlines) equal to whatever horizontal is (interpolation) and 2x any shadow masks if they are active, that should effectively solve the problem for this console, without creating a very complex set of extra options.

**Comment by sorgelig** [comment]
Seems no one understood what i've wrote.
Filter actually should be applied after deinterlacing. It means if you get 480i from core then filter should be applied to 480p resolution, not to 240p. So it's basically scaler issue.

**Comment by Kitrinx** [comment]
and i'm trying to explain that that won't work, because you shouldn't have scanlines on 480i content. You'll obliterate nearly half the image with the scanlines.

**Comment by tonurics** [comment]
Automatically applying the 2x logic to Shadow Masks are not desirable for non-CRT Shadow Mask effects [the majority of Shadow Masks] and will cause other regressions.

If this feature is pursued: it should be added in the form of a user setting or as part of a format update to the Shadow Mask files, so the correct and intended effects are applied.

**Comment by birdybro** [comment]
Yes, I made a mistake in my assumptions. Confirmed that the shadowmask should remain the same.

**Comment by sorgelig** [comment]
> and i'm trying to explain that that won't work, because you shouldn't have scanlines on 480i content. You'll obliterate nearly half the image with the scanlines.

read what i've wrote before. There is no 480i. only 480p after deinterlace.

**Comment by Kitrinx** [comment]
I know this. I understand that it's de-interlaced.  The SOURCE video is 480i, and 480i content should not have 240p style scanlines applied to it, not at 480p, not at 240p, not at any resolution. It should not have any scanlines at all if the source video is interlaced! If you apply scanlines at 480p there will be 2x too many and it looks broken and terrible and wrong. If you apply scanlines to a 480p image at 240p resolution they will be obscuring a lot of the image that should be visible.

**Comment by AtomicShroom** [comment]
Right. And so 480p shouldn't have scanlines, because it's progressive and has no scanlines by definition. We all want the same thing. ;)

**Comment by mjj03301977** [comment]
I’m guessing all the consoles have interlaced modes…I found this regarding the SNES:

“The following SNES games use interlaced modes for static screens like Air Strike Patrol, Bishoujo Wrestler Retsuden. Power Drive, Ranma 1/2: Chounai Gekitou Hen and the SNES Test Program.  It is also used in one of the endings in Chrono Trigger.”

**Comment by AtomicShroom** [comment]
I keep thinking about what shape this option could take, and I can't think of a simpler, more elegant solution than this:

Below the filters, have an option that says:  "Disable in interlaced:" with selections "Vert", "Horiz", and "Both".  That way you give people all the flexibility they could possibly want. 

A more complex option would be to provide the possibility of selecting a separate selection of filters for both progressive and interlaced resolutions.

And if you reeaaaaally want to go for accuracy, then accept no other substitute:  provide dynamic filters that alternate scanlines between odd/even lines at every frame, hence perfectly simulating all the flickery goodness of interlaced resolutions on a CRT.  🤪

**Comment by AtomicShroom** [comment]
I'm not really a fan of this implementation tbh. I tried it and it makes interlaced resolutions look much blurrier because it applies the same interpolation as horizontal, which when added up together, makes for too much interpolation all-around. (In my case anyway).  I'd like to be able to select a specific filter to use for vert when interlaced content is detected. If anything make this possible through the .ini file somehow?

**Comment by AtomicShroom** [comment]
Actually now that this has been released in Main, I realize it doesn’t work properly: it doesn’t turn off/on the vert filter automatically. I actually need to go into Video processing and toggle the vert filter setting to “from file” and then back to my selected filter for the scanlines to remain off. And then when the game switches to a progressive mode, scanlines don’t reactivate unless I go toggle the vert filter again. 

Also I would like to reiterate that I really don’t like the resulting look from this implementation. Duplicating my Horiz filter (GS_Sharpness_55) for Vert produces an overly blurry look. I would like to be able to pick a much less intense interpolation for the Vert filter instead. :/

**Comment by Kitrinx** [comment]
Seems to work fine for me. Are you using an extremely aggressive horizontal filter?

**Comment by Kitrinx** [comment]
![image](https://user-images.githubusercontent.com/15653832/170884006-7fdd9942-6e0a-4a5b-8021-698b4902bdd5.png)
![image](https://user-images.githubusercontent.com/15653832/170884011-5a1ca884-bde8-480f-8268-0b8f1566c1f3.png)
I didn't have to tweak anything for these changes to take place.

**Comment by AtomicShroom** [comment]
> @AtomicShroom are you running with `vsync_adjust=0` in your ini? It's possible that the filters aren't getting updated in that case.

Yes I'm using vsync_adjust=0.   

Otherwise one thing I was going to try when I get a chance is to see if this line in my .ini might also be the cause: 

vfilter_vertical_default=Scanlines - Adaptive/SLA_Dk_060_Br_090.txt

**Comment by AtomicShroom** [comment]
Okay so I tested and you're right:  It works correctly with vsync_adjust=1, and doesn't work with vsync_adjust=0.

**Comment by M-Walrus** [comment]
I noticed this with the PSX core also.  vsync_adjust 0 is buggy with the current implementation.  The vert filter would not work for me even with 240p content, until I disabled and re-enabled the filters entirely.

It would also be great if shadowmasks could automatically be disabled in 480i screens, as it just causes un-necessary noise.

**Comment by M-Walrus** [comment]
Seems that the issues referenced in this report have been fixed, and this can be closed out.  
I haven't noticed any issues with 480i applying scanline filters in the PSX core anymore, and the quirk with vsync_adjust 0 seems resolved as well.
