### ISSUE TITLE
Direct Video no longer syncs  to my CRT with latest version 20220517

### ISSUE THREAD

**Issue by chr0m** [MiSTer-devel/Main_MiSTer#605]
I updated to 20220517 and my CRT no longer syncs via direct video

It works if I go back to the previous version 20220511

**Comment by wickerwaka** [comment]
Good catch. Minimum HDMI dot clock is 25Mhz.

**Comment by sorgelig** [comment]
interesting, as all cores (at least i've tweaked for direct video) use video clock >25MHz.

**Comment by sorgelig** [comment]
Thanks for finding it out!

**Comment by chr0m** [comment]
Thanks for figuring this out!

**Comment by birdybro** [comment]
https://github.com/MiSTer-unstable-nightlies/Main_MiSTer/releases/download/unstable-builds/MiSTer_unstable_20220518_20ff6d

**Comment by chr0m** [comment]
@birdybro Thanks. It works!

**Comment by paulb-nl** [comment]
I suggest to enable Pixel repetition with Directvideo in the Menu core only because the pixel repetition is the reason why Vsync must be aligned to HSync start with Directvideo & composite_sync=1.

There are some cores which don't work with Directvideo and composite sync such as Atari ST(just fixed), Tatung Einstein, Armstrad, Coco3. These cores all work fine with Directvideo if pixel repetition is disabled.

Changing these cores to align Vsync to HSync is sometimes difficult because some can output interlaced and it takes time. So it seems better to fix it in here in Main.

**Comment by misteraddons** [comment]
Could this also be related to the PSX core’s “sync 480i to hdmi” option
required for cutscenes but then making 480i gameplay and menus wobble like
the de-interlacing doesn’t work?

**Comment by paulb-nl** [comment]
Do you mean on the analog output? The Sync 480i to HDMI is to prevent the scaler with vsync_adjust=2 to lose sync during 240p/480i transitions. It should not be enabled if you use the analog output.

**Comment by birdybro** [comment]
Exactly, maybe that's the source of this users problem. But it should only effect 480i video.

**Comment by misteraddons** [comment]
I mean through direct video. Check out the FMV on Tekken 3, and Gran
Turismo 1 and 2. Sync is broken without the “sync 480i to HDMI” option.
When you set that option it messes with deinterlacing for menus.

**Comment by chr0m** [comment]
> The Sync 480i to HDMI is to prevent the scaler with vsync_adjust=2 to lose sync during 240p/480i transitions. It should not be enabled if you use the analog output.

Hmmm, if I don't enable it PSX doesn't sync for me

**Comment by paulb-nl** [comment]
You should create an issue in the PSX repo for that. I am seeing the same behavior with a Ugreen DAC but not with another one. The PSX core also has some crazy sync issues with Directvideo in general if I connect the DACs to a HDMI splitter which works fine with all other cores.

**Comment by chr0m** [comment]
> You should create an issue in the PSX repo for that. I am seeing the same behavior with a Ugreen DAC but not with another one. The PSX core also has some crazy sync issues with Directvideo in general if I connect the DACs to a HDMI splitter which works fine with all other cores.

Which ugreen one? I have both :) I got one and it had issues with some other cores. Mainly the Atari consoles and Commodore 16. I got a different ugreen and it seems perfect on every core. The Tendak seemed to work on everything except PSX (with or without the 480i HDMI sync) It didn't seem to like 480i at all. I tried it in the Genesis 240p test suite.

I have a HDMI to VGA cable where PSX breaks when I plug it into a splitter, but strangely plugging it into the splitter fixes bouncing image issues I had on some other cores :)

My perfect combo now is https://www.ugreen.com/products/hdmi-to-vga-adapter-with-audio-jack?_pos=3&_sid=f2e327390&_ss=r combined with https://etim.net.au/shop/shop.php?crn=220&rn=582&action=show_detail

All of the other HDMI to VGA adapters I tried had issues with at least one core

**Comment by birdybro** [comment]
The only direct video issue I'm aware of that is the fault of the core and not the template/Main is with the SMS core's border issue --> https://github.com/MiSTer-devel/SMS_MiSTer/issues/120

So yes, the Main_MiSTer or Template_MiSTer repos are the appropriate places to raise issues regarding direct video not working.
