### ISSUE TITLE
Some cores not syncing when using 15kHz Direct Video

### ISSUE THREAD

**Issue by ArchiveRL** [MiSTer-devel/Main_MiSTer#615]
This is an issue I've had for nearly 2 years, but I was never quite sure what might be the cause. Basically, when connecting my MiSter to a 15 kHz CRT TV or a PVM, a few cores refuses to sync, namely:

Atari ST
Amstrad PCW
Tatung Einstein
Coco 3

These cores display ok natively on 15kHz via IO board. 
I think I've also seen this happening in some console games, where resolution is changed within a game, but I can't confirm that 100%.
There are also out of sync problems when using custom modelines, which otherwise work using the IO board. Eg [ao486, PC-88, x68000](https://github.com/MiSTer-devel/Main_MiSTer/wiki/MiSTer-CRT-Guide#ao486). 

Possible causes I've considered:
1)  cables - I've initially though it might be down to my cable lacking the 470 Ohm resistor ( I was using the MiST cable), but since then I've tested it also with a common VGA - BNC cable for PVM, a proper MiSTer cable from an official seller, and a new AG6200 based all-in-one cable prototype. Same results.
2) CRT sets - I've tested this on 4 different Trinitrons, couple of Philips TVs and a 15kHz PVM. Same results.
3) HDMI -VGA adapters - my adapter (called Logilink) is AG6200 based, and I've also tested it on the aforementioned all-in-one cable. I've also heard similar things from users. But, I've also heard that these cores (or at least Atari ST) do work for other Direct Video users  (though these reports weren't 100% confirmed). Therefore different adapter design could be a factor here.

Additional factors:
-when adding VGA2SCART adapters into the chain, the problem disappears. As in: MiSTer >> HDMI/VGA adapter >> VGA-VGA cable >> VGA2SCART adapter >> SCART to SCART cable >> SCART CRT TV
Example adapters [UMSA](https://arcadeforge.net/UMSA/UMSA-Ultimate-SCART-Adapter::57.html?language=en), [VGA to SCART](https://etim.net.au/shop/shop.php?crn=220&rn=582&action=show_detail)
Using these also makes the custom modelines work via Direct Video.

-a recent release [MiSTer_20220511](https://github.com/MiSTer-devel/Main_MiSTer/blob/master/releases/MiSTer_20220511) has broken Direct Video for most users. [It was reported](https://github.com/MiSTer-devel/Main_MiSTer/issues/605) and quickly fixed, but while testing it, I have discovered that it actually made these problematic cores work on Direct Video (I did not do update_all like the others, just dragged the binary manually to my MiSter via SSH. And my DV somehow still worked, though when I tried to run update scripts, image went out of sync). 

I realize this is a hard to pinpoint issue, possibly caused by different hardware and/or software factors, but perhaps somebody can see a common denomionator here. The fact that it was resolved (partially) in release 20220511 might mean that it is possible to be solved on the software side.

**Comment by paulb-nl** [comment]
I have talked about this here https://github.com/MiSTer-devel/Main_MiSTer/issues/605#issuecomment-1133884443

Actually these cores that you listed are not tweaked for Directvideo with composite_sync=1 so they don't work.

However it turns out that without pixel repetition enabled the cores work even without tweaking which is what happened with MiSTer 20220511.

With composite sync disabled and a VGA->SCART adapter that does HV sync combining it would already work so if it worked for other people then they had composite_sync=0.

Modelines only work with Directvideo disabled and composite_sync is only supported with Directvideo enabled so you still need a HV sync combiner if you use the HDMI output.

**Comment by ArchiveRL** [comment]
This is great, thank you. So from what I understand it's possible to be permanently fixed with that "pixel repetition" Menu core change?

Yes, when I was using the VGA2SCART adapter I had to set composite_sync=0. But I was under impression a few times other people referred to using DV just with a MiSTer cable and having the ST core working, which was confusing and threw me off.

I understand that modelines are a different matter and might never work with DV. It's ok, at least we know that an adapter might sort it out.

Interestingly, I've just tried...
`[corename]`
`composite_sync=1` or  `composite_sync=0`

...on these four cores (with an older mister main file). ST and PCW still refused to sync, but Coco and Einstein were displaying okay with `composite_sync=1`, despite me having `composite_sync=1` under the `[mister]` tag.

**Comment by paulb-nl** [comment]
MiSTer_20220517 is the one with the Directvideo bug so those cores should work with that one except for the Menu core. The nightlies after that won't work.

I will post a test build later for you to try.

**Comment by ArchiveRL** [comment]
I see...so the 605 got closed in regard to a nightly build...I got confused with the build numbers overall. Also, because in general the DV still works for me, [unlike for the other users](https://misterfpga.org/viewtopic.php?t=4744) (apart from when trying to run an update from the OSD menu).

Thanks a lot for looking into it.

**Comment by paulb-nl** [comment]
Yea that issue was closed too soon.

If the Menu core kept working for you that means that you have the static noise background on the menu. Switching to any other background with F1 on the keyboard or when running a script will enable the scaler & framebuffer and this is what triggered the bug.

Here is a test build of MiSTer main which should work for everything:
[MiSTer_DV.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/8754157/MiSTer_DV.zip)

**Comment by ArchiveRL** [comment]
Hi @paulb-nl, any chance to make a pull request on this? Cheers!

**Comment by paulb-nl** [comment]
Yes three days ago 😉 It is already merged.

https://github.com/MiSTer-devel/Main_MiSTer/commit/357fbb630e184eb1278ee2010f760ea8b0fde858

**Comment by ArchiveRL** [comment]
Drat! Somebody allegedly in the know told me it wasn't, hence the request. Sorry, and thanks again!

I guess it's time for closure :)
