### ISSUE TITLE
allow waitmount to apply to Menu core when added as a core exception

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Main_MiSTer#617]
https://github.com/MiSTer-devel/Main_MiSTer/blob/18785a56d8468cae8b3a10409c6dec508d8e8df7/MiSTer.ini#L212

Currently some users have issues with SSD or HDD storage not being recognized or initialized right away, and then MiSTer defaults to internal storage instead. For users with these drives, would it be possible to add support for them doing a core exception for the Menu core to add a delay before MiSTer goes into the menu? e.g.

```ini
[Menu]
waitmount=/media/usb0
```

Thank you! :)

**Comment by sorgelig** [comment]
wait is not applied for menu core on purpose, so menu will appear as soon as possible. 
Menu doesn't use games folder, so it's safe to start it without wait. Core will wait for storage if it's not yet mounted.

**Comment by birdybro** [comment]
This does effect scripts though like downloader and update_all. Maybe the issue is related to something else, as these drives were taking awhile, and multiple users had to do a cold boot to make them wake up. Closing this as it's not the appropriate issue for what those users seemed to be experiencing.

**Comment by sorgelig** [comment]
HDD are tend to go into sleep mode and then need some time to wake up. Not a good storage for MiSTer.. Some HDDs can be configured to prevent sleep.

**Comment by birdybro** [comment]
Yes, this was happening to users with an SSD however. I don't have their logs though in any detail so I can't tell what was happening. :)
