### ISSUE TITLE
Vibration sent to two (or more) controllers at once after pressing a button on additional controllers.

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/Main_MiSTer#619]
Vibration will be sent to two (or more) controllers at the same time if you press a button at any point on additional controllers.

Steps to repro:
1. Start MiSTer with 2 controllers connected.
2. Boot the PSX core and start a game with vibration (Metal Gear Solid's option menu has a vibration test).
3. Trigger vibration on controller 1 and notice that it is only sent to the controller you are using, as it should be.
4. Press any button on controller 2.
5. Trigger vibration on controller 1 again.

Result:  Both controller 1 & controller 2 vibrate.

**Comment by RobertPeip** [comment]
Will test this in psx core first and verify only pad1 sends rumble on

**Comment by AtomicShroom** [comment]
Many thanks Robert!   FYI I am unable to reproduce this in the GBA core (Drill Dozer), so it might be PSX-core specific.

**Comment by AtomicShroom** [comment]
More info:

I tried in Crash Team Racing with a 2-player VS race.  At all times, vibration for controller 1 was duplicated onto controller 2, while vibration events of player 2 were simply absent.

**Comment by RobertPeip** [comment]
bug was in psx core and is now fixed
