### ISSUE TITLE
Request: Parse bluetoothctl output for keyboard security code and display in OSD

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Main_MiSTer#626]
https://misterfpga.org/viewtopic.php?p=36155#p36155 <-- same issue this person figured out on their own

I tried to pair a new keyboard today but it is one that requires a security code upon pairing. The MiSTer bluetooth script (when you press F11 on another keyboard) does not display the security code and just hangs for 60 seconds until timeout, where it will try and scan for other devices. I had to manually set it up like in the linked comment in the official forums thread above.

Here is the example message from bluetoothctl:

```
[bluetooth]# pair D4:DC:0D:ED:13:6F
Attempting to pair with D4:DC:0D:ED:13:6F
[CHG] Device D4:DC:0D:ED:13:6F Connected: yes
[agent] Passkey: 094061
```

094061 is the number I had to type in to my keyboard and press enter within 60 seconds in order for it to pair successfully.

Could support for the output be added please? Thanks! :)

**Comment by sorgelig** [comment]
i remember it supported pin entering.. I will try.

**Comment by sorgelig** [comment]
just re-checked with mini BT keyboard. On pairing OSD shown: type code 659279 and then <enter>.
I've typed it on keyboard and succeeded pairing.
So i don't see problem here.

**Comment by birdybro** [comment]
Interesting, it didn't show up for my keyboard. Well I'll close this as it's probably device-specific. Thanks!

**Comment by sorgelig** [comment]
There are similar methods of pairing. Probably your keyboard use method not handled by current pairing agent. So you are welcome to add it if you want.
