### ISSUE TITLE
Switch to USB

### ISSUE THREAD

**Issue by Paradox** [MiSTer-devel/Main_MiSTer#630]
Please hide this option, or, at the very least, make it not the default option when you open the menu, I have accidentally hit this, so many times, and, I don't like it. Or, add a confirmation before switching, so we can cancel, if we didn't mean to hit it.

**Comment by birdybro** [comment]
It's not the default option when you open the menu. You have to go to the secondary menu to access it.

As far as the other candidates for default option, I think the others could be worse, except Reboot. People could accidentally remap keyboards, wipe out their gamepad settings, run a script accidentally, etc... Maybe help instead? I dunno.

**Comment by Paradox** [comment]
> It's not the default option when you open the menu. You have to go to the secondary menu to access it.
> 
> As far as the other candidates for default option, I think the others could be worse, except Reboot. People could accidentally remap keyboards, wipe out their gamepad settings, run a script accidentally, etc... Maybe help instead? I dunno. I could see the default option that is switched to being help as a better option.

All you have to do is hit B from the main menu, and it will bring you to the secondary menu, and, a single press of A will switch you over to USB, and, has the possibility, if you don't have an xbox controller, to prevent you from switching back, because all of your controller definitions are gone, unless you have a copy of /media/fat/config in /media/usb0/config.

**Comment by Paradox** [comment]
Even adding a confirmation to it would work.

**Comment by sorgelig** [comment]
Not a default option already.
