### ISSUE TITLE
vibration on button press with dualsense

### ISSUE THREAD

**Issue by JaydeSix** [MiSTer-devel/Main_MiSTer#632]
Using a dualsense (PS5) controller the square (left most) and triangle (top most) buttons will cause the controller to vibrate. Assigning actions to the buttons works but will still cause vibration.

This only happens in the menu core.

Some users on discord have this, others don't. Maybe dualsense firmware version related?

**Comment by sorgelig** [comment]
Some ppl said updating FW fixes vibration. Square and triangle should cause vibration in menu core.

**Comment by JaydeSix** [comment]
If it's suppose to cause vibration it is working as intended. Is there a way to stop this behavior? I prefer to control the menu with Square and X instead of X and Circle.

**Comment by birdybro** [comment]
Wired vs Wireless use makes a difference, as well as the firmware. Wired DualSense without a firmware update will result in the controller not working at all typically, so you should probably update it to rule that out --> https://controller.dl.playstation.net/controller/lang/en/fwupdater.html

If you don't have a windows pc and only linux, this method might work alternatively --> https://linuxgamingcentral.com/posts/how-to-update-dualsense-firmware-on-linux/ (I haven't tested this, it might not work, and on some odd chance could brick your DualSense, you've been warned!!)

Additionally, I've only used Bluetooth 5.0 adapters with my Dualsense, as that's what it's designed for, and maybe a Bluetooth 2.0 adapter might not be as compatible (but it should be the same, just lower performance, higher latency, etc...).

**Comment by JaydeSix** [comment]
> Wired vs Wireless use makes a difference on the dualsense in general, but not sure if it does for vibration, as well as the firmware. Wired DualSense without a firmware update will result in the controller not working at all typically, so you should probably update it to rule that out --> https://controller.dl.playstation.net/controller/lang/en/fwupdater.html
> 
> If you don't have a windows pc and only linux, this method might work alternatively --> https://linuxgamingcentral.com/posts/how-to-update-dualsense-firmware-on-linux/ (I haven't tested this, it might not work, and on some odd chance could brick your DualSense, you've been warned!!)
> 
> Additionally, I've only used Bluetooth 5.0 adapters with my Dualsense, as that's what it's designed for, and maybe a Bluetooth 2.0 adapter might not be as compatible (but it should be the same, just lower performance, higher latency, etc...).

Thank you for the info, the firmware should be up to date on it (using my PS5) and I am using a 5.0 bluetooth adapter, I hear under that and you will lose features like touchpad mouse support.

What I thought was a problem was buttons causing vibration in the menu but sorgelig has said that is intended, so now I'm asking if there is a way to turn it off so I can assign those buttons without them vibrating the controller.

**Comment by sorgelig** [comment]
I've modified the test of vibration. Now you have to hold down L button then press square/triangle for vibration.

**Comment by JaydeSix** [comment]
> I've modified the test of vibration. Now you have to hold down L button then press square/triangle for vibration. It will be in next Main release

Thank you so much, I'll mark this as closed.
