### ISSUE TITLE
Load default data in MRA for the NVRAM

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#637]
Although the MRA can demand for NVRAM support using `<nvram>`, MiSTer firmware doesn't allow to provide a default value for this data. This code will not work:

```
    <nvram index="2" size="128">
        <part>
            02 00 01 00 00 01 01 01 01 00 00 01 00 00 00 02
            81 cd 10 0e 30 fd 81 88 2e 4d c9 53 c9 c9 c9 c9
            4d 20 44 41 20 45 4e 49 4a 20 50 41 4e 41 20 2e
            20 20 55 53 45 50 20 52 41 50 47 4e 4a 20 20 32
            20 20 41 43 43 50 4d 4f 31 20 39 39 2e 30 20 20
            50 20 6f 72 72 67 6d 61 64 65 42 20 20 79 20 20
            20 20 4d 20 73 61 74 61 75 73 75 67 20 20 20 20
            20 20 20 20 68 53 6e 69 68 6f 72 61 2e 61 20 20
        </part>
    </nvram>
```

MiSTer will not send the chunk of data in the MRA file.

And this behaviour is needed for games that require some content loaded in the NVRAM to boot up correctly. Ideally, MiSTer should send the default data if there is no NVRAM file already saved in the SD card. If the SD card holds a file, then it should send the file and not the data.

Could you add support for this to the firmware, please?

Thank you

**Comment by sorgelig** [comment]
What is the purpose of empty tag <part>?

**Comment by jotego** [comment]
Do you mean, what is the purpose of this?

```
    <nvram index="2" size="128"/>
```

This declares the NVRAM usage, but it has no `<part>` tag. It works correctly in getting data saved to the SD card loaded 

In the previous example, there was a `<part>` with content, it wasn't empty. But MiSTer doesn't seem to send that content. It would be useful to provide a default content, because some games won't boot if there's no default value in the NVRAM.

**Comment by sorgelig** [comment]
i mean that preloaded text doesn't require `<part></part>` frame as it already has `<nvram></nvram>` frame. 

Anyway, test this build:
[MiSTer.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/8860435/MiSTer.zip)

**Comment by atrac17** [comment]
I have yet to try this elsewhere, but with CPS2 if an NVRAM file is present
in config it over writes the value provided by the MRA when loading.

**Comment by jotego** [comment]
Sorry, I closed this by mistake.

There are cases where a ROM file exists for the EEPROM in the MAME ROM set (see Super Pang). In these cases the `part` syntax is more flexible as it could refer to either a file or to explicit hex content.

```
    <nvram index="2" size="128">
        <part name="eeprom-spang.bin" crc="deae1291"/>
   </nvram>
```

I think adding the default contents as a `<nvram><part>` tag, following the same syntax as for `<rom>` is the best approach because the syntax is consistent and the download process will not send data twice (as I said [above](https://github.com/MiSTer-devel/Main_MiSTer/issues/637#issuecomment-1151179698))

**Comment by sorgelig** [comment]
As you already pointed out basically it's already implemented and in more generic way in `<rom>` section. So just preload the data as a part with an index same as nvram. If there is saved content, then it will be loaded on top of it. With nvram small sizes it is unnoticeable. I don't see a reason to doubling it.

**Comment by jotego** [comment]
If we keep the dual `<rom>` and `<nvram>` label usages, it is important to guarantee that the `rom` will be executed first, so the `nvram` can overwrite it. That's the current behaviour, so as long as it doesn't change, we are good.

Thanks for the discussion

**Comment by sorgelig** [comment]
Execution sequence depends on xml sequence. So it's up to those who write xml.

**Comment by boogermann** [comment]
> If we keep the dual `<rom>` and `<nvram>` label usages, it is important to guarantee that the `rom` will be executed first, so the `nvram` can overwrite it. That's the current behaviour, so as long as it doesn't change, we are good.
> 
> Thanks for the discussion

@jotego That's how Alan recommends it.
I did a PR  for that over a year ago to address that, so it would work as Sorg mentioned, but he said it was redundant. 
The PR is here: https://github.com/MiSTer-devel/Main_MiSTer/pull/372
