### ISSUE TITLE
OSD: text completely removed when too long

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#639]
A line like in this in the MRA file:

```
        <dip name="World Records" bits="12" ids="Erase on Reset,Dont Erase"/>
```

Will fail to display the first option because:

```
World Records:Erase on Reset
```
is larger than 28 characters. The OSD will only display the option title `World Records:` but the option item will be left blank. The user will be confused about it. I think that truncating the string will be a safer option for the user:

```
World Recors:Erase on Res
```

Didn't the OSD options used to scroll when too long? Maybe it was only file names... Anyway, I understand that the core developer should check that the options look good but a safe fall back behaviour on the firmware side will help too. Please consider changing the behaviour from _not displaying anything_, to _truncating the string_.

**Comment by birdybro** [comment]
This occurs specifically for DIPS I think, I just ran into the same thing a couple days ago and @wickerwaka confirmed it is a bug, since that kind of scrolling does work with other menu items.

**Comment by sorgelig** [comment]
Scrolling of items is not implemented and i don't want to make code more complicated just because of this. Scrolling items won't look good and won't be convenient to navigate. Make shorter items. Debug your core before release to make sure OSD items are fit.

**Comment by birdybro** [comment]
Totally understandable, technical debt can be a real issue of course. Thanks for considering it!

**Comment by jotego** [comment]
I have been able to cut the text in most of my MRA files. Some of them really don't have a meaningful way of trimming the text. Anyway, I'm closing this issue as it is understood and the decision is not to change it.
