### ISSUE TITLE
floating-point refresh rates not supported by calculated video mode lines

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Main_MiSTer#640]
`video_mode=1920,1080,59.7`

The above does not work, because `strtoul` is used to parse `59.7`, which doesn't work.  Also, the `val[2]` passed into `video_calculate_cvt()` is just a `uint32`, even though that function's parameter can accept a `float`.

**Comment by wickerwaka** [comment]
Yeah the mode parameters are all integer right now. Any particular reason you want to be so explicit about the refresh rate instead of letting vsync_adjust set it for you?

**Comment by c0d3h4x0r** [comment]
Yes -- because vsync_adjust doesn't always use refresh rates my TV likes, so I need manual control.

Sent via Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by c0d3h4x0r** [comment]
Any objection to me coding up a fix?

**Comment by wickerwaka** [comment]
I have no objects, but I don't approve PRs.

**Comment by c0d3h4x0r** [comment]
Looks like this was already fixed by somebody else?
