### ISSUE TITLE
calculated video_mode doesn't match the same preset mode

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Main_MiSTer#641]
`video_mode=12` works on my 4K TV to set 1920x1440@60Hz.  The MiSTer stdout shows:

```
Send HDMI parameters:
video: 1920(1920), 48(48), 32(32), 80(80), 1440(1440), 2(2), 4(4), 38(38), -hsync, -vsync
```

`video_mode=1920,1440,60` does not work on the same TV (never achieves picture sync).  The MiSTer stdout shows:

```
Send HDMI parameters:
video: 1920(1920), 48(48), 32(32), 80(80), 1440(1440), 3(3), 4(4), 34(34), -hsync, -vsync
```

Note that `38` != `34` and `2` != `3`.

Shouldn't these two ways of defining the same video mode yield the same numbers and results?

**Comment by wickerwaka** [comment]
They aren't guaranteed to be the same. I don't know what the source of the preset mode timing parameters are and it's not something I would want to modify in order to make them match the calculated modes since it could cause issues (like you have demonstrated). 

What display do you have? I'm surprised that a display that could support this resolution would be so sensitive to this.

**Comment by c0d3h4x0r** [comment]
> The preset video mode timings are hand crafted and aren't following any one particular timing formula.

Why?

>Changing the presets to exactly match CVT timings could have been a breaking change for some users

I'm not suggesting the presets should be changed.  I'm suggesting the custom mode calculations should be corrected/adjusted.

**Comment by wickerwaka** [comment]
> I'm not suggesting the presets should be changed. I'm suggesting the custom mode calculations should be corrected/adjusted.

The custom mode calculations are correct and there is no programmatic adjustment that could be made to make it match all of the preset modes. If you use a modeline generator like the `cvt` command line tool you will get the same timing that MiSTer is using for the calculated mode.

Why does a non-standard work when a standard one doesn't? I don't know, there difference in the signal timing is so small I'm surprised it matters. One thing to try is adding a `+hsync` flag to the video_mode and see if that behaves better.
