### ISSUE TITLE
MGL with AO486 core

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Main_MiSTer#662]
I tried the new feature "setname" of MGL file.
With the core AO486, the VHD mounted seems to be stored on ao486sys.cfg so it doesn't depend of the setname.
In this case we can't have different configuration with setname's different.

Thanks,

**Comment by sorgelig** [comment]
i will see what can i do there

**Comment by sorgelig** [comment]
should be fixed

**Comment by wwark** [comment]
Yes it is working great thank you for the quick fix
![image](https://user-images.githubusercontent.com/469461/179418992-c5ad2b17-b17d-4ed9-834f-771eb460105a.png)
