### ISSUE TITLE
Browse .zip files in as directories in main menu

### ISSUE THREAD

**Issue by wizzomafizzo** [MiSTer-devel/Main_MiSTer#663]
It would be good to have the ability for the main menu to treat a .zip file as a directory under certain conditions. For example, a file called _Stuff.zip full of .mgl files in /media/fat would should up in the root of the menu as a Stuff directory and be browsable as one. Similar to the current functionality of the file picker in cores.

The reason I ask for this is that when you have **a lot** of .mgl files, they will be way larger on disk because of the allocation tables minimum size. An index of all your games can quite easily hit 10GB+ despite only being around 15MB actual size. That size difference can mean a lot when you're really trying to pack an SD card.

**Comment by sorgelig** [comment]
Every good idea can lead to absurd... Making thousands MGL files is how originally useful idea becomes a pain.

**Comment by wizzomafizzo** [comment]
> An idea can lead to absurd... Making thousands MGL files is how originally useful idea becomes a pain.

Can you please humour me then and explain what .mgl are actually for in your opinion? What is your own use case for them?

**Comment by sorgelig** [comment]
For example you play a single game often, so you want to make a shortcut. Or you have several games you often play. Something like that. 
It doesn't mean each of 3000+ NES games should have its own MGL.

**Comment by wizzomafizzo** [comment]
Ok that's fair.

From my and other user's perspective, this thousands of mgls thing comes from having a single menu to seamlessly browse all the games feeling and looking a lot better than the load rom option of each core. It changes the workflow as well, from "browse for an NES game" to "browse for a game" because switching cores breaks up that flow.

You can say "why do you need so many games?" and that is fair criticism. But the fact is many (most?) people do. It also makes the mister a lot more fun when inviting friends to play and mess around with all the shit games.

Combining with a script also means you can dump in game packs without concern and they will be automatically organised and laid out. I have no interest in curating a list of special NES games, I am willing to download a 1GB zip file and throw it on my SD card.

The fact is this request was a nice-to-have, and someone with 2TB worth of games will not care about 10GB of wasted space if they want a full index of mgls. I will drop it if you aren't into it.
