### ISSUE TITLE
Status registry updated after ROM downloads, no before

### ISSUE THREAD

**Issue by spark2k06** [MiSTer-devel/Main_MiSTer#685]
I have put a trace over the status bit[3] that I use to determine the model of a PCXT:

![image](https://user-images.githubusercontent.com/3509674/186406398-d3fdfe94-3da5-4c5a-af0c-c0303c9e0c89.png)

The thing is that I notice that before sending the ROMs, it is always 0, when I have it set to 1 in this example:

![image](https://user-images.githubusercontent.com/3509674/186406899-72b4ffa7-7d35-4743-9f6a-d9172a3ea581.png)

And indeed, this is what this status[3] looks like at 1 when the PCXT core is started, but it's too late... I needed to know this value before, just before starting the download process (ioctl_download):

![image](https://user-images.githubusercontent.com/3509674/186408381-1fba15d6-4b3a-4f0d-92ca-4349f619150c.png)
![image](https://user-images.githubusercontent.com/3509674/186407578-52bdba4a-8f0f-4bda-ba23-5b19883492f9.png)

I need to know this first, because the core loads one ROM or another, depending on the model, and if not, it always loads the first one at startup because status[3] is always 0 at that moment.

**Comment by sorgelig** [comment]
You need to change the logic of core. Your core needs to accept both ROMs regardless the model. Then when model bit gets it value, correct (proloaded) BIOS will be used. 
One important thing: there is so-called soft-reset bit [0] in status. So it's advised to keep core in reset/pause state while [0] is 1. While [0] is 1 all ROMs are loaded and status bits get restored. And when [0] goes to 0, status bits are restored and ROMs are loaded.

**Comment by spark2k06** [comment]
But that forces me to preload the two ROMs in the core and I only need one... when, if I have the bit available before starting the ROM download, I can reserve 64Kb instead of 128Kb, I don't know, it seems like a waste of resources.

**Comment by spark2k06** [comment]
Reviewing the changes that would need to be made in Main, I understand the complexity. I adapt to the requirements of storing both ROMs in the core.

Thank you!
