### ISSUE TITLE
COREsys.cfg items overlapping with FCx feature in OSD menu

### ISSUE THREAD

**Issue by spark2k06** [MiSTer-devel/Main_MiSTer#687]
The items of the FCx feature do not correspond to the applied configuration (OSD display level only):

![FCx](https://user-images.githubusercontent.com/3509674/186583229-6fdbecf8-4b19-4070-a69f-824e931da29c.jpg)

Here you can see filenames that actually correspond to COREsys.cfg elements, in this case they are HDD/FDD images from another section:

![sys_cfg](https://user-images.githubusercontent.com/3509674/186583436-296eb315-3ce6-4297-9513-2d729bba2816.jpg)

**Comment by sorgelig** [comment]
In FC option, the C is a modifier for F option. So FC is still a subset of F and thus shares a common pool of indexes. So make sure you have different indexes. For example FC1 and F1 will use the same index and may conflict (depending on core logic).

**Comment by spark2k06** [comment]
Perhaps I have not made myself clear. The overlap I am referring to (but only at the OSD display level) is between Fx/FCx and Sx. That is, they work well internally and do what they have to do, although they share the numerical value of x, the problem is in the OSD display, that Fx/FCx shows the texts that would correspond to Sx, taken from COREsys.cfg, the visual information should be obtained from the COREf0.cfg, COREf1.cfg, etc... .

**Comment by spark2k06** [comment]
With this fix, this situation can be avoided for the PCXT core:

https://github.com/MiSTer-devel/Main_MiSTer/pull/694

**Comment by spark2k06** [comment]
Pull request accepted.
