### ISSUE TITLE
since Mister_20190318 the define core buttons feature is broken

### ISSUE THREAD

**Issue by theflynn49** [MiSTer-devel/Main_MiSTer#69]
Hello. 
since Mister_20190318 the "define core buttons" feature is broken : with my USB Sony "analog" controller, it does not detect the "LEFT" and "UP" buttons anymore. MiSTer_20190302 is working fine.

some debug that **may** help (when I press and release the UP button then the LEFT one): 
strace -pxxxx -e "trace=!clock_gettime,poll"
read(19, "\237\240\222\\\305\244\r\0\3\0\1\0\0\0\0\0", 16) = 16
ioctl(19, EVIOCGABS(ABS_Y), {**value=0**, minimum=0, ...}) = 0
read(19, "\237\240\222\\\305\244\r\0\0\0\0\0\0\0\0\0", 16) = 16
read(19, "\240\240\222\\\205\243\10\0\3\0\1\0\200\0\0\0", 16) = 16
ioctl(19, EVIOCGABS(ABS_Y), {value=128, minimum=0, ...}) = 0
read(19, "\240\240\222\\\205\243\10\0\0\0\0\0\0\0\0\0", 16) = 16
read(19, "\254\240\222\\\5;\17\0\3\0\0\0\0\0\0\0", 16) = 16
ioctl(19, EVIOCGABS(ABS_X), **{value=0,** minimum=0, ...}) = 0
read(19, "\254\240\222\\\5;\17\0\0\0\0\0\0\0\0\0", 16) = 16
read(19, "\255\240\222\\\304]\4\0\3\0\0\0\200\0\0\0", 16) = 16
ioctl(19, EVIOCGABS(ABS_X), {value=128, minimum=0, ...}) = 0
read(19, "\255\240\222\\\304]\4\0\0\0\0\0\0\0\0\0", 16) = 16

**Comment by sorgelig** [comment]
You need to setup the joystick in Menu core with new MiSTer. Then you may be will need to re-define the buttons in the cores.

**Comment by theflynn49** [comment]
I don't get what you mean. 
Unless I'm wrong  the function that re-define the buttons is what is broken.
Maybe there is something I missed.

**Comment by theflynn49** [comment]
Oh, ok ! I see it now.
I totally missed that, sorry :D 
I close this ticket, my bad.
