### ISSUE TITLE
[FeatureRequest] Add git client binary to Linux MiSTer

### ISSUE THREAD

**Issue by sromeroi** [MiSTer-devel/Main_MiSTer#690]
(Sorry if this is not the right repository to request this).

I miss the "git" client binary into the Linux bundled with MiSTer to update staff (sync config files, update scripts, etc).

Is it possible to include it in future updates?

Thanks

**Comment by dcrespo3d** [comment]
I would like too, to have the git client binary included with the MiSTer linux distribution.

Currently I am copying binaries from a Raspberry Pi 1 and it works perfectly, but it gets deleted on every update and it's a bit of a hassle.

Could it be included in a future update?

Thanks and regards!

**Comment by birdybro** [comment]
I definitely can't speak for sorgelig who runs the project, so I'll just try and add some perspective. Typically the scope and purpose of the MiSTer flavor of the linux binary is to allow the MiSTer to behave as an appliance, sorta like a game console, so it is kept very minimal deliberately. The method of releasing the full Linux binary that is used also requires it to stay very minimal in size due to GitHub file size limits. Do you have a figure on the total size of the Git binary including the prereqs that may need to be added?

**Comment by dcrespo3d** [comment]
I am using git for synchronizing saved games and config files across two MiSTers. I don't just need to download files, I need to upload them and keep them synced and unconflicted. As I use git in may daily work, it's the ideal tool for me.

The total size requirements are around 3 Megabytes. I have managed to get git working with a minimal set of files:
- /usr/bin/git 2 ·····  642 072 bytes
- /usr/lib/libpcre2-8.so.0.10.1 ····  563 040 bytes
- /usr/lib/libpcre2-posix.2.0.3 ···· 9 628 bytes
And some symlinks, such as
libpcre2-8.so.0 -> libpcre2-8.so.0.10.1
libpcre2-posix.2 -> libpcre2-posix.2.0.3

Would that size increase be acceptable?

**Comment by birdybro** [comment]
Ah if it's just for syncs, doesn't rsync already serve this purpose? I do understand the preference to use git though. You could just add the things you need placed in the linux folder that gets wiped out into your own custom DB. Just raising ideas to try and help, not suggesting what is better than the other. :)

**Comment by sorgelig** [comment]
MiSTer linux cannot include everything.. It's already almost hit the limit of compressed linux.img i able to keep in github. git is not the usual utility for MiSTer. You can add it yourself to your own MiSTer as extension.

**Comment by sromeroi** [comment]
> 

I intented to use git client to download (and keep updated) scripts (in /media/fat/Scripts) from github, updating with simple `git pull`'s instead of downloading zips, copying to the SD, etc.

I get the point about the size through. Thanks anyway.

**Comment by birdybro** [comment]
Yup, I think this is a good usecase for a custom downloader DB, that way you can reinstall git and other customizations in the linux folder via downloader, it will download from the custom set of files you have stored somewhere on the internet.

**Comment by dcrespo3d** [comment]
I think I will leave a copy of the git binaries in the /media/fat/Scripts folder, with a script ready for copying the binaries to /usr, and invoke it after each update. Good enough.

Anyway, thanks for your work on this wonderful project :-)

**Comment by sorgelig** [comment]
path variable already points to /media/fat/linux
so you may place binaries there

**Comment by jotego** [comment]
> MiSTer linux cannot include everything.. It's already almost hit the limit of compressed linux.img i able to keep in github. git is not a usual utility for MiSTer. You can add it yourself to your own MiSTer as extension.

I suggest to close this issue as *won't do*
