### ISSUE TITLE
[Feature Request] Add PAL 50Hz to 60Hz conversion for VGA

### ISSUE THREAD

**Issue by Grieverheart** [MiSTer-devel/Main_MiSTer#699]
PAL 50Hz video on a CRT, especially a PVM and depending on the lighting conditions, produces noticeable flicker. It would be nice if there was a toggle for upsampling 50Hz to 60Hz to reduce flicker. Currently, this could be achieved using `vga_scaler=1` and `vsync_adjust=0`, but this is a global setting and means HDMI output will be 240p, which is not very nice if you'd e.g. like to capture a high resolution signal while playing on a 240p monitor.

**Comment by sorgelig** [comment]
Video is produced by core. Main has no control over it. So 50->60 conversion should be done in the core, and obviously it's per-core task. 
As you already pointed out, it's done by using VGA scaler. MiSTer never advertised as dual video output. So you either use HDMI or VGA, not both. Many video settings are depend on it too. So what is good for VGA may be not good for HDMI, and opposite. 
So either your main output is VGA or HDMI.
