### ISSUE TITLE
INI ERROR volumectl: unknown option

### ISSUE THREAD

**Issue by CMR779** [MiSTer-devel/Main_MiSTer#702]
This pops up when I start mister.  I am running the latest version updated with the update_all script.  I've tried setting this with the INI script as well as doing it manually with text editor.  I've tried turning it on and off, but neither does anything.

**Comment by sorgelig** [comment]
just remove volumectl from INI file.
It's not a error but hint that may be INI has wrong option.

**Comment by CMR779** [comment]
Thanks, it worked.  The message is gone.
