### ISSUE TITLE
INI Error

### ISSUE THREAD

**Issue by HiroiSekai** [MiSTer-devel/Main_MiSTer#703]
On a weekly basis, I run the MiSTer Downloader script to see if there are any updates for the cores I play on. I have never had any issue and it has run as expected.

However, today I ran the downloader script, and it seemed to run more commands than usual, running what appeared to be some delete commands that I haven't seen before.

Afterwards, now whenever I boot the MiSTer or any core, I get an error:

1 INI ERROR
VOLUMECTL: UNKNOWN OPTION

I get it as a pop-up, and it doesn't seem to actually affect booting the OS or the games themselves. However, I do stream using the MiSTer and would prefer not to have this error popup constantly if possible. Plus, maybe there's some underlying issue from this I can't immediately see.

Any suggestions on this new error? Thank you.

**Comment by birdybro** [comment]
Remove the line that says "volumectl" from your .ini file. It's unneeded. I submitted a PR referenced just now that will solve the issue if people choose to add this deprecated setting to their Ini with the script in the future.

**Comment by HiroiSekai** [comment]
Perfect, easy fix. Thank you!
