### ISSUE TITLE
(similar to issue #41) Minimig feature request: Provide a way to map two controller buttons to Amiga joystick's UP

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Main_MiSTer#71]
This is similar to issue #41 (which was closed as "Won't Fix"), but with a more specific and compelling usage case in mind.

Most Amiga platforming games use the joystick UP for "jump", which is really annoying when folks today are predominantly using gamepad-style controllers with all kinds of extra action buttons.  In emulators, my strong preference is to map two controller buttons (D-pad UP, and one of the many action buttons) to the Amiga joystick's UP, so that I can have a dedicated jump button for platformers.  But switching over to using my MiSTer is a step backward for usability, because I'm stuck using the D-pad's "up" for jump.

Would it be possible to add a special option, only for the Minimig core, to allow mapping a second controller button to UP?

**Comment by sorgelig** [comment]
You can use "button remap for a game" in OSD. 
In remapping press the new desired key you want to use as UP then press DPAD UP. Then press enter.

**Comment by c0d3h4x0r** [comment]
The notion of "a game" is a little weird for a computer such as Amiga.  If you're only running .adf images, then is each floppy considered to be its own "game"?  How about if you're booting off an .hdf and using WHDLoad?

I definitely want a global setting, not something I have to configure for each and every game.

**Comment by sorgelig** [comment]
It's not strictly per single game. It's just temporary map till you load the other core.

**Comment by c0d3h4x0r** [comment]
There's no way to make it permanent for that core?

**Comment by sorgelig** [comment]
I'm working on improving button assignment where you will be able to assign 2 sets

**Comment by c0d3h4x0r** [comment]
Woo-hoo!  Thank you!

**Comment by sorgelig** [comment]
So, i think it's already solved.
