### ISSUE TITLE
Feature request: Mt32-pi volume and user io 

### ISSUE THREAD

**Issue by malaespera** [MiSTer-devel/Main_MiSTer#717]
Add volume control option for mt 32-pi.
It would be very useful for devices without physical volume controls. 

And an option to choose the primary or secondary user io for the mt32-pi.

Thanks for your amazing work.

**Comment by sorgelig** [comment]
there is no such thing as primary or secondary USER I/O. MiSTer has only one USER I/O

**Comment by brandon-arnold** [comment]
> there is no such thing as primary or secondary USER I/O. MiSTer has only one USER I/O

@sorgelig I don't fault you for being unaware of the d3fmod design's MiSTer Ironclad+ Mini-ITX package, but I've seen a lot of folks buying it on various MiSTer groups. Anyway one of the expansion products, the [Ironclad Internal Mt32-Pi Hat](https://www.d3fmod.com/mt32-pi-hat/), surprisingly requires forked, non-official cores to support the MT32-pi.

> The mt32-pi internal hat uses the secondary user i/o port so, for now, it needs modified cores to work, you can replace your existing cores or have both installed at the same time. Work is been done to include this cores into update_all script to make things easier.

These are the pins that he refers to as "the secondary user i/o port":

![IMG_4588](https://github.com/MiSTer-devel/Main_MiSTer/assets/7827691/03d5357e-b4ba-4a72-bcf9-88b3f96e8406)

And here are his off-piste cores required to get it to run: [MiSTer-Enhanced/Distribution_MiSTer](https://github.com/MiSTer-Enhanced/Distribution_MiSTer)

I don't really care who does and doesn't agree if there is a "secondary user i/o port," but now you know.

**Comment by sorgelig** [comment]
There are many incompatible HW mods. If you gather all of them - you will never make a working thing.

**Comment by brandon-arnold** [comment]
@sorgelig I know that. Anyway I think an MT32-pi volume option is a very legitimate feature request. Since the op seems to have bundled two things into this feature request, should I put it up separately?

**Comment by sorgelig** [comment]
I will check what can i do

**Comment by brandon-arnold** [comment]
> I will check what can i do. MT32-pi is fully controlled by cores and has nothing to do with Main.

Oh, that makes perfect sense. In that case it sounds like the feature requests need to go to these lesser-developed cores. Thank you @sorgelig !
