### ISSUE TITLE
Pressing "Space" to skip defining a button mapping is broken in 20190422

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Main_MiSTer#72]
Now when I press the space bar to skip mapping a button, the OSD assigns the space bar to the button instead of skipping.

**Comment by sorgelig** [comment]
I don't see such behavior.
Note that skip available only for gamepads/joysticks. Keyboards have no skip function, so all buttons must be assigned.
In which assignment you get space map instead of skip?

**Comment by c0d3h4x0r** [comment]
In Minimig core button mappings, during my second pass through it to try to assign only an additional action button to “UP” as secondary.

(sent from my mobile phone)

On Apr 22, 2019, at 2:24 AM, sorgelig <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see such behavior.
Note that skip available only for gamepads/joysticks. Keyboards have no skip function, so all buttons must be assigned.
In which assignment you get space map instead of skip?

**Comment by sorgelig** [comment]
I've just tried and don't see this issue. How you know the space is actually assigned?
There is one catch: The first mapping button (RIGHT) determine which gamepad (or keyboard) you want to use for assignment. So if you start with "Space" button, then it will think you want to assign keys on keyboard. So the first button should be on gamepad. You can define the same buttons for second set instead of skipping, just use other button for "UP" in second set.

**Comment by c0d3h4x0r** [comment]
So that is the problem: I don't want to assign a secondary mapping for RIGHT, so I am pressing "Space" on the keyboard when prompted.  It would help a lot of the first prompt said something like "<Press any key/button on the device you wish to map>" instead of "Press: RIGHT".

**Comment by c0d3h4x0r** [comment]
Oh... but that's not how it works.  You are tying together the mapping of RIGHT with the device identification.  Instead, it should ask for "any key/button on the device" first, then ask to press the mapping for RIGHT as the second step.

**Comment by c0d3h4x0r** [comment]
For Amiga, it would also be very useful to map gamepad buttons to keyboard keys... for example, the "P" key is used to pause most games, so I'd like to be able to map that to a button on my gamepad.  But that's a separate feature request, I know :)

**Comment by c0d3h4x0r** [comment]
Okay, when I repeat all of the same mappings the second time through (rather than trying to skip the ones I don't want to change), and then just push a different button for UP, then it all works.  So I guess this now boils down to just a usability and/or documentation issue.

**Comment by sorgelig** [comment]
Original button definition supported only one button set. And there was no case when you woulddn't want to assign the directional key.
Even with 2 sets, it's not a problem to define the same buttons at least for directional buttons.

Mapping buttons to keyboard is exactly what "Remap button for a game" is made for. I'm not going to make permanent mapping as it's very depending on specific game.

**Comment by sorgelig** [comment]
Original problem is fixed some time ago.
