### ISSUE TITLE
Add driver support for Realtek RTL8811AU

### ISSUE THREAD

**Issue by kolbasky** [MiSTer-devel/Main_MiSTer#725]
I currently own TP-Link Archer T2U v3 wifi dongle, which is not working with mister fpga.
After some googling i figured out, that the chip is RTL8811AU.
And after some more googling, i found that drivers from this repo might fit https://github.com/aircrack-ng/rtl8812au
Unfortunately, i can't build them on my PC, since they require arm64 architecture. And mister itself lacks build tools.

Any assistance will be greatly appreciated :-)

**Comment by birdybro** [comment]
This issue should be closed here and reopened here --> https://github.com/MiSTer-devel/Linux-Kernel_MiSTer

The RTL8811AU is already supported as far as I can tell, but maybe your VendorID and ProductID are not getting picked up correctly.
