### ISSUE TITLE
0bda:c820 Realtek Semiconductor Corp. 802.11ac NIC, rtl8821cu not working properly. 

### ISSUE THREAD

**Issue by AkliDev** [MiSTer-devel/Main_MiSTer#727]
https://misterfpga.org/viewtopic.php?p=66923#p66923

Hi, I have a combo BT/WF5 device that is not working with the wifi script in the scripts directory.
Says "Failed to bring up wlan0."
Bluetooth works fine.  
Believe the chip is RTL8821CU.

When running iwlist wlan0 scan it can find access points. Not sure what is wrong maybe it is a driver issue? 

It seems that WPA authentication is buggy (for 8821cu) or wpasupplicant.conf needs extra configuration for this device.

Any help/guidance will be appreciated.

**Comment by sorgelig** [comment]
1) such issue should be reported in https://github.com/MiSTer-devel/Linux-Kernel_MiSTer repository.
2) generally speaking MiSTer supports very limited list of dongles. You can't buy a random WiFi, and very specially COMBO dongle and expect it to work. It's rather you have to expect it WON'T work if you pick it randomly. And probably it won't be fixed till someone experienced in Linux drivers with same dongle on hand will make it work and submit the patch to Linux repository.
3) before buy wifi/bt dongle go to MiSTer forum (or discord) and ask which dongles are known to be working.

**Comment by AkliDev** [comment]
Alright sorry for posting here. This dongle is the one sold on mr addons. So I thought it would work.

**Comment by sorgelig** [comment]
Then it's better to ask for support from them. Probably dongle works but requires some settings. Since they sell it for MiSTer, they should know how to set it up.
