### ISSUE TITLE
number after the comma on the video_info in the MiSTer.ini

### ISSUE THREAD

**Issue by steffpga** [MiSTer-devel/Main_MiSTer#736]
Hello Sorgelig,
I would like to know if it is possible to have a number with more than one decimal place on the video_info in the mister.ini?
Indeed, the NeoGeo core, for example, displays the value of 59.2hz while the native frequency is 59.186hz.
The analog pocket displays 3 digits after the decimal point and it would be great if this was also the case on our MiSTer.
Thanks in advance

**Comment by sorgelig** [comment]
The size of info line is limited.

**Comment by steffpga** [comment]
Thank you for your responsiveness !
I assume it's a technical limitation...
That's a shame...
Thank you for this beautiful community!

**Comment by jotego** [comment]
@steffpga please close the issue if you're satisfied with the reply. Thanks :-)
