### ISSUE TITLE
Feature request: Config titles in menu

### ISSUE THREAD

**Issue by sbugliarisi** [MiSTer-devel/Main_MiSTer#748]
When alternate config ini files are used and you go into the MiSTer menu to switch between them it shows MAIN, ALT1, ALT2, ALT3. This feature request is to have a mechanism (maybe through the ini file?) that allows the user to specify alternative text. E.g. "CRT" instead of ALT1, or "PVM" instead of ALT2, etc. I realize there isn't much screen real estate so keep the custom name at 4 characters

![MiSTer-menu](https://user-images.githubusercontent.com/42358150/221001681-ac9a32f1-aca5-4a73-a0e1-17d60931b779.png)

**Comment by sorgelig** [comment]
i will think about it

**Comment by birdybro** [comment]
Might be simple with an ini option?

```ini
[MiSTer]
ini_name=MAIN          ; restricted to 4 characters, default is MAIN, ALT1, ALT2, ALT3
```

**Comment by sbugliarisi** [comment]
Thanks sorelig! And thanks birdybro, I think managing this through an ini option would be perfect

**Comment by Toryalai1** [comment]
This is already possible by just changing the name of the different ini files
