### ISSUE TITLE
Wi-Fi issue iin my TP-Link Archer T2U Nano

### ISSUE THREAD

**Issue by JEFFHD3D** [MiSTer-devel/Main_MiSTer#756]
Guys, my dongle has stopped working on the MiSTer and cannot connect to the internet.
I tested it on my PC and it's working.

Please help me to resolve this.

**Comment by gkrzystek** [comment]
update your mister over ethernet, with latest build archer nano t2u driver were updated to working one.

**Comment by JEFFHD3D** [comment]
I'll try.
Thank you!
