### ISSUE TITLE
Proposed autosave SRAM solution

### ISSUE THREAD

**Issue by vertexmachina** [MiSTer-devel/Main_MiSTer#760]
I believe that having SRAM for old consoles save to disk automatically like people are accustomed to from using emulators would improve the user experience for the MiSTer project by quite a lot. Personally, I like to pretend I'm playing the original hardware and needing to open the OSD every so often out of fear of losing progress breaks that illusion.

I've seen discussions about this missing feature on the forums and it seems that the main arguments against implementing it are:

1. Writing to the SD card frequently can wear it out.
2. If it writes to disk whenever the SRAM changes, it can lead to unnecessary writes due to the SRAM on old consoles sometimes being used as extra RAM space.
3. If it writes to disk at some fixed time interval, the timer could fire while the SRAM is currently being updated, leading to a corrupted save file.

In response to 1, users should be able to decide whether they care about that for themselves.

In response to 2, I agree that writing whenever the SRAM changes is not a great idea and likely overly complicated to implement.

That leaves the timer as the best option. Here is my proposed solution to add the feature while mitigating the concerns:

Add a config option that lets users choose the timer interval for autosaves, defaulted to off, with a comment explaining the potential wear of the SD card if the interval is set too low.

To prevent any accidental corruption of the *.sav* file, use a separate *.autosav* file instead when autosaves are enabled. When a game is loaded and the *.sav* file is usually mounted, check the *autosave_interval* config setting and, if non-zero, mount the *.autosav*  file to the save slot instead.

When the autosave timer fires, run the normal saving procedure that runs when the *Save Backup RAM* option is selected in the OSD; because the *.autosav* file was mounted to the save slot, it will be the one that is written to with no extra logic required.

If autosaving is enabled and the user selects *Save Backup RAM* in the OSD, do the normal saving procedure so that the *.autosav* file is updated, make a backup of the *.sav* file, and then overwrite the *.sav* file with the contents of the *.autosav* file. This ensures that if anything ever goes wrong with any of the saving, there will always be a semi-recent backup so that not *all* save data is lost.

There could also be another configuration option added to keep N number of save backups, similar to a rotating log file. When *Save Backup RAM* is selected, it rotates all of the existing backups by one (*.sav2* becomes *.sav3*, *.sav1* becomes *.sav2*, *.sav* becomes *.sav1*) , and then does the *.autosav* to *.sav* copy. This is also just a useful feature to give users extra assurance that they won't ever lose their one and only save file.

This feature is so important to me that I've already implemented it for my own use and it's been working well. I have the autosave interval set to 60 seconds and then whenever I've finished a session I open the OSD and select *Save Backup RAM* to finalize everything and make a backup. That ensures I only need to ever open the OSD once per session.

I would be happy to work with you to get it integrated into the project if you find value in it. I've only been playing console cores (NES, SNES, Genesis) and so it would likely need additional work to ensure it works with the other cores as well.

**Comment by sorgelig** [comment]
Besides listed arguments, there is one most important is missing: corrupted filesystem because MiSTer can be switched off at any time, including the time when .sav file is being written. It was discussed a lot already.

**Comment by vertexmachina** [comment]
The use of a separate *.autosav* file along with the rolling backup system should mitigate that risk.

**Comment by sorgelig** [comment]
You didn't understand the nature of "corrupted filesystem". Corrupted - means catalog or other parts got corrupted, so it has nothing to do with specific sav file.

**Comment by vertexmachina** [comment]
Understood.
