### ISSUE TITLE
Mouse input clamping appears to be incorrect leading to overflows when moving quickly

### ISSUE THREAD

**Issue by garyjsweet** [MiSTer-devel/Main_MiSTer#764]
I have an ultimarc u-trak trackball along with a homemade rotary encoder based spinner. I've been noticing odd behaviour
when the trackball or spinner are moved very quickly. The cursor appears to move backwards briefly, or stalls for a short period
of time. Slow to medium movements worked just fine.

After some debugging I found that the mouse deltas are being incorrectly clamped to -255 to 255 inside user_io_mouse().

Despite the fact that byte-0 of the mouse data contains effective sign bits for the x & y directions (in bits 4 & 5 respectively) the
actual 8-bit delta value is also signed - at least on all the devices I've tested (trackball, spinner, real-mice).

When I clamp from -127 to 127 instead the weird overflow behaviour with fast movements goes away; this makes game play much more predictable in games like missile command for example.

I have a PR ready which I'll push shortly.

**Comment by sorgelig** [comment]
closing this issue as there is discussion in PR already.
