### ISSUE TITLE
All Irem cores - HQ2X scandoubler effect

### ISSUE THREAD

**Issue by TTurbo23** [MiSTer-devel/Main_MiSTer#772]
Request to add HQ2X scandoubler effect to all Irem cores.

**Comment by sorgelig** [comment]
Please open issue in specific core. It has nothing to do with Main.

**Comment by TTurbo23** [comment]
It was the first time I raised an issue and I added it to the wrong one, not being familiar. It was a mistake.

Thanks
Terry.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
