### ISSUE TITLE
Wallpaper-to-config mapping still uses _alt_# after config name update

### ISSUE THREAD

**Issue by prenetic** [MiSTer-devel/Main_MiSTer#778]
Running the latest builds as of this writing. I've got three named MiSTer configurations:

```
MiSTer_HdrV.ini
MiSter_Safe.ini
MiSTer_Strm.ini
```

Previously these would be `MiSTer_alt_1.ini` etc., which would map to `wallpapers_alt_1` and so on. Now that we can create custom names for the configs, it would make sense that the wallpaper folders match against the config label and not the index they're sorted into when being loaded in.

For example, using the `MiSTer_Strm.ini` profile above, the corresponding wallpaper folder should be `wallpapers_Strm` however this does not work currently. Instead I've got to look at which order the configs are loaded in the UI, and then name the wallpaper folder using the old style and corresponding slot (in this case `wallpapers_alt_3`. Any time the order of configs changes, this process needs to be repeated for every profile affected.

**Comment by sorgelig** [comment]
i forgot about that. Will fix it

**Comment by sorgelig** [comment]
fixed
