### ISSUE TITLE
Mister crashes after 1-2 hours game time

### ISSUE THREAD

**Issue by Splendicaindica** [MiSTer-devel/Main_MiSTer#780]
I'm experiencing a recurring issue to where the system crashes after only playing 1-2 hours. It happened while playing super mario bros on nes; it happened while playing chrono trigger on snes. When it crashes, rebooting it brings up the menu just fine - and the menu operates fine; I can load cores -- but none of the games work. They look like they're loading, but I'm ultimately left with just a black screen. 

I can retry an hour later and the thing still won't work, but if I leave it off for like a day or 2 then it'll play just fine again. Is this a problem with the SD card or the board itself you think? Let me know if I should be posting this somewhere else. Thanks.

**Comment by Splendicaindica** [comment]
Just to be clear, after this happens none of the games on any core will work.

**Comment by sorgelig** [comment]
Please ask on mister forum: https://misterfpga.org/
It has nothing to do with bugs, but rather your way of use MiSTer. May be not enough cooling. May be SD card gets too hot and again not enough cooling. It's possible a problem with the board. Or something else...
