### ISSUE TITLE
Support for Thrustmaster Guillemot Force Feedback Racing Wheel in input.cpp

### ISSUE THREAD

**Issue by dnwe** [MiSTer-devel/Main_MiSTer#799]
I saw [setup_wheels](https://github.com/MiSTer-devel/Main_MiSTer/blob/3facf0b3dd39b61b11347adda23b9db3d0da54c0/input.cpp#L4126-L4245) provides some axis mapping for various pre-defined wheels. Please could we add the same for 06f8:0004? The wheel is supported by the built-in `iforce` kernel module and generates events as expected in the serial console, but the wheel cannot be mapped on the input menu as stick tilts, the wheel is just ignored. Please find below the axis information from serial console

[    1.978684] usb 1-1.4: New USB device found, idVendor=06f8, idProduct=0004, bcdDevice= 1.00
[    1.978722] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    1.978758] usb 1-1.4: Product: Guillemot Force Feedback Racing Wheel
[    1.978777] usb 1-1.4: Manufacturer: Guillemot Corp.

![image](https://github.com/MiSTer-devel/Main_MiSTer/assets/8060970/0660bfa2-0835-4323-9900-a48413f60374)

### Wheel

06f8:0004:01 P2 Input event: type=EV_ABS, Axis=8 [-1920...1920], Offset=-2048 
06f8:0004:01 P2 Input event: type=EV_ABS, Axis=8 [-1920...1920], Offset=0 
06f8:0004:01 P2 Input event: type=EV_ABS, Axis=8 [-1920...1920], Offset=2048 

Axis: 8 
Range: -1920...1920 
Center offset: 0 
Full left offset: -2048 
Full right offset: +2048

### Throttle

06f8:0004:01 P2 Input event: type=EV_ABS, Axis=9 [0...255], Offset=0
06f8:0004:01 P2 Input event: type=EV_ABS, Axis=9 [0...255], Offset=255 

Axis: 9
 Range: 0…255
Default offset: 0 
Fully pressed offset: 255 

### Brake

06f8:0004:01 P2 Input event: type=EV_ABS, Axis=10 [0...255], Offset=0
 06f8:0004:01 P2 Input event: type=EV_ABS, Axis=10 [0...255], Offset=255 

Axis: 10 
Range: 0…255
Default offset: 0
 Fully pressed offset: 255

**Comment by dnwe** [comment]
Presumably something like this, but I haven't tested a build yet:
```diff
diff --git a/input.cpp b/input.cpp
index f919f7b..6ac2cf7 100644
--- a/input.cpp
+++ b/input.cpp
@@ -4232,6 +4232,31 @@ static void setup_wheels()
 				}
 			}
 
+			// Guillemot Wheels
+			else if (input[i].vid == 0x06f8)
+			{
+				switch (input[i].pid)
+				{
+				case 0x0004: // Force Feedback Racing Wheel
+					input[i].wh_steer = 8;
+					input[i].wh_accel = 9;
+					input[i].wh_brake = 10;
+					input[i].quirk = QUIRK_WHEEL;
+					break;
+				}
+
+				if (input[i].quirk == QUIRK_WHEEL)
+				{
+					struct input_event ie = {};
+					ie.type = EV_FF;
+					ie.code = FF_AUTOCENTER;
+					ie.value = 0xFFFFUL * cfg.wheel_force / 100;
+					write(pool[i].fd, &ie, sizeof(ie));
+
+					set_wheel_range(i, cfg.wheel_range);
+				}
+			}
+
 			//Namco NeGcon via RetroZord adapter
 			else if (input[i].vid == 0x2341 && input[i].pid == 0x8036 && strstr(input[i].name, "RZordPsWheel"))
 			{
```

**Comment by sorgelig** [comment]
Only those who have such wheel are able to test

**Comment by dnwe** [comment]
Yeah I understand, I will attempt a build and will feedback if it’s successful — just raising the issue to check the general method is expected to need a change like this

**Comment by dnwe** [comment]
@sorgelig I had some time this weekend so I build Main_MiSTer and tested this out. The underlying issue turned out to be that the axis 7 and 8 (which is used for the wheel) were being skipped in the input code as they were commented up as "paddle axis - skip from mapping", so I had to add a `&& input[dev].quirk != QUIRK_WHEEL` check to those to allow the Thrustmaster Guillemot wheel to be mappable in the input menu.

Once I'd done that the wheel could be mapped successfully 


```patch
diff --git a/input.cpp b/input.cpp
index f919f7b..7bcde42 100644
--- a/input.cpp
+++ b/input.cpp
@@ -2558,7 +2558,7 @@ static void input_cb(struct input_event *ev, struct input_absinfo *absinfo, int
 		}
 
 		// paddle axis - skip from mapping
-		if ((ev->type == EV_ABS || ev->type == EV_REL) && (ev->code == 7 || ev->code == 8)) return;
+		if ((ev->type == EV_ABS || ev->type == EV_REL) && (ev->code == 7 || ev->code == 8) && input[dev].quirk != QUIRK_WHEEL) return;
 
 		if (ev->type == EV_KEY && mapping_button>=0 && !osd_event)
 		{
@@ -3167,7 +3167,7 @@ static void input_cb(struct input_event *ev, struct input_absinfo *absinfo, int
 				if (ev->value < absinfo->minimum) value = absinfo->minimum;
 				else if (ev->value > absinfo->maximum) value = absinfo->maximum;
 
-				if (ev->code == 8)
+				if (ev->code == 8 && input[dev].quirk != QUIRK_WHEEL)
 				{
 					if (input[dev].num && input[dev].num <= NUMPLAYERS)
 					{
@@ -4232,6 +4232,31 @@ static void setup_wheels()
 				}
 			}
 
+			// Guillemot Wheels
+			else if (input[i].vid == 0x06f8)
+			{
+				switch (input[i].pid)
+				{
+				case 0x0004: // Force Feedback Racing Wheel
+					input[i].wh_steer = 8;
+					input[i].wh_accel = 9;
+					input[i].wh_brake = 10;
+					input[i].quirk = QUIRK_WHEEL;
+					break;
+				}
+
+				if (input[i].quirk == QUIRK_WHEEL)
+				{
+					struct input_event ie = {};
+					ie.type = EV_FF;
+					ie.code = FF_AUTOCENTER;
+					ie.value = 0xFFFFUL * cfg.wheel_force / 100;
+					write(pool[i].fd, &ie, sizeof(ie));
+
+					set_wheel_range(i, cfg.wheel_range);
+				}
+			}
+
 			//Namco NeGcon via RetroZord adapter
 			else if (input[i].vid == 0x2341 && input[i].pid == 0x8036 && strstr(input[i].name, "RZordPsWheel"))
 			{
```

**Comment by dnwe** [comment]
Using the wheel wheel with the PSX core — when I configure it as “Wheel-Neg-Con” everything works pretty well except the brake and throttle pedals are seemingly axis-inverted, as-in they are both defaulting to fully on and I have to press the brake fully down in order to release the brake and press the accelerator down to reduce my speed

**Comment by dnwe** [comment]
They work fine/correctly in outrun and turbo outrun though

**Comment by dnwe** [comment]
Hmm, but spy hunter has the same problem as PSX. Accelerator pedal behaviour is inverted, have to depress to slow down

**Comment by dnwe** [comment]
I’m a bit confused by the [pedal code](https://github.com/MiSTer-devel/PSX_MiSTer/commit/7bfbe03d525afd343d00d1c0310b28bfa0361f5f) in the PSX core that inverts values of <0:

```c
if (to_integer(joypad.Analog2Y) < 0) then
                                 newPedal := -joypad.Analog2Y;
```

It seems like the code in Main_MiSTer was forcing the values into the range of -127…127?

https://github.com/MiSTer-devel/Main_MiSTer/blob/45e46704a8a21a364b70828bca4c46b6a3d50a8f/input.cpp#L3232

**Comment by sorgelig** [comment]
> It seems like the code in Main_MiSTer was forcing the values into the range of -127…127?

yes, it's normalized all possible range to a standard -127..127.

If your pedals doing opposite directions, then you need to add a correction in Main. But make sure it's only applied to your wheel only.

**Comment by dnwe** [comment]
@sorgelig but from the code it seems like the PSX core is then translating the -127…127 range to be +127…0…+127

**Comment by sorgelig** [comment]
Framework provides standard range while cores convert it to their required ranges.

**Comment by dnwe** [comment]
It seems in reality that pedals always provide 0 to -127 and mine differs because the ev->value for the pedal starts at -127 and goes to 0 on depression. 

So yes I can add an inversion of that range via a config var (or alternatively make it a per-device toggle):

```patch
diff --git a/cfg.cpp b/cfg.cpp
index 1cfb1a8..d9f7121 100644
--- a/cfg.cpp
+++ b/cfg.cpp
@@ -98,6 +98,7 @@ static const ini_var_t ini_vars[] =
 	{ "RUMBLE", (void *)(&(cfg.rumble)), UINT8, 0, 1},
 	{ "WHEEL_FORCE", (void*)(&(cfg.wheel_force)), UINT8, 0, 100 },
 	{ "WHEEL_RANGE", (void*)(&(cfg.wheel_range)), UINT16, 0, 1000 },
+	{ "WHEEL_PEDAL_INVERT", (void *)(&(cfg.wheel_pedal_invert)), UINT8, 0, 1},
 	{ "HDMI_GAME_MODE", (void *)(&(cfg.hdmi_game_mode)), UINT8, 0, 1},
 	{ "VRR_MODE", (void *)(&(cfg.vrr_mode)), UINT8, 0, 3},
 	{ "VRR_MIN_FRAMERATE", (void *)(&(cfg.vrr_min_framerate)), UINT8, 0, 255},
diff --git a/cfg.h b/cfg.h
index c06aa06..27f7019 100644
--- a/cfg.h
+++ b/cfg.h
@@ -73,6 +73,7 @@ typedef struct {
 	uint8_t rumble;
 	uint8_t wheel_force;
 	uint16_t wheel_range;
+	uint8_t wheel_pedal_invert;
 	uint8_t hdmi_game_mode;
 	uint8_t vrr_mode;
 	uint8_t vrr_min_framerate;
diff --git a/input.cpp b/input.cpp
index f919f7b..9ee457c 100644
--- a/input.cpp
+++ b/input.cpp
@@ -3230,6 +3230,10 @@ static void input_cb(struct input_event *ev, struct input_absinfo *absinfo, int
 					if (input[dev].quirk == QUIRK_WHEEL)
 					{
 						int wh_value = ((127 * (ev->value - absinfo->minimum)) / (absinfo->maximum - absinfo->minimum)) - 127;
+						if (cfg.wheel_pedal_invert > 0) {
+							// if cfg is set to invert pedal values range
+							wh_value = ~(wh_value + 127);
+						}
 
 						if (ev->code == input[dev].wh_steer)
 						{
```

And indeed if I make this change then both Spy Hunter and the PSX core games (Gran Turismo, Need for Speed etc.) work correctly now.

However, as previously mentioned, Outrun (and Turbo Outrun) both work correctly with and without this inversion change, so it seems like that core is already handling the appropriate complementing on its own? [jtoutrun_main.v#L314](https://github.com/jotego/jtcores/blob/7cb672267154064bbaf587839077d2568d17415d/cores/outrun/hdl/jtoutrun_main.v#L314)

**Comment by sorgelig** [comment]
Every wheel model is added in code, so INI option is unnecessary. Correct range can be made inside the specific wheel support.

**Comment by jsmolina** [comment]
@dnwe does the PSX Gran turismo is too sensitive for you? 
you said you configured as "Wheel-Neg-Con", but turning left or right is too sensitive and I'm like driving drunk 😄

**Comment by dnwe** [comment]
@jsmolina you'll want to experiment with `wheel_range` in your MiSTer.ini file and you can also use the NegCon tuning in-game where that exists — from memory I think I have something like:
```
wheel_force=75
wheel_range=125
```

**Comment by Pasha-74** [comment]
@dnwe Hi! I have a Thrustmaster Guillemot Force Feedback Racing Wheel, I can connect/run it on Windows 10?

**Comment by sonik-br** [comment]
Hi @dnwe,
Not exactly related to mister... But I'm trying to understand the iforce protocol and devices so I can emulate one (mostly to play some super old games with FFB)
Do you still have the device? If so, could you dump it's usb descriptors (including HID) and share?

**Comment by dnwe** [comment]
Sure, `sudo lsusb -vd 06f8:0004` output is:
https://gist.github.com/dnwe/67ecc31df1221fbaade844f15d67bb0a

**Comment by jsmolina** [comment]
@dnwe you might be interested, as I ported (AI helped) the linux driver to windows:
https://github.com/jsmolina/guillemot-force-feedback-wheel-driver-port/blob/main/README.md
