### ISSUE TITLE
HDMI ARC issues

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/Main_MiSTer#80]
**NOTE:** This may possibly be a hardware bug with the DE10-Nano. However, I believe this needs to be documented somewhere for the MiSTer community to see if others are having the issue and discuss if there is a possible resolution (even if it ends up requiring a hardware modification).

**My Setup:** So in my main setup my HDTV is connected to an audio receiver via HDMI which uses ARC (audio return channel) to pass audio from the TV to the receiver, as well as let me control the receiver for things such as adjusting the volume via the TV remote. This is a standard feature of HDMI since version 1.4 (if your TV and receiver support it).

**The Issue:** When the MiSTer (DE10-Nano) is connected to my TV and powered off, HDMI ARC does not function at all for anything. This means any audio from the TV or devices connected to the TV is not passed to the receiver, and the TV cannot control the receiver (adjust volume, power receiver off). Once the DE10-Nano is powered on, ARC will start working again but the behavior is sometimes inconsistent. Audio will start working, but sometimes the control functions (volume adjustment) won't work. Unplugging the HDMI cable from the DE10-Nano 'fixes' the problem.

**Troubleshooting Performed:** I removed all cables (even power) from the MiSTer except HDMI, and the issue was still present. I also removed the IO board and SDRAM board, but the issue was still present. I could plug the HDMI cable back in afterwards and audio on ARC would continue working, but once I power cycle the TV the issue would return if the HDMI cable is connected to the DE10-Nano. Enable DVI mode on MiSTer didn't seem to help either (which makes sense since the issue is present when the DE10-Nano is powered off). I tried different HDMI cables between the TV and receiver, and between the TV and MiSTer. It also behaved the same on multiple HDMI ports and even on a HDMI switch connected to the TV (even when the switch was powered off).

HDMI pin 14 is responsible for ARC. I've heard some devices can cause issues with ARC if pin 14 is connected to ground. I checked HDMI pin 14 on the DE10-Nano with a multi-meter and it doesn't appear to be connected to ground.

**Anyone Else?** Does anyone else have this issue with their DE10-Nano/MiSTer when connecting it to a HDTV that also has the TV connected to a receiver via HDMI with ARC? I realize connecting the MiSTer's HDMI directly to the receiver would probably be a work-around, but all the HDMI ports on my receiver are full (and some devices have to be directly connected to the receiver as the TV doesn't pass all surround sound formats to the receiver via ARC).

**Comment by sorgelig** [comment]
It's not related to MiSTer project. It's DE10-nano HW. Simple treat it as HDMI 1.3 or whatever lower version. It's impossible to fix it from software side.
Solution is found on forum - use special HDMI pass-through adapter which disconnects the pin in question, so at least CEC start to work.

Since it's not a MiSTer issue, i close it. You can discuss about it on the forum to get more attention and find more workarounds.
