### ISSUE TITLE
CD audio does not work with CHD files, but works with cue/bin/iso

### ISSUE THREAD

**Issue by limi** [MiSTer-devel/Main_MiSTer#805]
First off, thank you very much to @zakk4223 and paulb-nl for making CDDA support happen In the Amiga and ao486 cores! It works great, and lets us get an early version of CD32 support available.

CDDA audio works great if you use cue/bin or cue/iso files, but not CHD files. Other CD cores like MegaCD and TurboGrafx cores work with CHD and produce CD audio.

Steps to reproduce:

1. Load Super Stardust in bin/cue format for CD32 on Minimig, it has CD audio.
2. Convert that same files to CHD using `chdman`, and load it on the Minimig core, there is no audio.

**Comment by zakk4223** [comment]
Super stardust has CD audio for me even when used as a CHD. I did like 90% of the development with an audio cd converted to chd (I never want to listen to Information Society again).

What version of chdman are you using to convert?

**Comment by limi** [comment]
Oh, that's great to hear that it's supposed to work! May be operator error, then — will try a few other disc images and see if I can get it working.

I'm using `chdman 0.257`, the latest available in the Homebrew package manager, and I have successfully used it with other CD-based cores in the past.

>  (I never want to listen to Information Society again)

😆

Thanks for the quick feedback, I will do some more digging and close the issue if I get it working.

**Comment by limi** [comment]
OK, I have no idea what happened there. I literally ran the same command again, on the same computer, with the same version of `chdman`, and the new CHD image works. The previous one still doesn't. 🤷‍♂️

Sorry about that!
