### ISSUE TITLE
Keyboard Remappings Ignored In Controller Mapping Sub Menu

### ISSUE THREAD

**Issue by RumblePen** [MiSTer-devel/Main_MiSTer#816]
I remapped every key I would need from a full-sized keyboard to a mini wireless numpad. I am unable to leave buttons undefined by pressing Space, or end by pressing Enter with my numpad. I have to lug out my big keyboard every time I setup a new controller. I have confirmed in InputTest's advanced screen that the same keyboard codes are mapped to the numpad.

**Comment by sorgelig** [comment]
It's unclear what kind of remapping you are doing. Is it in Menu or other core?

**Comment by RumblePen** [comment]
In the main mister menu.

**Comment by sorgelig** [comment]
1) There is no such thing as undefined in that mapping. So you just press the keys you want to change. If you didn't change some key then it will act as-is.
2) "ESC" if you want to clear the map. "Enter" if you want to finish. You need to press them in first part of mapping.

I've checked, and didn't find any problem. I've also added improvements in mapping dialog.

**Comment by RumblePen** [comment]
the problem isnt with the keyboard remapping, its that the remapped keys dont work in the controller setup menu. when setting up a controller you can hit Space to skip Joystick Tilt Right, Mouse Click Right, etc. well I have Space remapped correctly to my little wireless numpad, but pressing Space on my numpad does nothing.

**Comment by birdybro** [comment]
That input defining ignores your prior remapping. This is probably a good thing because what happens if you forget where you remapped your input for space? Also the menu would be misleading since "space" wouldn't be space on the keyboard anymore etc...

**Comment by RumblePen** [comment]
we are in a menu no longer mapping keyboards. I am setting up a snes controller, for example, defining up,down, A, B, etc. when I am asked for an irrelevant input, or something I don't care to define, and need to press Space to skip to the next input, pressing Space on my little numpad does nothing and I am stuck in the gamepad setup dialog until I get out another keyboard and press Space, even though both the little numpad's key (that has had Space remapped to it) is sending out the same code as the Keyboard's space, as confirmed in InputTest's Advanced screen.

**Comment by sorgelig** [comment]
i see where is the problem. You are trying to use non-real space and esc keys in mapping menu. Key remapping is basically for cores, not for OSD. I need to check if it possible to make it system wide without loops

**Comment by RumblePen** [comment]
If you are unable to do this, could you maybe add a timeout delay to automatically skip to the next step in the gamepad mapping menu, effectively automatically pressing Space after 3-5 seconds?

**Comment by sorgelig** [comment]
Forgot to mention. In new Main release key remap is system wide now. So it should work.

**Comment by RumblePen** [comment]
Cool, thanks!
