### ISSUE TITLE
Cold Reboot Disables USB OTG Hub

### ISSUE THREAD

**Issue by RumblePen** [MiSTer-devel/Main_MiSTer#817]
Whenever I do a cold reboot, everything plugged into my USB hub isn't recognized. I have to power on/off the mister to get everything back to normal. This has never happened powering on the mister or doing a regular reboot.

**Comment by sorgelig** [comment]
de10-nano has buggy USB hub controller, so nothing can be done here from software side. Time after time Linux driver gets updated but so far no much help from it.
You can try to re-arrange USB devices on ports - sometimes it helps. Also official MiSTer USB hub has less such problems then other hubs.

It has nothing to do with Main, so i close this issue.
