### ISSUE TITLE
Bug: Odd input behaviour when assigning multiple inputs to a single button

### ISSUE THREAD

**Issue by bc-bytes** [MiSTer-devel/Main_MiSTer#824]
I have noticed some odd behaviour with inputs on MiSTer when assigning multiple inputs to a single button. Consider these two scenarios:

R-Type
A = shot, B = fire pod, C = A (set C to autofire = 32ms). The goal of this configuration is to allow for autofire of the shot (hold C) and allow for shot to be charged when holding A. Keep C held down then switch to holding A to charge beam. Notice that A does not start charging the beam. The only way this will work is if you deliberately introduce a slight delay when physically switching between C and A, or A and C. At first I though this was perhaps an issue with autofire. But, I just picked up on something similar in Rastan Saga, that does not involve autofire (see below).

Rastan Saga
A = slash, B = jump, C = UP + B. Use C to jump onto a rope (to do a bigger jump) while up is pressed. Notice that even though up was help the whole time, your character does not continue to move up the rope. Much like the issue I describe with R-Type, you can't move up the rope unless you release all buttons / directions then press up again. It's only C that causes this, if you do a big jump normally (hold UP + B) you continue to travel up the rope as normal.

I tested these exact scenarios on MAME, and was not able to reproduce these issues. I am using an arcade stick that has a Brook Universal board in it, and used the same stick on both MiSTer and MAME.

The ability to combine inputs is extremely useful, so hope that it can be fixed to align with how it works in MAME.

**Comment by deepthaw** [comment]
I think this depends on how the behavior of press/release of multiple copies of the same button is defined.

I believe (but may be wrong) that if a controller was wired to have two copies of the same button, it would act the way you describe and the way MAME functions. The button being held would keep the circuit closed and prevent the other button from being able to look like the button was released.

A solution would be to OR the state of each physical button which is assigned as a primary or alternate mapping for a core button and send that result to the FPGA. I’m testing a fix I wrote that takes that approach and will submit it as a PR once I’m happy with it. It’s presently working with both hardware autofire and MiSTer’s built-in autofire in R-Type and I’ll test it in Rastan next.
