### ISSUE TITLE
Bug: 8BitDo N64 Mod Kit by the wire does not work two C buttons the up and the left

### ISSUE THREAD

**Issue by odiaboeeu** [MiSTer-devel/Main_MiSTer#826]
Hi Sorg

Forgive me for opening this issue here, I don't know it's the right place.

For some reason 8BitDo N64 Mod Kit using by wire does not work two buttons C the up and the left, all other buttons work normally.

n64 rumble function also does not work :(

the mod uses dinput only, I don't know if that would be the problem.

Another thing, it has been a long time since I used BT and now I was trying to use it recognizes the controls, but when it will start any Core the mister freezes and to be able to use has to synchronize the control after the core is started.

I have CRS 4.0 I don't know when it started behaving like this, so I don't know if it's a problem in it or if I'll need to buy another one. On Windows it works normally.

NOTE: Doing the procedure I mentioned in using the BT controller after starting the core all the buttons work  using the 8BitDo N64 Mod Kit.

Thanks for your work!

**Comment by odiaboeeu** [comment]
Maybe that's the problem? The C up button is Z rotation and the left C button is the Z axis both in the negative position and the C to the right is the positive Z axis, and the C down is the positive rotation.

Photo taken from the controller in Windows:

<img width="311" alt="Captura de tela 2023-09-25 203656" src="https://github.com/MiSTer-devel/Main_MiSTer/assets/55262527/1c0884e5-9e59-4445-b169-16d435ba1b2d">

**Comment by sorgelig** [comment]
if joystick have very non-standard codes/axis then it may not work properly on MiSTer

**Comment by odiaboeeu** [comment]
Stranger is that in bt works normal all buttons and only on the wire is so, I'll buy a new bt this time one of tp link

**Comment by sorgelig** [comment]
I know some joysticks work completely different depending if it BT or wire connection.

**Comment by odiaboeeu** [comment]
Well I'll close the issue. Once again thank for your work Sorg 🙏
