### ISSUE TITLE
N64: can't turn left/right on a xbox-like generic controller

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/Main_MiSTer#829]
I do have this pad (Tronsmart mars g01)
<img width="350" alt="image" src="https://github.com/MiSTer-devel/Main_MiSTer/assets/447481/cbac1650-8f0a-438c-9133-f53d4352addd">

It works perfectly in PSX core. 
In Main menu I am requested to move Stick0, Stick1 and Digital, althought the ascii art draw shows only digital controls, like this:
<img width="281" alt="image" src="https://github.com/MiSTer-devel/Main_MiSTer/assets/447481/3237a6ba-f8da-4d60-82a0-93fff5efaac1">

When on N64 core, I try to configure it and I am able to select buttons for left/right/up/down with ANY of analogs and ANY of the digitals. Same for C left, C right, C up, C down, any digital or analog is ok.

BUT, ingame, sometimes I can go up/down but NEVER left or right. C left/... will work perfectly with whatever I configured (analog0, analog1, or digital).

it might be related to this fix? https://github.com/MiSTer-devel/Main_MiSTer/pull/828

**Comment by jsmolina** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/assets/447481/4a0933c8-08b2-495b-a7f0-eeebd851d618

this is a video of n64 controller tester rom

**Comment by MikeS11** [comment]
Do you fully setup the controller in main? If you cant use the analog stick left/right or down/up, thats typically a symptom of not setting up the controller in main first correctly. Its a very easy mistake to make. E.g. anytime it asks you to tilt right or down on an analog stick, make sure you follow it.

**Comment by jsmolina** [comment]
yep you were right, I had to skip Mouse part by pressing space or it didn't configured it correctly.

**Comment by Sawtaytoes** [comment]
This needs to be documented somewhere. I've been hours searching, asking AI, whatever, but I didn't realize "Menu: OK" doesn't mean press "OK", it means press the "select menu item" button.
