### ISSUE TITLE
wiki add-ons sdram shows only half image

### ISSUE THREAD

**Issue by goofyseeker311** [MiSTer-devel/Main_MiSTer#848]
somehow the wiki addons sdram vertical/horizontal etc sdram image is cut half off.

**Comment by sorgelig** [comment]
Hmm... I cannot find the problem.
Can you post the link? Or may be screenshot.
Probably it's something with your browser settings

**Comment by goofyseeker311** [comment]
maybe, using microsoft edge on win11.

![68747470733a2f](https://github.com/MiSTer-devel/Main_MiSTer/assets/19920254/e74cc8b4-74d3-42d4-931a-f937c1f703da)

**Comment by sorgelig** [comment]
i've rechecked with different browsers - no problem with that pic.
May be try to clear the cache.

**Comment by goofyseeker311** [comment]
ctrl-f5 does not do anything, maybe some cdn has corrupted data.

**Comment by sorgelig** [comment]
Closed as not an issue.

**Comment by sorgelig** [comment]
I believe it's something to do with caching server. I can't control it from my side.
