### ISSUE TITLE
CSR8510 Bluetooth Controller Support is broken with full size framebuffer activated

### ISSUE THREAD

**Issue by polyh3dron** [MiSTer-devel/Main_MiSTer#85]
1. Connect CSR8510 Bluetooth Dongle to MiSTer
2. Update to current Linux and MiSTer with current .INI from this repo (v0527)
3. Pair Bluetooth Controller and set it up
4. Controller will work fine with default .INI settings
5. Modify MiSTer.INI to make fb_size=1 (to activate full size framebuffer)
6. Reboot
7. Turn on bluetooth controller and navigate the menus for about a minute or so. Expected behavior would be for it to continue working.
8.Bluetooth controller will stop responding, sometimes with the last input being held down. The controller will no longer work until a reboot.
9. Changing fb_size back to 0 will fix the issue, but framebuffer functionality will no longer be active.

**Comment by polyh3dron** [comment]
Swap full size framebuffer activation with composite sync activation, and similar results will show up with bluetooth controller support.

**Comment by polyh3dron** [comment]
inadvertent close.

**Comment by sorgelig** [comment]
What menus you talking about? Linux menus like ini settings? Or OSD menu?
What is the HDMI resolution?

**Comment by sorgelig** [comment]
Not confirmed. User specific HW setup, some baggy USB device.
