### ISSUE TITLE
how is md5 calculated

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#851]
I am trying to add the md5 sum to a single file transfer:

```
    <rom index="17" zip="myfile.zip" md5="54bbe4c4caa4cf40d17c50fac313bd5f">
        <part name="myfile.bin" crc="95a2afcc"/>
    </rom>
```

But the number calculated by MiSTer for md5 does not match my calculation. I apply the algorithm to the raw file (myfile.bin) not the zip file. I have tried swapping the byte order just in case this is a low/high endian thing, but still the numbers produced by MiSTer are different. 

What does MiSTer use to calculate the number? I am assuming each `<rom>` block has its independent md5 value, is that so?

**Comment by sorgelig** [comment]
to get it simple, open console log and there you will see a calculated value which later you can insert in your xml file.
But since you already has CRC, you may use md5="none". CRC should be enough

**Comment by jotego** [comment]
The thing is that the CRC value is treated differently. If the md5 fails, the user gets a message. But if the CRC is not matched, the user does not get a message.

I would like the users to get the message.

**Comment by sorgelig** [comment]
then get it from debug console

**Comment by jotego** [comment]
The problem with that is that I handle about 1,000 MRA files so I need an automated workflow. I need to generate the md5 number the way MiSTer does automatically.

**Comment by sorgelig** [comment]
Source code is available. md5 lib is called from `mra_loader.cpp`, so whole logic is there.

**Comment by wickerwaka** [comment]
The main "gotcha" I see is that a file will be re-read and the md5 updated based on the entire contents of the file for each instance of a `map`. Does the md5 match in the most basic cases?

**Comment by jotego** [comment]
> The main "gotcha" I see is that a file will be re-read and the md5 updated based on the entire contents of the file for each instance of a `map`. Does the md5 match in the most basic cases?

The md5 does not match for the case of a single file with no interleave. I should look at the file pointed by sorgelig to find out where it is messed up, because I think it is, at least conceptually.

**Comment by jotego** [comment]
I will close this one as it is similar to #741, which is mine too. I'll try to look for help to get a better implementation on the MiSTer firmware, addressing #422 too
