### ISSUE TITLE
HDMI orientation and custom mode for flipped resolution display

### ISSUE THREAD

**Issue by sreuter** [MiSTer-devel/Main_MiSTer#86]
Hi there,

I'm trying to get a Waveshare HDMI display working with the MiSTer. As the h/w resolutions are pretty much inverted, the 1080p@60 does mostly show garbage and I can see that the display is also rotated.

Waveshare documented their recommended settings for the RaspberryPi (`hdmi_timings=1080 1 26 4 50 1920 1 8 2 6 0 0 0 60 0 135580000 3`) [here](https://www.waveshare.com/w/upload/b/be/5.5inch_HDMI_AMOLED_User_Manual_EN.pdf) but I wasn't able to successfully translate this to a custom MiSTer video_mode. Even if I would, I assume it would still need to change hdmi orientation somehow, which doesn't seem support at this point?

Any help/input on this is highly appreciated!

**Comment by sorgelig** [comment]
Rotation is not supported and probably never will as it very resource hungry feature. Especially if you want to display 1920x1080 resolution. For rotation, it will require to read the memory in non-sequential order like one word then skip 7KB and then next word, and so on. It won't reach required pixel rate and will eat the whole DDR3 bandwidth. 
Buy a display with correct orientation.

**Comment by sreuter** [comment]
Thanks for the swift reply! This unfortunately throws me back quite a bit, as I was working with a friend on a handheld case (similar to the Switch design, with display, speaker, etc.) for the MiSTer, and finding a compact FULL HD AMOLED including controller was not. I understand it's not an easy thing to pull off tho, so I'll keep searching for another display that fits the purpose.

**Comment by sorgelig** [comment]
AMOLED is really a bad choice for gaming device.
Games have many static pictures which will burn out the pixels (blue especially).
You need a traditional matte IPS display for the best experience.

**Comment by smokku** [comment]
My two 7+ year old PS Vitas, with no burnt AMOLED pixels, would like to discuss that thesis. ;-)

**Comment by sorgelig** [comment]
My 10+ experience of AMOLED on Samsung phones shows this problem. 
Even though i don't use phone much per day i see see darkened spots on monotonic blue screen.

Even from your screen datasheet:
> However, it is easy to face burn-in problem if displaying same content for long time. As we test, the AMOLED cannot be restored if it display same static image for 168 hours because of burn-in problem.In this case, we recommend you to set screen saver and do not let the AMOLED display same staticimage for long time（cannot longer than 1h）

so you play some game 1 hour which uses some static bar displaying the energy, lives, scores, etc and voila - you've got burned spot.

**Comment by sorgelig** [comment]
It's not that AMOLED cannot be used in gaming devices. It's just not rational. For example you can use PS Vita as a hammer, but will it be rational? Probably no.
Today's IPS screens have pretty much close to AMOLED characteristics. AMOLEDs also have after-light traces. So, for example Samsung UI avoid high contrast white/black move. So they use some dark gray in UI to avoid smearing effect while scrolling. 
All-in-all AMOLED is not for gaming. It's good for movies.
