### ISSUE TITLE
PSX Core [PSX_20230503] - Games on External Issue

### ISSUE THREAD

**Issue by ransom1122** [MiSTer-devel/Main_MiSTer#861]
Hi,

It seems when external hdd is plugged in mister and you turn on your mister. No PSX games work from wither internal or external. It just black screens..

It seems (Well at my end at least) when ext hdd is plugged in when the mister is turned on, psx games wont boot
The way we got it to work was to boot the game off internal and have any external hdds unplugged.

If you want to boot the game or any other psx games off external (Well at my end at least)..

1. Boot Mister with ext hdd unplugged
2. Launch any PSX game off internal
3. after game is loaded plug external hdd in mister
4. "only then" Launch any PSX game off external

The Ext HDD I am using is plugged into a powered hub, and I have no issues with this hub or ext hdd with other cores...

I am at a loss why this is happening, ive done multiple tests and it behaves the same way, The core never had this problem from what I recall in the past...

**Comment by ransom1122** [comment]
Fixed my own issue, to play games off external hdd you must additional dump all your psx bios roms onto your external hdd as well as your internal, dumping them here fixes my issue
/media/usb0/games/PSX

**Comment by sorgelig** [comment]
For better experience use only one location per specific core. So either internal or external, not both.
