### ISSUE TITLE
Launching PS1 game with setname defined in an MGL causes disc to not be loaded

### ISSUE THREAD

**Issue by RGarciaLago** [MiSTer-devel/Main_MiSTer#864]
Launching a PS1 game with an MGL that uses the `<setname>` command causes the disc to not load; booting into the PS1 bios instead. The example below demonstrates the issue and if you remove `<setname>` from that MGL the game loads without issue. As a comparison the TG16 core can load a game with an MGL that has `<setname>` defined without issue.

```
<mistergamedescription>
	<rbf>_Console/PSX</rbf>
	<setname>PSX_LightGun</setname>
	<file delay="1" type="s" index="1" path="../../../../media/fat/games/PSX/Light-gun/Time Crisis/Time Crisis (USA).chd"/>
</mistergamedescription>
```

**Comment by sorgelig** [comment]
Once you set <setname>, core start to look for CD and BIOS files in games/<setname>
Although you provide a path for CD, you use relative path which starts from non-existing folder (media/fat/games/PSX_LightGun) and eventually failed.

Try absolute path 	`<file delay="1" type="s" index="1" path="/media/fat/games/PSX/Light-gun/Time Crisis/Time Crisis (USA).chd"/>`

**Comment by RGarciaLago** [comment]
@sorgelig thank you, that resolved the issue! Apologies for this being user error, I'll close the issue.

Interestingly, all my MGL files are setup with a nonexistent relative path but strangely they all worked until using `setname` with the PSX core. I'll get to work correcting that issue on my end.
