### ISSUE TITLE
High Score Save in core menu (alt+F12)

### ISSUE THREAD

**Issue by Bandmo** [MiSTer-devel/Main_MiSTer#878]
I have a mister arcade set up in the middle school where I teach. The kids love to show off their high scores. I would like to have the high scores save once the cores menu is opened with alt+f12 as well as the main osd menu.

I have a button on my cabinet dedicated to getting into the core menu for game selection so kids can’t access the settings or scripts in the main menu.

**Comment by sorgelig** [comment]
Main is unaware about highscores of specific arcade. Highscore save is made inside the core, thus you need to contact the authors of cores where highscore need to be saved (saved in specific time).
