### ISSUE TITLE
USB device (re-)connection issue

### ISSUE THREAD

**Issue by goofyseeker311** [MiSTer-devel/Main_MiSTer#881]
I wonder if this is a de10-nano board feature/issue or a mister issue.

The usb-devices dont connect sometimes very often when you unplug a keyboard and/or mouse using otg usb-cable with or without a usb-hub. Sometimes the devices dont get recognized at all and dont turn on even with full power plug off restart. Sometimes only putting keyboard AND a mouse will get both recognized and turned on, sometimes only with the keyboard the keyboard will not get turned on at all.

It's somewhat random when the de10 nano decides to accept an usb-device, but usually it recognizes all devices on first power-off boot, then after something is disconnected it will not get recognized when plugged back in, no matter how many times trying to reconnect.

The keyboard is a typical logitech device (low power assumed) and mouse is a high end laser optical rgb device (higher power assumed).

**Comment by sorgelig** [comment]
USB on Cyclone V chips is kind of buggy. It may not work with some USB hubs. It may be picky with specific devices plugged to specific USB hub ports. Basically official MiSTer USB hub is fine while other USB hubs might have less success. You may try to change/swap ports of devices on USB hub.

**Comment by goofyseeker311** [comment]
my otg-cable has only one usb-a socket and thats chained to a usb-hub.

anyways, why does hdmi-audio source get lost after a boot (to a bmd converted device).
video come's in nicely.

**Comment by goofyseeker311** [comment]
Its most likely a power delivery issue, because sometimes the usb-hub does not even have the power led turned on.

**Comment by sorgelig** [comment]
Don't draw the power from USB connector of DE10-nano. It's weak. So you need powered USB hub. This particular issue is not present on official MiSTer USB hub board.
