### ISSUE TITLE
Proposal: add disable_autofire to MiSTer.ini

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/Main_MiSTer#89]
Hi!

Some controllers/adapters lacking the HOME/MENU button, but providing combos for it (like START + SELECT), have trouble to get the menu to show up. Instead we get auto-fire enabled to either SELECT or START.

My proposal is to add a disable_autofire (defaults to 0) option to MiSTer.ini that will disable auto-fire and make those controllers having the HOME button key combo to work fine (at the expense of losing auto-fire).

Let me know if that's something you think it's fair so I can implement, test and open a PR.

Cheers!

**Comment by bootsector** [comment]
Thanks for the feedback!

Yeah, a slightly different way to activate auto-fire like, for example, having LEFT + FIRE BUTTON + MENU instead of only FIRE BUTTON + MENU would work as well in my use case.

Thanks for looking at this!

**Comment by sorgelig** [comment]
i will handle it.

**Comment by sorgelig** [comment]
Implemented without needing this option.
