### ISSUE TITLE
Feature Request: Enhanced patch support

### ISSUE THREAD

**Issue by deepthaw** [MiSTer-devel/Main_MiSTer#896]
I've started maintaining a fork of the Arcade Offsets repository and have been thinking about ways to improve patch support within MiSTer.

MRAs can include patches, but this is presently limited to a string of data written to a given offset. Complex romhacks can create extremely large MRA files and also run into issues that could make them difficult to distribute. If code or graphics data was relocated in a hack, the MRA would have to include the entirety of the relocated data which could be considered violation of copyright. I have a few ideas listed below that could be implemented partially or in full to make distribution of patches/romhacks easier and more robust. I would be willing to try submitting some of the required code myself, as an exercise in refreshing my C++ skills.

### Add repeat and relocate attributes to patch elements within MRA files.
This would allow for both basic RLE to reduce patch sizes as well as circumventing the issue with relocated data being duplicated in whole within MRA files. Tools could be written to take advantage of this functionality and projects like Arcade Offsets could regenerate new MRA files which are both smaller and have less likelihood of containing copyrighted data.
### Extend patch support to MGL files
MGL files seem to be similar to MRA files, enough so that in-line patch support could feasibly be extended to them. This would allow the creation of MGL files which contain console romhacks without requiring the user to apply the hack or download a pre-patched rom themselves.

## IPS (and other format) support within MRA and MGL files
IPS support has been discussed before, and due to the limitations of the format, is a UX nightmare. IPS patches give us nothing to help identify what files should actually be patched, and there's dozens of ways applying a patch could go wrong (wrong ROM version, wrong header, etc.) and result in the software failing to launch, crashing, or acting incorrectly.

I propose that any IPS support initially be added in the "backend" and exposed not to the end users directly, but allow it be integrated into MRA and MGL files. This would allow the distribution of MRA/MGL files that reference patches that the MRA/MGL creator is not comfortable with including inline for copyright or other reasons. Alternately, as new versions of romhacks are released, users could update just the IPS file without requiring the generation of a new MRA/MGL.

This would require adding an "ips" attribute to the part element within MRAs, and extending the part functionality to MGL files. A new global directory into which IPS (and in the future, other patch format) files would be placed would be defined and MRA/MGL files would reference them in that manner. The patch(es) would be applied at the time the ROM is assembled and sent to the core, removing the need for any menu modifications.

Because MRA (and potentially) MGL files can enforce the checking of CRCs, this would prevent patches from being applied to incorrect versions of ROMs and allow a more helpful error to be displayed in the event of a mismatch.

## Final State
The end result of these proposed changes would be that repositories would exist which tools such as update_all could pull MRA/MGL files from automatically that would either: already contain the patch embedded or: require the user to locate the patch (by name) and drop it into a folder on their MiSTer. Core authors could programmatically generate MRAs that reference patch data that they do not wish to distribute themselves. If a popular romhack is updated and was referenced externally, end-users could update the romhack themselves simply by copying over the newest revision. This would increase the accessibility and exposure of romhacks and even when an external patch must be acquired, end-users will likely be more comfortable simply dragging it to a folder on their MiSTer than trying to run the appropriate patch tool themselves and transfer ROMs about (arcade patches can be especially tricky given the number of files that may be patched.)

## General IPS/patch support
Once the ability to apply patches to non-arcade games has been implemented, a user more clever than me could build upon it to potentially solve the UX problem in an elegant way that doesn't also add complexities to precious OSD/Menu space.

**Comment by deepthaw** [comment]
Few follow-ups on the issue:

I'm willing to put in the work to implement this. It'll probably take a while as I refresh my C++ skills but that's something I look forward to doing. I'm hoping for some guidance as to feasibility/practicality/etc. before I invest any time into it. I plan on doing it in steps, starting with improvements to MRA, then extending that to MGL, then working on the IPS support.

The primary goal is the improvement of how MRA files can be patched. Examples from Arcade Offsets, the MRA for Super Street Fighter II Turbo: New Legacy is over 2MB, largely due to runs of consecutive data while Street Fighter II' Mix is over 7MB and very tricky to distribute due to graphics data being relocated or reused from other titles - an external patch file would be a much better way to distribute it.

**Comment by sorgelig** [comment]
It will depends on complexity in implementation.
Sometimes it's easier to apply patch on PC then use it on MiSTer. It needs to be done once.

**Comment by deepthaw** [comment]
> It will depends on complexity in implementation.
> 
> Sometimes it's easier to apply patch on PC then use it on MiSTer. It needs to be done once.

It *is* generally easier for a modestly knowledgeable user to just apply the patch themselves especially to console ROMs. However arcade ROMs are typically split up into multiple files, require multiple patches be applied, and then a new MRA be generated to launch the patched version.

The first part I propose, enhanced patching functionality within MRAs themselves, would let authors (or patch collators) distribute a single MRA file and would have minimal if any chance of distributing any of the contents of the original rom. [Arcade Offsets](https://github.com/Toryalai1/Arcade_Offset) currently takes this approach of distributing MRA files with patches embedded which works well but there's a lurking fear that due to the present limitations of MRA files they could contain more data than needed, including portions of game or graphics data verbatim.

I am willing to write up an initial implementation for MRA, potentially based on the [BPS format](https://github.com/blakesmith/rombp/blob/master/docs/bps_spec.md). It would be implemented either as an extension of current patch elements or a new element to ensure all existing MRA files continue to function identically.

**Comment by deepthaw** [comment]
I've not had time to pursue this, and interest isn't too high so I'm closing it for now. If I do revisit this, I'll do so with code already created as a demonstration of functionality.
