### ISSUE TITLE
Add Wiki for Menu Configuration Strings

### ISSUE THREAD

**Issue by addisonElliott** [MiSTer-devel/Main_MiSTer#9]
Big fan of the project. I am a newcomer just exploring this and trying to implement my own core for the fun of it.

I spent a few hours trying to figure out the `CONF_STR` and exactly how it works. Once I got into *main.c* it started to make more sense. Anyway, I think adding a Wiki page for this would be immensely helpful.

Unfortunately, I don't have the time but here is a start for notes:
https://gist.github.com/addisonElliott/a790a91f4120ff8cada2b4dc8e98be77

I envision that adding to it with some examples, pictures would be really helpful. It isn't too difficult to understand once it is laid out.

**Comment by sorgelig** [comment]
MiSTer is supposed to be a community driven project. If you are willing to help with better API description, then i can give you access to the Wiki. I cannot do (and don't have time) everything by myself.

**Comment by addisonElliott** [comment]
Of course. The biggest issue was I did not have access to the Wiki. I'm not too familiar with the Wiki, but it may be beneficial to make that open to everyone to edit.

My thoughts are maybe I get a foundation going for the page and people add to it as they go.

**Comment by sorgelig** [comment]
I've opened Wiki for public edit.

**Comment by addisonElliott** [comment]
Thank you. Closing this issue now.
