### ISSUE TITLE
Neo Geo game lags

### ISSUE THREAD

**Issue by city41** [MiSTer-devel/Main_MiSTer#904]
I have made a ROM hack of the Neo Geo game King of Fighters 94 (more info [here](https://neorh.mattgreer.dev)).

On the MiSTer, this game is very laggy. Inputs are not responsive, and there is graphical noise at the top of the screen.

I originally suspected the NeoGeo core, but it doesn't seem to be the cause. I now suspect the main MiSTer binaries themselves are somehow causing this.

Here is a video showing why I say that

https://github.com/MiSTer-devel/Main_MiSTer/assets/141159/242df79f-3c4b-4548-95c0-ffeb7928fd17

Here is the summary of that video
- real Neo Geo hardware using a NeoSD, kof94te 1.2.4: no issues at all, game runs as intended
- MiSTer v230223, OS v221224, NeoGeo_20240418, kof94te 1.2.4: no issues at all*
- MiSTer v240505, OS v231108, NeoGeo_20240418, kof94te 1.2.4: very laggy, graphical issues, not running as expected.

*on 230223, the game is possibly running a bit faster than on real hardware, but I've not measured that accurately to be sure and if it does, it's not a big deal IMO.

Is there perhaps a setting in the main ini that can improve this? Or any other way the performance of v230223 can be restored?

Here is a repro
* build kof94te 1.2.4 in .neo format using kof94.zip from MAME. Can easily be done in one click at https://neorh.mattgreer.dev
* copy kof94te.neo to `/media/fat/games/NEOGEO`
* launch the Neo Geo core, then choose "The King of Fighters '94:TE"
* press start and A until you arrive at the character select screen

From there everything about this screen is very laggy. Pressing the joystick to try and move the cursor only works every so often. Placing the cursor on random select makes the lag more obvious, as it will run quite slowly.

**Comment by paulb-nl** [comment]
The kof94te.neo file uses the same ID (0x55) as the original Kof94. The original cartridge uses slow ROM and so it has wait states enabled.  If wait states are not used then there will be sprite glitches even on original hardware.

Your hack needs to run without wait states so a solution is to set a different ID in the .neo file.

**Comment by city41** [comment]
Ah interesting. Yes changing the NGH number does restore how it worked on 230223.

And the wait states explains the graphical issues I've seen. Since I've also seen them on the original game I figured that's just how it is. So thanks for that, I'll see if I can get my hack to work with wait states.

Thanks!

**Comment by city41** [comment]
@paulb-nl I'm interested in your input on this.

We have been discussing this on the neo-geo forum. And we're kind of at a crossroads and unsure what is happening.

The thing is the hack is never laggy at all on real hardware using a NeoSD. So that opened the question, maybe the NeoSD doesn't set wait cycles? We *think* it does set wait cycles if the file is named exactly `kof94.neo`. That's our best theory and it does seem to pan out through experimentation. But we don't know for sure. I've reached out to TerraOnion but so far no response.

So it seems like there are three possibilities:

* the NeoSD never sets wait cycles, allowing the hack to run at full speed, but also allowing graphical glitches in both the hack and kof94 itself.
* the NeoSD does set wait cycles on the hack, and since it runs just fine it suggest maybe the mister's wait cycle implementation is not accurate.
* The NeoSD does set wait cycles on KOF94 itself, but not on the hack. I think this is possible if the NeoSD is say using CRCs to figure out what game it is.

No one has ever witnessed graphcal glitching with OG KOF94 on a NeoSD. Which to me makes possibility 1 unlikely. But it is true the graphical glitches are random, rapid, and rare. So it's possible we've just been unlucky.

btw, the hack is at 1.3.1 beta 3, which main purpose is to address the mister lagginess. It is working great on the mister with slowrom (ie using ngh 55), and 1.3.1 proper should be released pretty soon.

**Comment by paulb-nl** [comment]
I have doubts that NeoSD is actually using wait cycles.

Check out this comment from PepAlacant here https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/201#issuecomment-1655135496

He says the glitches in Kof94 show up with NeoSD or bootleg carts and can usually be resolved after resetting the Neo Geo a few times.

If it is using wait cycles somehow then it would be easiest to just read the NGH number instead of having to calculate the CRC or needing a specific file name.

Another game you can try is Ninja Commando. There will be glitches in a certain part if wait cycles are not used. Check the top left and right in this video:

https://github.com/MiSTer-devel/Main_MiSTer/assets/2227984/99d7ea34-70fb-456e-ae83-c7a4dd4e9bef

If you can make some kind of CPU speed test that displays the value on screen then we could compare the CPU speed with NeoSD and MiSTer.

Nice work on getting the hack working with wait cycles.

**Comment by city41** [comment]
Yes, Ninja Commando shows those glitches on the NeoSD. I think you are probably right, the NeoSD does not set wait cycles.

> If you can make some kind of CPU speed test that displays the value on screen then we could compare the CPU speed with NeoSD and MiSTer.

I could probably do that, let me think about that. Not sure it's needed, I think Ninja Commando is pretty conclusive evidence.

Thanks for the help!

**Comment by city41** [comment]
Oh and just to add one last thing. KOF94 does have a deterministic graphical glitch: win quotes.


https://github.com/MiSTer-devel/Main_MiSTer/assets/141159/8f7b66c1-1d50-463b-ab74-9fdd554c5331

That flickering happens on the NeoSD (that is a NeoSD being used in the video), or the MiSTer with slowrom disabled. It does not happen on the MiSTer with slowrom enabled, or a real KOF94 cart.
