### ISSUE TITLE
Feature request: Minimig config files - possible to rename?

### ISSUE THREAD

**Issue by mickstone** [MiSTer-devel/Main_MiSTer#91]
Hi Team,

I'm not sure if this is MiSTer or minimig related, so please close if not MiSTer.
It would be great if you could allow the config files for minimig to be customised.  For example "Workbench 3.1 A1200 AGA - NTSC" for example

**Comment by sorgelig** [comment]
OSD menu doesn't have ability to enter any text, so it's impossible to rename it there. That's why MiSTer show some info about config to get a clue.

**Comment by mickstone** [comment]
Thanks for the info
