### ISSUE TITLE
FileSave function doesn't update full_path on each call

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Main_MiSTer#910]
The FileSave function in file_io.cpp doesn't update full_path on each call from what I can tell. When I was testing a user's save issue I noticed this. To reproduce the issue do the following:

1. Load core and game that does saving.
2. Open OSD to save game.
3. Check saves folder for new save
4. Rename that save file.
5. Make another save happen in the game and open OSD to autosave again.
6. The renamed save file is updated instead of generating a new save file.

The behavior most would expect is that a new save file would be created. I'm not very good at C at all, but it looks like the `full_path` variable needs to be called again within the FileSave function maybe? Not sure, someone who knows C better can help hopefully.

**Comment by sorgelig** [comment]
It's not supposed to do the way you are doing.
Save file is opened and keep opened till you open another ROM. 
So you have to open another ROM before you rename/copy the save file.

**Comment by birdybro** [comment]
Yeah, I guess that makes sense. It was unintuitive to me and seemed incorrect because of how software typically works, but of course this isn't your typical software ;)

Thanks!
