### ISSUE TITLE
Button Mapping: First button from 2 button menu combo triggers Clear All

### ISSUE THREAD

**Issue by saftle** [MiSTer-devel/Main_MiSTer#92]
**Expected Result:**
Both buttons should be required to be pressed at the same time in order to initiate Clear All. Each of the individual buttons should be able to be bound.

**Current Behavior:**
Pressing the first button triggers the Clear All preventing the button from being mapped.

**Comment by sorgelig** [comment]
i've pushed the fix. 
If you can compile yourself then test it.

**Comment by saftle** [comment]
Thank you! The fix worked perfectly.
