### ISSUE TITLE
Main Mister Menu Does Not Work For CRT Monitor For MisterPi

### ISSUE THREAD

**Issue by SamuelBanya** [MiSTer-devel/Main_MiSTer#920]
I have the Mister Pi mega pack with the IO board at the top of the unit.

I have set the following settings enabled in the ini menu settings:
forced_scandoubler: on
vga_scaler: off
composite_sync: off

Yet, I am getting a weird flashing effect on the main menu when trying to use the VGA out for a CRT monitor.

I have had to resort to using an HDMI monitor to navigate the main menu to access a core, and once I am in the core menu, the CRT monitor works without an issue.

Any ideas on what to do? Thanks.

Uploaded a video that showcases this flash effect for the main Mister menu via the VGA out:
https://github.com/user-attachments/assets/1e902adc-91a0-4894-8c22-858d3d267667

**Comment by sorgelig** [comment]
Please use MiSTer forum for discussion: https://misterfpga.org/
Github is for developing and bug reports only.

**Comment by SamuelBanya** [comment]
This is a main Mister menu issue, and it has been reported by multiple people even with supposedly correct user settings.

**Comment by RetroShopPT** [comment]
The problem is that your SDCard has an outdated MiSTer and menu.rbf. I've had this problem reported to me countless times and the answer has always been the same: if Update All doesn't fetch the files automatically, you can copy the file manually from GitHub mister-devel to the SDCard.
