### ISSUE TITLE
[Request] ntsc_mode=auto

### ISSUE THREAD

**Issue by retrorepair** [MiSTer-devel/Main_MiSTer#941]
Not sure how easy or not it would be to add but the majority of early 90s onwards TVs in europe are capable of PAL and NTSC. Would a "auto" flag be possible based on the video system the core is set to?

It's a shame having to edit the ini when wanting to change between PAL and NTSC for composite/svideo modes.

**Comment by birdybro** [comment]
You can alternatively use an alternate ini and just open the OSD menu and hold back + direction to switch.

https://mister-devel.github.io/MkDocs_MiSTer/advanced/ini/#alternate-mister-ini-files

**Comment by retrorepair** [comment]
That's true. It'd be nice if that wasn't needed though via a 4th setting.

Can info like video standard be fed back to main from the core? I've played with cores before but no idea how main works or how to compile it.

**Comment by MikeS11** [comment]
> Not sure how easy or not it would be to add but the majority of early 90s onwards TVs in europe are capable of PAL and NTSC. Would a "auto" flag be possible based on the video system the core is set to?
> 
> It's a shame having to edit the ini when wanting to change between PAL and NTSC for composite/svideo modes.

PAL/NTSC are auto (E.g. If the cores fps is less than 55), its PAL60 or PAL-M that require a forced change in the ini

Here is the source in main for that section:

int pal = fps < 55.f;
double CLK_REF = (pal || (cfg.ntsc_mode == 1)) ? 4.43361875f : (cfg.ntsc_mode == 2) ? 3.575611f : 3.579545f;

It should work normal on all the consoles, all the arcades or at least 99% are NTSC, is there a specific example thats off?

**Comment by retrorepair** [comment]
So if I load a PAL rom and then an NTSC rom then the svideo/composite output would automatically change pal and ntsc? Ehat ntsc_mode would be needed for that to work? It looked to me like it's hard set to ntsc, pal60 or pal-m

**Comment by MikeS11** [comment]
Yeah, the core changes the ref freq and uses the correct yc.txt entry based on the cores video freq. But it won't help if your looking for pal60. I use it all the time when testing, especially figuring out all the different Saturn phase increment for composite.
