### ISSUE TITLE
I broke the main MiSTer again :(

### ISSUE THREAD

**Issue by the-importer** [MiSTer-devel/Main_MiSTer#95]
So I transferred the new main (20190609) via FileZilla, but now I get a black screen when booting. I can still access the cores via FileZilla, but I can't control from the MiSTer hardware itself. I tried sending the file from both ASCII and Binary mode in FileZilla, but no differences.

What can I do about this?

**Comment by sorgelig** [comment]
This is not the topic for issues.
Download the whole release with installer and update it offline of PC.
