### ISSUE TITLE
Core settings menu doesn't change correct entry

### ISSUE THREAD

**Issue by zakk4223** [MiSTer-devel/Main_MiSTer#96]
See video: https://www.youtube.com/watch?v=x0xQTgUb26Y

Summary: In newer cores, the settings menu appears to be broken. The entry being changed does not correspond to the entry you have highlighted; it will change a value higher up in the menu instead.

After some experimentation it seems it was introduced in cores on or after May 10th, 2019

Is it possibly something about my setup? Note in the video it doesn't happen with an older Genesis core loaded

**Comment by sorgelig** [comment]
You have to update MiSTer binary to latest
