### ISSUE TITLE
Quartus Scaler IP in Wiki

### ISSUE THREAD

**Issue by DiscoStarslayer** [MiSTer-devel/Main_MiSTer#97]
I was reading this page: https://github.com/MiSTer-devel/Main_MiSTer/wiki/Core-porting-notes

At the very end it mentions

> Scaler uses "Video and Image Processing"(VIP) modules from Megacore IP bundled with Standard Quartus license. Free/Web version of Quartus can compile the scaler code, but it will work as a trial version - video will work around 1 hour and then will start to blink. Trial version won't have RBF and can be uploaded to FPGA only through USB Blaster.

> Scaler code is distributed in vip.qsys form. You need to open vip.qsys in QSYS and regenerate the code. After that, you will be able to compile the Full version.

Looking at the modern ZX Spectrum core's github though, it seems like this IP was removed from the project back in February: https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/commit/3b23a8fb2555670707ffdfe4ec3e96c53ee4c47d

This is great news, as it means the project can be fully built with the free edition.

Does it make sense to remove this line? (I can do it, but I'm very new to this project so didn't want to step on any toes on the wiki, and maybe I'm incorrect with this suggestion)

**Comment by sorgelig** [comment]
I've removed that clause. 
Thanks for info.
